<?php
/**
 * Locale data for 'addressesData'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCLDRResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '1',
  'address' => 
  array (
    'GB' => 
    array (
      'postCodeRegex' => 'GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%S%n%Z',
    ),
    'JE' => 
    array (
      'postCodeRegex' => 'JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%nJERSEY%n%Z',
    ),
    'GG' => 
    array (
      'postCodeRegex' => 'GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%nGUERNSEY%n%Z',
    ),
    'IM' => 
    array (
      'postCodeRegex' => 'IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'US' => 
    array (
      'postCodeRegex' => '\\d{5}([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'CA' => 
    array (
      'postCodeRegex' => '[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'DE' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'JP' => 
    array (
      'postCodeRegex' => '\\d{3}-\\d{4}',
      'addressFormat' => '〒%Z%n%S%C%n%A%n%O%n%N',
    ),
    'FR' => 
    array (
      'postCodeRegex' => '\\d{2}[ ]?\\d{3}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'AU' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%n%C %S %Z',
    ),
    'IT' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C %S',
    ),
    'CH' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%nCH-%Z %C',
    ),
    'AT' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C',
    ),
    'ES' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C %S',
    ),
    'NL' => 
    array (
      'postCodeRegex' => '\\d{4}[ ]?[A-Z]{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C',
    ),
    'BE' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C',
    ),
    'DK' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C',
    ),
    'SE' => 
    array (
      'postCodeRegex' => '\\d{3}[ ]?\\d{2}',
      'addressFormat' => '%O%n%N%n%A%nSE-%Z %C',
    ),
    'NO' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'BR' => 
    array (
      'postCodeRegex' => '\\d{5}[\\-]?\\d{3}',
      'addressFormat' => '%O%n%N%n%A%n%C-%S%n%Z',
    ),
    'PT' => 
    array (
      'postCodeRegex' => '\\d{4}([\\-]\\d{3})?',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'FI' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%O%n%N%n%A%nFI-%Z %C',
    ),
    'AX' => 
    array (
      'postCodeRegex' => '22\\d{3}',
      'addressFormat' => '%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    ),
    'KR' => 
    array (
      'postCodeRegex' => '\\d{3}[\\-]\\d{3}',
      'addressFormat' => '%S %C%D%n%A%n%O%n%N%nSEOUL %Z',
    ),
    'CN' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%Z%n%S%C%D%n%A%n%O%n%N',
    ),
    'TW' => 
    array (
      'postCodeRegex' => '\\d{3}(\\d{2})?',
      'addressFormat' => '%Z%n%S%C%n%A%n%O%n%N',
    ),
    'SG' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%nSINGAPORE %Z',
    ),
    'DZ' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'AD' => 
    array (
      'postCodeRegex' => 'AD\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%Z %S',
    ),
    'AR' => 
    array (
      'postCodeRegex' => '([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?',
      'addressFormat' => '%N%n%O%n%A%n%Z %C%n%S',
    ),
    'AM' => 
    array (
      'postCodeRegex' => '(37)?\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z%n%C%n%S',
    ),
    'AZ' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%nAZ %Z %C',
    ),
    'BH' => 
    array (
      'postCodeRegex' => '((1[0-2]|[2-9])\\d{2})?',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'BD' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C - %Z',
    ),
    'BB' => 
    array (
      'postCodeRegex' => '(BB\\d{5})?',
    ),
    'BY' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%S%n%Z %C %X%n%A%n%O%n%N',
    ),
    'BM' => 
    array (
      'postCodeRegex' => '[A-Z]{2}[ ]?[A-Z0-9]{2}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'BA' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'IO' => 
    array (
      'postCodeRegex' => 'BBND 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'BN' => 
    array (
      'postCodeRegex' => '[A-Z]{2}[ ]?\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'BG' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'KH' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'CV' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C%n%S',
    ),
    'CL' => 
    array (
      'postCodeRegex' => '\\d{7}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C%n%S',
    ),
    'CR' => 
    array (
      'postCodeRegex' => '\\d{4,5}|\\d{3}-\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'HR' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%nHR-%Z %C',
    ),
    'CY' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'CZ' => 
    array (
      'postCodeRegex' => '\\d{3}[ ]?\\d{2}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'DO' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'EC' => 
    array (
      'postCodeRegex' => '([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?',
      'addressFormat' => '%N%n%O%n%A%n%Z%n%C',
    ),
    'EG' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%S%n%Z',
    ),
    'EE' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'FO' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%A%nFO%Z %C',
    ),
    'GE' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'GR' => 
    array (
      'postCodeRegex' => '\\d{3}[ ]?\\d{2}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'GL' => 
    array (
      'postCodeRegex' => '39\\d{2}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'GT' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z- %C',
    ),
    'HT' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%nHT%Z %C %X',
    ),
    'HN' => 
    array (
      'postCodeRegex' => '(?:\\d{5})?',
      'addressFormat' => '%N%n%O%n%A%n%C, %S%n%Z',
    ),
    'HU' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%C%n%A%n%Z',
    ),
    'IS' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'IN' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z%n%S',
    ),
    'ID' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z%n%S',
    ),
    'IE' => 
    array (
      'postCodeRegex' => '((D|DUBLIN)?([1-9]|6[wW]|1[0-8]|2[024]))?',
      'addressFormat' => '%N%n%O%n%A%n%C%n%S',
    ),
    'IL' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'JO' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'KZ' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%Z%n%S%n%C%n%A%n%O%n%N',
    ),
    'KE' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%Z',
    ),
    'KW' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'LA' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'LV' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C, LV-%Z',
    ),
    'LB' => 
    array (
      'postCodeRegex' => '(\\d{4}([ ]?\\d{4})?)?',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'LI' => 
    array (
      'postCodeRegex' => '(948[5-9])|(949[0-7])',
      'addressFormat' => '%O%n%N%n%A%nFL-%Z %C',
    ),
    'LT' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%O%n%N%n%A%nLT-%Z %C',
    ),
    'LU' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%nL-%Z %C',
    ),
    'MK' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'MY' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C, %S',
    ),
    'MV' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'MT' => 
    array (
      'postCodeRegex' => '[A-Z]{3}[ ]?\\d{2,4}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'MU' => 
    array (
      'postCodeRegex' => '(\\d{3}[A-Z]{2}\\d{3})?',
      'addressFormat' => '%N%n%O%n%A%n%Z%n%C',
    ),
    'MX' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C, %S',
    ),
    'MD' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%nMD-%Z %C',
    ),
    'MC' => 
    array (
      'postCodeRegex' => '980\\d{2}',
      'addressFormat' => '%N%n%O%n%A%nMC-%Z %C %X',
    ),
    'MA' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'NP' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'NZ' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'NI' => 
    array (
      'postCodeRegex' => '((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?',
      'addressFormat' => '%N%n%O%n%A%n%Z%n%C, %S',
    ),
    'NG' => 
    array (
      'postCodeRegex' => '(\\d{6})?',
      'addressFormat' => '%N%n%O%n%A%n%C %Z%n%S',
    ),
    'OM' => 
    array (
      'postCodeRegex' => '(PC )?\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%Z%n%C',
    ),
    'PK' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C-%Z',
    ),
    'PY' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'PH' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C%n%S',
    ),
    'PL' => 
    array (
      'postCodeRegex' => '\\d{2}-\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'PR' => 
    array (
      'postCodeRegex' => '00[679]\\d{2}([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C PR %Z',
    ),
    'RO' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'RU' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%Z %C  %n%A%n%O%n%N',
    ),
    'SM' => 
    array (
      'postCodeRegex' => '4789\\d',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'SA' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'SN' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'SK' => 
    array (
      'postCodeRegex' => '\\d{3}[ ]?\\d{2}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'SI' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%nSI- %Z %C',
    ),
    'ZA' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%Z',
    ),
    'LK' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%Z',
    ),
    'TJ' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'TH' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%S %Z',
    ),
    'TN' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'TR' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'TM' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'UA' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%Z %C%n%A%n%O%n%N',
    ),
    'UY' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C %S',
    ),
    'UZ' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C%n%S',
    ),
    'VA' => 
    array (
      'postCodeRegex' => '00120',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'VE' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z, %S',
    ),
    'ZM' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'AS' => 
    array (
      'postCodeRegex' => '96799',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'CC' => 
    array (
      'postCodeRegex' => '6799',
      'addressFormat' => '%O%n%N%n%A%n%C %S %Z',
    ),
    'CK' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'RS' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'ME' => 
    array (
      'postCodeRegex' => '8\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'CS' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'YU' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'CX' => 
    array (
      'postCodeRegex' => '6798',
      'addressFormat' => '%O%n%N%n%A%n%C %S %Z',
    ),
    'ET' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'FK' => 
    array (
      'postCodeRegex' => 'FIQQ 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'NF' => 
    array (
      'postCodeRegex' => '2899',
      'addressFormat' => '%O%n%N%n%A%n%C %S %Z',
    ),
    'FM' => 
    array (
      'postCodeRegex' => '(9694[1-4])([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'GF' => 
    array (
      'postCodeRegex' => '9[78]3\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'GN' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%Z %A %C',
    ),
    'GP' => 
    array (
      'postCodeRegex' => '9[78][01]\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'GS' => 
    array (
      'postCodeRegex' => 'SIQQ 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'GU' => 
    array (
      'postCodeRegex' => '969[123]\\d([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'GW' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'HM' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%O%n%N%n%A%n%C %S %Z',
    ),
    'IQ' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%O%n%N%n%A%n%C, %S%n%Z',
    ),
    'KG' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%Z %C %X%n%A%n%O%n%N',
    ),
    'LR' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C %X',
    ),
    'LS' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z',
    ),
    'MG' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'MH' => 
    array (
      'postCodeRegex' => '969[67]\\d([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'MN' => 
    array (
      'postCodeRegex' => '\\d{6}',
      'addressFormat' => '%N%n%O%n%A%n%S %C-%X%n%Z',
    ),
    'MP' => 
    array (
      'postCodeRegex' => '9695[012]([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'MQ' => 
    array (
      'postCodeRegex' => '9[78]2\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'NC' => 
    array (
      'postCodeRegex' => '988\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'NE' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'VI' => 
    array (
      'postCodeRegex' => '008(([0-4]\\d)|(5[01]))([ \\-]\\d{4})?',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'PF' => 
    array (
      'postCodeRegex' => '987\\d{2}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C %S',
    ),
    'PG' => 
    array (
      'postCodeRegex' => '\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%C %Z %S',
    ),
    'PM' => 
    array (
      'postCodeRegex' => '9[78]5\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'PN' => 
    array (
      'postCodeRegex' => 'PCRN 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'PW' => 
    array (
      'postCodeRegex' => '96940',
      'addressFormat' => '%N%n%O%n%A%n%C %S %Z',
    ),
    'RE' => 
    array (
      'postCodeRegex' => '9[78]4\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'SH' => 
    array (
      'postCodeRegex' => '(ASCN|STHL) 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'SJ' => 
    array (
      'postCodeRegex' => '\\d{4}',
      'addressFormat' => '%N%n%O%n%A%n%Z %C',
    ),
    'SO' => 
    array (
      'postCodeRegex' => '\\d{5}',
      'addressFormat' => '%N%n%O%n%A%n%C, %S %Z',
    ),
    'SZ' => 
    array (
      'postCodeRegex' => '[HLMS]\\d{3}',
      'addressFormat' => '%N%n%O%n%A%n%C%n%Z',
    ),
    'TC' => 
    array (
      'postCodeRegex' => 'TKCA 1ZZ',
      'addressFormat' => '%N%n%O%n%A%n%X%n%C%n%Z',
    ),
    'WF' => 
    array (
      'postCodeRegex' => '986\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
    'YT' => 
    array (
      'postCodeRegex' => '976\\d{2}',
      'addressFormat' => '%O%n%N%n%A%n%Z %C %X',
    ),
  ),
);
