<?php
/**
 * Locale data for 'af_ZA'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '4123',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM y',
    'long' => 'dd MMMM y',
    'medium' => 'dd MMM y',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januarie',
      2 => 'Februarie',
      3 => 'Maart',
      4 => 'April',
      5 => 'Mei',
      6 => 'Junie',
      7 => 'Julie',
      8 => 'Augustus',
      9 => 'September',
      10 => 'Oktober',
      11 => 'November',
      12 => 'Desember',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mar',
      4 => 'Apr',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Aug',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Des',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
    'wide' => 
    array (
      4 => 'April',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sondag',
      1 => 'Maandag',
      2 => 'Dinsdag',
      3 => 'Woensdag',
      4 => 'Donderdag',
      5 => 'Vrydag',
      6 => 'Saterdag',
    ),
    'abbreviated' => 
    array (
      0 => 'So',
      1 => 'Ma',
      2 => 'Di',
      3 => 'Wo',
      4 => 'Do',
      5 => 'Vr',
      6 => 'Sa',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'D',
      3 => 'W',
      4 => 'D',
      5 => 'V',
      6 => 'S',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Australiese dollar',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'Brasiliaanse real',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Kanadese dollar',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Sjinese joean renminbi',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Euro',
      'name-single' => 'euro',
      'name-multiple' => 'euro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Britse pond',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
      'name' => 'Hong Kong dollar',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
      'name' => 'Israeliese nuwe sikkel',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Indiese rupee',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Japannese jen',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
      'name' => 'Suid-Koreaanse won',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'Meksikaanse peso',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
      'name' => 'Nieu-Seeland dollar',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
      'name' => 'Thaise baht',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
      'name' => 'Nuwe Taiwanese dollar',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Amerikaanse dollar',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
      'name' => 'Viëtnamese dong',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'CFA frank BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
      'name' => 'Oos-Karibbiese dollar',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'CFA frank BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
      'name' => 'CFP-frank',
    ),
    'ZAR' => 
    array (
      'symbol' => 'R',
      'name' => 'Suid-Afrikaanse rand',
    ),
    'AED' => 
    array (
      'name' => 'Verenigde Arabiese Emirate dirham',
    ),
    'AFN' => 
    array (
      'name' => 'Afgaanse afgani',
    ),
    'ALL' => 
    array (
      'name' => 'Albanese lek',
    ),
    'AMD' => 
    array (
      'name' => 'Armeense dram',
    ),
    'ANG' => 
    array (
      'name' => 'Nederlands-Antilliaanse gulde',
    ),
    'AOA' => 
    array (
      'name' => 'Angolese kwanza',
    ),
    'ARS' => 
    array (
      'name' => 'Argentynse peso',
    ),
    'AWG' => 
    array (
      'name' => 'Arubaanse floryn',
    ),
    'AZN' => 
    array (
      'name' => 'Azerbeidjaanse manat',
    ),
    'BAM' => 
    array (
      'name' => 'Bosnië en Herzegowina omskakelbare marka',
    ),
    'BBD' => 
    array (
      'name' => 'Barbados-dollar',
    ),
    'BDT' => 
    array (
      'name' => 'Bangladesjiese taka',
    ),
    'BGN' => 
    array (
      'name' => 'Bulgaarse lev',
    ),
    'BHD' => 
    array (
      'name' => 'Bahrainse dinar',
    ),
    'BIF' => 
    array (
      'name' => 'Burundiese frank',
    ),
    'BMD' => 
    array (
      'name' => 'Bermuda-dollar',
    ),
    'BND' => 
    array (
      'name' => 'Broeneise dollar',
    ),
    'BOB' => 
    array (
      'name' => 'Boliviaanse boliviano',
    ),
    'BSD' => 
    array (
      'name' => 'Bahamiaanse dollar',
    ),
    'BTN' => 
    array (
      'name' => 'Bhoetanese ngoeltroem',
    ),
    'BWP' => 
    array (
      'name' => 'Botswana pula',
    ),
    'BYR' => 
    array (
      'name' => 'Belo-Russiese roebel',
    ),
    'BZD' => 
    array (
      'name' => 'Beliziese dollar',
    ),
    'CDF' => 
    array (
      'name' => 'Kongolese frank',
    ),
    'CHF' => 
    array (
      'name' => 'Switserse frank',
    ),
    'CLP' => 
    array (
      'name' => 'Chileense peso',
    ),
    'COP' => 
    array (
      'name' => 'Colombiaanse peso',
    ),
    'CRC' => 
    array (
      'name' => 'Costa Ricaanse colón',
    ),
    'CUC' => 
    array (
      'name' => 'Kubaanse omskakelbare peso',
    ),
    'CUP' => 
    array (
      'name' => 'Kubaanse peso',
    ),
    'CVE' => 
    array (
      'name' => 'Kaap Verdiese escudo',
    ),
    'CZK' => 
    array (
      'name' => 'Tsjeggiese kroon',
    ),
    'DJF' => 
    array (
      'name' => 'Djiboeti frank',
    ),
    'DKK' => 
    array (
      'name' => 'Deense kroon',
    ),
    'DOP' => 
    array (
      'name' => 'Dominikaanse peso',
    ),
    'DZD' => 
    array (
      'name' => 'Algeriese dinar',
    ),
    'EGP' => 
    array (
      'name' => 'Egiptiese pond',
    ),
    'ERN' => 
    array (
      'name' => 'Eritrese nakfa',
    ),
    'ETB' => 
    array (
      'name' => 'Etiopiese birr',
    ),
    'FJD' => 
    array (
      'name' => 'Fidjiaanse dollar',
    ),
    'FKP' => 
    array (
      'name' => 'Falkland-eilande pond',
    ),
    'GEL' => 
    array (
      'name' => 'Georgiese lari',
    ),
    'GHC' => 
    array (
      'name' => 'Ghanese cedi (1979-2007)',
    ),
    'GHS' => 
    array (
      'name' => 'Ghanese cedi',
    ),
    'GIP' => 
    array (
      'name' => 'Gibraltarese pond',
    ),
    'GMD' => 
    array (
      'name' => 'Gambiese dalasi',
    ),
    'GNF' => 
    array (
      'name' => 'Guinese frank',
    ),
    'GNS' => 
    array (
      'name' => 'Guinese syli',
    ),
    'GTQ' => 
    array (
      'name' => 'Guatemalaanse quetzal',
    ),
    'GYD' => 
    array (
      'name' => 'Guyanese dollar',
    ),
    'HNL' => 
    array (
      'name' => 'Hondurese lempira',
    ),
    'HRK' => 
    array (
      'name' => 'Kroatiese kuna',
    ),
    'HTG' => 
    array (
      'name' => 'Haïtiaanse gourde',
    ),
    'HUF' => 
    array (
      'name' => 'Hongaarse forint',
    ),
    'IDR' => 
    array (
      'name' => 'Indonesiese roepia',
    ),
    'IQD' => 
    array (
      'name' => 'Irakse dinar',
    ),
    'IRR' => 
    array (
      'name' => 'Iranse rial',
    ),
    'ISK' => 
    array (
      'name' => 'Yslandse kroon',
    ),
    'JMD' => 
    array (
      'name' => 'Jamaikaanse dollar',
    ),
    'JOD' => 
    array (
      'name' => 'Jordaniese dinar',
    ),
    'KES' => 
    array (
      'name' => 'Keniaanse sjieling',
    ),
    'KGS' => 
    array (
      'name' => 'Kirgisiese som',
    ),
    'KHR' => 
    array (
      'name' => 'Kambodjaanse riel',
    ),
    'KMF' => 
    array (
      'name' => 'Comoriese frank',
    ),
    'KPW' => 
    array (
      'name' => 'Noord-Koreaanse won',
    ),
    'KWD' => 
    array (
      'name' => 'Koeweitse dinar',
    ),
    'KYD' => 
    array (
      'name' => 'Cayman-eilande dollar',
    ),
    'KZT' => 
    array (
      'name' => 'Kazakse tenge',
    ),
    'LAK' => 
    array (
      'name' => 'Laosiaanse kip',
    ),
    'LBP' => 
    array (
      'name' => 'Lebanese pond',
    ),
    'LKR' => 
    array (
      'name' => 'Sri Lankaanse roepee',
    ),
    'LRD' => 
    array (
      'name' => 'Liberiese dollar',
    ),
    'LSL' => 
    array (
      'name' => 'Lesotho loti',
    ),
    'LTL' => 
    array (
      'name' => 'Litause litas',
    ),
    'LVL' => 
    array (
      'name' => 'Lettiese lats',
    ),
    'LYD' => 
    array (
      'name' => 'Libiese dinar',
    ),
    'MAD' => 
    array (
      'name' => 'Marokkaanse dirham',
    ),
    'MDL' => 
    array (
      'name' => 'Moldowiese leu',
    ),
    'MGA' => 
    array (
      'name' => 'Malgassiese ariary',
    ),
    'MKD' => 
    array (
      'name' => 'Macedoniese denar',
    ),
    'MMK' => 
    array (
      'name' => 'Myanma Kyat',
    ),
    'MNT' => 
    array (
      'name' => 'Mongoolse toegrik',
    ),
    'MOP' => 
    array (
      'name' => 'Macaose pataca',
    ),
    'MRO' => 
    array (
      'name' => 'Mauritaniese ouguiya',
    ),
    'MUR' => 
    array (
      'name' => 'Mauritiaanse rupee',
    ),
    'MVR' => 
    array (
      'name' => 'Malediviese rufia',
    ),
    'MWK' => 
    array (
      'name' => 'Malawiese kwacha',
    ),
    'MYR' => 
    array (
      'name' => 'Maleisiese ringgit',
    ),
    'MZM' => 
    array (
      'name' => 'Mosambiekse metical (1980-2006)',
    ),
    'MZN' => 
    array (
      'name' => 'Mosambiekse metical',
    ),
    'NAD' => 
    array (
      'name' => 'Namibiese dollar',
    ),
    'NGN' => 
    array (
      'name' => 'Nigeriese naira',
    ),
    'NIO' => 
    array (
      'name' => 'Nicaraguaanse córdoba',
    ),
    'NOK' => 
    array (
      'name' => 'Noorse kroon',
    ),
    'NPR' => 
    array (
      'name' => 'Nepalese roepee',
    ),
    'OMR' => 
    array (
      'name' => 'Omaanse rial',
    ),
    'PAB' => 
    array (
      'name' => 'Panamese balboa',
    ),
    'PEN' => 
    array (
      'name' => 'Peruaanse nuwe sol',
    ),
    'PGK' => 
    array (
      'name' => 'Papoease kina',
    ),
    'PHP' => 
    array (
      'name' => 'Filippynse peso',
    ),
    'PKR' => 
    array (
      'name' => 'Pakistanse roepee',
    ),
    'PLN' => 
    array (
      'name' => 'Poolse zloty',
    ),
    'PYG' => 
    array (
      'name' => 'Paraguaanse guarani',
    ),
    'QAR' => 
    array (
      'name' => 'Katarese rial',
    ),
    'RSD' => 
    array (
      'name' => 'Serbiese dinar',
    ),
    'RUB' => 
    array (
      'name' => 'Russiese roebel',
    ),
    'RWF' => 
    array (
      'name' => 'Rwandiese frank',
    ),
    'SAR' => 
    array (
      'name' => 'Saoedi-Arabiese riyal',
    ),
    'SBD' => 
    array (
      'name' => 'Salomons-eilande dollar',
    ),
    'SCR' => 
    array (
      'name' => 'Seychellese rupee',
    ),
    'SDG' => 
    array (
      'name' => 'Soedannese pond',
    ),
    'SDP' => 
    array (
      'name' => 'Soedannese pond (1957-1998)',
    ),
    'SEK' => 
    array (
      'name' => 'Sweedse kroon',
    ),
    'SGD' => 
    array (
      'name' => 'Singapoer-dollar',
    ),
    'SHP' => 
    array (
      'name' => 'Sint Helena pond',
    ),
    'SLL' => 
    array (
      'name' => 'Sierra Leonese leone',
    ),
    'SOS' => 
    array (
      'name' => 'Somaliese sjieling',
    ),
    'SRD' => 
    array (
      'name' => 'Surinaamse dollar',
    ),
    'STD' => 
    array (
      'name' => 'São Tomé en Príncipe dobra',
    ),
    'SYP' => 
    array (
      'name' => 'Siriese pond',
    ),
    'SZL' => 
    array (
      'name' => 'Swazilandse lilangeni',
    ),
    'TJS' => 
    array (
      'name' => 'Tadjikse roebel',
    ),
    'TMT' => 
    array (
      'name' => 'Toerkmeense manat',
    ),
    'TND' => 
    array (
      'name' => 'Tunisiese dinar',
    ),
    'TOP' => 
    array (
      'name' => 'Tongaanse pa\'anga',
    ),
    'TRL' => 
    array (
      'name' => 'Turkse lier (1922-2005)',
    ),
    'TRY' => 
    array (
      'name' => 'Turkse lier',
    ),
    'TTD' => 
    array (
      'name' => 'Trinidad en Tobago dollar',
    ),
    'TZS' => 
    array (
      'name' => 'Tanzaniese sjieling',
    ),
    'UAH' => 
    array (
      'name' => 'Oekraïnse hriwna',
    ),
    'UGX' => 
    array (
      'name' => 'Ugandese sjieling',
    ),
    'UYU' => 
    array (
      'name' => 'Uruguaanse peso',
    ),
    'UZS' => 
    array (
      'name' => 'Oezbekiese som',
    ),
    'VEF' => 
    array (
      'name' => 'Venezolaanse bolivar',
    ),
    'VUV' => 
    array (
      'name' => 'Vanuatu vatu',
    ),
    'WST' => 
    array (
      'name' => 'Samoaanse tala',
    ),
    'XXX' => 
    array (
      'name' => 'Onbekende geldeenheid',
    ),
    'YER' => 
    array (
      'name' => 'Jemenitiese rial',
    ),
    'ZMK' => 
    array (
      'name' => 'Zambiese kwacha',
    ),
    'ZWD' => 
    array (
      'name' => 'Zimbabwiese dollar',
    ),
  ),
  'languages' => 
  array (
    'ab' => 'Abkasies',
    'af' => 'Afrikaans',
    'ak' => 'Akan',
    'sq' => 'Albanees',
    'en_US' => 'Amerikaanse Engels',
    'am' => 'Amharies',
    'afa' => 'Ander Afro-Asiaties',
    'egy' => 'Antieke Egipties',
    'grc' => 'Antieke Grieks',
    'ar' => 'Arabies',
    'arc' => 'Aramees',
    'hy' => 'Armeens',
    'as' => 'Assamees',
    'en_AU' => 'Australiese Engels',
    'ay' => 'Aymara',
    'az' => 'Azeri',
    'bat' => 'Baltiese taal',
    'bnt' => 'Bantoe',
    'eu' => 'Baskies',
    'bn' => 'Bengaals',
    'ber' => 'Berbers',
    'bh' => 'Biharise taal',
    'my' => 'Birmaans',
    'bs' => 'Bosnies',
    'pt_BR' => 'Brasiliaanse Portugees',
    'br' => 'Bretons',
    'en_GB' => 'Britse Engels',
    'bg' => 'Bulgaars',
    'chr' => 'Cherokees',
    'da' => 'Deens',
    'dv' => 'Divehi',
    'de' => 'Duits',
    'dz' => 'Dzongkha',
    'efi' => 'Efik',
    'en' => 'Engels',
    'eo' => 'Esperanto',
    'et' => 'Estnies',
    'fo' => 'Faroees',
    'phn' => 'Fenisies',
    'fj' => 'Fidjiaans',
    'fil' => 'Filippyns',
    'fi' => 'Fins',
    'fr' => 'Frans',
    'gl' => 'Galisies',
    'sgn' => 'Gebaretaal',
    'zxx' => 'Geen linguistiese inhoud',
    'ka' => 'Georgies',
    'gem' => 'Germaanse taal',
    'got' => 'Goties',
    'el' => 'Grieks',
    'gn' => 'Guarani',
    'gu' => 'Gudjarati',
    'ha' => 'Hausa',
    'haw' => 'Hawaies',
    'ht' => 'Haïtiaans',
    'he' => 'Hebreeus',
    'hit' => 'Hetities',
    'hi' => 'Hindi',
    'hu' => 'Hongaars',
    'pt_PT' => 'Iberiese Portugees',
    'es_ES' => 'Iberiese Spaans',
    'ga' => 'Iers',
    'ig' => 'Igbo',
    'ine' => 'Indo-Europese taal',
    'id' => 'Indonesies',
    'ia' => 'Interlingua',
    'ie' => 'Interlingue',
    'it' => 'Italiaans',
    'ja' => 'Japannees',
    'jv' => 'Javaans',
    'yi' => 'Jiddisj',
    'en_CA' => 'Kanadese Engels',
    'fr_CA' => 'Kanadese Frans',
    'kn' => 'Kannada',
    'yue' => 'Kantonees',
    'ks' => 'Kasjmirs',
    'ca' => 'Katalaans',
    'kk' => 'Kazak',
    'cel' => 'Keltiese taal',
    'cu' => 'Kerkslawies',
    'km' => 'Khmer',
    'khi' => 'Khoi-San taal',
    'ky' => 'Kirgisies',
    'tlh' => 'Klingon',
    'ku' => 'Koerdies',
    'cop' => 'Kopties',
    'ko' => 'Koreaans',
    'kw' => 'Kornies',
    'hr' => 'Kroaties',
    'art' => 'Kunsmatige taal',
    'kru' => 'Kurukh',
    'lo' => 'Lao',
    'la' => 'Latyn',
    'es_419' => 'Latyns-Amerikaanse Spaans',
    'lv' => 'Letties',
    'li' => 'Limburgs',
    'ln' => 'Lingaals',
    'lt' => 'Litaus',
    'lb' => 'Luxemburgs',
    'ml' => 'Malabaars',
    'ms' => 'Maleisies',
    'mg' => 'Malgassies',
    'mt' => 'Maltees',
    'gv' => 'Manx',
    'mi' => 'Maori',
    'mr' => 'Marathi',
    'mas' => 'Masai',
    'mk' => 'Masedonies',
    'mn' => 'Mongools',
    'nl' => 'Nederlands',
    'ne' => 'Nepalees',
    'nd' => 'Noord-Ndebele',
    'nso' => 'Noord-Sotho',
    'se' => 'Noordelike Sami',
    'no' => 'Noors',
    'nb' => 'Noorse Bokmål',
    'nn' => 'Noorweegse Nynorsk',
    'ny' => 'Nyanja',
    'oc' => 'Occitaans',
    'uk' => 'Oekraïens',
    'ur' => 'Oerdoe',
    'uz' => 'Oezbeeks',
    'und' => 'Onbekende of ongeldige taal',
    'de_AT' => 'Oostenrykse Duits',
    'or' => 'Oriya',
    'os' => 'Osseties',
    'pa' => 'Pandjabi',
    'fa' => 'Persies',
    'pl' => 'Pools',
    'pt' => 'Portugees',
    'ps' => 'Pushto',
    'qu' => 'Quechua',
    'rm' => 'Reto-Romaans',
    'ro' => 'Roemeens',
    'rn' => 'Rundi',
    'ru' => 'Russies',
    'rw' => 'Rwandees',
    'sm' => 'Samoaans',
    'sg' => 'Sango',
    'sa' => 'Sanskrit',
    'sem' => 'Semitiese taal',
    'sr' => 'Serwies',
    'sh' => 'Serwo-Kroaties',
    'swb' => 'Shimaorees',
    'sn' => 'Shona',
    'sd' => 'Sindhi',
    'si' => 'Sinhala',
    'zh' => 'Sjinees',
    'sco' => 'Skots',
    'gd' => 'Skotse Gallies',
    'sla' => 'Slawiese taal',
    'sk' => 'Slowaaks',
    'sl' => 'Sloweens',
    'so' => 'Somalies',
    'es' => 'Spaans',
    'nr' => 'Suid-Ndebele',
    'st' => 'Suid-Sotho',
    'su' => 'Sundanees',
    'sw' => 'Swahili',
    'ss' => 'Swazi',
    'sv' => 'Sweeds',
    'gsw' => 'Switserse Duits',
    'fr_CH' => 'Switserse Frans',
    'de_CH' => 'Switserse hoog-Duits',
    'tg' => 'Tadjik',
    'ty' => 'Tahities',
    'ta' => 'Tamil',
    'tt' => 'Tataars',
    'te' => 'Telugu',
    'tet' => 'Tetum',
    'th' => 'Thais',
    'bo' => 'Tibettaans',
    'ti' => 'Tigrinya',
    'tpi' => 'Tok Pisin',
    'to' => 'Tonga',
    'zh_Hant' => 'Tradisionele Chinees',
    'cs' => 'Tsjeggies',
    'ts' => 'Tsonga',
    'tn' => 'Tswana',
    'tk' => 'Turkmeens',
    'tr' => 'Turks',
    'tw' => 'Twi',
    'ug' => 'Uyghur',
    'mul' => 'Veelvuldige tale',
    've' => 'Venda',
    'zh_Hans' => 'Vereenvoudigde Chinees',
    'vi' => 'Viëtnamees',
    'nl_BE' => 'Vlaams',
    'cy' => 'Wallies',
    'fy' => 'Wes-Fries',
    'be' => 'Wit-Russies',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yo' => 'Yoruba',
    'is' => 'Yslands',
    'zu' => 'Zoeloe',
  ),
  'countries' => 
  array (
    'AF' => 'Afganistan',
    'AL' => 'Albanië',
    'DZ' => 'Algerië',
    'AS' => 'Amerikaans Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarktika',
    'AG' => 'Antigua en Barbuda',
    'AR' => 'Argentinië',
    'AM' => 'Armenië',
    'AW' => 'Aruba',
    'AC' => 'Ascension-eiland',
    'AZ' => 'Aserbeidjan',
    'AU' => 'Australië',
    'BS' => 'Bahamas',
    'BH' => 'Bahrein',
    'BD' => 'Bangladesj',
    'BB' => 'Barbados',
    'BE' => 'België',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhoetan',
    'BF' => 'Boerkina Fasso',
    'BO' => 'Bolivië',
    'BA' => 'Bosnië en Herzegowina',
    'BW' => 'Botswana',
    'BV' => 'Bouveteiland',
    'BR' => 'Brasilië',
    'IO' => 'Britse Indiese Oseaan Gebied',
    'VG' => 'Britse Maagde-eilande',
    'BN' => 'Broenei',
    'BG' => 'Bulgarye',
    'BI' => 'Burundi',
    'EA' => 'Ceuta en Melilla',
    'CL' => 'Chili',
    'CY' => 'Ciprus',
    'CP' => 'Clipperton-eiland',
    'CC' => 'Cocos- [Keeling] eilande',
    'KM' => 'Comore',
    'CK' => 'Cookeilande',
    'CR' => 'Costa Rica',
    'DK' => 'Denemarke',
    'DG' => 'Diego Garcia',
    'DJ' => 'Djiboeti',
    'DM' => 'Dominika',
    'DO' => 'Dominikaanse Republiek',
    'DE' => 'Duitsland',
    'EC' => 'Ecuador',
    'EG' => 'Egipte',
    'IM' => 'Eiland Man',
    'GQ' => 'Ekwatoriaal-Guinee',
    'ER' => 'Eritrea',
    'EE' => 'Estland',
    'ET' => 'Ethiopië',
    'EU' => 'Europese Unie',
    'FK' => 'Falkland-eilande [Malvinas]',
    'FO' => 'Faroëreilande',
    'FJ' => 'Fidji',
    'PH' => 'Filippyne',
    'FI' => 'Finland',
    'FR' => 'Frankryk',
    'GF' => 'Frans-Guyana',
    'PF' => 'Frans-Polinesië',
    'TF' => 'Franse Suidelike Gebiede',
    'GA' => 'Gaboen',
    'GM' => 'Gambië',
    'GE' => 'Georgië',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GD' => 'Grenada',
    'GR' => 'Griekeland',
    'GL' => 'Groenland',
    'GB' => 'Groot-Brittanje',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinee',
    'GW' => 'Guinee-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haïti',
    'HM' => 'Heard-eiland en McDonald-eilande',
    'HN' => 'Honduras',
    'HU' => 'Hongarye',
    'HK' => 'Hongkong',
    'IE' => 'Ierland',
    'IN' => 'Indië',
    'ID' => 'Indonesië',
    'IQ' => 'Irak',
    'IR' => 'Iran',
    'IL' => 'Israel',
    'IT' => 'Italië',
    'CI' => 'Ivoorkus',
    'JM' => 'Jamaika',
    'JP' => 'Japan',
    'YE' => 'Jemen',
    'JE' => 'Jersey',
    'JO' => 'Jordanië',
    'KY' => 'Kaaimanseilande',
    'CV' => 'Kaap Verde',
    'KH' => 'Kambodja',
    'CM' => 'Kameroen',
    'CA' => 'Kanada',
    'IC' => 'Kanarie-eilande',
    'KZ' => 'Kasakstan',
    'QA' => 'Katar',
    'KE' => 'Kenia',
    'CX' => 'Kerseiland',
    'KG' => 'Kirgisië',
    'KI' => 'Kiribati',
    'KW' => 'Koeweit',
    'CO' => 'Kolombië',
    'CD' => 'Kongo (DRK)',
    'CG' => 'Kongo [Republiek]',
    'HR' => 'Kroasië',
    'CU' => 'Kuba',
    'LA' => 'Laos',
    'LS' => 'Lesotho',
    'LV' => 'Letland',
    'LB' => 'Libanon',
    'LR' => 'Liberië',
    'LY' => 'Libië',
    'LI' => 'Liechtenstein',
    'LT' => 'Litaue',
    'LU' => 'Luxemburg',
    'MO' => 'Macau',
    'MK' => 'Macedonië',
    'MG' => 'Madagaskar',
    'MW' => 'Malawi',
    'MV' => 'Maledive',
    'MY' => 'Maleisië',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MA' => 'Marokko',
    'MH' => 'Marshall-eilande',
    'MQ' => 'Martinique',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Meksiko',
    'MM' => 'Mianmar',
    'FM' => 'Mikronesië',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolië',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MZ' => 'Mosambiek',
    'MR' => 'Mouritanië',
    'NA' => 'Namibië',
    'NR' => 'Naoeroe',
    'NL' => 'Nederland',
    'AN' => 'Nederlands-Antille',
    'NP' => 'Nepal',
    'NI' => 'Nicaragua',
    'NC' => 'Nieu-Kaledonië',
    'NZ' => 'Nieu-Seeland',
    'NE' => 'Niger',
    'NG' => 'Nigerië',
    'NU' => 'Niue',
    'KP' => 'Noord-Korea',
    'MP' => 'Noordelike Marianaeilande',
    'NO' => 'Noorweë',
    'NF' => 'Norfolk-eiland',
    'UA' => 'Oekraine',
    'UZ' => 'Oesbekistan',
    'OM' => 'Oman',
    'QO' => 'Omliggende Oseanië',
    'ZZ' => 'Onbekend gebied',
    'TL' => 'Oos-Timor',
    'AT' => 'Oostenryk',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestina',
    'PA' => 'Panama',
    'PG' => 'Papoea Nieu-Guinee',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PN' => 'Pitcairn',
    'PL' => 'Pole',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'RO' => 'Roemenië',
    'RU' => 'Rusland',
    'RW' => 'Rwanda',
    'RE' => 'Réunion',
    'KN' => 'Saint Kitts en Nevis',
    'VC' => 'Saint Vincent en die Grenadine',
    'SV' => 'Salvador',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome en Principe',
    'SA' => 'Saoedi-Arabië',
    'SN' => 'Senegal',
    'CF' => 'Sentraal-Afrikaanse Republiek',
    'RS' => 'Serwië',
    'CS' => 'Serwië en Montenegro',
    'SC' => 'Seychelle',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapoer',
    'BL' => 'Sint Barthélemy',
    'SH' => 'Sint Helena',
    'LC' => 'Sint Lucia',
    'MF' => 'Sint Martin',
    'PM' => 'Sint-Pierre en Miquelon',
    'SY' => 'Sirië',
    'CN' => 'Sjina',
    'SK' => 'Slowakye',
    'SI' => 'Slowenië',
    'SD' => 'Soedan',
    'SB' => 'Solomon Eilande',
    'SO' => 'Somalië',
    'ES' => 'Spanje',
    'LK' => 'Sri Lanka',
    'ZA' => 'Suid-Afrika',
    'GS' => 'Suid-Georgië en die Suid-Sandwich-eilande',
    'KR' => 'Suid-Korea',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard en Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Swede',
    'CH' => 'Switserland',
    'TJ' => 'Tadjikistan',
    'TW' => 'Taiwan',
    'TZ' => 'Tanzanië',
    'TH' => 'Thailand',
    'CZ' => 'Tjeggiese Republiek',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad en Tobago',
    'TA' => 'Tristan da Cunha',
    'TD' => 'Tsjaad',
    'TN' => 'Tunisië',
    'TM' => 'Turkmenië',
    'TC' => 'Turks en Caicos Eilande',
    'TR' => 'Turkye',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UY' => 'Uruguay',
    'VI' => 'V.S. Maagde-eilande',
    'UM' => 'VS klein omliggende eilande',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikaan',
    'VE' => 'Venezuela',
    'AE' => 'Verenigde Arabiese Emirate',
    'US' => 'Verenigde State van Amerika',
    'VN' => 'Viëtnam',
    'WF' => 'Wallis en Futuna',
    'EH' => 'Wes-Sahara',
    'BY' => 'Wit-Rusland',
    'IS' => 'Ysland',
    'ZM' => 'Zambië',
    'ZW' => 'Zimbabwe',
    'AX' => 'Åland-eilande',
  ),
);
