<?php
/**
 * Locale data for 'chr'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5905',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM d, y',
    'long' => 'MMMM d, y',
    'medium' => 'MMM d, y',
    'short' => 'M/d/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ᎤᏃᎸᏔᏅ',
      2 => 'ᎧᎦᎵ',
      3 => 'ᎠᏅᏱ',
      4 => 'ᎧᏬᏂ',
      5 => 'ᎠᏂᏍᎬᏘ',
      6 => 'ᏕᎭᎷᏱ',
      7 => 'ᎫᏰᏉᏂ',
      8 => 'ᎦᎶᏂ',
      9 => 'ᏚᎵᏍᏗ',
      10 => 'ᏚᏂᏅᏗ',
      11 => 'ᏅᏓᏕᏆ',
      12 => 'ᎤᏍᎩᏱ',
    ),
    'abbreviated' => 
    array (
      1 => 'ᎤᏃ',
      2 => 'ᎧᎦ',
      3 => 'ᎠᏅ',
      4 => 'ᎧᏬ',
      5 => 'ᎠᏂ',
      6 => 'ᏕᎭ',
      7 => 'ᎫᏰ',
      8 => 'ᎦᎶ',
      9 => 'ᏚᎵ',
      10 => 'ᏚᏂ',
      11 => 'ᏅᏓ',
      12 => 'ᎤᏍ',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Ꭴ',
      2 => 'Ꭷ',
      3 => 'Ꭰ',
      4 => 'Ꭷ',
      5 => 'Ꭰ',
      6 => 'Ꮥ',
      7 => 'Ꭻ',
      8 => 'Ꭶ',
      9 => 'Ꮪ',
      10 => 'Ꮪ',
      11 => 'Ꮕ',
      12 => 'Ꭴ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ᎤᎾᏙᏓᏆᏍᎬ',
      1 => 'ᎤᎾᏙᏓᏉᏅᎯ',
      2 => 'ᏔᎵᏁᎢᎦ',
      3 => 'ᏦᎢᏁᎢᎦ',
      4 => 'ᏅᎩᏁᎢᎦ',
      5 => 'ᏧᎾᎩᎶᏍᏗ',
      6 => 'ᎤᎾᏙᏓᏈᏕᎾ',
    ),
    'abbreviated' => 
    array (
      0 => 'ᏆᏍᎬ',
      1 => 'ᏉᏅᎯ',
      2 => 'ᏔᎵᏁ',
      3 => 'ᏦᎢᏁ',
      4 => 'ᏅᎩᏁ',
      5 => 'ᏧᎾᎩ',
      6 => 'ᏈᏕᎾ',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Ꮖ',
      1 => 'Ꮙ',
      2 => 'Ꮤ',
      3 => 'Ꮶ',
      4 => 'Ꮕ',
      5 => 'Ꮷ',
      6 => 'Ꭴ',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'ᏆᏏᎵᎢ ᎠᏕᎳ',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'ᎧᎾᏓ ᎠᏕᎳ',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'ᏓᎶᏂᎨ ᎠᏕᎳ',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'ᏳᎳᏛ',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'ᎩᎵᏏᏲ ᎠᏕᎳ',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'ᎢᏅᏗᎾ ᎠᏕᎳ',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'ᏣᏩᏂᏏ ᎠᏕᎳ',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'ᏍᏆᏂ ᎠᏕᎳ',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => '$',
      'name' => 'ᎤᏃᏍᏗ',
      'name-single' => 'ᎤᏃᏍᏗ',
      'name-multiple' => 'ᏧᏃᏍᏗ',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'RUB' => 
    array (
      'name' => 'ᏲᏂᎢ ᎠᏕᎳ',
    ),
  ),
  'languages' => 
  array (
    'mus' => 'ᎠᎫᏌ',
    'de' => 'ᎠᏂᏓᏥ',
    'cho' => 'ᎠᏣᏗ',
    'fr' => 'ᎦᎸᏥ',
    'cay' => 'ᎦᏳᎦ',
    'en' => 'ᎩᎵᏏ',
    'it' => 'ᎬᏩᎵᏲᏥᎢ',
    'moh' => 'ᎼᎻᎦ',
    'und' => 'ᏄᏬᎵᏍᏛᎾ ᎦᏬᏂᎯᏍᏗ',
    'pt' => 'ᏉᏧᎦᎵ',
    'es' => 'ᏍᏆᏂ',
    'see' => 'ᏏᏂᎦ',
    'zh' => 'ᏓᎶᏂᎨ',
    'chr' => 'ᏣᎳᎩ',
    'ja' => 'ᏣᏩᏂᏏ',
    'ru' => 'ᏲᏂᎢ',
  ),
  'countries' => 
  array (
    'US' => 'ᎠᎹᏰᏟ',
    'DE' => 'ᎠᏂᏛᏥ',
    'IN' => 'ᎢᏅᏗᎾ',
    'FR' => 'ᎦᎸᏥᏱ',
    'CA' => 'ᎨᎾᏓ',
    'GB' => 'ᎩᎵᏏᏲ',
    'ZZ' => 'ᏄᏬᎵᏍᏛᎾ ᎤᏔᏂᏗᎦᏙᎯ',
    'BR' => 'ᏆᏏᎵᎢ',
    'MX' => 'ᏍᏆᏂᏱ',
    'CN' => 'ᏓᎶᏂᎨᏍᏛ',
    'JP' => 'ᏣᏩᏂᏏ',
    'IT' => 'ᏲᎶ',
    'RU' => 'ᏲᏂᎢ',
  ),
);
