<?php
/**
 * Locale data for 'ha_Latn_GH'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '4123',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM, y',
    'long' => 'd MMMM, y',
    'medium' => 'd MMM, y',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Janairu',
      2 => 'Faburairu',
      3 => 'Maris',
      4 => 'Afirilu',
      5 => 'Mayu',
      6 => 'Yuni',
      7 => 'Yuli',
      8 => 'Agusta',
      9 => 'Satumba',
      10 => 'Oktoba',
      11 => 'Nuwamba',
      12 => 'Disamba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Fab',
      3 => 'Mar',
      4 => 'Afi',
      5 => 'May',
      6 => 'Yun',
      7 => 'Yul',
      8 => 'Agu',
      9 => 'Sat',
      10 => 'Okt',
      11 => 'Nuw',
      12 => 'Dis',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Lahadi',
      1 => 'Litinin',
      2 => 'Talata',
      3 => 'Laraba',
      4 => 'Alhamis',
      5 => 'Jumma\'a',
      6 => 'Asabar',
    ),
    'abbreviated' => 
    array (
      0 => 'Lh',
      1 => 'Li',
      2 => 'Ta',
      3 => 'Lr',
      4 => 'Al',
      5 => 'Ju',
      6 => 'As',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'L',
      1 => 'L',
      2 => 'T',
      3 => 'L',
      4 => 'A',
      5 => 'J',
      6 => 'A',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Dalar Ostareliya',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Dalar Kanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Kuɗin Caina/Sin',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Yuro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Fam kin Ingila',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Kuɗin Indiya',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Kuɗin Japan',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Dalar Amurka',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Kuɗin Sefa na Afirka Ta Tsakiya',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Kuɗin Sefa na Afirka Ta Yamma',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'NGN' => 
    array (
      'symbol' => '₦',
      'name' => 'Naira',
    ),
    'AED' => 
    array (
      'name' => 'Kuɗin Haɗaɗɗiyar Daular Larabawa',
    ),
    'AOA' => 
    array (
      'name' => 'Kuɗin Angola',
    ),
    'BHD' => 
    array (
      'name' => 'Kuɗin Baharan',
    ),
    'BIF' => 
    array (
      'name' => 'Kuɗin Burundi',
    ),
    'BWP' => 
    array (
      'name' => 'Kuɗin Baswana',
    ),
    'CDF' => 
    array (
      'name' => 'Kuɗin Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'Kuɗin Suwizalan',
    ),
    'CVE' => 
    array (
      'name' => 'Kuɗin Tsibiran Kap Barde',
    ),
    'DJF' => 
    array (
      'name' => 'Kuɗin Jibuti',
    ),
    'DZD' => 
    array (
      'name' => 'Kuɗin Aljeriya',
    ),
    'EGP' => 
    array (
      'name' => 'Fam kin Masar',
    ),
    'ERN' => 
    array (
      'name' => 'Kuɗin Eritireya',
    ),
    'ETB' => 
    array (
      'name' => 'Kuɗin Habasha',
    ),
    'GHC' => 
    array (
      'name' => 'Cedi',
    ),
    'GMD' => 
    array (
      'name' => 'Kuɗin Gambiya',
    ),
    'GNS' => 
    array (
      'name' => 'Kuɗin Gini',
    ),
    'KES' => 
    array (
      'name' => 'Sulen Kenya',
    ),
    'KMF' => 
    array (
      'name' => 'Kuɗin Kwamoras',
    ),
    'LRD' => 
    array (
      'name' => 'Dalar Laberiya',
    ),
    'LSL' => 
    array (
      'name' => 'Kuɗin Lesoto',
    ),
    'LYD' => 
    array (
      'name' => 'Kuɗin Libiya',
    ),
    'MAD' => 
    array (
      'name' => 'Kuɗin Maroko',
    ),
    'MGA' => 
    array (
      'name' => 'Kuɗin Madagaskar',
    ),
    'MRO' => 
    array (
      'name' => 'Kuɗin Moritaniya',
    ),
    'MUR' => 
    array (
      'name' => 'Kuɗin Moritus',
    ),
    'MWK' => 
    array (
      'name' => 'Kuɗin Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Kuɗin Mozambik',
    ),
    'NAD' => 
    array (
      'name' => 'Dalar Namibiya',
    ),
    'RWF' => 
    array (
      'name' => 'Kuɗin Ruwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Riyal',
    ),
    'SCR' => 
    array (
      'name' => 'Kuɗin Saishal',
    ),
    'SDG' => 
    array (
      'name' => 'Fam kin Sudan',
    ),
    'SHP' => 
    array (
      'name' => 'Fam kin San Helena',
    ),
    'SLL' => 
    array (
      'name' => 'Kuɗin Salewo',
    ),
    'SOS' => 
    array (
      'name' => 'Sulen Somaliya',
    ),
    'STD' => 
    array (
      'name' => 'Kuɗin Sawo Tome da Paransip',
    ),
    'SZL' => 
    array (
      'name' => 'Kuɗin Lilangeni',
    ),
    'TND' => 
    array (
      'name' => 'Kuɗin Tunisiya',
    ),
    'TZS' => 
    array (
      'name' => 'Sulen Tanzaniya',
    ),
    'UGX' => 
    array (
      'name' => 'Sule Yuganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Kuɗin Afirka Ta Kudu',
    ),
    'ZMK' => 
    array (
      'name' => 'Kuɗin Zambiya',
    ),
    'ZWD' => 
    array (
      'name' => 'Dalar zimbabuwe',
    ),
  ),
  'languages' => 
  array (
    'af' => 'Afirkanci',
    'ak' => 'Akan',
    'am' => 'Amharik',
    'hy' => 'Armeniyanci',
    'as' => 'Asamisanci',
    'az' => 'Azerbaijanci',
    'gl' => 'Bagalike',
    'sl' => 'Basulabe',
    'sk' => 'Basulake',
    'xh' => 'Bazosa',
    'be' => 'Belarusanci',
    'bn' => 'Bengali',
    'bh' => 'Bihari',
    'bs' => 'Bosniyanci',
    'bg' => 'Bulgaranci',
    'br' => 'Buretananci',
    'my' => 'Burmanci',
    'sq' => 'D\'an/\'Yar Kabilar Albaniya',
    'eo' => 'D\'an/\'Yar Kabilar Andalus',
    'te' => 'D\'an/\'Yar Kabilar Telug',
    'ga' => 'Dan Ailan',
    'fil' => 'Dan Filifin',
    'la' => 'Dan Kabilar Latin',
    'mk' => 'Dan Masedoniya',
    'eu' => 'Dan/\'Yar Kabilar Bas',
    'kn' => 'Dan/\'Yar Kabilar Kannada',
    'da' => 'Danish',
    'fr' => 'Faransanci',
    'fo' => 'Faroese',
    'pt_BR' => 'Fotigis (Burazil)',
    'el' => 'Girkanci',
    'gu' => 'Gujarati',
    'gn' => 'Guwaraniyanci',
    'vi' => 'Harshen Biyetinam',
    'cs' => 'Harshen Cak',
    'hi' => 'Harshen Hindi',
    'hu' => 'Harshen Hungari',
    'id' => 'Harshen Indunusiya',
    'km' => 'Harshen Kimar',
    'ko' => 'Harshen Koreya',
    'ms' => 'Harshen Malai',
    'mt' => 'Harshen Maltis',
    'pl' => 'Harshen Polan',
    'pt' => 'Harshen Portugal',
    'zh' => 'Harshen Sin',
    'sw' => 'Harshen Suwahili',
    'sv' => 'Harshen Suwedan',
    'tr' => 'Harshen Turkiyya',
    'ur' => 'Harshen Urdu',
    'uk' => 'Harshen Yukuren',
    'zu' => 'Harshen Zulu',
    'ha' => 'Hausa',
    'nl' => 'Holanci',
    'ie' => 'Intagulanci',
    'ig' => 'Inyamuranci',
    'es' => 'Ispaniyanci',
    'et' => 'Istoniyanci',
    'it' => 'Italiyanci',
    'jv' => 'Jabananci',
    'de' => 'Jamusanci',
    'ja' => 'Japananci',
    'ka' => 'Jojiyanci',
    'fy' => 'K\'abilan Firsi',
    'mr' => 'K\'abilan Marathi',
    'gd' => 'K\'abilan Scots Gaelic',
    'ml' => 'Kabilar Maleyalam',
    'cy' => 'Kabilar Welsh',
    'ca' => 'Kataloniyanci',
    'rw' => 'Kiniyaruwanda',
    'ky' => 'Kirgizanci',
    'tlh' => 'Klingon',
    'ku' => 'Kurdanci',
    'hr' => 'Kuroshiyan',
    'sh' => 'Kuroweshiyancin-Sabiya',
    'lo' => 'Laothian',
    'ar' => 'Larabci',
    'lv' => 'Latbiyanci',
    'ln' => 'Lingala',
    'lt' => 'Lituweniyanci',
    'mn' => 'Mongolian',
    'ne' => 'Nepali',
    'or' => 'Oriyanci',
    'oc' => 'Ositanci',
    'fa' => 'Parisanci',
    'ps' => 'Pashtanci',
    'pa' => 'Punjabi',
    'ru' => 'Rashanci',
    'ro' => 'Romaniyanci',
    'sr' => 'Sabiyan',
    'sa' => 'Sanskrit',
    'st' => 'Sesotanci',
    'sd' => 'Sindiyanci',
    'si' => 'Sinhalanci',
    'so' => 'Somali',
    'su' => 'Sundanese',
    'ta' => 'Tamil',
    'th' => 'Thai',
    'ti' => 'Tigriyanci',
    'tw' => 'Tiwiniyanci',
    'tk' => 'Tukmenistanci',
    'en' => 'Turanci',
    'ug' => 'Ugiranci',
    'uz' => 'Uzbek',
    'he' => 'Yahudanci',
    'yo' => 'Yarbanci',
    'ia' => 'Yare Tsakanin Kasashe',
    'nn' => 'Yaren Kasar Norway',
    'pt_PT' => 'Yaren Kasar Portugal',
    'fi' => 'Yaren mutanen Finland',
    'is' => 'Yaren mutanen Iceland',
    'no' => 'Yaren mutanen Norway',
  ),
  'countries' => 
  array (
    'AF' => 'Afaganistan',
    'ZA' => 'Afirka Ta Kudu',
    'CI' => 'Aibari Kwas',
    'IS' => 'Aisalan',
    'AL' => 'Albaniya',
    'DZ' => 'Aljeriya',
    'US' => 'Amurka',
    'AD' => 'Andora',
    'AI' => 'Angila',
    'AO' => 'Angola',
    'AG' => 'Antigwa da Barbuba',
    'AN' => 'Antiya Na Holan',
    'AR' => 'Arjantiniya',
    'AM' => 'Armeniya',
    'AW' => 'Aruba',
    'IE' => 'Ayalan',
    'AZ' => 'Azarbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Baharan',
    'BD' => 'Bangiladas',
    'VU' => 'Banuwatu',
    'BB' => 'Barbadas',
    'BM' => 'Barmuda',
    'BW' => 'Baswana',
    'VA' => 'Batikan',
    'BY' => 'Belarus',
    'BE' => 'Belgiyom',
    'BZ' => 'Beliz',
    'VE' => 'Benezuwela',
    'BJ' => 'Binin',
    'BR' => 'Birazil',
    'GB' => 'Birtaniya',
    'VN' => 'Biyetinam',
    'BO' => 'Bolibiya',
    'BA' => 'Bosniya Harzagobina',
    'BG' => 'Bulgariya',
    'BF' => 'Burkina Faso',
    'MM' => 'Burma, Miyamar',
    'BI' => 'Burundi',
    'BN' => 'Burune',
    'BT' => 'Butan',
    'TD' => 'Cadi',
    'CN' => 'Caina, Sin',
    'CL' => 'Cayile',
    'DK' => 'Danmark',
    'DM' => 'Dominika',
    'EC' => 'Ekwador',
    'SV' => 'El Salbador',
    'ER' => 'Eritireya',
    'EE' => 'Estoniya',
    'FR' => 'Faransa',
    'FJ' => 'Fiji',
    'PH' => 'Filipin',
    'FI' => 'Finlan',
    'PF' => 'Folinesiya Ta Faransa',
    'GA' => 'Gabon',
    'GM' => 'Gambiya',
    'GH' => 'Gana',
    'GN' => 'Gini',
    'GW' => 'Gini Bisau',
    'GF' => 'Gini Ta Faransa',
    'GQ' => 'Gini Ta Ikwaita',
    'GR' => 'Girka',
    'GD' => 'Girnada',
    'GL' => 'Grinlan',
    'GY' => 'Guyana',
    'GP' => 'Gwadaluf',
    'GU' => 'Gwam',
    'GT' => 'Gwatamala',
    'ET' => 'Habasha',
    'HT' => 'Haiti',
    'AE' => 'Haɗaɗɗiyar Daular Larabawa',
    'NL' => 'Holan',
    'HN' => 'Honduras',
    'HU' => 'Hungari',
    'IN' => 'Indiya',
    'ID' => 'Indunusiya',
    'IR' => 'Iran',
    'IQ' => 'Iraƙi',
    'IT' => 'Italiya',
    'IL' => 'Izira\'ila',
    'JM' => 'Jamaika',
    'CF' => 'Jamhuriyar Afirka Ta Tsakiya',
    'CZ' => 'Jamhuriyar Cak',
    'CD' => 'Jamhuriyar Dimokuraɗiyyar Kongo',
    'DO' => 'Jamhuriyar Dominika',
    'DE' => 'Jamus',
    'JP' => 'Japan',
    'GI' => 'Jibaraltar',
    'DJ' => 'Jibuti',
    'GE' => 'Jiwarjiya',
    'JO' => 'Jordan',
    'NC' => 'Kaledoniya Sabuwa',
    'CM' => 'Kamaru',
    'KH' => 'Kambodiya',
    'CA' => 'Kanada',
    'KZ' => 'Kazakistan',
    'KE' => 'Kenya',
    'KG' => 'Kirgizistan',
    'KI' => 'Kiribati',
    'CO' => 'Kolambiya',
    'CG' => 'Kongo',
    'KP' => 'Koreya Ta Arewa',
    'KR' => 'Koreya Ta Kudu',
    'HR' => 'Kurowaishiya',
    'KM' => 'Kwamoras',
    'CR' => 'Kwasta Rika',
    'QA' => 'Kwatar',
    'KW' => 'Kwiyat',
    'CU' => 'Kyuba',
    'LB' => 'Labanan',
    'LR' => 'Laberiya',
    'LV' => 'Latibiya',
    'LA' => 'Lawas',
    'LS' => 'Lesoto',
    'LY' => 'Libiya',
    'LI' => 'Licansitan',
    'LT' => 'Lituweniya',
    'LU' => 'Lukusambur',
    'MG' => 'Madagaskar',
    'MX' => 'Makasiko',
    'MY' => 'Malaisiya',
    'MW' => 'Malawi',
    'MV' => 'Maldibi',
    'MD' => 'Maldoba',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MN' => 'Mangoliya',
    'MS' => 'Manserati',
    'MA' => 'Maroko',
    'MQ' => 'Martinik',
    'EG' => 'Masar, Misira',
    'MK' => 'Masedoniya',
    'YT' => 'Mayoti',
    'FM' => 'Mikuronesiya',
    'MC' => 'Monako',
    'MR' => 'Moritaniya',
    'MU' => 'Moritus',
    'MZ' => 'Mozambik',
    'NG' => 'Najeriya',
    'NA' => 'Namibiya',
    'NR' => 'Nauru',
    'NP' => 'Nefal',
    'NE' => 'Nijar',
    'NI' => 'Nikaraguwa',
    'NU' => 'Niyu',
    'NO' => 'Norwe',
    'NZ' => 'Nuzilan',
    'OM' => 'Oman',
    'AU' => 'Ostareliya',
    'AT' => 'Ostiriya',
    'PK' => 'Pakistan',
    'PS' => 'Palasɗinu',
    'PW' => 'Palau',
    'PA' => 'Panama',
    'PG' => 'Papuwa Nugini',
    'PY' => 'Paragai',
    'PE' => 'Peru',
    'PN' => 'Pitakarin',
    'PL' => 'Polan',
    'PR' => 'Porto Riko',
    'PT' => 'Portugal',
    'RU' => 'Rasha',
    'RE' => 'Rawuniyan',
    'RO' => 'Romaniya',
    'RW' => 'Ruwanda',
    'SC' => 'Saishal',
    'SL' => 'Salewo',
    'WS' => 'Samowa',
    'AS' => 'Samowa Ta Amurka',
    'VC' => 'San Binsan Da Girnadin',
    'SH' => 'San Helena',
    'KN' => 'San Kiti Da Nebis',
    'LC' => 'San Lusiya',
    'SM' => 'San Marino',
    'PM' => 'San Piyar Da Mikelan',
    'CS' => 'Sarbiya Da Mantanegiro',
    'ST' => 'Sawo Tome Da Paransip',
    'SY' => 'Sham, Siriya',
    'CY' => 'Sifurus',
    'SG' => 'Singapur',
    'SN' => 'Sinigal',
    'ES' => 'Sipen',
    'LK' => 'Siri Lanka',
    'SO' => 'Somaliya',
    'SD' => 'Sudan',
    'SK' => 'Sulobakiya',
    'SI' => 'Sulobeniya',
    'SR' => 'Suriname',
    'SZ' => 'Suwazilan',
    'SE' => 'Suwedan',
    'CH' => 'Suwizalan',
    'TH' => 'Tailan',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TK' => 'Takelau',
    'TO' => 'Tanga',
    'TZ' => 'Tanzaniya',
    'TL' => 'Timor Ta Gabas',
    'TT' => 'Tirinidad Da Tobago',
    'TG' => 'Togo',
    'VI' => 'Tsibiran Birjin Ta Amurka',
    'FK' => 'Tsibiran Falkilan',
    'KY' => 'Tsibiran Kaiman',
    'CV' => 'Tsibiran Kap Barde',
    'CK' => 'Tsibiran Kuku',
    'MP' => 'Tsibiran Mariyana Na Arewa',
    'MH' => 'Tsibiran Marshal',
    'SB' => 'Tsibiran Salaman',
    'VG' => 'Tsibirin Birjin Na Birtaniya',
    'NF' => 'Tsibirin Narfalk',
    'TV' => 'Tubalu',
    'TN' => 'Tunisiya',
    'TC' => 'Turkis Da Tsibiran Kaikwas',
    'TR' => 'Turkiyya',
    'TM' => 'Turkumenistan',
    'UZ' => 'Uzubekistan',
    'WF' => 'Walis Da Futuna',
    'YE' => 'Yamal',
    'IO' => 'Yankin Birtaniya Na Tekun Indiya',
    'UG' => 'Yuganda',
    'UA' => 'Yukaran',
    'UY' => 'Yurugai',
    'ZM' => 'Zambiya',
    'ZW' => 'Zimbabuwe',
    'SA' => 'Ƙasar Makka',
  ),
);
