<?php
/**
 * Locale data for 'kab_DZ'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM, y',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Yennayer',
      2 => 'Fuṛar',
      3 => 'Meɣres',
      4 => 'Yebrir',
      5 => 'Mayyu',
      6 => 'Yunyu',
      7 => 'Yulyu',
      8 => 'Ɣuct',
      9 => 'Ctembeṛ',
      10 => 'Tubeṛ',
      11 => 'Nunembeṛ',
      12 => 'Duǧembeṛ',
    ),
    'abbreviated' => 
    array (
      1 => 'Yen',
      2 => 'Fur',
      3 => 'Meɣ',
      4 => 'Yeb',
      5 => 'May',
      6 => 'Yun',
      7 => 'Yul',
      8 => 'Ɣuc',
      9 => 'Cte',
      10 => 'Tub',
      11 => 'Nun',
      12 => 'Duǧ',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Y',
      2 => 'F',
      3 => 'M',
      4 => 'Y',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'Ɣ',
      9 => 'C',
      10 => 'T',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Yanass',
      1 => 'Sanass',
      2 => 'Kraḍass',
      3 => 'Kuẓass',
      4 => 'Samass',
      5 => 'Sḍisass',
      6 => 'Sayass',
    ),
    'abbreviated' => 
    array (
      0 => 'Yan',
      1 => 'San',
      2 => 'Kraḍ',
      3 => 'Kuẓ',
      4 => 'Sam',
      5 => 'Sḍis',
      6 => 'Say',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Y',
      1 => 'S',
      2 => 'K',
      3 => 'K',
      4 => 'S',
      5 => 'S',
      6 => 'S',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Adular n Lusṭrali',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Adular Akanadi',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Ayuwan Renminbi Acinwa',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Uru',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Apund Sterling Aglizi',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Arupi Ahendi',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Ayen Ajappuni',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Adular WD',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Afrank BCEA CFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Afrank BCEAO CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'DZD' => 
    array (
      'symbol' => 'DA',
      'name' => 'Adinar Azzayri',
    ),
    'AED' => 
    array (
      'name' => 'Adirham n Tgeldunin Taɛrabin Yedduklen',
    ),
    'AOA' => 
    array (
      'name' => 'Akwanza n Ungula',
    ),
    'BHD' => 
    array (
      'name' => 'Adinar Abaḥrini',
    ),
    'BIF' => 
    array (
      'name' => 'Afrank Aburandi',
    ),
    'BWP' => 
    array (
      'name' => 'Apula Abusṭwanan',
    ),
    'CDF' => 
    array (
      'name' => 'Afrank Akunguli',
    ),
    'CHF' => 
    array (
      'name' => 'Afrank Aswis',
    ),
    'CVE' => 
    array (
      'name' => 'Akabuviradinu Askudi',
    ),
    'DJF' => 
    array (
      'name' => 'Afrank Ajibuti',
    ),
    'EGP' => 
    array (
      'name' => 'Apund Amaṣri',
    ),
    'ERN' => 
    array (
      'name' => 'Anakfa Iritiri',
    ),
    'ETB' => 
    array (
      'name' => 'Abir Utyupi',
    ),
    'GHC' => 
    array (
      'name' => 'Asidi Aɣani',
    ),
    'GMD' => 
    array (
      'name' => 'Adalasi Agambi',
    ),
    'GNS' => 
    array (
      'name' => 'Afrank Aɣini',
    ),
    'KES' => 
    array (
      'name' => 'Aciling Akini',
    ),
    'KMF' => 
    array (
      'name' => 'Afrank Akamiruni',
    ),
    'LRD' => 
    array (
      'name' => 'Adular Alibiri',
    ),
    'LSL' => 
    array (
      'name' => 'Aluṭi Alizuṭi',
    ),
    'LYD' => 
    array (
      'name' => 'Adinar Alibi',
    ),
    'MAD' => 
    array (
      'name' => 'Adirham Amerruki',
    ),
    'MGA' => 
    array (
      'name' => 'Aryari Amalgac',
    ),
    'MRO' => 
    array (
      'name' => 'Agiya Amuriṭani',
    ),
    'MUR' => 
    array (
      'name' => 'Arupi Amurisi',
    ),
    'MWK' => 
    array (
      'name' => 'Akwaca Amalawi',
    ),
    'MZM' => 
    array (
      'name' => 'Amitikal Amuzembiqi',
    ),
    'NAD' => 
    array (
      'name' => 'Adular Anamibi',
    ),
    'NGN' => 
    array (
      'name' => 'Anayra Anijiri',
    ),
    'RWF' => 
    array (
      'name' => 'Afrank Aruwandi',
    ),
    'SAR' => 
    array (
      'name' => 'Aryal Asuɛudi',
    ),
    'SCR' => 
    array (
      'name' => 'Arupi Aseycili',
    ),
    'SDG' => 
    array (
      'name' => 'Apund Asudani',
    ),
    'SHP' => 
    array (
      'name' => 'Apund Asant Ilini',
    ),
    'SLL' => 
    array (
      'name' => 'Alyun',
    ),
    'SOS' => 
    array (
      'name' => 'Aciling Aṣumali',
    ),
    'STD' => 
    array (
      'name' => 'Asw Ṭum d Udubra Amenzay',
    ),
    'SZL' => 
    array (
      'name' => 'Alilangini',
    ),
    'TND' => 
    array (
      'name' => 'Adinar Atunsi',
    ),
    'TZS' => 
    array (
      'name' => 'Aciling Aṭanẓani',
    ),
    'UGX' => 
    array (
      'name' => 'Aciling Awgandi',
    ),
    'ZAR' => 
    array (
      'name' => 'Arand Afriqi n Wadda',
    ),
    'ZMK' => 
    array (
      'name' => 'Akwaca Azambi',
    ),
    'ZWD' => 
    array (
      'name' => 'Adular Azimbabwi',
    ),
  ),
  'languages' => 
  array (
    'bn' => 'Tabengalit',
    'be' => 'Tabilarusit',
    'bg' => 'Tabulgarit',
    'my' => 'Taburmisit',
    'vi' => 'Tabyiṭnamit',
    'zh' => 'Tacinwat, Tamundarint',
    'nl' => 'Tadučit',
    'fa' => 'Tafarisit',
    'fr' => 'Tafransist',
    'en' => 'Taglizit',
    'el' => 'Tagrikit',
    'hi' => 'Tahendit',
    'hu' => 'Tahungarit',
    'ha' => 'Tahwasit',
    'ja' => 'Tajapunit',
    'jv' => 'Tajavanit',
    'ak' => 'Takanit',
    'km' => 'Takemrit',
    'ko' => 'Takurit',
    'de' => 'Talmant',
    'am' => 'Tamahrict',
    'ms' => 'Tamalawit',
    'id' => 'Tandunisit',
    'ne' => 'Tanipalit',
    'pl' => 'Tapulunit',
    'pa' => 'Tapunjabit',
    'pt' => 'Tapurtugalit',
    'kab' => 'Taqbaylit',
    'ro' => 'Tarumanit',
    'ru' => 'Tarusit',
    'rw' => 'Taruwandit',
    'es' => 'Taspenyulit',
    'sv' => 'Taswidit',
    'yo' => 'Tayurubit',
    'zu' => 'Tazulut',
    'cs' => 'Tačikit',
    'ar' => 'Taɛrabt',
    'so' => 'Taṣumalit',
    'it' => 'Taṭalyanit',
    'ta' => 'Taṭamulit',
    'th' => 'Taṭaylundit',
    'tr' => 'Taṭurkit',
    'ig' => 'Tigbut',
    'uk' => 'Tukranit',
    'ur' => 'Turdut',
  ),
  'countries' => 
  array (
    'AF' => 'Afɣanistan',
    'IO' => 'Akal Aglizi deg Ugaraw Ahendi',
    'AN' => 'Antilles n Tmura-Yessakesren',
    'AR' => 'Arjuntin',
    'AM' => 'Arminya',
    'AW' => 'Aruba',
    'VA' => 'Awanek n Vatikan',
    'AZ' => 'Azrabijan',
    'BS' => 'Bahamas',
    'BD' => 'Bangladac',
    'BB' => 'Barbadus',
    'BH' => 'Baḥrin',
    'BE' => 'Belǧik',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BY' => 'Bilarus',
    'BZ' => 'Biliz',
    'BJ' => 'Binin',
    'BR' => 'Brizil',
    'BN' => 'Bruney',
    'BG' => 'Bulgari',
    'BO' => 'Bulivi',
    'BI' => 'Burandi',
    'BF' => 'Burkina Fasu',
    'BA' => 'Busna d Hersek',
    'BW' => 'Bustwana',
    'KH' => 'Cambudya',
    'CL' => 'Cili',
    'CY' => 'Cipr',
    'DK' => 'Denmark',
    'DM' => 'Duminik',
    'PS' => 'Falisṭin d Ɣezza',
    'FJ' => 'Fiji',
    'PH' => 'Filipin',
    'FI' => 'Finlund',
    'FR' => 'Fransa',
    'GA' => 'Gabun',
    'GM' => 'Gambya',
    'GD' => 'Grunad',
    'GL' => 'Grunland',
    'GY' => 'Guwana',
    'GP' => 'Gwadalupi',
    'GU' => 'Gwam',
    'GT' => 'Gwatimala',
    'HT' => 'Hayti',
    'HN' => 'Hunduras',
    'HU' => 'Hungri',
    'EC' => 'Ikwaṭur',
    'ID' => 'Indunizi',
    'IR' => 'Iran',
    'ER' => 'Iritiria',
    'IS' => 'Island',
    'EE' => 'Istunya',
    'IL' => 'Izrayil',
    'JM' => 'Jamyika',
    'JP' => 'Jappu',
    'GI' => 'Jibraltar',
    'GE' => 'Jiyurji',
    'NC' => 'Kalidunya Tamaynut',
    'CM' => 'Kamirun',
    'CA' => 'Kanada',
    'KZ' => 'Kazaxistan',
    'HR' => 'Kerwasya',
    'KE' => 'Kinya',
    'KI' => 'Kiribati',
    'KG' => 'Kirigistan',
    'CU' => 'Kuba',
    'CO' => 'Kulumbi',
    'KM' => 'Kumur',
    'CG' => 'Kungu',
    'KP' => 'Kurya, Ufella',
    'KR' => 'Kurya, Wadda',
    'CR' => 'Kusta Rika',
    'KW' => 'Kuwayt',
    'CI' => 'Kuṭ Divwar',
    'CN' => 'Lacin',
    'GR' => 'Lagris',
    'JO' => 'Lajurdani',
    'AL' => 'Lalbani',
    'DE' => 'Lalman',
    'LV' => 'Latvia',
    'LA' => 'Laws',
    'LI' => 'Layctenstan',
    'DZ' => 'Lezzayer',
    'IN' => 'Lhend',
    'LR' => 'Libirya',
    'LY' => 'Libya',
    'IE' => 'Lirlund',
    'LS' => 'Lizuṭu',
    'LT' => 'Liṭwanya',
    'MA' => 'Lmerruk',
    'LB' => 'Lubnan',
    'LU' => 'Luksamburg',
    'YE' => 'Lyamen',
    'IQ' => 'Lɛiraq',
    'MG' => 'Madaɣecqer',
    'MW' => 'Malawi',
    'MV' => 'Maldib',
    'ML' => 'Mali',
    'MY' => 'Malizya',
    'MT' => 'Malṭ',
    'MQ' => 'Martinik',
    'MK' => 'Masidwan',
    'YT' => 'Mayuṭ',
    'EG' => 'Maṣr',
    'MX' => 'Meksik',
    'FM' => 'Mikrunizya',
    'MD' => 'Muldabi',
    'MC' => 'Munaku',
    'MN' => 'Mungulya',
    'MS' => 'Munsirat',
    'MU' => 'Muris',
    'MR' => 'Muriṭanya',
    'MZ' => 'Muzembiq',
    'MM' => 'Myanmar',
    'NA' => 'Namibya',
    'NE' => 'Nijer',
    'NG' => 'Nijirya',
    'NI' => 'Nikaragwa',
    'NP' => 'Nipal',
    'NU' => 'Niwi',
    'NR' => 'Nuru',
    'NO' => 'Nurvij',
    'PK' => 'Pakistan',
    'PW' => 'Palu',
    'PA' => 'Panam',
    'PY' => 'Paragway',
    'PE' => 'Piru',
    'PN' => 'Pitkarin',
    'PL' => 'Pulund',
    'PF' => 'Pulunizi tafransist',
    'PR' => 'Purtu Riku',
    'PT' => 'Purtugal',
    'QA' => 'Qaṭar',
    'RU' => 'Rrus',
    'RO' => 'Rumani',
    'RW' => 'Ruwanda',
    'SV' => 'Salvadur',
    'WS' => 'Samwa',
    'AS' => 'Samwa Tamarikanit',
    'KN' => 'San Kits d Nivis',
    'LC' => 'San Lučya',
    'SM' => 'San Marinu',
    'PM' => 'San Pyar d Miklun',
    'VC' => 'San Vansu d Grunadin',
    'SH' => 'Sant Ilina',
    'ST' => 'Saw Tumi d Pransip',
    'SC' => 'Seycel',
    'SG' => 'Singafur',
    'SN' => 'Sinigal',
    'SL' => 'Sira Lyun',
    'CS' => 'Sirbya d Muntinigru',
    'SK' => 'Sluvakya',
    'SI' => 'Sluvinya',
    'ES' => 'Spanya',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Surinam',
    'SY' => 'Surya',
    'SA' => 'Suɛudiya Taɛrabt',
    'SZ' => 'Swazilund',
    'SE' => 'Swid',
    'CH' => 'Swis',
    'ZA' => 'Tafriqt Wadda',
    'GB' => 'Tagelda Yedduklen',
    'TJ' => 'Tajikistan',
    'DO' => 'Tigduda Taduminikit',
    'CD' => 'Tigduda Tagdudant n Kungu',
    'CF' => 'Tigduda n Tefriqt Talemmast',
    'AE' => 'Tigeldunin Yedduklen Taɛrabin',
    'NF' => 'Tigzirin Tinawfukin',
    'VG' => 'Tigzirin Tiverjiniyin Tigliziyin',
    'FK' => 'Tigzirin n Falkland',
    'KY' => 'Tigzirin n Kamyan',
    'CK' => 'Tigzirin n Kuk',
    'MH' => 'Tigzirin n Marcal',
    'MP' => 'Tigzirin n Maryan Ufella',
    'SB' => 'Tigzirin n Sulumun',
    'CV' => 'Tigzirin n yixef azegzaw',
    'RE' => 'Timlilit',
    'NL' => 'Timura-Yessakesren',
    'TL' => 'Tumur Asamar',
    'TN' => 'Tunes',
    'UA' => 'Ukran',
    'AD' => 'Undura',
    'AI' => 'Ungiya',
    'AO' => 'Ungula',
    'AG' => 'Untiga d Barbuda',
    'UY' => 'Urugway',
    'AU' => 'Ustrali',
    'AT' => 'Ustriya',
    'ET' => 'Utyupi',
    'UZ' => 'Uzbaxistan',
    'UG' => 'Uɣanda',
    'VU' => 'Vanwatu',
    'VE' => 'Venzwila',
    'VN' => 'Vyeṭnam',
    'VI' => 'W.D. Tigzirin n Virginya',
    'US' => 'WDM',
    'WF' => 'Wallis d Futuna',
    'ZM' => 'Zambya',
    'NZ' => 'Ziland Tamaynut',
    'ZW' => 'Zimbabwi',
    'TD' => 'Čad',
    'CZ' => 'Čček',
    'OM' => 'Ɛuman',
    'GH' => 'Ɣana',
    'GF' => 'Ɣana tafransist',
    'GN' => 'Ɣinya',
    'PG' => 'Ɣinya Tamaynut Tapaput',
    'GQ' => 'Ɣinya Tasebgast',
    'GW' => 'Ɣinya-Bisaw',
    'DJ' => 'Ǧibuti',
    'SO' => 'Ṣumal',
    'TZ' => 'Ṭanzanya',
    'TH' => 'Ṭayland',
    'TW' => 'Ṭaywan',
    'IT' => 'Ṭelyan',
    'TT' => 'Ṭrindad d Ṭubagu',
    'TG' => 'Ṭugu',
    'TK' => 'Ṭuklu',
    'TO' => 'Ṭunga',
    'TR' => 'Ṭurk',
    'TC' => 'Ṭurk d Tegzirin n Kaykus',
    'TM' => 'Ṭurkmanistan',
    'TV' => 'Ṭuvalu',
  ),
);
