<?php
/**
 * Locale data for 'ki'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5799',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Njenuarĩ',
      2 => 'Mwere wa kerĩ',
      3 => 'Mwere wa gatatũ',
      4 => 'Mwere wa kana',
      5 => 'Mwere wa gatano',
      6 => 'Mwere wa gatandatũ',
      7 => 'Mwere wa mũgwanja',
      8 => 'Mwere wa kanana',
      9 => 'Mwere wa kenda',
      10 => 'Mwere wa ikũmi',
      11 => 'Mwere wa ikũmi na ũmwe',
      12 => 'Ndithemba',
    ),
    'abbreviated' => 
    array (
      1 => 'JEN',
      2 => 'WKR',
      3 => 'WGT',
      4 => 'WKN',
      5 => 'WTN',
      6 => 'WTD',
      7 => 'WMJ',
      8 => 'WNN',
      9 => 'WKD',
      10 => 'WIK',
      11 => 'WMW',
      12 => 'DIT',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'K',
      3 => 'G',
      4 => 'K',
      5 => 'G',
      6 => 'G',
      7 => 'M',
      8 => 'K',
      9 => 'K',
      10 => 'I',
      11 => 'I',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Kiumia',
      1 => 'Njumatatũ',
      2 => 'Njumaine',
      3 => 'Njumatana',
      4 => 'Aramithi',
      5 => 'Njumaa',
      6 => 'Njumamothi',
    ),
    'abbreviated' => 
    array (
      0 => 'KMA',
      1 => 'NTT',
      2 => 'NMN',
      3 => 'NMT',
      4 => 'ART',
      5 => 'NMA',
      6 => 'NMM',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'K',
      1 => 'N',
      2 => 'N',
      3 => 'N',
      4 => 'A',
      5 => 'N',
      6 => 'N',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Dola ya Australia',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Ndora ya Kananda',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Yuan Renminbi ya China',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Yuro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Mbauini cia Ngeretha',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Rubia rwa India',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Sarafu ya Kijapani',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Ndora cia Amerika',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Faranga CFA BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Faranga CFA BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'KES' => 
    array (
      'symbol' => 'Ksh',
      'name' => 'Ciringi ya Kenya',
    ),
    'AED' => 
    array (
      'name' => 'Dirham ya Falme za Kiarabu',
    ),
    'AOA' => 
    array (
      'name' => 'Kwanza ya Angola',
    ),
    'BHD' => 
    array (
      'name' => 'Dinari ya Bahareni',
    ),
    'BIF' => 
    array (
      'name' => 'Faranga ya Burundi',
    ),
    'BWP' => 
    array (
      'name' => 'Pula ya Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'Faranga ya Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'Faranga ya Uswisi',
    ),
    'CVE' => 
    array (
      'name' => 'Eskudo ya Kepuvede',
    ),
    'DJF' => 
    array (
      'name' => 'Faranga ya Jibuti',
    ),
    'DZD' => 
    array (
      'name' => 'Dinari ya Aljeria',
    ),
    'EGP' => 
    array (
      'name' => 'Pauni ya Misri',
    ),
    'ERN' => 
    array (
      'name' => 'Nakfa ya Eritrea',
    ),
    'ETB' => 
    array (
      'name' => 'Bir ya Uhabeshi',
    ),
    'GHC' => 
    array (
      'name' => 'Sedi ya Ghana',
    ),
    'GMD' => 
    array (
      'name' => 'Dalasi ya Gambia',
    ),
    'GNS' => 
    array (
      'name' => 'Faranga ya Gine',
    ),
    'KMF' => 
    array (
      'name' => 'Faranga ya Komoro',
    ),
    'LRD' => 
    array (
      'name' => 'Dola ya Liberia',
    ),
    'LSL' => 
    array (
      'name' => 'Loti ya Lesoto',
    ),
    'LYD' => 
    array (
      'name' => 'Dinari ya Libya',
    ),
    'MAD' => 
    array (
      'name' => 'Dirham ya Moroko',
    ),
    'MGA' => 
    array (
      'name' => 'Ariary ya Bukini',
    ),
    'MRO' => 
    array (
      'name' => 'Ugwiya ya Moritania',
    ),
    'MUR' => 
    array (
      'name' => 'Rupia ya Morisi',
    ),
    'MWK' => 
    array (
      'name' => 'Kwacha ya Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Metikali ya Msumbiji',
    ),
    'NAD' => 
    array (
      'name' => 'Dola ya Namibia',
    ),
    'NGN' => 
    array (
      'name' => 'Naira ya Nijeria',
    ),
    'RWF' => 
    array (
      'name' => 'Faranga ya Rwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Riyal ya Saudia',
    ),
    'SCR' => 
    array (
      'name' => 'Rupia ya Shelisheli',
    ),
    'SDG' => 
    array (
      'name' => 'Pauni ya Sudani',
    ),
    'SHP' => 
    array (
      'name' => 'Pauni ya Santahelena',
    ),
    'SLL' => 
    array (
      'name' => 'Leoni',
    ),
    'SOS' => 
    array (
      'name' => 'ciringi cia cumarĩ',
    ),
    'STD' => 
    array (
      'name' => 'Dobra ya Sao Tome na Principe',
    ),
    'SZL' => 
    array (
      'name' => 'Lilangeni',
    ),
    'TND' => 
    array (
      'name' => 'Dinari ya Tunisia',
    ),
    'TZS' => 
    array (
      'name' => 'ciringi cia Tanizania',
    ),
    'UGX' => 
    array (
      'name' => 'ciringi cia Ũganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Randi ya Afrika Kusini',
    ),
    'ZMK' => 
    array (
      'name' => 'Kwacha ya Zambia',
    ),
    'ZWD' => 
    array (
      'name' => 'Dola ya Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ki' => 'Gikuyu',
    'en' => 'Gĩthungũ',
    'fa' => 'Kiajemi',
    'ak' => 'Kiakan',
    'am' => 'Kiamhari',
    'bn' => 'Kibangla',
    'be' => 'Kibelarusi',
    'bg' => 'Kibulgaria',
    'my' => 'Kiburma',
    'cs' => 'Kichecki',
    'el' => 'Kigiriki',
    'ha' => 'Kihausa',
    'es' => 'Kihispania',
    'nl' => 'Kiholanzi',
    'hu' => 'Kihungari',
    'ig' => 'Kiigbo',
    'id' => 'Kiindonesia',
    'jv' => 'Kijava',
    'km' => 'Kikambodia',
    'ko' => 'Kikorea',
    'ms' => 'Kimalesia',
    'ne' => 'Kinepali',
    'rw' => 'Kinyarwanda',
    'pl' => 'Kipolandi',
    'pa' => 'Kipunjabi',
    'pt' => 'Kireno',
    'ro' => 'Kiromania',
    'sv' => 'Kiswidi',
    'th' => 'Kitailandi',
    'ta' => 'Kitamil',
    'tr' => 'Kituruki',
    'uk' => 'Kiukrania',
    'ur' => 'Kiurdu',
    'vi' => 'Kivietinamu',
    'yo' => 'Kiyoruba',
    'zu' => 'Kizulu',
    'ar' => 'Kĩarabu',
    'fr' => 'Kĩbaranja',
    'zh' => 'Kĩcaina',
    'so' => 'Kĩcumarĩ',
    'hi' => 'Kĩhĩndĩ',
    'ja' => 'Kĩnjabani',
    'de' => 'Kĩnjeremani',
    'ru' => 'Kĩracia',
    'it' => 'Kĩtaliano',
  ),
  'countries' => 
  array (
    'ZA' => 'Afrika Kusini',
    'AF' => 'Afuganistani',
    'IS' => 'Aislandi',
    'AR' => 'Ajentina',
    'AL' => 'Albania',
    'DZ' => 'Aljeria',
    'US' => 'Amerika',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AG' => 'Antigua na Barbuda',
    'AN' => 'Antili za Uholanzi',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'IE' => 'Ayalandi',
    'AZ' => 'Azabajani',
    'BB' => 'Babadosi',
    'BS' => 'Bahama',
    'BH' => 'Bahareni',
    'BD' => 'Bangladeshi',
    'BY' => 'Belarusi',
    'BZ' => 'Belize',
    'BJ' => 'Benini',
    'BM' => 'Bermuda',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia na Hezegovina',
    'BW' => 'Botswana',
    'BR' => 'Brazili',
    'BN' => 'Brunei',
    'BF' => 'Bukinafaso',
    'MG' => 'Bukini',
    'BG' => 'Bulgaria',
    'BT' => 'Butani',
    'CN' => 'Caina',
    'TD' => 'Chadi',
    'CL' => 'Chile',
    'DK' => 'Denmaki',
    'DM' => 'Dominika',
    'EC' => 'Ekwado',
    'SV' => 'Elsavado',
    'IO' => 'Eneo la Uingereza katika Bahari Hindi',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'AE' => 'Falme za Kiarabu',
    'FJ' => 'Fiji',
    'PH' => 'Filipino',
    'GA' => 'Gaboni',
    'GM' => 'Gambia',
    'GN' => 'Gine',
    'GW' => 'Ginebisau',
    'GQ' => 'Ginekweta',
    'GD' => 'Grenada',
    'GL' => 'Grinlandi',
    'GY' => 'Guyana',
    'GP' => 'Gwadelupe',
    'GU' => 'Gwam',
    'GT' => 'Gwatemala',
    'GF' => 'Gwiyana ya Ufaransa',
    'HT' => 'Haiti',
    'ES' => 'Hispania',
    'HN' => 'Hondurasi',
    'HU' => 'Hungaria',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IQ' => 'Iraki',
    'IL' => 'Israeli',
    'IT' => 'Italia',
    'JM' => 'Jamaika',
    'CF' => 'Jamhuri ya Afrika ya Kati',
    'CZ' => 'Jamhuri ya Cheki',
    'DO' => 'Jamhuri ya Dominika',
    'CD' => 'Jamhuri ya Kidemokrasia ya Kongo',
    'GI' => 'Jibralta',
    'DJ' => 'Jibuti',
    'GE' => 'Jojia',
    'KH' => 'Kambodia',
    'CM' => 'Kameruni',
    'CA' => 'Kanada',
    'QA' => 'Katari',
    'KZ' => 'Kazakistani',
    'KE' => 'Kenya',
    'CV' => 'Kepuvede',
    'KI' => 'Kiribati',
    'KG' => 'Kirigizistani',
    'NF' => 'Kisiwa cha Norfok',
    'CU' => 'Kiumba',
    'CI' => 'Kodivaa',
    'CO' => 'Kolombia',
    'KM' => 'Komoro',
    'CG' => 'Kongo',
    'HR' => 'Korasia',
    'KP' => 'Korea Kaskazini',
    'KR' => 'Korea Kusini',
    'CR' => 'Kostarika',
    'CY' => 'Kuprosi',
    'KW' => 'Kuwaiti',
    'LA' => 'Laosi',
    'LU' => 'Lasembagi',
    'LV' => 'Lativia',
    'LB' => 'Lebanoni',
    'LS' => 'Lesoto',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Lishenteni',
    'LT' => 'Litwania',
    'MW' => 'Malawi',
    'MY' => 'Malesia',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MQ' => 'Martiniki',
    'MK' => 'Masedonia',
    'YT' => 'Mayotte',
    'BI' => 'Mburundi',
    'MX' => 'Meksiko',
    'FM' => 'Mikronesia',
    'EG' => 'Misri',
    'MV' => 'Modivu',
    'MD' => 'Moldova',
    'MC' => 'Monako',
    'MN' => 'Mongolia',
    'MS' => 'Montserrati',
    'MU' => 'Morisi',
    'MR' => 'Moritania',
    'MA' => 'Moroko',
    'MZ' => 'Msumbiji',
    'MM' => 'Myama',
    'NG' => 'Nainjeria',
    'NA' => 'Namimbia',
    'NR' => 'Nauru',
    'NP' => 'Nepali',
    'GH' => 'Ngana',
    'GB' => 'Ngeretha',
    'NE' => 'Nijeri',
    'NI' => 'Nikaragwa',
    'NU' => 'Niue',
    'JP' => 'Njabani',
    'DE' => 'Njeremani',
    'JO' => 'Njorondani',
    'NO' => 'Norwe',
    'NC' => 'Nyukaledonia',
    'NZ' => 'Nyuzilandi',
    'OM' => 'Omani',
    'PK' => 'Pakistani',
    'PW' => 'Palau',
    'PA' => 'Panama',
    'PG' => 'Papua',
    'PY' => 'Paragwai',
    'PE' => 'Peru',
    'PN' => 'Pitkairni',
    'PL' => 'Polandi',
    'PF' => 'Polinesia ya Ufaransa',
    'PR' => 'Pwetoriko',
    'RE' => 'Riyunioni',
    'RO' => 'Romania',
    'RW' => 'Rwanda',
    'SM' => 'Samarino',
    'WS' => 'Samoa',
    'AS' => 'Samoa ya Marekani',
    'SH' => 'Santahelena',
    'KN' => 'Santakitzi na Nevis',
    'LC' => 'Santalusia',
    'PM' => 'Santapieri na Mikeloni',
    'VC' => 'Santavisenti na Grenadini',
    'ST' => 'Sao Tome na Principe',
    'SA' => 'Saudi',
    'SN' => 'Senegali',
    'CS' => 'Serbia na Montenegro',
    'SC' => 'Shelisheli',
    'SL' => 'Siera Leoni',
    'SG' => 'Singapoo',
    'SY' => 'Siria',
    'LK' => 'Sirilanka',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SO' => 'Somaria',
    'SD' => 'Sudani',
    'SR' => 'Surinamu',
    'TH' => 'Tailandi',
    'TW' => 'Taiwani',
    'TJ' => 'Tajikistani',
    'TZ' => 'Tanzania',
    'TL' => 'Timori ya Mashariki',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad na Tobago',
    'TN' => 'Tunisia',
    'TM' => 'Turukimenistani',
    'TV' => 'Tuvalu',
    'IR' => 'Uajemi',
    'FR' => 'Ubaranja',
    'BE' => 'Ubelgiji',
    'FI' => 'Ufini',
    'UG' => 'Uganda',
    'GR' => 'Ugiriki',
    'ET' => 'Uhabeshi',
    'NL' => 'Uholanzi',
    'PS' => 'Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina',
    'UA' => 'Ukraini',
    'PT' => 'Ureno',
    'UY' => 'Urugwai',
    'RU' => 'Urusi',
    'SZ' => 'Uswazi',
    'SE' => 'Uswidi',
    'CH' => 'Uswisi',
    'TR' => 'Uturuki',
    'UZ' => 'Uzibekistani',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikani',
    'VE' => 'Venezuela',
    'VN' => 'Vietinamu',
    'CK' => 'Visiwa vya Cook',
    'FK' => 'Visiwa vya Falkland',
    'KY' => 'Visiwa vya Kayman',
    'MP' => 'Visiwa vya Mariana vya Kaskazini',
    'MH' => 'Visiwa vya Marshal',
    'SB' => 'Visiwa vya Solomon',
    'TC' => 'Visiwa vya Turki na Kaiko',
    'VI' => 'Visiwa vya Virgin vya Marekani',
    'VG' => 'Visiwa vya Virgin vya Uingereza',
    'WF' => 'Walis na Futuna',
    'YE' => 'Yemeni',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
  ),
);
