<?php
/**
 * Locale data for 'kw'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Mys Genver',
      2 => 'Mys Whevrel',
      3 => 'Mys Merth',
      4 => 'Mys Ebrel',
      5 => 'Mys Me',
      6 => 'Mys Efan',
      7 => 'Mys Gortheren',
      8 => 'Mye Est',
      9 => 'Mys Gwyngala',
      10 => 'Mys Hedra',
      11 => 'Mys Du',
      12 => 'Mys Kevardhu',
    ),
    'abbreviated' => 
    array (
      1 => 'Gen',
      2 => 'Whe',
      3 => 'Mer',
      4 => 'Ebr',
      5 => 'Me',
      6 => 'Efn',
      7 => 'Gor',
      8 => 'Est',
      9 => 'Gwn',
      10 => 'Hed',
      11 => 'Du',
      12 => 'Kev',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'De Sul',
      1 => 'De Lun',
      2 => 'De Merth',
      3 => 'De Merher',
      4 => 'De Yow',
      5 => 'De Gwener',
      6 => 'De Sadorn',
    ),
    'abbreviated' => 
    array (
      0 => 'Sul',
      1 => 'Lun',
      2 => 'Mth',
      3 => 'Mhr',
      4 => 'Yow',
      5 => 'Gwe',
      6 => 'Sad',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
  ),
  'languages' => 
  array (
    'de' => 'Almaynek',
    'ar' => 'Arabek',
    'eu' => 'Baskek',
    'zh' => 'Chinek',
    'zh_Hant' => 'Chinek hengovek',
    'zh_Hans' => 'Chinek sempel',
    'da' => 'Danek',
    'fr' => 'Frenkek',
    'nl' => 'Iseldiryek',
    'it' => 'Italek',
    'ja' => 'Japanek',
    'yue' => 'Kantonek',
    'cy' => 'Kembrek',
    'kw' => 'Kernewek',
    'pt' => 'Portyngalek',
    'pt_BR' => 'Portyngalek Brasil',
    'ru' => 'Russek',
    'en' => 'Sowsnek',
    'es' => 'Spaynek',
    'ga' => 'Wordhonek',
  ),
  'countries' => 
  array (
    'DE' => 'Almayn',
    'BR' => 'Brasil',
    'CN' => 'China',
    'IN' => 'Eynda',
    'IT' => 'Itali',
    'JP' => 'Japan',
    'FR' => 'Pow Frenk',
    'RU' => 'Russi',
    'GB' => 'Rywvaneth Unys',
    'US' => 'Statys Unys',
  ),
);
