<?php
/**
 * Locale data for 'ln'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'sánzá ya yambo',
      2 => 'sánzá ya míbalé',
      3 => 'sánzá ya mísáto',
      4 => 'sánzá ya mínei',
      5 => 'sánzá ya mítáno',
      6 => 'sánzá ya motóbá',
      7 => 'sánzá ya nsambo',
      8 => 'sánzá ya mwambe',
      9 => 'sánzá ya libwa',
      10 => 'sánzá ya zómi',
      11 => 'sánzá ya zómi na mɔ̌kɔ́',
      12 => 'sánzá ya zómi na míbalé',
    ),
    'abbreviated' => 
    array (
      1 => 'yan',
      2 => 'fbl',
      3 => 'msi',
      4 => 'apl',
      5 => 'mai',
      6 => 'yun',
      7 => 'yul',
      8 => 'agt',
      9 => 'stb',
      10 => 'ɔtb',
      11 => 'nvb',
      12 => 'dsb',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'y',
      2 => 'f',
      3 => 'm',
      4 => 'a',
      5 => 'm',
      6 => 'y',
      7 => 'y',
      8 => 'a',
      9 => 's',
      10 => 'ɔ',
      11 => 'n',
      12 => 'd',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'eyenga',
      1 => 'mokɔlɔ mwa yambo',
      2 => 'mokɔlɔ mwa míbalé',
      3 => 'mokɔlɔ mwa mísáto',
      4 => 'mokɔlɔ ya mínéi',
      5 => 'mokɔlɔ ya mítáno',
      6 => 'mpɔ́sɔ',
    ),
    'abbreviated' => 
    array (
      0 => 'eye',
      1 => 'ybo',
      2 => 'mbl',
      3 => 'mst',
      4 => 'min',
      5 => 'mtn',
      6 => 'mps',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'e',
      1 => 'y',
      2 => 'm',
      3 => 'm',
      4 => 'm',
      5 => 'm',
      6 => 'p',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Dolarɛ ya Ositali',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Dolarɛ ya Kanadá',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Yuanɛ Renminbi ya Sinɛ',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Ɛlɔ́',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Paunɛ ya Angɛlɛtɛ́lɛ',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Rupi ya Índɛ',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Yeni ya Zapɔ',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Dolarɛ ya Ameriki',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Falánga CFA BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Falánga CFA BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'AED' => 
    array (
      'name' => 'Dirihamɛ ya Lémila alabo',
    ),
    'AOA' => 
    array (
      'name' => 'Kwanza ya Angóla',
    ),
    'BHD' => 
    array (
      'name' => 'Dinarɛ ya Bahrɛnɛ',
    ),
    'BIF' => 
    array (
      'name' => 'Falánga ya Burundi',
    ),
    'BWP' => 
    array (
      'name' => 'Pula ya Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'Falánga ya Kongó',
    ),
    'CHF' => 
    array (
      'name' => 'Falánga ya Swisɛ',
    ),
    'CVE' => 
    array (
      'name' => 'Esikudo ya Kapevɛrɛ',
    ),
    'DJF' => 
    array (
      'name' => 'Falánga ya Dzibuti',
    ),
    'DZD' => 
    array (
      'name' => 'Dinarɛ ya Alizeri',
    ),
    'EGP' => 
    array (
      'name' => 'Paunɛ ya Ezípitɛ',
    ),
    'ERN' => 
    array (
      'name' => 'Nakfa ya Elitlɛ',
    ),
    'ETB' => 
    array (
      'name' => 'Birɛ ya Etsiópi',
    ),
    'GHC' => 
    array (
      'name' => 'Sedi ya Gana',
    ),
    'GMD' => 
    array (
      'name' => 'Dalasi ya Gambi',
    ),
    'GNS' => 
    array (
      'name' => 'Falánga ya Ginɛ',
    ),
    'KES' => 
    array (
      'name' => 'Shilingɛ ya Kenya',
    ),
    'KMF' => 
    array (
      'name' => 'Falánga ya Komoro',
    ),
    'LRD' => 
    array (
      'name' => 'Dolarɛ ya Liberya',
    ),
    'LSL' => 
    array (
      'name' => 'Loti ya Lesóto',
    ),
    'LYD' => 
    array (
      'name' => 'Dinarɛ ya Libí',
    ),
    'MAD' => 
    array (
      'name' => 'Dirihame ya Marokɛ',
    ),
    'MGA' => 
    array (
      'name' => 'Falánga ya Madagasikarɛ',
    ),
    'MRO' => 
    array (
      'name' => 'Ugwiya ya Moritani',
    ),
    'MUR' => 
    array (
      'name' => 'Rupi ya Morisi',
    ),
    'MWK' => 
    array (
      'name' => 'Kwasha ya Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Metikali ya Mozambiki',
    ),
    'NAD' => 
    array (
      'name' => 'Dolarɛ ya Namibi',
    ),
    'NGN' => 
    array (
      'name' => 'Naira ya Nizerya',
    ),
    'RWF' => 
    array (
      'name' => 'Falánga ya Rwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Riyalɛ ya Alabi Sawuditɛ',
    ),
    'SCR' => 
    array (
      'name' => 'Rupi ya Sɛshɛlɛ',
    ),
    'SDG' => 
    array (
      'name' => 'Dinarɛ ya Sudá',
    ),
    'SDP' => 
    array (
      'name' => 'Paunɛ ya Sudá',
    ),
    'SHP' => 
    array (
      'name' => 'Paunɛ ya Sántu elena',
    ),
    'SLL' => 
    array (
      'name' => 'Leonɛ',
    ),
    'SOS' => 
    array (
      'name' => 'Shilingɛ ya Somali',
    ),
    'STD' => 
    array (
      'name' => 'Dobra ya Sao Tomé mpé Presipe',
    ),
    'SZL' => 
    array (
      'name' => 'Lilangeni',
    ),
    'TND' => 
    array (
      'name' => 'Dinarɛ ya Tinizi',
    ),
    'TZS' => 
    array (
      'name' => 'Shilingɛ ya Tanzani',
    ),
    'UGX' => 
    array (
      'name' => 'Shilingɛ ya Uganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Randɛ ya Afríka Súdi',
    ),
    'ZMK' => 
    array (
      'name' => 'Kwasha ya Zambi',
    ),
    'ZWD' => 
    array (
      'name' => 'Dolarɛ ya Zimbabwɛ',
    ),
  ),
  'languages' => 
  array (
    'ak' => 'Akan',
    'ha' => 'Hausa',
    'ig' => 'Igbo',
    'rw' => 'Kinyarwanda',
    'ar' => 'Lialabo',
    'de' => 'Lialemá',
    'am' => 'Liamariki',
    'bn' => 'Libengali',
    'bg' => 'Libiligali',
    'my' => 'Libilimá',
    'be' => 'Libyelorisí',
    'nl' => 'Lifalamá',
    'fr' => 'Lifalansɛ́',
    'el' => 'Ligeleki',
    'hi' => 'Lihindi',
    'km' => 'Likambodza',
    'ko' => 'Likoreya',
    'uk' => 'Likrɛni',
    'ms' => 'Limalezi',
    'id' => 'Lindonezi',
    'ne' => 'Linepalɛ',
    'ln' => 'Lingála',
    'en' => 'Lingɛlɛ́sa',
    'hu' => 'Liongili',
    'fa' => 'Lipelésanɛ',
    'pa' => 'Lipendzabi',
    'pl' => 'Lipolonɛ',
    'pt' => 'Lipulutugɛ́si',
    'ru' => 'Lirisí',
    'ro' => 'Liromani',
    'zh' => 'Lisinwa',
    'es' => 'Lisipanye',
    'so' => 'Lisomali',
    'sv' => 'Lisuwedɛ',
    'it' => 'Litaliano',
    'ta' => 'Litamuli',
    'th' => 'Litaye',
    'tr' => 'Litiliki',
    'cs' => 'Litshekɛ',
    'ur' => 'Liurdu',
    'vi' => 'Liviyetinámi',
    'ja' => 'Lizapɔ',
    'jv' => 'Lizava',
    'yo' => 'Yoruba',
    'zu' => 'Zulu',
  ),
  'countries' => 
  array (
    'AF' => 'Afiganisitá',
    'ZA' => 'Afríka ya Súdi',
    'SA' => 'Alabi Sawuditɛ',
    'DE' => 'Alemani',
    'AL' => 'Alibani',
    'DZ' => 'Alizɛri',
    'US' => 'Ameriki',
    'AM' => 'Amɛni',
    'AD' => 'Andorɛ',
    'AI' => 'Angiyɛ',
    'AO' => 'Angóla',
    'GB' => 'Angɛlɛtɛ́lɛ',
    'AG' => 'Antiga mpé Barbuda',
    'AN' => 'Antiyɛ ya Olandɛ',
    'AR' => 'Arizantinɛ',
    'AW' => 'Aruba',
    'HT' => 'Ayiti',
    'AZ' => 'Azɛlɛbaizá',
    'BS' => 'Bahamasɛ',
    'BH' => 'Bahrɛnɛ',
    'BB' => 'Barɛbadɛ',
    'BE' => 'Beleziki',
    'BZ' => 'Belizɛ',
    'BD' => 'Bengalidɛsi',
    'BJ' => 'Benɛ',
    'BM' => 'Bermuda',
    'BG' => 'Biligari',
    'SB' => 'Bisanga Solomɔ',
    'CV' => 'Bisanga bya Kapevɛrɛ',
    'KY' => 'Bisanga bya Kayíma',
    'CK' => 'Bisanga bya Kookɛ',
    'FK' => 'Bisanga bya Maluni',
    'MP' => 'Bisanga bya Marianɛ ya nɔ́rdi',
    'MH' => 'Bisanga bya Marishalɛ',
    'TC' => 'Bisanga bya Turki mpé Kaiko',
    'VI' => 'Bisanga bya Vierzi ya Ameriki',
    'VG' => 'Bisanga bya Vierzi ya Angɛlɛtɛ́lɛ',
    'BO' => 'Bolivi',
    'BA' => 'Bosini mpé Hezegovine',
    'BW' => 'Botswana',
    'BR' => 'Brezílɛ',
    'BN' => 'Brineyi',
    'BF' => 'Bukina Faso',
    'BI' => 'Burundi',
    'BT' => 'Butáni',
    'BY' => 'Byelorisi',
    'DK' => 'Danɛmarike',
    'DM' => 'Domínike',
    'DJ' => 'Dzibuti',
    'EC' => 'Ekwatɛ́lɛ',
    'ER' => 'Elitelɛ',
    'NF' => 'Esanga Norfokɛ',
    'ES' => 'Esipanye',
    'EE' => 'Esitoni',
    'ET' => 'Etsíopi',
    'EG' => 'Ezípite',
    'FR' => 'Falánsɛ',
    'FJ' => 'Fidzi',
    'FI' => 'Filandɛ',
    'PH' => 'Filipinɛ',
    'GA' => 'Gabɔ',
    'GM' => 'Gambi',
    'GH' => 'Gana',
    'GR' => 'Geleki',
    'GD' => 'Gelenadɛ',
    'GN' => 'Ginɛ',
    'GW' => 'Ginɛbisau',
    'GQ' => 'Ginɛ́kwatɛ́lɛ',
    'GY' => 'Giyane',
    'GF' => 'Giyanɛ ya Falánsɛ',
    'GL' => 'Gowelande',
    'GP' => 'Gwadɛlupɛ',
    'GU' => 'Gwamɛ',
    'GT' => 'Gwatémala',
    'UA' => 'Ikrɛni',
    'ID' => 'Indonezi',
    'IQ' => 'Iraki',
    'IE' => 'Irelandɛ',
    'UY' => 'Irigwei',
    'IR' => 'Irâ',
    'IS' => 'Isilandɛ',
    'IL' => 'Isirayelɛ',
    'IT' => 'Itali',
    'NC' => 'Kaledoni ya sika',
    'KH' => 'Kambodza',
    'CM' => 'Kamɛrune',
    'CA' => 'Kanada',
    'QA' => 'Katari',
    'KZ' => 'Kazakisitá',
    'KE' => 'Kenya',
    'CU' => 'Kiba',
    'KG' => 'Kigizisitá',
    'KI' => 'Kiribati',
    'CO' => 'Kolombi',
    'KM' => 'Komorɛ',
    'CG' => 'Kongo',
    'KP' => 'Korɛ ya nɔ́rdi',
    'KR' => 'Korɛ ya súdi',
    'CR' => 'Kositarika',
    'CI' => 'Kotídivualɛ',
    'KW' => 'Koweti',
    'HR' => 'Krowasi',
    'LA' => 'Lawosi',
    'RE' => 'Lenyo',
    'LS' => 'Lesoto',
    'LV' => 'Letoni',
    'LB' => 'Libá',
    'LR' => 'Libériya',
    'LY' => 'Libí',
    'LU' => 'Likisambulu',
    'LI' => 'Lishɛteni',
    'LT' => 'Litwani',
    'AE' => 'Lɛmila alabo',
    'IO' => 'Mabelé ya Angɛlɛtɛ́lɛ na mbú ya Indiya',
    'MG' => 'Madagasikari',
    'MV' => 'Madívɛ',
    'MW' => 'Malawi',
    'MY' => 'Malezi',
    'MT' => 'Malitɛ',
    'ML' => 'Malí',
    'MA' => 'Marokɛ',
    'MQ' => 'Martiniki',
    'MK' => 'Masedwanɛ',
    'YT' => 'Mayotɛ',
    'MX' => 'Meksike',
    'FM' => 'Mikronezi',
    'MD' => 'Molidavi',
    'MC' => 'Monako',
    'MN' => 'Mongolí',
    'MU' => 'Morisɛ',
    'MR' => 'Moritani',
    'MM' => 'Mozambiki',
    'MZ' => 'Mozambíki',
    'MS' => 'Mɔsera',
    'NA' => 'Namibi',
    'NR' => 'Nauru',
    'NP' => 'Nepálɛ',
    'NI' => 'Nikaragwa',
    'NG' => 'Nizerya',
    'NE' => 'Nizɛrɛ',
    'NO' => 'Norivezɛ',
    'NU' => 'Nyué',
    'NL' => 'Olandɛ',
    'OM' => 'Ománɛ',
    'HN' => 'Ondurasɛ',
    'HU' => 'Ongili',
    'AU' => 'Ositáli',
    'AT' => 'Otilisi',
    'PK' => 'Pakisitá',
    'PY' => 'Palagwei',
    'PW' => 'Palau',
    'PS' => 'Palɛsine',
    'PA' => 'Panama',
    'PG' => 'Papwazi Ginɛ ya sika',
    'PN' => 'Pikairni',
    'PF' => 'Polinezi ya Falánsɛ',
    'PL' => 'Poloni',
    'PT' => 'Putúlugɛsi',
    'PE' => 'Péru',
    'PR' => 'Pɔtoriko',
    'CZ' => 'Repibiki Tsekɛ',
    'CD' => 'Repibiki demokratiki ya Kongó',
    'CF' => 'Repibiki ya Afríka ya Káti',
    'DO' => 'Repibiki ya Domínikɛ',
    'RU' => 'Risí',
    'RO' => 'Romani',
    'RW' => 'Rwanda',
    'WS' => 'Samoa',
    'AS' => 'Samoa ya Ameriki',
    'ST' => 'Sao Tomé mpé Presipɛ',
    'SV' => 'Savadɔrɛ',
    'SN' => 'Senegalɛ',
    'CS' => 'Serebi mpé Monténegro',
    'SL' => 'Siera Leonɛ',
    'SK' => 'Silovaki',
    'SI' => 'Siloveni',
    'SG' => 'Singapurɛ',
    'CN' => 'Sinɛ',
    'LK' => 'Sirilanka',
    'SY' => 'Sirí',
    'SO' => 'Somali',
    'SD' => 'Sudá',
    'SR' => 'Surinamɛ',
    'SZ' => 'Swazilandi',
    'CH' => 'Swisɛ',
    'SE' => 'Swédɛ',
    'SM' => 'Sántu Marinɛ',
    'SH' => 'Sántu eleni',
    'KN' => 'Sántu krístofe mpé Nevɛ̀s',
    'LC' => 'Sántu lisi',
    'PM' => 'Sántu pététo mpé Mikelɔ',
    'VC' => 'Sántu vesá mpé Gelenadinɛ',
    'CL' => 'Síli',
    'CY' => 'Sípɛlɛ',
    'SC' => 'Sɛshɛlɛ',
    'TH' => 'Tailandɛ',
    'TW' => 'Taiwanin',
    'TZ' => 'Tanzani',
    'TJ' => 'Tazikisitá',
    'TM' => 'Tikɛménisitá',
    'TR' => 'Tiliki',
    'TL' => 'Timorɛ ya Moniɛlɛ',
    'TT' => 'Tinidadɛ mpé Tobago',
    'TN' => 'Tinizi',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TD' => 'Tsádi',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UZ' => 'Uzibɛkisitá',
    'VU' => 'Vanuatu',
    'VA' => 'Vatiká',
    'VE' => 'Venézuela',
    'VN' => 'Viyetinamɛ',
    'WF' => 'Walisɛ mpé Futuna',
    'YE' => 'Yemɛnɛ',
    'JM' => 'Zamaiki',
    'ZM' => 'Zambi',
    'JP' => 'Zapɔ',
    'NZ' => 'Zelandɛ ya sika',
    'GI' => 'Zibatalɛ',
    'ZW' => 'Zimbabwe',
    'GE' => 'Zorzi',
    'JO' => 'Zɔdani',
    'IN' => 'Índɛ',
  ),
);
