<?php
/**
 * Locale data for 'mgh_MZ'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Mweri wo kwanza',
      2 => 'Mweri wo unayeli',
      3 => 'Mweri wo uneraru',
      4 => 'Mweri wo unecheshe',
      5 => 'Mweri wo unethanu',
      6 => 'Mweri wo thanu na mocha',
      7 => 'Mweri wo saba',
      8 => 'Mweri wo nane',
      9 => 'Mweri wo tisa',
      10 => 'Mweri wo kumi',
      11 => 'Mweri wo kumi na moja',
      12 => 'Mweri wo kumi na yel\'li',
    ),
    'abbreviated' => 
    array (
      1 => 'Kwa',
      2 => 'Una',
      3 => 'Rar',
      4 => 'Che',
      5 => 'Tha',
      6 => 'Moc',
      7 => 'Sab',
      8 => 'Nan',
      9 => 'Tis',
      10 => 'Kum',
      11 => 'Moj',
      12 => 'Yel',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'K',
      2 => 'U',
      3 => 'R',
      4 => 'C',
      5 => 'T',
      6 => 'M',
      7 => 'S',
      8 => 'N',
      9 => 'T',
      10 => 'K',
      11 => 'M',
      12 => 'Y',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sabato',
      1 => 'Jumatatu',
      2 => 'Jumanne',
      3 => 'Jumatano',
      4 => 'Arahamisi',
      5 => 'Ijumaa',
      6 => 'Jumamosi',
    ),
    'abbreviated' => 
    array (
      0 => 'Sab',
      1 => 'Jtt',
      2 => 'Jnn',
      3 => 'Jtn',
      4 => 'Ara',
      5 => 'Iju',
      6 => 'Jmo',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'J',
      2 => 'J',
      3 => 'J',
      4 => 'A',
      5 => 'I',
      6 => 'J',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'MZN' => 
    array (
      'symbol' => 'MTn',
    ),
  ),
  'languages' => 
  array (
    'fa' => 'Iajemi',
    'ar' => 'Iarabu',
    'bn' => 'Ibangla',
    'be' => 'Ibelausi',
    'bg' => 'Ibulgaria',
    'my' => 'Iburma',
    'cs' => 'Icheki',
    'zh' => 'Ichina',
    'fr' => 'Ifaransa',
    'ig' => 'Igbo',
    'el' => 'Igiriki',
    'ha' => 'Ihausa',
    'hi' => 'Ihindi',
    'es' => 'Ihispaniola',
    'nl' => 'Iholanzi',
    'hu' => 'Ihungari',
    'ur' => 'Ihurdu',
    'ja' => 'Ijapani',
    'jv' => 'Ijava',
    'de' => 'Ijerimani',
    'km' => 'Ikambodia',
    'ak' => 'Ikan',
    'ko' => 'Ikorea',
    'ms' => 'Imalesia',
    'am' => 'Imhari',
    'ne' => 'Inepali',
    'en' => 'Ingilishi',
    'rw' => 'Inyaranda',
    'pl' => 'Ipolandi',
    'pa' => 'Ipunjabi',
    'ru' => 'Irisi',
    'ro' => 'Iromania',
    'so' => 'Isomali',
    'sv' => 'Iswidi',
    'th' => 'Itailandi',
    'it' => 'Italiano',
    'ta' => 'Itamil',
    'tr' => 'Ituruki',
    'uk' => 'Iukran',
    'vi' => 'Ivyetinamu',
    'yo' => 'Iyoruba',
    'zu' => 'Izulu',
    'mgh' => 'Makua',
    'pt' => 'Nreno',
  ),
  'countries' => 
  array (
    'ZA' => 'Afrika du Sulu',
    'DZ' => 'Alujeria',
    'IT' => 'Italia',
    'PY' => 'Paragwai',
    'AL' => 'Ualbania',
    'AD' => 'Uandora',
    'IE' => 'Uayalandi',
    'AZ' => 'Uazabajani',
    'BJ' => 'Ubelin',
    'MG' => 'Ubukini',
    'TD' => 'Uchadi',
    'CZ' => 'Ucheki',
    'CL' => 'Uchile',
    'CN' => 'Uchina',
    'DK' => 'Udenimaka',
    'DM' => 'Udominika',
    'FR' => 'Ufaransa',
    'GF' => 'Ufaransa yo Gwaya',
    'PF' => 'Ufaransa yo Potina',
    'FJ' => 'Ufiji',
    'PH' => 'Ufilipino',
    'FI' => 'Ufini',
    'AF' => 'Ufugustani',
    'GA' => 'Ugaboni',
    'GM' => 'Ugambia',
    'GH' => 'Ugana',
    'GN' => 'Ugine',
    'GW' => 'Uginebisau',
    'GD' => 'Ugrenada',
    'GL' => 'Ugrinlandi',
    'GY' => 'Uguyana',
    'GP' => 'Ugwadelupe',
    'GU' => 'Ugwam',
    'GT' => 'Ugwatemala',
    'ET' => 'Uhabeshi',
    'HT' => 'Uhaiti',
    'IN' => 'Uhindini',
    'ES' => 'Uhispania',
    'HN' => 'Uhondurasi',
    'HU' => 'Uhungaria',
    'IL' => 'Uisraeli',
    'JM' => 'Ujamaika',
    'JP' => 'Ujapani',
    'GI' => 'Ujibralta',
    'DJ' => 'Ujibuti',
    'TJ' => 'Ujikistani',
    'GE' => 'Ujojia',
    'KH' => 'Ukambodia',
    'CA' => 'Ukanada',
    'QA' => 'Ukatari',
    'KZ' => 'Ukazakistani',
    'KE' => 'Ukenya',
    'CI' => 'Ukodiva',
    'CO' => 'Ukolombia',
    'KM' => 'Ukomoro',
    'CG' => 'Ukongo',
    'HR' => 'Ukorasia',
    'KP' => 'Ukorea Kaskazini',
    'KR' => 'Ukorea Kusini',
    'CU' => 'Ukuba',
    'CY' => 'Ukuprosi',
    'LV' => 'Ulativia',
    'LB' => 'Ulebanoni',
    'LS' => 'Ulesoto',
    'LR' => 'Uliberia',
    'LY' => 'Ulibya',
    'MW' => 'Umalawi',
    'ME' => 'Umantegro',
    'US' => 'Umarekani',
    'MK' => 'Umasedonia',
    'EG' => 'Umisiri',
    'MZ' => 'Umozambiki',
    'ID' => 'Undonesia',
    'NE' => 'Unijeri',
    'NG' => 'Unijeria',
    'NO' => 'Unorwe',
    'OM' => 'Uomani',
    'PK' => 'Upakistani',
    'PA' => 'Upanama',
    'PG' => 'Upapua',
    'PE' => 'Uperuu',
    'PN' => 'Upitkairni',
    'PL' => 'Upolandi',
    'PR' => 'Upwetoriko',
    'ER' => 'Uriterea',
    'RE' => 'Uriyunioni',
    'RO' => 'Uromania',
    'BI' => 'Urundi',
    'RW' => 'Urwanda',
    'SV' => 'Usalavado',
    'SM' => 'Usamarino',
    'WS' => 'Usamoa',
    'AS' => 'Usamoa ya Marekani',
    'SH' => 'Usantahelena',
    'KN' => 'Usantakitzi na Nevis',
    'LC' => 'Usantalusia',
    'PM' => 'Usantapieri na Mikeloni',
    'VC' => 'Usantavisenti na Grenadini',
    'ST' => 'Usao Tome na Principe',
    'SA' => 'Usaudi',
    'LU' => 'Usembaji',
    'SN' => 'Usenegali',
    'SC' => 'Ushelisheli',
    'LI' => 'Ushenteni',
    'CS' => 'Usiera Leoni',
    'SG' => 'Usingapoo',
    'SY' => 'Usiria',
    'LK' => 'Usirilanka',
    'SK' => 'Uslovakia',
    'SI' => 'Uslovenia',
    'SO' => 'Usomalia',
    'SD' => 'Usudani',
    'SR' => 'Usurinamu',
    'SZ' => 'Uswazi',
    'SE' => 'Uswidi',
    'CH' => 'Uswisi',
    'TH' => 'Utailandi',
    'TZ' => 'Utanzania',
    'TL' => 'Utimo Mashariki',
    'TG' => 'Utogo',
    'TK' => 'Utokelau',
    'TO' => 'Utonga',
    'TT' => 'Utrinidad na Tobago',
    'TR' => 'Utuki',
    'TN' => 'Utunisia',
    'TM' => 'Uturukimenistani',
    'TV' => 'Utuvalu',
    'LT' => 'Utwania',
    'VU' => 'Uvanuatu',
    'VA' => 'Uvatikani',
    'VE' => 'Uvenezuela',
    'VN' => 'Uvietinamu',
    'WF' => 'Uwalis na Futuna',
    'YE' => 'Uyemeni',
    'JO' => 'Uyordani',
    'ZM' => 'Uzambia',
    'ZW' => 'Uzimbabwe',
    'IQ' => 'Wiraki',
  ),
);
