<?php
/**
 * Locale data for 'mua_CM'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Fĩi Loo',
      2 => 'Cokcwaklaŋne',
      3 => 'Cokcwaklii',
      4 => 'Fĩi Marfoo',
      5 => 'Madǝǝuutǝbijaŋ',
      6 => 'Mamǝŋgwãafahbii',
      7 => 'Mamǝŋgwãalii',
      8 => 'Madǝmbii',
      9 => 'Fĩi Dǝɓlii',
      10 => 'Fĩi Mundaŋ',
      11 => 'Fĩi Gwahlle',
      12 => 'Fĩi Yuru',
    ),
    'abbreviated' => 
    array (
      1 => 'FLO',
      2 => 'CLA',
      3 => 'CKI',
      4 => 'FMF',
      5 => 'MAD',
      6 => 'MBI',
      7 => 'MLI',
      8 => 'MAM',
      9 => 'FDE',
      10 => 'FMU',
      11 => 'FGW',
      12 => 'FYU',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'O',
      2 => 'A',
      3 => 'I',
      4 => 'F',
      5 => 'D',
      6 => 'B',
      7 => 'L',
      8 => 'M',
      9 => 'E',
      10 => 'U',
      11 => 'W',
      12 => 'Y',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Com\'yakke',
      1 => 'Comlaaɗii',
      2 => 'Comzyiiɗii',
      3 => 'Comkolle',
      4 => 'Comkaldǝɓlii',
      5 => 'Comgaisuu',
      6 => 'Comzyeɓsuu',
    ),
    'abbreviated' => 
    array (
      0 => 'Cya',
      1 => 'Cla',
      2 => 'Czi',
      3 => 'Cko',
      4 => 'Cka',
      5 => 'Cga',
      6 => 'Cze',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Y',
      1 => 'L',
      2 => 'Z',
      3 => 'O',
      4 => 'A',
      5 => 'G',
      6 => 'E',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'solai Australya',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'solai Kanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'solai Syiŋ',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'solai Euro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'solai Britaniya',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'solai India',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'solai Japoŋ',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Solai Amerika',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'solai BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'solai BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'AED' => 
    array (
      'name' => 'Solai Arabiya',
    ),
    'AOA' => 
    array (
      'name' => 'solai Angola',
    ),
    'BHD' => 
    array (
      'name' => 'solai Barenya',
    ),
    'BIF' => 
    array (
      'name' => 'solai Burundi',
    ),
    'BWP' => 
    array (
      'name' => 'solai Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'solai Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'Solai Swiss',
    ),
    'CVE' => 
    array (
      'name' => 'solai Kapverdiya',
    ),
    'DJF' => 
    array (
      'name' => 'solai Djibouti',
    ),
    'DZD' => 
    array (
      'name' => 'solai Algerya',
    ),
    'EGP' => 
    array (
      'name' => 'solai Egypt',
    ),
    'ERN' => 
    array (
      'name' => 'solai Eritre',
    ),
    'ETB' => 
    array (
      'name' => 'solai Etiopia',
    ),
    'GHC' => 
    array (
      'name' => 'solai Gana',
    ),
    'GMD' => 
    array (
      'name' => 'solai Gambiya',
    ),
    'GNS' => 
    array (
      'name' => 'solai Guine',
    ),
    'KES' => 
    array (
      'name' => 'solai Kenia',
    ),
    'KMF' => 
    array (
      'name' => 'solai Komorya',
    ),
    'LRD' => 
    array (
      'name' => 'solai Liberiya',
    ),
    'LSL' => 
    array (
      'name' => 'solai Lesotho',
    ),
    'LYD' => 
    array (
      'name' => 'solai Libya',
    ),
    'MAD' => 
    array (
      'name' => 'Solai Marok',
    ),
    'MGA' => 
    array (
      'name' => 'Solai Malagasya',
    ),
    'MRO' => 
    array (
      'name' => 'Solai Mauritaniya',
    ),
    'MUR' => 
    array (
      'name' => 'Solai Mauricǝ',
    ),
    'MWK' => 
    array (
      'name' => 'Solai Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Solai Mozambika',
    ),
    'NAD' => 
    array (
      'name' => 'Solai Namibiya',
    ),
    'NGN' => 
    array (
      'name' => 'Solai Nigeriya',
    ),
    'RWF' => 
    array (
      'name' => 'Solai Rwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Solai Saudiya',
    ),
    'SCR' => 
    array (
      'name' => 'Solai Saichel',
    ),
    'SDG' => 
    array (
      'name' => 'Solai Sudaŋ ma dii ne dinar',
    ),
    'SDP' => 
    array (
      'name' => 'Solai Sudaŋ ma dii ne livre',
    ),
    'SHP' => 
    array (
      'name' => 'Solai Helena',
    ),
    'SLL' => 
    array (
      'name' => 'solai Sierra leonǝ',
    ),
    'SOS' => 
    array (
      'name' => 'Solai Somaliya',
    ),
    'STD' => 
    array (
      'name' => 'Solai Sao Tome',
    ),
    'SZL' => 
    array (
      'name' => 'solai Swaziland',
    ),
    'TND' => 
    array (
      'name' => 'Solai Tunisiya',
    ),
    'TZS' => 
    array (
      'name' => 'Solai Tanzaniya',
    ),
    'UGX' => 
    array (
      'name' => 'Solai Uganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Solai Africa nekǝsǝŋ',
    ),
    'ZMK' => 
    array (
      'name' => 'Solai Zambiya',
    ),
    'ZWD' => 
    array (
      'name' => 'Solai Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ak' => 'Akaŋ',
    'am' => 'Amharik',
    'ar' => 'Arabiya',
    'be' => 'Belarussiya',
    'bn' => 'Bengalia',
    'my' => 'Birmania',
    'bg' => 'Bulgaria',
    'es' => 'Espaniya',
    'de' => 'Germaŋ',
    'el' => 'Grek',
    'ha' => 'Haussa',
    'hi' => 'Hindi',
    'hu' => 'Hungariya',
    'ig' => 'Igbo',
    'id' => 'Indonesiya',
    'it' => 'Italiya',
    'jv' => 'Javaniya',
    'km' => 'Kmer',
    'ko' => 'Korea',
    'mua' => 'MUNDAŊ',
    'ms' => 'Malasiya',
    'ne' => 'Nepaliya',
    'fa' => 'Persia',
    'pl' => 'Poloniya',
    'pa' => 'Pǝnjabi',
    'ro' => 'Romaniya',
    'ru' => 'Russiya',
    'so' => 'Somaliya',
    'sv' => 'Swedia',
    'cs' => 'Syekya',
    'th' => 'Tai',
    'ta' => 'Tamul',
    'tr' => 'Turk',
    'uk' => 'Ukrainia',
    'ur' => 'Urdu',
    'vi' => 'Vietnamiya',
    'yo' => 'Yoruba',
    'en' => 'Zah Anglofoŋ',
    'zh' => 'Zah Syiŋ',
    'fr' => 'Zah sǝr Franssǝ',
    'ja' => 'Zah sǝr Japoŋ',
    'pt' => 'Zah sǝr Portugal',
    'rw' => 'Zah sǝr Rwanda',
    'nl' => 'Zah sǝr ma kasǝŋ',
    'zu' => 'Zulu',
  ),
  'countries' => 
  array (
    'AF' => 'Afghanistaŋ',
    'ZA' => 'Afrika nekǝsǝŋ',
    'AL' => 'Albaniya',
    'DZ' => 'Algeriya',
    'US' => 'Amerika',
    'AD' => 'Andorra',
    'IO' => 'Anglofoŋ ma Indiya',
    'AO' => 'Angola',
    'AI' => 'Anguiya',
    'AG' => 'Antiguan ne Barbuda',
    'AR' => 'Argentiniya',
    'AM' => 'Armeniya',
    'AW' => 'Aruba',
    'AU' => 'Australiya',
    'AT' => 'Austriya',
    'AZ' => 'Azerbaijaŋ',
    'BS' => 'Bahamas',
    'BH' => 'Bahraiŋ',
    'BD' => 'Bangladeshiya',
    'BB' => 'Barbadiya',
    'BY' => 'Belarussiya',
    'BE' => 'Belgika',
    'BZ' => 'Beliziya',
    'BJ' => 'Beniŋ',
    'BM' => 'Bermudiya',
    'BO' => 'Boliviya',
    'BA' => 'Bosniya ne Herzegovina',
    'BW' => 'Botswana',
    'BR' => 'Brazilya',
    'BN' => 'Bruniya',
    'BG' => 'Bulgariya',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'BT' => 'Butaŋ',
    'CF' => 'Centrafrika',
    'DK' => 'Daŋmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominik',
    'EC' => 'Ekwatǝr',
    'ES' => 'Espaŋiya',
    'EE' => 'Estoniya',
    'ET' => 'Etiopia',
    'PH' => 'Filipiŋ',
    'FR' => 'Franssǝ',
    'GA' => 'Gaboŋ',
    'GM' => 'Gambiya',
    'GH' => 'Gana',
    'GE' => 'Georgiya',
    'DE' => 'Germaniya',
    'GD' => 'Grenadǝ',
    'GN' => 'Guine',
    'GW' => 'Guine ma Bissao',
    'GY' => 'Guyana',
    'GU' => 'Gwam',
    'GT' => 'Gwatemala',
    'HU' => 'Hungriya',
    'ID' => 'Indonesiya',
    'IQ' => 'Irak',
    'IR' => 'Iraŋ',
    'IT' => 'Italiya',
    'JM' => 'Jamaika',
    'JP' => 'Japaŋ',
    'JO' => 'Jordaniya',
    'NC' => 'Kaledoniya mafuu',
    'KH' => 'Kambodiya',
    'CM' => 'Kameruŋ',
    'CA' => 'Kanada',
    'CV' => 'Kap ma laŋne',
    'QA' => 'Katar',
    'KY' => 'Kayman ma laŋne',
    'KZ' => 'Kazakstaŋ',
    'KG' => 'Kirgizstaŋ',
    'CO' => 'Kolombiya',
    'KM' => 'Komora',
    'CG' => 'Kongo',
    'CK' => 'Kook ma laŋne',
    'CR' => 'Kosta Rika',
    'HR' => 'Kroatiya',
    'CU' => 'Kuba',
    'LV' => 'Letoniya',
    'LB' => 'Libaŋ',
    'LR' => 'Liberiya',
    'LY' => 'Libiya',
    'LI' => 'Lichtǝnsteiŋ',
    'LT' => 'Lituaniya',
    'MK' => 'Macedoniya',
    'MG' => 'Madagaskar',
    'MY' => 'Malaysiya',
    'MV' => 'Maldivǝ',
    'MA' => 'Marok',
    'MQ' => 'Martinika',
    'MR' => 'Mauritaniya',
    'YT' => 'Mayot',
    'MX' => 'Mexiko',
    'FM' => 'Micronesiya',
    'MD' => 'Moldoviya',
    'MC' => 'Monako',
    'MN' => 'Mongoliya',
    'MZ' => 'Mozambika',
    'NA' => 'Namibiya',
    'NG' => 'Nigeriya',
    'NI' => 'Nikaragwa',
    'NU' => 'Niwe',
    'NF' => 'Norfolk ma laŋne',
    'NO' => 'Norvegǝ',
    'OM' => 'Omaŋ',
    'PK' => 'Pakistaŋ',
    'PG' => 'Papuasiya Guine mafuu',
    'PY' => 'Paragwai',
    'PE' => 'Peru',
    'PN' => 'Pitkairn',
    'PL' => 'Pologŋ',
    'PR' => 'Porto Riko',
    'RO' => 'Romaniya',
    'RU' => 'Russiya',
    'RW' => 'Rwanda',
    'SC' => 'Saichel',
    'AS' => 'Samoa Amerika',
    'ST' => 'Sao Tome ne Principe',
    'SN' => 'Senegal',
    'VG' => 'Ser Anglofon ma laŋne',
    'CI' => 'Ser Ivoiriya',
    'CS' => 'Serbiya ne Montenegro',
    'SL' => 'Sierra Leonǝ',
    'SG' => 'Singapur',
    'SK' => 'Slovakiya',
    'SI' => 'Sloveniya',
    'SO' => 'Somaliya',
    'SD' => 'Sudaŋ',
    'TD' => 'Syad',
    'CL' => 'Syili',
    'CY' => 'Syipriya',
    'CN' => 'Syiŋ',
    'SY' => 'Syria',
    'GB' => 'Sǝr Anglofoŋ',
    'SA' => 'Sǝr Arabiya',
    'AE' => 'Sǝr Arabiya ma taini',
    'DO' => 'Sǝr Dominik ma lii',
    'EG' => 'Sǝr Egypt',
    'ER' => 'Sǝr Eritre',
    'FJ' => 'Sǝr Fiji',
    'FI' => 'Sǝr Finland',
    'GI' => 'Sǝr Gibraltar',
    'GR' => 'Sǝr Grek',
    'GL' => 'Sǝr Groenland',
    'GQ' => 'Sǝr Guine',
    'GF' => 'Sǝr Guyana ma Franssǝ',
    'GP' => 'Sǝr Gwadeloupǝ',
    'HT' => 'Sǝr Haiti',
    'SH' => 'Sǝr Helena',
    'HN' => 'Sǝr Honduras',
    'IN' => 'Sǝr Indǝ',
    'IE' => 'Sǝr Ireland',
    'IS' => 'Sǝr Island',
    'IL' => 'Sǝr Israel',
    'KE' => 'Sǝr Kenya',
    'KI' => 'Sǝr Kiribati',
    'CD' => 'Sǝr Kongo ma dii ne zair',
    'KP' => 'Sǝr Kore fah sǝŋ',
    'KR' => 'Sǝr Kore nekǝsǝŋ',
    'KW' => 'Sǝr Kowait',
    'KN' => 'Sǝr Kristof ne Nievǝ',
    'LK' => 'Sǝr Lanka',
    'LA' => 'Sǝr Laos',
    'LS' => 'Sǝr Lesotho',
    'LC' => 'Sǝr Lucia',
    'LU' => 'Sǝr Luxemburg',
    'MW' => 'Sǝr Malawi',
    'ML' => 'Sǝr Mali',
    'MT' => 'Sǝr Malta',
    'MP' => 'Sǝr Maria ma laŋne',
    'SM' => 'Sǝr Marino',
    'MH' => 'Sǝr Marshall ma laŋne',
    'MU' => 'Sǝr Mauricǝ',
    'MS' => 'Sǝr Montserrat',
    'MM' => 'Sǝr Myanmar',
    'NR' => 'Sǝr Nauru',
    'NP' => 'Sǝr Nepal',
    'NE' => 'Sǝr Niger',
    'PW' => 'Sǝr Palau',
    'PS' => 'Sǝr Palestiniya',
    'PA' => 'Sǝr Panama',
    'PF' => 'Sǝr Polynesiya ma Franssǝ',
    'PT' => 'Sǝr Portugal',
    'PM' => 'Sǝr Pǝtar ne Mikǝlon',
    'RE' => 'Sǝr Reunion',
    'SB' => 'Sǝr Salomon ma laŋne',
    'SV' => 'Sǝr Salvador',
    'WS' => 'Sǝr Samoa',
    'SE' => 'Sǝr Sued',
    'SR' => 'Sǝr Surinam',
    'SZ' => 'Sǝr Swaziland',
    'CH' => 'Sǝr Swiss',
    'CZ' => 'Sǝr Syek',
    'TG' => 'Sǝr Togo',
    'TK' => 'Sǝr Tokelau',
    'TO' => 'Sǝr Tonga',
    'TV' => 'Sǝr Tuvalu',
    'VU' => 'Sǝr Vanuatu',
    'VE' => 'Sǝr Venezuela',
    'VN' => 'Sǝr Vietnam',
    'VC' => 'Sǝr Vinceŋ ne Grenadiŋ',
    'VI' => 'Sǝr amerika ma laŋne',
    'NL' => 'Sǝr ma kasǝŋ',
    'AN' => 'Sǝr ma kasǝŋ ma laŋne',
    'FK' => 'Sǝr malouniya ma laŋne',
    'TH' => 'Tailand',
    'TW' => 'Taiwaŋ',
    'TJ' => 'Tajikistaŋ',
    'TZ' => 'Tanzaniya',
    'TL' => 'Timoriya',
    'TT' => 'Trinite ne Tobago',
    'TN' => 'Tunisiya',
    'TR' => 'Turkiya',
    'TC' => 'Turkiya ne kaicos ma laŋne',
    'TM' => 'Turkmenistaŋ',
    'UG' => 'Uganda',
    'UA' => 'Ukraiŋ',
    'UY' => 'Urugwai',
    'UZ' => 'Uzbekistaŋ',
    'VA' => 'Vaticaŋ',
    'WF' => 'Wallis ne Futuna',
    'YE' => 'Yemeŋ',
    'ZM' => 'Zambiya',
    'NZ' => 'Zeland mafuu',
    'ZW' => 'Zimbabwe',
  ),
);
