<?php
/**
 * Locale data for 'nd_ZW'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Zibandlela',
      2 => 'Nhlolanja',
      3 => 'Mbimbitho',
      4 => 'Mabasa',
      5 => 'Nkwenkwezi',
      6 => 'Nhlangula',
      7 => 'Ntulikazi',
      8 => 'Ncwabakazi',
      9 => 'Mpandula',
      10 => 'Mfumfu',
      11 => 'Lwezi',
      12 => 'Mpalakazi',
    ),
    'abbreviated' => 
    array (
      1 => 'Zib',
      2 => 'Nhl',
      3 => 'Mbi',
      4 => 'Mab',
      5 => 'Nkw',
      6 => 'Nhl',
      7 => 'Ntu',
      8 => 'Ncw',
      9 => 'Mpa',
      10 => 'Mfu',
      11 => 'Lwe',
      12 => 'Mpa',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Z',
      2 => 'N',
      3 => 'M',
      4 => 'M',
      5 => 'N',
      6 => 'N',
      7 => 'N',
      8 => 'N',
      9 => 'M',
      10 => 'M',
      11 => 'L',
      12 => 'M',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sonto',
      1 => 'Mvulo',
      2 => 'Sibili',
      3 => 'Sithathu',
      4 => 'Sine',
      5 => 'Sihlanu',
      6 => 'Mgqibelo',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mvu',
      2 => 'Sib',
      3 => 'Sit',
      4 => 'Sin',
      5 => 'Sih',
      6 => 'Mgq',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'S',
      3 => 'S',
      4 => 'S',
      5 => 'S',
      6 => 'M',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Dola yase Australia',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Dola yase Khanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Yuan Renminbi yase China',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Yuro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Phawundi yase Ngilandi',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Rupi yase Indiya',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Yeni yase Japhani',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Dola yase Amelika',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Fulenki CFA BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Fulenki CFA BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'AED' => 
    array (
      'name' => 'Dola laseArab',
    ),
    'AOA' => 
    array (
      'name' => 'Kwanza yase Angola',
    ),
    'BHD' => 
    array (
      'name' => 'Dinari yase Bhahareni',
    ),
    'BIF' => 
    array (
      'name' => 'Fulenki yase Bhurundi',
    ),
    'BWP' => 
    array (
      'name' => 'Phula yase Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'Fulenki yase Khongo',
    ),
    'CHF' => 
    array (
      'name' => 'Fulenki yase Swisi',
    ),
    'CVE' => 
    array (
      'name' => 'Escudo Caboverdiano',
    ),
    'DJF' => 
    array (
      'name' => 'Fulenki yase Jibhuthi',
    ),
    'DZD' => 
    array (
      'name' => 'Dinali yase Aljeriya',
    ),
    'EGP' => 
    array (
      'name' => 'Phawundi laseGibhide',
    ),
    'ERN' => 
    array (
      'name' => 'Nakfa yase Eritrea',
    ),
    'ETB' => 
    array (
      'name' => 'Dola laseEthiopia',
    ),
    'GHC' => 
    array (
      'name' => 'Sedi yase Ghana',
    ),
    'GMD' => 
    array (
      'name' => 'Dalasi yase Gambia',
    ),
    'GNS' => 
    array (
      'name' => 'Fulenki yase Gine',
    ),
    'KES' => 
    array (
      'name' => 'Shilingi yase Kenya',
    ),
    'KMF' => 
    array (
      'name' => 'Fulenki yase Khomoro',
    ),
    'LRD' => 
    array (
      'name' => 'Dola yase Libheriya',
    ),
    'LSL' => 
    array (
      'name' => 'Lothi yase Lesotho',
    ),
    'LYD' => 
    array (
      'name' => 'Dinari yase Libya',
    ),
    'MAD' => 
    array (
      'name' => 'Dirham yase Morokho',
    ),
    'MGA' => 
    array (
      'name' => 'Fulenki yase Malagasi',
    ),
    'MRO' => 
    array (
      'name' => 'Ugwiya yase Moritaniya',
    ),
    'MUR' => 
    array (
      'name' => 'Rupi yase Morishasi',
    ),
    'MWK' => 
    array (
      'name' => 'Kwacha yase Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Metikali yase Mozambiki',
    ),
    'NAD' => 
    array (
      'name' => 'Dola yase Namibiya',
    ),
    'NGN' => 
    array (
      'name' => 'Nayira yase Nijeriya',
    ),
    'RWF' => 
    array (
      'name' => 'Fulenki yase Ruwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Riyal yase Saudi',
    ),
    'SCR' => 
    array (
      'name' => 'Rupi yase Seyisheli',
    ),
    'SDG' => 
    array (
      'name' => 'Dinari yase Sudani',
    ),
    'SDP' => 
    array (
      'name' => 'Phawundi yase Sudani',
    ),
    'SHP' => 
    array (
      'name' => 'Phawundindi laseSt Helena',
    ),
    'SLL' => 
    array (
      'name' => 'Leyoni',
    ),
    'SOS' => 
    array (
      'name' => 'Shilingi yase Somaliya',
    ),
    'STD' => 
    array (
      'name' => 'Dobra yase Sao Tome lo Principe',
    ),
    'SZL' => 
    array (
      'name' => 'Lilangeni',
    ),
    'TND' => 
    array (
      'name' => 'Dinari yase Tunisiya',
    ),
    'TZS' => 
    array (
      'name' => 'Shilingi yase Tanzaniya',
    ),
    'UGX' => 
    array (
      'name' => 'Shilingi yase Uganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Randi yase Afrika ye Zanzi',
    ),
    'ZMK' => 
    array (
      'name' => 'Kwacha yase Zambiya',
    ),
    'ZWD' => 
    array (
      'name' => 'Dola yase Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ak' => 'Isi-Akhani',
    'ar' => 'Isi-Alabhu',
    'am' => 'Isi-Amaharikhi',
    'be' => 'Isi-Bhelarashiyani',
    'bn' => 'Isi-Bhengali',
    'bg' => 'Isi-Bulgaria',
    'my' => 'Isi-Burma',
    'zh' => 'Isi-China',
    'cs' => 'Isi-Czech',
    'nl' => 'Isi-Dutch',
    'fr' => 'Isi-Fulentshi',
    'el' => 'Isi-Giliki',
    'hu' => 'Isi-Hangari',
    'ha' => 'Isi-Hausa',
    'hi' => 'Isi-Hindi',
    'ig' => 'Isi-Igbo',
    'id' => 'Isi-Indonesia',
    'it' => 'Isi-Italiano',
    'de' => 'Isi-Jalimani',
    'ja' => 'Isi-Japhani',
    'jv' => 'Isi-Java',
    'km' => 'Isi-Khambodiya',
    'ko' => 'Isi-Koriya',
    'ms' => 'Isi-Malayi',
    'ne' => 'Isi-Nepali',
    'en' => 'Isi-Ngisi',
    'fa' => 'Isi-Pheshiyani',
    'pl' => 'Isi-Pholoshi',
    'pa' => 'Isi-Phunjabi',
    'pt' => 'Isi-Potukezi',
    'ru' => 'Isi-Rashiya',
    'ro' => 'Isi-Romani',
    'rw' => 'Isi-Ruwanda',
    'es' => 'Isi-Sipeyini',
    'so' => 'Isi-Somali',
    'sv' => 'Isi-Swidishi',
    'ta' => 'Isi-Thamil',
    'th' => 'Isi-Thayi',
    'tr' => 'Isi-Thekishi',
    'ur' => 'Isi-Udu',
    'uk' => 'Isi-Ukrain',
    'vi' => 'Isi-Vietnamese',
    'yo' => 'Isi-Yorubha',
    'zu' => 'Isi-Zulu',
    'nd' => 'IsiNdebele',
  ),
  'countries' => 
  array (
    'AF' => 'Afghanistan',
    'AR' => 'Ajentina',
    'AL' => 'Albania',
    'DZ' => 'Aljeriya',
    'US' => 'Amelika',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AG' => 'Antigua le Barbuda',
    'AM' => 'Armenia',
    'AW' => 'Arubha',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BB' => 'Bhabhadosi',
    'BS' => 'Bhahamas',
    'BH' => 'Bhahareni',
    'BD' => 'Bhangiladeshi',
    'BY' => 'Bhelarusi',
    'BE' => 'Bhelgium',
    'BZ' => 'Bhelize',
    'BM' => 'Bhemuda',
    'BJ' => 'Bhenini',
    'BO' => 'Bholiviya',
    'BA' => 'Bhosnia le Herzegovina',
    'BF' => 'Bhukina Faso',
    'BG' => 'Bhulgariya',
    'BI' => 'Bhurundi',
    'BT' => 'Bhutani',
    'BW' => 'Botswana',
    'BR' => 'Brazili',
    'IO' => 'British Indian Ocean Territory',
    'VG' => 'British Virgin Islands',
    'BN' => 'Brunei',
    'KH' => 'Cambodia',
    'CV' => 'Cape Verde Islands',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chadi',
    'CL' => 'Chile',
    'CN' => 'China',
    'CK' => 'Cook Islands',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'CD' => 'Democratic Republic of the Congo',
    'DK' => 'Denmakhi',
    'DJ' => 'Djibouti',
    'DO' => 'Dominican Republic',
    'DM' => 'Dominikha',
    'TL' => 'East Timor',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'Furansi',
    'GA' => 'Gabhoni',
    'GM' => 'Gambiya',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'GF' => 'Gwiyana ye Furansi',
    'HT' => 'Hayiti',
    'HN' => 'Honduras',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'Indiya',
    'ID' => 'Indonesiya',
    'IQ' => 'Iraki',
    'IR' => 'Iran',
    'IE' => 'Ireland',
    'IL' => 'Isuraeli',
    'IT' => 'Itali',
    'CI' => 'Ivory Coast',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JO' => 'Jodani',
    'QA' => 'Kathari',
    'KZ' => 'Kazakhstan',
    'CM' => 'Khameruni',
    'CA' => 'Khanada',
    'KE' => 'Khenya',
    'KI' => 'Khiribati',
    'CO' => 'Kholombiya',
    'KM' => 'Khomoro',
    'CG' => 'Khongo',
    'CR' => 'Khosta Rikha',
    'KW' => 'Khuweiti',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LB' => 'Lebhanoni',
    'LS' => 'Lesotho',
    'LR' => 'Libheriya',
    'LY' => 'Libhiya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MK' => 'Macedonia',
    'MG' => 'Madagaska',
    'MW' => 'Malawi',
    'MV' => 'Maldives',
    'MY' => 'Malezhiya',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Meksikho',
    'FM' => 'Micronesia',
    'MD' => 'Moldova',
    'MC' => 'Monakho',
    'MN' => 'Mongolia',
    'MS' => 'Montserrat',
    'MA' => 'Morokho',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'ZA' => 'Mzansi ye Afrika',
    'NA' => 'Namibhiya',
    'NR' => 'Nauru',
    'NP' => 'Nephali',
    'NL' => 'Netherlands',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeriya',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'KP' => 'North Korea',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Noweyi',
    'OM' => 'Omani',
    'PW' => 'Palau',
    'PS' => 'Palestinian West Bank and Gaza',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PK' => 'Phakistani',
    'PE' => 'Pheru',
    'PH' => 'Philippines',
    'PL' => 'Pholandi',
    'PF' => 'Pholinesiya ye Fulansi',
    'PN' => 'Pitcairn',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'RU' => 'Rashiya',
    'RO' => 'Romania',
    'RW' => 'Ruwanda',
    'RE' => 'Réunion',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'PM' => 'Saint Pierre and Miquelon',
    'VC' => 'Saint Vincent and the Grenadines',
    'AS' => 'Samoa ye Amelika',
    'WS' => 'Samowa',
    'SM' => 'San Marino',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegali',
    'CS' => 'Serbia and Montenegro',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somaliya',
    'KR' => 'South Korea',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudani',
    'SR' => 'Suriname',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syria',
    'ST' => 'São Tomé and Príncipe',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzaniya',
    'TH' => 'Thayilandi',
    'TW' => 'Thayiwani',
    'TR' => 'Thekhi',
    'TG' => 'Thogo',
    'TK' => 'Thokelawu',
    'TO' => 'Thonga',
    'TV' => 'Thuvalu',
    'TT' => 'Trinidad le Tobago',
    'TN' => 'Tunisiya',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks and Caicos Islands',
    'VI' => 'U.S. Virgin Islands',
    'UG' => 'Uganda',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'UZ' => 'Uzbekistan',
    'VA' => 'Vatican State',
    'VE' => 'Venezuela',
    'VU' => 'Vhanuatu',
    'VN' => 'Vietnam',
    'WF' => 'Wallis and Futuna',
    'YE' => 'Yemeni',
    'UA' => 'Yukreini',
    'UY' => 'Yurugwai',
    'ZM' => 'Zambiya',
    'ZW' => 'Zimbabwe',
  ),
);
