<?php
/**
 * Locale data for 'nn_NO'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '4123',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '−',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0 %',
  'currencyFormat' => '#,##0.00 ¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE d. MMMM y',
    'long' => 'd. MMMM y',
    'medium' => 'd. MMM y',
    'short' => 'dd.MM.yy',
  ),
  'timeFormats' => 
  array (
    'full' => '\'kl\'. HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'januar',
      2 => 'februar',
      3 => 'mars',
      4 => 'april',
      5 => 'mai',
      6 => 'juni',
      7 => 'juli',
      8 => 'august',
      9 => 'september',
      10 => 'oktober',
      11 => 'november',
      12 => 'desember',
    ),
    'abbreviated' => 
    array (
      1 => 'jan.',
      2 => 'feb.',
      3 => 'mars',
      4 => 'apr.',
      5 => 'mai',
      6 => 'juni',
      7 => 'juli',
      8 => 'aug.',
      9 => 'sep.',
      10 => 'okt.',
      11 => 'nov.',
      12 => 'des.',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mar',
      4 => 'apr',
      6 => 'jun',
      7 => 'jul',
      8 => 'aug',
      9 => 'sep',
      10 => 'okt',
      11 => 'nov',
      12 => 'des',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'søndag',
      1 => 'måndag',
      2 => 'tysdag',
      3 => 'onsdag',
      4 => 'torsdag',
      5 => 'fredag',
      6 => 'laurdag',
    ),
    'abbreviated' => 
    array (
      0 => 'sø.',
      1 => 'må.',
      2 => 'ty.',
      3 => 'on.',
      4 => 'to.',
      5 => 'fr.',
      6 => 'la.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'O',
      4 => 'T',
      5 => 'F',
      6 => 'L',
    ),
    'abbreviated' => 
    array (
      0 => 'søn',
      1 => 'mån',
      2 => 'tys',
      3 => 'ons',
      4 => 'tor',
      5 => 'fre',
      6 => 'lau',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'australsk dollar',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'brasiliansk real',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'kanadisk dollar',
      'name-single' => 'kanadisk dollar',
      'name-multiple' => 'kanadiske dollar',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'kinesisk yuan renminbi',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'euro',
      'name-single' => 'euro',
      'name-multiple' => 'euro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'britisk pund sterling',
      'name-single' => 'britisk pund sterling',
      'name-multiple' => 'britiske pund sterling',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
      'name' => 'Hongkong-dollar',
      'name-single' => 'Hongkong-dollar',
      'name-multiple' => 'Hongkong-dollar',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
      'name' => 'israelsk ny shekel',
      'name-single' => 'israelsk ny shekel',
      'name-multiple' => 'israelske nye sheklar',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'indisk rupi',
      'name-single' => 'indisk rupi',
      'name-multiple' => 'indiske rupier',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'japansk yen',
      'name-single' => 'japansk yen',
      'name-multiple' => 'japanske yen',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
      'name' => 'sørkoreansk won',
      'name-single' => 'sørkoreansk won',
      'name-multiple' => 'sørkoreanske won',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'meksikansk peso',
      'name-single' => 'meksikansk peso',
      'name-multiple' => 'meksikanske peso',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
      'name' => 'new zealandsk dollar',
      'name-single' => 'new zealandsk dollar',
      'name-multiple' => 'new zealandske dollar',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
      'name' => 'thailandsk baht',
      'name-single' => 'thailandsk baht',
      'name-multiple' => 'thailandske baht',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
      'name' => 'taiwansk ny dollar',
      'name-single' => 'taiwansk ny dollar',
      'name-multiple' => 'taiwanske nye dollar',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'amerikansk dollar',
      'name-single' => 'amerikansk dollar',
      'name-multiple' => 'amerikanske dollar',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
      'name' => 'vietnamesisk dong',
      'name-single' => 'vietnamesisk dong',
      'name-multiple' => 'vietnamesiske dong',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'CFA franc BEAC',
      'name-single' => 'CFA franc BEAC',
      'name-multiple' => 'CFA franc BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
      'name' => 'austkaribisk dollar',
      'name-single' => 'austkaribisk dollar',
      'name-multiple' => 'austkaribiske dollar',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'CFA franc BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
      'name' => 'CFP franc',
      'name-single' => 'CFP-franc',
      'name-multiple' => 'CFP-franc',
    ),
    'NOK' => 
    array (
      'symbol' => 'kr',
      'name' => 'norsk krone',
      'name-single' => 'norsk krone',
      'name-multiple' => 'norske kroner',
    ),
    'ADP' => 
    array (
      'name' => 'andorransk peseta',
    ),
    'AED' => 
    array (
      'name' => 'UAE dirham',
    ),
    'AFA' => 
    array (
      'name' => 'afghani (1927-2002)',
    ),
    'AFN' => 
    array (
      'name' => 'afghani',
    ),
    'ALL' => 
    array (
      'name' => 'albansk lek',
    ),
    'AMD' => 
    array (
      'name' => 'armensk dram',
    ),
    'ANG' => 
    array (
      'name' => 'nederlansk antillegylden',
    ),
    'AOA' => 
    array (
      'name' => 'angolsk kwanza',
    ),
    'AOK' => 
    array (
      'name' => 'angolsk kwanza (1977-1990)',
    ),
    'AON' => 
    array (
      'name' => 'angolsk ny kwanza (1990-2000)',
    ),
    'AOR' => 
    array (
      'name' => 'angolsk kwanza reajustado (1995-1999)',
    ),
    'ARA' => 
    array (
      'name' => 'argentisk austral',
    ),
    'ARP' => 
    array (
      'name' => 'argentinsk peso (1983-1985)',
    ),
    'ARS' => 
    array (
      'name' => 'argentinsk peso',
    ),
    'ATS' => 
    array (
      'name' => 'austerriksk schilling',
    ),
    'AWG' => 
    array (
      'name' => 'arubisk gylden',
    ),
    'AZM' => 
    array (
      'name' => 'aserbaijansk manat',
    ),
    'AZN' => 
    array (
      'name' => 'aserbajdsjansk manat',
      'name-single' => 'aserbajdsjansk manat',
      'name-multiple' => 'aserbajdsjanske manat',
    ),
    'BAD' => 
    array (
      'name' => 'bosnisk-hercegovinsk dinar',
    ),
    'BAM' => 
    array (
      'name' => 'bosnisk-hercegovinsk mark (konvertibel)',
    ),
    'BBD' => 
    array (
      'name' => 'barbadisk dollar',
    ),
    'BDT' => 
    array (
      'name' => 'bangladeshisk taka',
    ),
    'BEC' => 
    array (
      'name' => 'belgisk franc (konvertibel)',
    ),
    'BEF' => 
    array (
      'name' => 'belgisk franc',
    ),
    'BEL' => 
    array (
      'name' => 'belgisk franc (finansiell)',
    ),
    'BGL' => 
    array (
      'name' => 'bulgarsk hard lev',
    ),
    'BGN' => 
    array (
      'name' => 'bulgarsk ny lev',
    ),
    'BHD' => 
    array (
      'name' => 'bahrainsk dinar',
    ),
    'BIF' => 
    array (
      'name' => 'burundisk franc',
    ),
    'BMD' => 
    array (
      'name' => 'bermudisk dollar',
    ),
    'BND' => 
    array (
      'name' => 'bruneisk dollar',
    ),
    'BOB' => 
    array (
      'name' => 'boliviano',
    ),
    'BOP' => 
    array (
      'name' => 'bolivisk peso',
    ),
    'BOV' => 
    array (
      'name' => 'bolivisk mvdol',
    ),
    'BRB' => 
    array (
      'name' => 'brasiliansk cruzeiro novo (1967-1986)',
    ),
    'BRC' => 
    array (
      'name' => 'brasiliansk cruzado',
    ),
    'BRE' => 
    array (
      'name' => 'brasiliansk cruzeiro (1990-1993)',
    ),
    'BRN' => 
    array (
      'name' => 'brasiliansk cruzado novo',
    ),
    'BRR' => 
    array (
      'name' => 'brasiliansk cruzeiro',
    ),
    'BSD' => 
    array (
      'name' => 'bahamisk dollar',
    ),
    'BTN' => 
    array (
      'name' => 'bhutansk ngultrum',
    ),
    'BUK' => 
    array (
      'name' => 'burmesisk kyat',
    ),
    'BWP' => 
    array (
      'name' => 'botswansk pula',
      'name-single' => 'botswansk pula',
      'name-multiple' => 'botswanske pula',
    ),
    'BYB' => 
    array (
      'name' => 'kviterussisk ny rubel (1994-1999)',
      'name-single' => 'kviterussisk ny rubel (BYB)',
      'name-multiple' => 'kviterussiske nye rublar (BYB)',
    ),
    'BYR' => 
    array (
      'name' => 'kviterussisk rubel',
      'name-single' => 'kviterussisk rubel',
      'name-multiple' => 'kviterussiske rublar',
    ),
    'BZD' => 
    array (
      'name' => 'belizisk dollar',
      'name-single' => 'belizisk dollar',
      'name-multiple' => 'beliziske dollar',
    ),
    'CDF' => 
    array (
      'name' => 'kongolesisk franc',
      'name-single' => 'kongolesisk franc',
      'name-multiple' => 'kongolesiske franc',
    ),
    'CHE' => 
    array (
      'name' => 'WIR euro',
      'name-single' => 'WIR euro',
      'name-multiple' => 'WIR euro',
    ),
    'CHF' => 
    array (
      'name' => 'sveitsisk franc',
      'name-single' => 'sveitsisk franc',
      'name-multiple' => 'sveitsiske franc',
    ),
    'CHW' => 
    array (
      'name' => 'WIR franc',
      'name-single' => 'WIR franc',
      'name-multiple' => 'WIR franc',
    ),
    'CLF' => 
    array (
      'name' => 'chilensk unidades de fomento',
      'name-single' => 'chilensk unidades de fomento',
      'name-multiple' => 'chilenske unidades de fomento',
    ),
    'CLP' => 
    array (
      'name' => 'chilensk peso',
      'name-single' => 'chilensk peso',
      'name-multiple' => 'chilenske peso',
    ),
    'COP' => 
    array (
      'name' => 'colombiansk peso',
      'name-single' => 'colombiansk peso',
      'name-multiple' => 'colombianske peso',
    ),
    'COU' => 
    array (
      'name' => 'unidad de valor real',
      'name-single' => 'unidad de valor real',
      'name-multiple' => 'unidad de valor real',
    ),
    'CRC' => 
    array (
      'name' => 'costaricansk colon',
      'name-single' => 'costaricansk colon',
      'name-multiple' => 'costaricanske colon',
    ),
    'CSD' => 
    array (
      'name' => 'gammal serbisk dinar',
      'name-single' => 'gammal serbisk dinar',
      'name-multiple' => 'gamle serbiske dinarar',
    ),
    'CSK' => 
    array (
      'name' => 'tsjekkoslovakisk koruna (hard)',
      'name-single' => 'tsjekkoslovakisk koruna (hard)',
      'name-multiple' => 'tsjekkoslovakiske koruna (hard)',
    ),
    'CUC' => 
    array (
      'name-single' => 'kubansk peso (konvertibel)',
      'name-multiple' => 'kubanska pesos (konvertibla)',
    ),
    'CUP' => 
    array (
      'name' => 'kubansk peso',
      'name-single' => 'kubansk peso',
      'name-multiple' => 'kubanske peso',
    ),
    'CVE' => 
    array (
      'name' => 'kappverdisk escudo',
    ),
    'CYP' => 
    array (
      'name' => 'kypriotisk pund',
      'name-single' => 'kypriotisk pund',
      'name-multiple' => 'kypriotiske pund',
    ),
    'CZK' => 
    array (
      'name' => 'tsjekkisk koruna',
      'name-single' => 'tsjekkisk koruna',
      'name-multiple' => 'tsjekkiske koruna',
    ),
    'DDM' => 
    array (
      'name' => 'austtysk mark',
      'name-single' => 'austtysk mark',
      'name-multiple' => 'austtyske mark',
    ),
    'DEM' => 
    array (
      'name' => 'tysk mark',
      'name-single' => 'tysk mark',
      'name-multiple' => 'tyske mark',
    ),
    'DJF' => 
    array (
      'name' => 'djiboutisk franc',
      'name-single' => 'djiboutisk franc',
      'name-multiple' => 'djiboutiske franc',
    ),
    'DKK' => 
    array (
      'name' => 'dansk krone',
      'name-single' => 'dansk krone',
      'name-multiple' => 'danske kroner',
    ),
    'DOP' => 
    array (
      'name' => 'dominikansk peso',
      'name-single' => 'dominikansk peso',
      'name-multiple' => 'dominikanske peso',
    ),
    'DZD' => 
    array (
      'name' => 'algerisk dinar',
      'name-single' => 'algerisk dinar',
      'name-multiple' => 'algeriske dinarar',
    ),
    'ECS' => 
    array (
      'name' => 'ecuadoriansk sucre',
      'name-single' => 'ecuadoriansk sucre',
      'name-multiple' => 'ecuadorianske sucre',
    ),
    'ECV' => 
    array (
      'name' => 'ecuadoriansk unidad de valor constante (UVC)',
      'name-single' => 'ecuadoriansk unidad de valor constante (UVC)',
      'name-multiple' => 'ecuadorianske unidad de valor constante (UVC)',
    ),
    'EEK' => 
    array (
      'name' => 'estisk kroon',
      'name-single' => 'estisk kroon',
      'name-multiple' => 'estiske kroon',
    ),
    'EGP' => 
    array (
      'name' => 'egyptisk pund',
      'name-single' => 'egyptisk pund',
      'name-multiple' => 'egyptiske pund',
    ),
    'ERN' => 
    array (
      'name' => 'eritreisk nakfa',
      'name-single' => 'eritreisk nakfa',
      'name-multiple' => 'eritreiske nakfa',
    ),
    'ESA' => 
    array (
      'name' => 'spansk peseta (A-konto)',
      'name-single' => 'spansk peseta (A-konto)',
      'name-multiple' => 'spanske peseta (A-konto)',
    ),
    'ESB' => 
    array (
      'name' => 'spansk peseta (konvertibel konto)',
      'name-single' => 'spansk peseta (konvertibel konto)',
      'name-multiple' => 'spanske peseta (konvertibel konto)',
    ),
    'ESP' => 
    array (
      'name' => 'spansk peseta',
      'name-single' => 'spansk peseta',
      'name-multiple' => 'spanske peseta',
    ),
    'ETB' => 
    array (
      'name' => 'etiopisk birr',
      'name-single' => 'etiopisk birr',
      'name-multiple' => 'etiopiske birr',
    ),
    'FIM' => 
    array (
      'name' => 'finsk mark',
      'name-single' => 'finsk mark',
      'name-multiple' => 'finske mark',
    ),
    'FJD' => 
    array (
      'name' => 'fijiansk dollar',
      'name-single' => 'fijiansk dollar',
      'name-multiple' => 'fijianske dollar',
    ),
    'FKP' => 
    array (
      'name' => 'Falkland-pund',
      'name-single' => 'Falkland-pund',
      'name-multiple' => 'Falkland-pund',
    ),
    'FRF' => 
    array (
      'name' => 'fransk franc',
      'name-single' => 'fransk franc',
      'name-multiple' => 'franske franc',
    ),
    'GEK' => 
    array (
      'name' => 'georgisk kupon larit',
      'name-single' => 'georgisk kupon larit',
      'name-multiple' => 'georgiske kupon larit',
    ),
    'GEL' => 
    array (
      'name' => 'georgisk lari',
      'name-single' => 'georgisk lari',
      'name-multiple' => 'georgiske lari',
    ),
    'GHC' => 
    array (
      'name' => 'ghanesisk cedi (1979-2007)',
      'name-single' => 'ghanesisk cedi (GHC)',
      'name-multiple' => 'ghanesiske cedi (GHC)',
    ),
    'GHS' => 
    array (
      'name' => 'ghanesisk cedi',
      'name-single' => 'ghanesisk cedi',
      'name-multiple' => 'ghanesiske cedi',
    ),
    'GIP' => 
    array (
      'name' => 'gibraltarsk pund',
      'name-single' => 'gibraltarsk pund',
      'name-multiple' => 'gibraltarske pund',
    ),
    'GMD' => 
    array (
      'name' => 'gambisk dalasi',
      'name-single' => 'gambisk dalasi',
      'name-multiple' => 'gambiske dalasi',
    ),
    'GNF' => 
    array (
      'name' => 'guineansk franc',
      'name-single' => 'guineansk franc',
      'name-multiple' => 'guineanske franc',
    ),
    'GNS' => 
    array (
      'name' => 'guineansk syli',
      'name-single' => 'guineansk syli',
      'name-multiple' => 'guineanske syli',
    ),
    'GQE' => 
    array (
      'name' => 'ekvatorialguineansk ekwele guineana',
      'name-single' => 'ekvatorialguineansk ekwele',
      'name-multiple' => 'ekvatorialguineanske ekwele',
    ),
    'GRD' => 
    array (
      'name' => 'gresk drakme',
      'name-single' => 'gresk drakme',
      'name-multiple' => 'greske drakmer',
    ),
    'GTQ' => 
    array (
      'name' => 'guatemalansk quetzal',
      'name-single' => 'guatemalansk quetzal',
      'name-multiple' => 'guatemalanske quetzal',
    ),
    'GWE' => 
    array (
      'name' => 'portugisisk guinea escudo',
      'name-single' => 'portugisisk guinea escudo',
      'name-multiple' => 'portugisiske guinea escudo',
    ),
    'GWP' => 
    array (
      'name' => 'Guinea-Bissau-peso',
    ),
    'GYD' => 
    array (
      'name' => 'guyansk dollar',
      'name-single' => 'guyansk dollar',
      'name-multiple' => 'guyanske dollar',
    ),
    'HNL' => 
    array (
      'name' => 'honduransk lempira',
      'name-single' => 'honduransk lempira',
      'name-multiple' => 'honduranske lempira',
    ),
    'HRD' => 
    array (
      'name' => 'kroatisk dinar',
      'name-single' => 'kroatisk dinar',
      'name-multiple' => 'kroatiske dinarar',
    ),
    'HRK' => 
    array (
      'name' => 'kroatisk kuna',
      'name-single' => 'kroatisk kuna',
      'name-multiple' => 'kroatiske kuna',
    ),
    'HTG' => 
    array (
      'name' => 'haitisk gourde',
      'name-single' => 'haitisk gourde',
      'name-multiple' => 'haitiske gourde',
    ),
    'HUF' => 
    array (
      'name' => 'ungarsk forint',
      'name-single' => 'ungarsk forint',
      'name-multiple' => 'ungarske forintar',
    ),
    'IDR' => 
    array (
      'name' => 'indonesisk rupi',
      'name-single' => 'indonesisk rupi',
      'name-multiple' => 'indonesiske rupiar',
    ),
    'IEP' => 
    array (
      'name' => 'irsk pund',
      'name-single' => 'irsk pund',
      'name-multiple' => 'irske pund',
    ),
    'ILP' => 
    array (
      'name' => 'israelsk pund',
      'name-single' => 'israelsk pund',
      'name-multiple' => 'israelske pund',
    ),
    'IQD' => 
    array (
      'name' => 'iraksk dinar',
      'name-single' => 'irakisk dinar',
      'name-multiple' => 'irakiske dinarar',
    ),
    'IRR' => 
    array (
      'name' => 'iransk rial',
      'name-single' => 'iransk rial',
      'name-multiple' => 'iranske rialar',
    ),
    'ISK' => 
    array (
      'name' => 'islandsk krone',
      'name-single' => 'islandsk krone',
      'name-multiple' => 'islandske kroner',
    ),
    'ITL' => 
    array (
      'name' => 'italiensk lire',
      'name-single' => 'italiensk lire',
      'name-multiple' => 'italienske lire',
    ),
    'JMD' => 
    array (
      'name' => 'jamaikansk dollar',
      'name-single' => 'jamaikansk dollar',
      'name-multiple' => 'jamaikanske dollar',
    ),
    'JOD' => 
    array (
      'name' => 'jordansk dinar',
      'name-single' => 'jordansk dinar',
      'name-multiple' => 'jordanske dinarar',
    ),
    'KES' => 
    array (
      'name' => 'kenyansk shilling',
      'name-single' => 'kenyansk shilling',
      'name-multiple' => 'kenyanske shilling',
    ),
    'KGS' => 
    array (
      'name' => 'kirgisisk som',
      'name-single' => 'kirgisisk som',
      'name-multiple' => 'kirgisiske som',
    ),
    'KHR' => 
    array (
      'name' => 'kambodsjansk riel',
      'name-single' => 'kambodsjansk riel',
      'name-multiple' => 'kambodsjanske riel',
    ),
    'KMF' => 
    array (
      'name' => 'komorisk franc',
      'name-single' => 'komorisk franc',
      'name-multiple' => 'komoriske franc',
    ),
    'KPW' => 
    array (
      'name' => 'nordkoreansk won',
      'name-single' => 'nordkoreansk won',
      'name-multiple' => 'nordkoreanske won',
    ),
    'KWD' => 
    array (
      'name' => 'kuwaitisk dinar',
      'name-single' => 'kuwaitisk dinar',
      'name-multiple' => 'kuwaitiske dinarar',
    ),
    'KYD' => 
    array (
      'name' => 'caymansk dollar',
      'name-single' => 'caymansk dollar',
      'name-multiple' => 'caymanske dollar',
    ),
    'KZT' => 
    array (
      'name' => 'kasakhstansk tenge',
      'name-single' => 'kasakhstansk tenge',
      'name-multiple' => 'kasakhstanske tenge',
    ),
    'LAK' => 
    array (
      'name' => 'laotisk kip',
      'name-single' => 'laotisk kip',
      'name-multiple' => 'laotiske kip',
    ),
    'LBP' => 
    array (
      'name' => 'libanesisk pund',
      'name-single' => 'libanesisk pund',
      'name-multiple' => 'libanesiske pund',
    ),
    'LKR' => 
    array (
      'name' => 'srilankisk rupi',
      'name-single' => 'srilankisk rupi',
      'name-multiple' => 'srilankiske rupiar',
    ),
    'LRD' => 
    array (
      'name' => 'liberisk dollar',
      'name-single' => 'liberisk dollar',
      'name-multiple' => 'liberiske dollar',
    ),
    'LSL' => 
    array (
      'name' => 'lesothisk loti',
      'name-single' => 'lesothisk loti',
      'name-multiple' => 'lesothiske loti',
    ),
    'LTL' => 
    array (
      'name' => 'litauisk lita',
      'name-single' => 'litauisk lita',
      'name-multiple' => 'litauiske lita',
    ),
    'LTT' => 
    array (
      'name' => 'litauisk talona',
      'name-single' => 'litauisk talona',
      'name-multiple' => 'litauiske talona',
    ),
    'LUC' => 
    array (
      'name' => 'luxemburgsk konvertibel franc',
      'name-single' => 'luxemburgsk konvertibel franc',
      'name-multiple' => 'luxemburgske konvertible franc',
    ),
    'LUF' => 
    array (
      'name' => 'luxemburgsk franc',
      'name-single' => 'luxemburgsk franc',
      'name-multiple' => 'luxemburgske franc',
    ),
    'LUL' => 
    array (
      'name' => 'luxemburgsk finansiell franc',
      'name-single' => 'luxemburgsk finansiell franc',
      'name-multiple' => 'luxemburgske finansielle franc',
    ),
    'LVL' => 
    array (
      'name' => 'latvisk lat',
      'name-single' => 'latvisk lat',
      'name-multiple' => 'latviske lat',
    ),
    'LVR' => 
    array (
      'name' => 'latvisk rubel',
      'name-single' => 'latvisk rubel',
      'name-multiple' => 'latviske rublar',
    ),
    'LYD' => 
    array (
      'name' => 'libysk dinar',
      'name-single' => 'libysk dinar',
      'name-multiple' => 'libyske dinarar',
    ),
    'MAD' => 
    array (
      'name' => 'marokkansk dirham',
      'name-single' => 'marokkansk dirham',
      'name-multiple' => 'marokkanske dirham',
    ),
    'MAF' => 
    array (
      'name' => 'marokkansk franc',
      'name-single' => 'marokkansk franc',
      'name-multiple' => 'marokkanske franc',
    ),
    'MDL' => 
    array (
      'name' => 'moldovsk leu',
      'name-single' => 'moldovsk leu',
      'name-multiple' => 'moldovske lei',
    ),
    'MGA' => 
    array (
      'name' => 'madagassisk ariary',
      'name-single' => 'madagassisk ariary',
      'name-multiple' => 'madagassiske ariary',
    ),
    'MGF' => 
    array (
      'name' => 'madagassisk franc',
      'name-single' => 'madagassisk franc',
      'name-multiple' => 'madagassiske franc',
    ),
    'MKD' => 
    array (
      'name' => 'makedonsk denar',
      'name-single' => 'makedonsk denar',
      'name-multiple' => 'makedonske denarar',
    ),
    'MLF' => 
    array (
      'name' => 'malisk franc',
      'name-single' => 'malisk franc',
      'name-multiple' => 'maliske franc',
    ),
    'MMK' => 
    array (
      'name' => 'myanmarsk kyat',
      'name-single' => 'myanmarsk kyat',
      'name-multiple' => 'myanmarske kyat',
    ),
    'MNT' => 
    array (
      'name' => 'mongolsk tugrik',
      'name-single' => 'mongolsk tugrik',
      'name-multiple' => 'mongolske tugrik',
    ),
    'MOP' => 
    array (
      'name' => 'makaosk pataca',
      'name-single' => 'makaosk pataca',
      'name-multiple' => 'makaoske pataca',
    ),
    'MRO' => 
    array (
      'name' => 'mauritansk ouguiya',
      'name-single' => 'mauritansk ouguiya',
      'name-multiple' => 'mauritanske ouguiya',
    ),
    'MTL' => 
    array (
      'name' => 'maltesisk lira',
      'name-single' => 'maltesisk lira',
      'name-multiple' => 'maltesiske lira',
    ),
    'MTP' => 
    array (
      'name' => 'maltesisk pund',
      'name-single' => 'maltesisk pund',
      'name-multiple' => 'maltesiske pund',
    ),
    'MUR' => 
    array (
      'name' => 'mauritansk rupi',
      'name-single' => 'mauritansk rupi',
      'name-multiple' => 'mauritanske rupiar',
    ),
    'MVR' => 
    array (
      'name' => 'maldivisk rufiyaa',
      'name-single' => 'maldivisk rufiyaa',
      'name-multiple' => 'maldiviske rufiyaa',
    ),
    'MWK' => 
    array (
      'name' => 'malawisk kwacha',
      'name-single' => 'malawisk kwacha',
      'name-multiple' => 'malawiske kwacha',
    ),
    'MXP' => 
    array (
      'name' => 'meksikansk sølvpeso (1861-1992)',
      'name-single' => 'meksikansk sølvpeso (MXP)',
      'name-multiple' => 'meksikanske sølvpeso (MXP)',
    ),
    'MXV' => 
    array (
      'name' => 'meksikansk unidad de inversion (UDI)',
      'name-single' => 'meksikansk unidad de inversion (UDI)',
      'name-multiple' => 'meksikanske unidad de inversion (UDI)',
    ),
    'MYR' => 
    array (
      'name' => 'malaysisk ringgit',
      'name-single' => 'malaysisk ringgit',
      'name-multiple' => 'malaysiske ringgit',
    ),
    'MZE' => 
    array (
      'name' => 'mosambikisk escudo',
      'name-single' => 'mosambikisk escudo',
      'name-multiple' => 'mosambikiske escudo',
    ),
    'MZM' => 
    array (
      'name' => 'gammal mosambikisk metical',
      'name-single' => 'gammal mosambikisk metical',
      'name-multiple' => 'gamle mosambikiske metical',
    ),
    'MZN' => 
    array (
      'name' => 'mosambikisk metical',
    ),
    'NAD' => 
    array (
      'name' => 'namibisk dollar',
      'name-single' => 'namibisk dollar',
      'name-multiple' => 'namibiske dollar',
    ),
    'NGN' => 
    array (
      'name' => 'nigeriansk naira',
      'name-single' => 'nigeriansk naira',
      'name-multiple' => 'nigerianske naira',
    ),
    'NIC' => 
    array (
      'name' => 'nicaraguansk cordoba',
      'name-single' => 'nicaraguansk cordoba',
      'name-multiple' => 'nicaraguanske cordoba',
    ),
    'NIO' => 
    array (
      'name' => 'nicaraguansk cordoba oro',
      'name-single' => 'nicaraguansk cordoba oro',
      'name-multiple' => 'nicaraguanske cordoba oro',
    ),
    'NLG' => 
    array (
      'name' => 'nederlandsk gylden',
      'name-single' => 'nederlandsk gylden',
      'name-multiple' => 'nederlandske gylden',
    ),
    'NPR' => 
    array (
      'name' => 'nepalsk rupi',
      'name-single' => 'nepalsk rupi',
      'name-multiple' => 'nepalske rupiar',
    ),
    'OMR' => 
    array (
      'name' => 'omansk rial',
      'name-single' => 'omansk rial',
      'name-multiple' => 'omanske rial',
    ),
    'PAB' => 
    array (
      'name' => 'panamansk balboa',
      'name-single' => 'panamansk balboa',
      'name-multiple' => 'panamanske balboa',
    ),
    'PEI' => 
    array (
      'name' => 'peruansk inti',
      'name-single' => 'peruansk inti',
      'name-multiple' => 'peruanske inti',
    ),
    'PEN' => 
    array (
      'name' => 'peruansk nuevo sol',
      'name-single' => 'peruansk nuevo sol',
      'name-multiple' => 'peruanske nuevo sol',
    ),
    'PES' => 
    array (
      'name' => 'peruansk sol',
      'name-single' => 'peruansk sol',
      'name-multiple' => 'peruanske sol',
    ),
    'PGK' => 
    array (
      'name' => 'papuansk kina',
      'name-single' => 'papuansk kina',
      'name-multiple' => 'papuanske kina',
    ),
    'PHP' => 
    array (
      'name' => 'filippinsk peso',
      'name-single' => 'filippinsk peso',
      'name-multiple' => 'filippinske peso',
    ),
    'PKR' => 
    array (
      'name' => 'pakistansk rupi',
      'name-single' => 'pakistansk rupi',
      'name-multiple' => 'pakistanske rupiar',
    ),
    'PLN' => 
    array (
      'name' => 'polsk zloty',
      'name-single' => 'polsk zloty',
      'name-multiple' => 'polske zloty',
    ),
    'PLZ' => 
    array (
      'name' => 'polsk zloty (1950-1995)',
      'name-single' => 'polsk zloty (PLZ)',
      'name-multiple' => 'polske zloty (PLZ)',
    ),
    'PTE' => 
    array (
      'name' => 'portugisisk escudo',
      'name-single' => 'portugisisk escudo',
      'name-multiple' => 'portugisiske escudo',
    ),
    'PYG' => 
    array (
      'name' => 'paraguayansk guarani',
      'name-single' => 'paraguayansk guarani',
      'name-multiple' => 'paraguayanske guarani',
    ),
    'QAR' => 
    array (
      'name' => 'qatarsk rial',
      'name-single' => 'qatarsk rial',
      'name-multiple' => 'qatarske rial',
    ),
    'RHD' => 
    array (
      'name' => 'rhodesisk dollar',
      'name-single' => 'rhodesisk dollar',
      'name-multiple' => 'rhodesiske dollar',
    ),
    'ROL' => 
    array (
      'name' => 'gammal rumensk leu',
      'name-single' => 'gammal rumensk leu',
      'name-multiple' => 'gamle rumenske lei',
    ),
    'RON' => 
    array (
      'name' => 'rumensk leu',
      'name-single' => 'rumensk leu',
      'name-multiple' => 'rumenske lei',
    ),
    'RSD' => 
    array (
      'name' => 'serbisk dinar',
      'name-single' => 'serbisk dinar',
      'name-multiple' => 'serbiske dinarar',
    ),
    'RUB' => 
    array (
      'name' => 'russisk rubel',
    ),
    'RUR' => 
    array (
      'name' => 'russisk rubel (1991-1998)',
      'name-single' => 'russisk rubel (RUR)',
      'name-multiple' => 'russiske rublar (RUR)',
    ),
    'RWF' => 
    array (
      'name' => 'rwandisk franc',
      'name-single' => 'rwandisk franc',
      'name-multiple' => 'rwandiske franc',
    ),
    'SAR' => 
    array (
      'name' => 'saudiarabisk rial',
      'name-single' => 'saudiarabisk rial',
      'name-multiple' => 'saudiarabiske rial',
    ),
    'SBD' => 
    array (
      'name' => 'salomonsk dollar',
      'name-single' => 'salomonsk dollar',
      'name-multiple' => 'salomonske dollar',
    ),
    'SCR' => 
    array (
      'name' => 'seychellisk rupi',
      'name-single' => 'seychellisk rupi',
      'name-multiple' => 'seychelliske rupiar',
    ),
    'SDD' => 
    array (
      'name' => 'gammal sudanesisk dinar',
      'name-single' => 'gammal sudansk dinar',
      'name-multiple' => 'gamle sudanske dinarar',
    ),
    'SDG' => 
    array (
      'name' => 'sudansk pund',
      'name-single' => 'sudansk pund',
      'name-multiple' => 'sudanske pund',
    ),
    'SDP' => 
    array (
      'name' => 'gammalt sudanesisk pund',
      'name-single' => 'gammalt sudansk pund',
      'name-multiple' => 'gamle sudanske pund',
    ),
    'SEK' => 
    array (
      'name' => 'svensk krone',
      'name-single' => 'svensk krone',
      'name-multiple' => 'svenske kroner',
    ),
    'SGD' => 
    array (
      'name' => 'singaporsk dollar',
      'name-single' => 'singaporsk dollar',
      'name-multiple' => 'singaporske dollar',
    ),
    'SHP' => 
    array (
      'name' => 'sankthelensk pund',
      'name-single' => 'sankthelensk pund',
      'name-multiple' => 'sankthelenske pund',
    ),
    'SIT' => 
    array (
      'name' => 'slovensk tolar',
      'name-single' => 'slovensk tolar',
      'name-multiple' => 'slovenske tolar',
    ),
    'SKK' => 
    array (
      'name' => 'slovakisk koruna',
      'name-single' => 'slovakisk koruna',
      'name-multiple' => 'slovakiske koruna',
    ),
    'SLL' => 
    array (
      'name' => 'sierraleonsk leone',
      'name-single' => 'sierraleonsk leone',
      'name-multiple' => 'sierraleonske leone',
    ),
    'SOS' => 
    array (
      'name' => 'somalisk shilling',
      'name-single' => 'somalisk shilling',
      'name-multiple' => 'somaliske shilling',
    ),
    'SRD' => 
    array (
      'name' => 'surinamsk dollar',
      'name-single' => 'surinamsk dollar',
      'name-multiple' => 'surinamske dollar',
    ),
    'SRG' => 
    array (
      'name' => 'surinamsk gylden',
      'name-single' => 'surinamsk gylden',
      'name-multiple' => 'surinamske gylden',
    ),
    'STD' => 
    array (
      'name' => 'Sao Tome og Principe-dobra',
    ),
    'SUR' => 
    array (
      'name' => 'sovjetisk rubel',
      'name-single' => 'sovjetisk rubel',
      'name-multiple' => 'sovjetiske rublar',
    ),
    'SVC' => 
    array (
      'name' => 'salvadoransk colon',
      'name-single' => 'salvadoransk colon',
      'name-multiple' => 'salvadoranske colon',
    ),
    'SYP' => 
    array (
      'name' => 'syrisk pund',
      'name-single' => 'syrisk pund',
      'name-multiple' => 'syriske pund',
    ),
    'SZL' => 
    array (
      'name' => 'swazilandsk lilangeni',
      'name-single' => 'swazilandsk lilangeni',
      'name-multiple' => 'swazilandske lilangeni',
    ),
    'TJR' => 
    array (
      'name' => 'tadsjikisk rubel',
      'name-single' => 'tadsjikisk rubel',
      'name-multiple' => 'tadsjikiske rublar',
    ),
    'TJS' => 
    array (
      'name' => 'tadsjikisk somoni',
      'name-single' => 'tadsjikisk somoni',
      'name-multiple' => 'tadsjikiske somoni',
    ),
    'TMM' => 
    array (
      'name' => 'turkmensk manat',
      'name-single' => 'turkmensk manat',
      'name-multiple' => 'turkmenske manat',
    ),
    'TMT' => 
    array (
      'name-single' => 'turkmenistansk manat',
      'name-multiple' => 'turkmenistanska manat',
    ),
    'TND' => 
    array (
      'name' => 'tunisisk dinar',
      'name-single' => 'tunisisk dinar',
      'name-multiple' => 'tunisiske dinarar',
    ),
    'TOP' => 
    array (
      'name' => 'tongansk paʻanga',
      'name-single' => 'tongansk paʻanga',
      'name-multiple' => 'tonganske paʻanga',
    ),
    'TPE' => 
    array (
      'name' => 'timoresisk escudo',
      'name-single' => 'timoresisk escudo',
      'name-multiple' => 'timoresiske escudo',
    ),
    'TRL' => 
    array (
      'name' => 'gammal tyrkiske lire',
      'name-single' => 'gammal tyrkisk lire',
      'name-multiple' => 'gamle tyrkiske lire',
    ),
    'TRY' => 
    array (
      'name' => 'tyrkisk lire',
      'name-single' => 'tyrkisk lire',
      'name-multiple' => 'tyrkiske lire',
    ),
    'TTD' => 
    array (
      'name' => 'trinidadisk dollar',
      'name-single' => 'trinidadisk dollar',
      'name-multiple' => 'trinidadiske dollar',
    ),
    'TZS' => 
    array (
      'name' => 'tanzaniansk shilling',
      'name-single' => 'tanzaniansk shilling',
      'name-multiple' => 'tanzanianske shilling',
    ),
    'UAH' => 
    array (
      'name' => 'ukrainsk hryvnia',
      'name-single' => 'ukrainsk hryvnia',
      'name-multiple' => 'ukrainske hryvnia',
    ),
    'UAK' => 
    array (
      'name' => 'ukrainsk karbovanetz',
      'name-single' => 'ukrainsk karbovanetz',
      'name-multiple' => 'ukrainske karbovanetz',
    ),
    'UGS' => 
    array (
      'name' => 'ugandisk shilling (1966-1987)',
      'name-single' => 'ugandisk shilling (UGS)',
      'name-multiple' => 'ugandiske shilling (UGS)',
    ),
    'UGX' => 
    array (
      'name' => 'ugandisk shilling',
      'name-single' => 'ugandisk shilling',
      'name-multiple' => 'ugandiske shilling',
    ),
    'USN' => 
    array (
      'name' => 'amerikansk dollar (neste dag)',
      'name-single' => 'amerikansk dollar (neste dag)',
      'name-multiple' => 'amerikanske dollar (neste dag)',
    ),
    'USS' => 
    array (
      'name' => 'amerikansk dollar (same dag)',
      'name-single' => 'amerikansk dollar (same dag)',
      'name-multiple' => 'amerikanske dollar (same dag)',
    ),
    'UYI' => 
    array (
      'name' => 'uruguayansk peso en unidades indexadas',
      'name-single' => 'uruguayansk peso en unidades indexadas',
      'name-multiple' => 'uruguayanske peso en unidades indexadas',
    ),
    'UYP' => 
    array (
      'name' => 'uruguayansk peso (1975-1993)',
      'name-single' => 'uruguayansk peso (UYP)',
      'name-multiple' => 'uruguayanske peso (UYP)',
    ),
    'UYU' => 
    array (
      'name' => 'uruguayansk peso',
      'name-single' => 'uruguayansk peso',
      'name-multiple' => 'uruguayanske peso',
    ),
    'UZS' => 
    array (
      'name' => 'usbekisk sum',
      'name-single' => 'usbekisk sum',
      'name-multiple' => 'usbekiske sum',
    ),
    'VEB' => 
    array (
      'name' => 'venezuelansk bolivar',
      'name-single' => 'venezuelansk bolivar',
      'name-multiple' => 'venezuelanske bolivar',
    ),
    'VEF' => 
    array (
      'name' => 'venezuelansk bolivar fuerte',
      'name-single' => 'venezuelansk bolivar fuerte',
      'name-multiple' => 'venezuelanske bolivar fuerte',
    ),
    'VUV' => 
    array (
      'name' => 'vanuatuisk vatu',
      'name-single' => 'vanuatuisk vatu',
      'name-multiple' => 'vanuatuiske vatu',
    ),
    'WST' => 
    array (
      'name' => 'vestsamoisk tala',
      'name-single' => 'vestsamoisk tala',
      'name-multiple' => 'vestsamoiske tala',
    ),
    'XAG' => 
    array (
      'name' => 'sølv',
      'name-single' => 'sølv',
      'name-multiple' => 'sølv',
    ),
    'XAU' => 
    array (
      'name' => 'gull',
      'name-single' => 'gull',
      'name-multiple' => 'gull',
    ),
    'XBA' => 
    array (
      'name' => 'europeisk samansett eining',
      'name-single' => 'europeisk samansett eining',
      'name-multiple' => 'europeiske samansette einingar',
    ),
    'XBB' => 
    array (
      'name' => 'europeisk monetær eining',
      'name-single' => 'europeisk monetær eining',
      'name-multiple' => 'europeiske monetære einingar',
    ),
    'XBC' => 
    array (
      'name' => 'europeisk kontoeining (XBC)',
      'name-single' => 'europeisk kontoeining (XBC)',
      'name-multiple' => 'europeiske kontoeiningar (XBC)',
    ),
    'XBD' => 
    array (
      'name' => 'europeisk kontoeining (XBD)',
      'name-single' => 'europeisk kontoeining (XBD)',
      'name-multiple' => 'europeiske kontoeiningar (XBD)',
    ),
    'XDR' => 
    array (
      'name' => 'spesielle trekkrettar',
      'name-single' => 'spesiell trekkrett',
      'name-multiple' => 'spesielle trekkrettar',
    ),
    'XEU' => 
    array (
      'name' => 'europeisk valutaeining',
      'name-single' => 'europeisk valutaeining',
      'name-multiple' => 'europeiske valutaeiningar',
    ),
    'XFO' => 
    array (
      'name' => 'fransk gullfranc',
      'name-single' => 'fransk gullfranc',
      'name-multiple' => 'franske gullfranc',
    ),
    'XFU' => 
    array (
      'name' => 'fransk UIC-franc',
      'name-single' => 'fransk UIC-franc',
      'name-multiple' => 'franske UIC-franc',
    ),
    'XPD' => 
    array (
      'name' => 'palladium',
      'name-single' => 'palladium',
      'name-multiple' => 'palladium',
    ),
    'XPT' => 
    array (
      'name' => 'platina',
      'name-single' => 'platina',
      'name-multiple' => 'platina',
    ),
    'XRE' => 
    array (
      'name' => 'RINET-fond',
      'name-single' => 'RINET-fond',
      'name-multiple' => 'RINET-fond',
    ),
    'XTS' => 
    array (
      'name' => 'testvalutakode',
      'name-single' => 'testvalutakode',
      'name-multiple' => 'testvalutakode',
    ),
    'XXX' => 
    array (
      'name' => 'ukjend eller ugyldig valuta',
      'name-single' => 'ukjend/ugyldig valuta',
      'name-multiple' => 'ukjend eller ugyldig valuta',
    ),
    'YDD' => 
    array (
      'name' => 'jemenittisk dinar',
      'name-single' => 'jemenittisk dinar',
      'name-multiple' => 'jemenittiske dinarar',
    ),
    'YER' => 
    array (
      'name' => 'jemenittisk rial',
      'name-single' => 'jemenittisk rial',
      'name-multiple' => 'jemenittiske rialar',
    ),
    'YUD' => 
    array (
      'name' => 'jugoslavisk dinar (hard)',
      'name-single' => 'jugoslavisk dinar (hard)',
      'name-multiple' => 'jugoslaviske dinarar (hard)',
    ),
    'YUM' => 
    array (
      'name' => 'jugoslavisk noviy-dinar',
      'name-single' => 'jugoslaviske noviy-dinarar',
    ),
    'YUN' => 
    array (
      'name' => 'jugoslavisk konvertibel dinar',
      'name-single' => 'jugoslavisk konvertibel dinar',
      'name-multiple' => 'jugoslaviske konvertible dinarar',
    ),
    'ZAL' => 
    array (
      'name' => 'sørafrikansk rand (finansiell)',
    ),
    'ZAR' => 
    array (
      'name' => 'sørafrikansk rand',
    ),
    'ZMK' => 
    array (
      'name' => 'zambisk kwacha',
    ),
    'ZRN' => 
    array (
      'name' => 'zairisk ny zaire',
    ),
    'ZRZ' => 
    array (
      'name' => 'zairisk zaire',
    ),
    'ZWD' => 
    array (
      'name' => 'zimbabwisk dollar',
    ),
    'ZWL' => 
    array (
      'name-single' => 'Zimbabwe-dollar (2009)',
      'name-multiple' => 'Zimbabwe-dollar (2009)',
    ),
  ),
  'languages' => 
  array (
    'ab' => 'Abkhasisk',
    'ace' => 'Achinesisk',
    'ach' => 'Acoli',
    'ada' => 'Adangme',
    'ady' => 'Adyghe',
    'aa' => 'Afar',
    'afh' => 'Afrihili',
    'af' => 'Afrikaans',
    'afa' => 'Afroasiatisk språk',
    'agq' => 'Aghem',
    'ain' => 'Ainu',
    'ak' => 'Akan',
    'akk' => 'Akkadisk',
    'sq' => 'Albansk',
    'ale' => 'Aleutisk',
    'alg' => 'Algonkinsk språk',
    'tut' => 'Altaisk språk',
    'am' => 'Amharisk',
    'anp' => 'Angika',
    'mis' => 'Anna språk',
    'apa' => 'Apache-språk',
    'ar' => 'Arabisk',
    'an' => 'Aragonsk',
    'arc' => 'Arameisk',
    'arp' => 'Arapaho',
    'arn' => 'Araukansk',
    'arw' => 'Arawak',
    'hy' => 'Armensk',
    'rup' => 'Aromansk',
    'az' => 'Aserbajdsjansk',
    'as' => 'Assamisk',
    'ast' => 'Asturisk',
    'asa' => 'Asu (Tanzania)',
    'ath' => 'Athapaskansk språk',
    'cch' => 'Atsam',
    'de_AT' => 'Austerriksk tysk',
    'frs' => 'Austfrisisk',
    'en_AU' => 'Australisk engelsk',
    'aus' => 'Australsk språk',
    'map' => 'Austronesisk språk',
    'av' => 'Avarisk',
    'ae' => 'Avestisk',
    'awa' => 'Awadhi',
    'ay' => 'Aymara',
    'ksf' => 'Bafia',
    'ban' => 'Balinesisk',
    'bat' => 'Baltisk språk',
    'bal' => 'Baluchi',
    'bm' => 'Bambara',
    'bai' => 'Bamilekisk språk',
    'bad' => 'Banda',
    'bnt' => 'Bantu',
    'bas' => 'Basa',
    'ba' => 'Basjkirsk',
    'eu' => 'Baskisk',
    'btk' => 'Batak',
    'bej' => 'Beja',
    'bem' => 'Bemba',
    'bez' => 'Bena (Tanzania)',
    'bn' => 'Bengali',
    'ber' => 'Berbisk',
    'bho' => 'Bhojpuri',
    'bh' => 'Bihari',
    'bik' => 'Bikol',
    'bin' => 'Bini',
    'bi' => 'Bislama',
    'byn' => 'Blin',
    'zbl' => 'Blissymbol',
    'brx' => 'Bodo',
    'nb' => 'Bokmål',
    'bs' => 'Bosnisk',
    'bra' => 'Braj',
    'pt_BR' => 'Brasiliansk portugisisk',
    'br' => 'Bretonsk',
    'en_GB' => 'Britisk engelsk',
    'bug' => 'Buginesisk',
    'bg' => 'Bulgarsk',
    'bua' => 'Burjatisk',
    'my' => 'Burmesisk',
    'cad' => 'Caddo',
    'ceb' => 'Cebuansk',
    'chg' => 'Chagatai',
    'ch' => 'Chamorro',
    'chr' => 'Cherokee',
    'chy' => 'Cheyenne',
    'chb' => 'Chibcha',
    'chn' => 'Chinook',
    'chp' => 'Chipewiansk',
    'cho' => 'Choctaw',
    'chk' => 'Chuukesisk',
    'cr' => 'Cree',
    'mus' => 'Creek',
    'dak' => 'Dakota',
    'da' => 'Dansk',
    'dar' => 'Dargwa',
    'day' => 'Dayak',
    'del' => 'Delaware',
    'din' => 'Dinka',
    'dv' => 'Divehi',
    'doi' => 'Dogri',
    'dgr' => 'Dogrib',
    'dra' => 'Dravidisk språk',
    'dua' => 'Duala',
    'dyu' => 'Dyula',
    'dz' => 'Dzongkha',
    'efi' => 'Efik',
    'eka' => 'Ekajuk',
    'elx' => 'Elamittisk',
    'smn' => 'Enaresamisk',
    'en' => 'Engelsk',
    'en_US' => 'Engelsk (amerikansk)',
    'cpe' => 'Engelskbasert kreol- eller pidginspråk',
    'myv' => 'Erzya',
    'eo' => 'Esperanto',
    'et' => 'Estisk',
    'pt_PT' => 'Europeisk portugisisk',
    'ee' => 'Ewe',
    'ewo' => 'Ewondo',
    'fan' => 'Fang',
    'fat' => 'Fanti',
    'fj' => 'Fijiansk',
    'fil' => 'Filippinsk',
    'phi' => 'Filippinsk språk',
    'fi' => 'Finsk',
    'fiu' => 'Finsk-ugrisk språk',
    'nl_BE' => 'Flamsk',
    'mul' => 'Fleire språk',
    'fon' => 'Fon',
    'zh_Hans' => 'Forenkla kinesisk',
    'fr' => 'Fransk',
    'cpf' => 'Franskbasert kreol- eller pidginspråk',
    'fur' => 'Friuliansk',
    'ff' => 'Fulani',
    'fo' => 'Færøysk',
    'phn' => 'Fønikisk',
    'gaa' => 'Ga',
    'gl' => 'Galicisk',
    'egy' => 'Gammalegyptisk',
    'ang' => 'Gammalengelsk',
    'fro' => 'Gammalfransk',
    'grc' => 'Gammalgresk',
    'goh' => 'Gammalhøgtysk',
    'sga' => 'Gammalirsk',
    'non' => 'Gammalnorsk',
    'peo' => 'Gammalpersisk',
    'pro' => 'Gammalprovençalsk',
    'lg' => 'Ganda',
    'gay' => 'Gayo',
    'gba' => 'Gbaya',
    'ka' => 'Georgisk',
    'gem' => 'Germansk språk',
    'gez' => 'Ges',
    'gon' => 'Gondi',
    'gor' => 'Gorontalo',
    'got' => 'Gotisk',
    'grb' => 'Grebo',
    'el' => 'Gresk',
    'gn' => 'Guarani',
    'gu' => 'Gujarati',
    'gwi' => 'Gwichin',
    'hai' => 'Haida',
    'ht' => 'Haitisk',
    'ha' => 'Hausa',
    'haw' => 'Hawaiisk',
    'he' => 'Hebraisk',
    'hz' => 'Herero',
    'hit' => 'Hettittisk',
    'hil' => 'Hiligaynon',
    'him' => 'Himachali',
    'hi' => 'Hindi',
    'ho' => 'Hiri motu',
    'hmn' => 'Hmong',
    'hup' => 'Hupa',
    'hsb' => 'Høgsorbisk',
    'iba' => 'Iban',
    'es_ES' => 'Iberisk spansk',
    'ig' => 'Ibo',
    'io' => 'Ido',
    'ijo' => 'Ijo',
    'ilo' => 'Iloko',
    'inc' => 'Indisk språk',
    'ine' => 'Indo-europeisk språk',
    'id' => 'Indonesisk',
    'inh' => 'Ingusjisk',
    'ia' => 'Interlingua',
    'ie' => 'Interlingue',
    'iu' => 'Inuktitut',
    'ik' => 'Inupiak',
    'ira' => 'Iransk språk',
    'iro' => 'Irokansk språk',
    'ga' => 'Irsk',
    'is' => 'Islandsk',
    'it' => 'Italiensk',
    'sah' => 'Jakutsk',
    'ja' => 'Japansk',
    'jv' => 'Javanesisk',
    'yi' => 'Jiddisk',
    'kaj' => 'Jju',
    'dyo' => 'Jola-fonyi',
    'yo' => 'Joruba',
    'ypk' => 'Jupisk språk',
    'jrb' => 'Jødearabisk',
    'jpr' => 'Jødepersisk',
    'kbd' => 'Kabardisk',
    'kab' => 'Kabylsk',
    'kac' => 'Kachin',
    'kl' => 'Kalaallisut; grønlandsk',
    'xal' => 'Kalmyk',
    'kam' => 'Kamba',
    'cmc' => 'Kamisk språk',
    'en_CA' => 'Kanadisk engelsk',
    'fr_CA' => 'Kanadisk fransk',
    'kn' => 'Kannada',
    'yue' => 'Kantonesisk',
    'kr' => 'Kanuri',
    'kea' => 'Kapverdisk',
    'krc' => 'Karachay-balkar',
    'kaa' => 'Karakalpakisk',
    'krl' => 'Karelsk',
    'kar' => 'Karensk',
    'car' => 'Karibisk',
    'kk' => 'Kasakhisk',
    'ks' => 'Kasjmiri',
    'csb' => 'Kasjubisk',
    'ca' => 'Katalansk',
    'cau' => 'Kaukasisk språk',
    'kaw' => 'Kawi',
    'cel' => 'Keltisk språk',
    'kha' => 'Khasi',
    'km' => 'Khmer',
    'khi' => 'Khoisanspråk',
    'kho' => 'Khotanesisk',
    'ebu' => 'Kiembu',
    'kg' => 'Kikongo',
    'ki' => 'Kikuyu',
    'kmb' => 'Kimbundu',
    'zh' => 'Kinesisk',
    'rw' => 'Kinjarwanda',
    'ky' => 'Kirgisisk',
    'gil' => 'Kiribatisk',
    'nwc' => 'Klassisk newarisk',
    'syc' => 'Klassisk syrisk',
    'tlh' => 'Klingon',
    'kv' => 'Komi',
    'kok' => 'Konkani',
    'cop' => 'Koptisk',
    'ko' => 'Koreansk',
    'kw' => 'Kornisk',
    'kfo' => 'Koro',
    'co' => 'Korsikansk',
    'kos' => 'Kosraeansk',
    'kpe' => 'Kpelle',
    'crp' => 'Kreol- eller pidginspråk',
    'crh' => 'Krimtatarisk',
    'hr' => 'Kroatisk',
    'kro' => 'Kru',
    'kj' => 'Kuanyama',
    'kum' => 'Kumyk',
    'art' => 'Kunstig språk',
    'ku' => 'Kurdisk',
    'kru' => 'Kurukh',
    'cus' => 'Kusjitisk språk',
    'kut' => 'Kutenai',
    'be' => 'Kviterussisk',
    'nmg' => 'Kwasio',
    'cu' => 'Kyrkjeslavisk',
    'lad' => 'Ladinsk',
    'lah' => 'Lahnda',
    'lam' => 'Lamba',
    'lo' => 'Laotisk',
    'la' => 'Latin',
    'es_419' => 'Latinamerikansk spansk',
    'lv' => 'Latvisk',
    'lez' => 'Lezghian',
    'li' => 'Limburgisk',
    'ln' => 'Lingala',
    'lt' => 'Litauisk',
    'jbo' => 'Lojban',
    'loz' => 'Lozi',
    'lu' => 'Luba-katanga',
    'lua' => 'Luba-lulua',
    'lui' => 'Luiseno',
    'smj' => 'Lulesamisk',
    'lun' => 'Lunda',
    'luo' => 'Luo',
    'lus' => 'Lushai',
    'lb' => 'Luxemburgsk',
    'dsb' => 'Lågsorbisk',
    'nds' => 'Lågtysk',
    'mg' => 'Madagassisk',
    'mad' => 'Maduresisk',
    'mag' => 'Magahi',
    'mai' => 'Maithili',
    'mak' => 'Makasar',
    'mk' => 'Makedonsk',
    'ml' => 'Malayalam',
    'ms' => 'Malayisk',
    'mt' => 'Maltesisk',
    'mdr' => 'Mandar',
    'man' => 'Mandingo',
    'mnc' => 'Mandsju',
    'mni' => 'Manipuri',
    'mno' => 'Manobospråk',
    'gv' => 'Manx',
    'mi' => 'Maori',
    'mr' => 'Marathi',
    'chm' => 'Mari',
    'mh' => 'Marshallesisk',
    'mwr' => 'Marwari',
    'mas' => 'Masai',
    'myn' => 'Mayaspråk',
    'enm' => 'Mellomengelsk',
    'frm' => 'Mellomfransk',
    'gmh' => 'Mellomhøgtysk',
    'mga' => 'Mellomirsk',
    'dum' => 'Mellumnederlandsk',
    'men' => 'Mende',
    'mic' => 'Micmac',
    'min' => 'Minangkabau',
    'mwl' => 'Mirandesisk',
    'moh' => 'Mohawk',
    'mdf' => 'Moksha',
    'mo' => 'Moldavisk',
    'mkh' => 'Mon-khmerspråk',
    'lol' => 'Mongo',
    'mn' => 'Mongolsk',
    'mos' => 'Mossi',
    'mua' => 'Mundang',
    'mun' => 'Mundaspråk',
    'nqo' => 'N\'ko',
    'nah' => 'Nahuatl',
    'nap' => 'Napolitansk',
    'na' => 'Nauru',
    'nv' => 'Navajo',
    'ng' => 'Ndonga',
    'nl' => 'Nederlandsk',
    'ne' => 'Nepalsk',
    'new' => 'Newari',
    'nia' => 'Nias',
    'nic' => 'Niger-kordofaniansk språk',
    'ssa' => 'Nilo-saharaspråk',
    'niu' => 'Niueansk',
    'nog' => 'Nogai',
    'nd' => 'Nord-ndebele',
    'nai' => 'Nordamerikansk indiansk språk',
    'frr' => 'Nordfrisisk',
    'se' => 'Nordsamisk',
    'nso' => 'Nordsotho',
    'no' => 'Norsk',
    'nub' => 'Nubisk språk',
    'nus' => 'Nuer',
    'nym' => 'Nyamwezi',
    'ny' => 'Nyanja',
    'nyn' => 'Nyankole',
    'nn' => 'Nynorsk',
    'nyo' => 'Nyoro',
    'nzi' => 'Nzima',
    'oj' => 'Ojibwa',
    'oc' => 'Oksitansk',
    'luy' => 'Olulujia',
    'or' => 'Oriya',
    'om' => 'Oromo',
    'osa' => 'Osage',
    'os' => 'Ossetisk',
    'oto' => 'Otomisk språk',
    'ota' => 'Ottomansk tyrkisk',
    'pal' => 'Pahlavi',
    'pau' => 'Palauisk',
    'pi' => 'Pali',
    'pam' => 'Pampanga',
    'pag' => 'Pangasinan',
    'pa' => 'Panjabi',
    'pap' => 'Papiamento',
    'paa' => 'Papuisk språk',
    'ps' => 'Pashto',
    'fa' => 'Persisk',
    'pl' => 'Polsk',
    'pon' => 'Ponapisk',
    'pt' => 'Portugisisk',
    'cpp' => 'Portugisiskbasert kreol- eller pidginspråk',
    'pra' => 'Prakrit-språk',
    'qu' => 'Quechua',
    'raj' => 'Rajasthani',
    'rap' => 'Rapanui',
    'rar' => 'Rarotongansk',
    'rm' => 'Retoromansk',
    'rom' => 'Romani',
    'roa' => 'Romansk språk',
    'rof' => 'Rombo',
    'root' => 'Rot',
    'ro' => 'Rumensk',
    'rn' => 'Rundi',
    'ru' => 'Russisk',
    'rwk' => 'Rwa',
    'sal' => 'Salishansk språk',
    'sam' => 'Samaritansk arameisk',
    'smi' => 'Samisk språk',
    'sm' => 'Samoansk',
    'sad' => 'Sandawe',
    'sg' => 'Sango',
    'sbp' => 'Sangu',
    'sa' => 'Sanskrit',
    'sat' => 'Santali',
    'sc' => 'Sardinsk',
    'sas' => 'Sasak',
    'sel' => 'Selkupisk',
    'sem' => 'Semittisk språk',
    'cai' => 'Sentralamerikansk indiansk språk',
    'sr' => 'Serbisk',
    'sh' => 'Serbokroatisk',
    'srr' => 'Serer',
    'shn' => 'Shan',
    'swb' => 'Shimaore',
    'sn' => 'Shona',
    'ii' => 'Sichuan-yi',
    'scn' => 'Siciliansk',
    'sid' => 'Sidamo',
    'bla' => 'Siksika',
    'sd' => 'Sindhi',
    'si' => 'Singalesisk',
    'sit' => 'Sino-tibetansk språk',
    'sio' => 'Sioux-språk',
    'sms' => 'Skoltesamisk',
    'sco' => 'Skotsk',
    'gd' => 'Skotsk-gælisk',
    'den' => 'Slavej',
    'sla' => 'Slavisk språk',
    'sk' => 'Slovakisk',
    'sl' => 'Slovensk',
    'sog' => 'Sogdisk',
    'so' => 'Somali',
    'son' => 'Songhai',
    'snk' => 'Soninke',
    'wen' => 'Sorbisk språk',
    'es' => 'Spansk',
    'srn' => 'Sranan tongo',
    'suk' => 'Sukuma',
    'sux' => 'Sumerisk',
    'su' => 'Sundanesisk',
    'sus' => 'Susu',
    'gsw' => 'Sveitsertysk',
    'fr_CH' => 'Sveitsisk fransk',
    'de_CH' => 'Sveitsisk høgtysk',
    'sv' => 'Svensk',
    'sw' => 'Swahili',
    'ss' => 'Swati',
    'syr' => 'Syrisk',
    'alt' => 'Sør-altai',
    'nr' => 'Sør-ndebele',
    'sai' => 'Søramerikansk indiansk språk',
    'sma' => 'Sørsamisk',
    'st' => 'Sørsotho',
    'tl' => 'Tagalog',
    'ty' => 'Tahitisk',
    'tai' => 'Taispråk',
    'tmh' => 'Tamasjek',
    'ta' => 'Tamil',
    'twq' => 'Tasawaq',
    'tt' => 'Tatarisk',
    'tg' => 'Tatsjikisk',
    'sgn' => 'Teiknspråk',
    'te' => 'Telugu',
    'tem' => 'Temne',
    'ter' => 'Tereno',
    'tet' => 'Tetum',
    'th' => 'Thai',
    'bo' => 'Tibetansk',
    'ti' => 'Tigrinja',
    'tig' => 'Tigré',
    'tiv' => 'Tivi',
    'tli' => 'Tlingit',
    'tpi' => 'Tok pisin',
    'tkl' => 'Tokelau',
    'tog' => 'Tonga (Nyasa)',
    'to' => 'Tonga (Tonga-øyane)',
    'zh_Hant' => 'Tradisjonell kinesisk',
    'tsi' => 'Tsimshian',
    'cs' => 'Tsjekkisk',
    'ce' => 'Tsjetsjensk',
    'cv' => 'Tsjuvansk',
    'ts' => 'Tsonga',
    'tn' => 'Tswana',
    'tum' => 'Tumbuka',
    'tup' => 'Tupi-språk',
    'tk' => 'Turkmensk',
    'tvl' => 'Tuvalu',
    'tyv' => 'Tuvinisk',
    'tw' => 'Twi',
    'kcg' => 'Tyap',
    'tr' => 'Tyrkisk',
    'de' => 'Tysk',
    'udm' => 'Udmurt',
    'uga' => 'Ugaritisk',
    'ug' => 'Uigurisk',
    'und' => 'Ukjent språk',
    'uk' => 'Ukrainsk',
    'umb' => 'Umbundu',
    'hu' => 'Ungarsk',
    'ur' => 'Urdu',
    'uz' => 'Usbekisk',
    'zxx' => 'Utan språkleg innhald',
    'vai' => 'Vai',
    'wa' => 'Vallonsk',
    've' => 'Venda',
    'fy' => 'Vestfrisisk',
    'vi' => 'Vietnamesisk',
    'vo' => 'Volapyk',
    'vot' => 'Votisk',
    'wak' => 'Wakasjansk språk',
    'wal' => 'Walamo',
    'cy' => 'Walisisk',
    'war' => 'Waray',
    'was' => 'Washo',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yav' => 'Yangben',
    'yao' => 'Yao',
    'yap' => 'Yapesisk',
    'znd' => 'Zande',
    'zap' => 'Zapotec',
    'dje' => 'Zarma',
    'zza' => 'Zaza',
    'zen' => 'Zenaga',
    'za' => 'Zhuang',
    'zu' => 'Zulu',
    'zun' => 'Zuni',
  ),
  'countries' => 
  array (
    'AF' => 'Afghanistan',
    'AL' => 'Albania',
    'DZ' => 'Algerie',
    'AS' => 'Amerikansk Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarktis',
    'AG' => 'Antigua og Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AC' => 'Ascension',
    'AZ' => 'Aserbajdsjan',
    'TL' => 'Aust-Timor',
    'AT' => 'Austerrike',
    'AU' => 'Australia',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BE' => 'Belgia',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia og Hercegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvetøya',
    'BR' => 'Brasil',
    'IO' => 'Britiske område i Det indiske hav',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'CA' => 'Canada',
    'KY' => 'Caymanøyane',
    'EA' => 'Ceuta og Melilla',
    'CL' => 'Chile',
    'CX' => 'Christmasøya',
    'CP' => 'Clippertonøya',
    'CO' => 'Colombia',
    'CK' => 'Cookøyane',
    'CR' => 'Costa Rica',
    'CU' => 'Cuba',
    'DK' => 'Danmark',
    'VI' => 'Dei amerikanske jomfruøyane',
    'VG' => 'Dei britiske jomfruøyane',
    'AN' => 'Dei nederlandske Antillane',
    'AE' => 'Dei sameinte arabiske emirata',
    'DO' => 'Den dominikanske republikken',
    'EU' => 'Den europeiske unionen',
    'CF' => 'Den sentralafrikanske republikken',
    'DG' => 'Diego Garcia',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'GQ' => 'Ekvatorial-Guinea',
    'SV' => 'El Salvador',
    'CI' => 'Elfenbeinskysten',
    'ER' => 'Eritrea',
    'EE' => 'Estland',
    'ET' => 'Etiopia',
    'FK' => 'Falklandsøyane',
    'FJ' => 'Fiji',
    'PH' => 'Filippinane',
    'FI' => 'Finland',
    'FR' => 'Frankrike',
    'GF' => 'Fransk Guyana',
    'PF' => 'Fransk Polynesia',
    'TF' => 'Franske sørområde',
    'FO' => 'Færøyane',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GD' => 'Grenada',
    'GL' => 'Grønland',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard- og McDonaldsøyane',
    'GR' => 'Hellas',
    'HN' => 'Honduras',
    'HK' => 'Hongkong',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IQ' => 'Irak',
    'IR' => 'Iran',
    'IE' => 'Irland',
    'IS' => 'Island',
    'IL' => 'Israel',
    'IT' => 'Italia',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KH' => 'Kambodsja',
    'CM' => 'Kamerun',
    'IC' => 'Kanariøyane',
    'CV' => 'Kapp Verde',
    'KZ' => 'Kasakhstan',
    'KE' => 'Kenya',
    'CN' => 'Kina',
    'KG' => 'Kirgisistan',
    'KI' => 'Kiribati',
    'CC' => 'Kokosøyane',
    'KM' => 'Komorene',
    'CG' => 'Kongo-Brazzaville',
    'CD' => 'Kongo-Kinshasa',
    'HR' => 'Kroatia',
    'KW' => 'Kuwait',
    'BY' => 'Kviterussland',
    'CY' => 'Kypros',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LS' => 'Lesotho',
    'LB' => 'Libanon',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Liechtenstein',
    'LT' => 'Litauen',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MG' => 'Madagaskar',
    'MK' => 'Makedonia',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldivane',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'IM' => 'Man',
    'MA' => 'Marokko',
    'MH' => 'Marshalløyane',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Mikronesiaføderasjonen',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MZ' => 'Mosambik',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NL' => 'Nederland',
    'NP' => 'Nepal',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'KP' => 'Nord-Korea',
    'MP' => 'Nord-Marianane',
    'NO' => 'Noreg',
    'NF' => 'Norfolkøyane',
    'NC' => 'Ny-Caledonia',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinsk territorium',
    'PA' => 'Panama',
    'PG' => 'Papua Ny-Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PN' => 'Pitcairn',
    'PL' => 'Polen',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RO' => 'Romania',
    'RU' => 'Russland',
    'RW' => 'Rwanda',
    'RE' => 'Réunion',
    'BL' => 'Saint Barthélemy',
    'SH' => 'Saint Helena',
    'MF' => 'Saint Martin',
    'SB' => 'Salomonøyane',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'CS' => 'Serbia og Montenegro',
    'SC' => 'Seychellane',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SO' => 'Somalia',
    'ES' => 'Spania',
    'LK' => 'Sri Lanka',
    'KN' => 'St. Christopher og Nevis',
    'LC' => 'St. Lucia',
    'PM' => 'St. Pierre og Miquelon',
    'VC' => 'St. Vincent og Grenadinane',
    'GB' => 'Storbritannia',
    'SD' => 'Sudan',
    'SR' => 'Surinam',
    'SJ' => 'Svalbard og Jan Mayen',
    'CH' => 'Sveits',
    'SE' => 'Sverige',
    'SZ' => 'Swaziland',
    'SY' => 'Syria',
    'ST' => 'São Tomé og Príncipe',
    'ZA' => 'Sør-Afrika',
    'GS' => 'Sør-Georgia og Sør-Sandwich-øyane',
    'KR' => 'Sør-Korea',
    'TJ' => 'Tadsjikistan',
    'TW' => 'Taiwan',
    'TZ' => 'Tanzania',
    'TD' => 'Tchad',
    'TH' => 'Thailand',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad og Tobago',
    'TA' => 'Tristan da Cunha',
    'CZ' => 'Tsjekkia',
    'TN' => 'Tunisia',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks- og Caicosøyane',
    'TV' => 'Tuvalu',
    'TR' => 'Tyrkia',
    'DE' => 'Tyskland',
    'US' => 'USA',
    'UM' => 'USAs ytre småøyar',
    'UG' => 'Uganda',
    'ZZ' => 'Ukjent område',
    'UA' => 'Ukraina',
    'HU' => 'Ungarn',
    'UY' => 'Uruguay',
    'UZ' => 'Usbekistan',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikanstaten',
    'VE' => 'Venezuela',
    'EH' => 'Vest-Sahara',
    'VN' => 'Vietnam',
    'WF' => 'Wallis og Futuna',
    'YE' => 'Yemen',
    'QO' => 'Ytre Oseania',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
    'AX' => 'Åland',
  ),
);
