<?php
/**
 * Locale data for 'rn_BI'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0 %',
  'currencyFormat' => '#,##0.00¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'd/M/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Nzero',
      2 => 'Ruhuhuma',
      3 => 'Ntwarante',
      4 => 'Ndamukiza',
      5 => 'Rusama',
      6 => 'Ruheshi',
      7 => 'Mukakaro',
      8 => 'Nyandagaro',
      9 => 'Nyakanga',
      10 => 'Gitugutu',
      11 => 'Munyonyo',
      12 => 'Kigarama',
    ),
    'abbreviated' => 
    array (
      1 => 'Mut.',
      2 => 'Gas.',
      3 => 'Wer.',
      4 => 'Mat.',
      5 => 'Gic.',
      6 => 'Kam.',
      7 => 'Nya.',
      8 => 'Kan.',
      9 => 'Nze.',
      10 => 'Ukw.',
      11 => 'Ugu.',
      12 => 'Uku.',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ku w\'indwi',
      1 => 'Ku wa mbere',
      2 => 'Ku wa kabiri',
      3 => 'Ku wa gatatu',
      4 => 'Ku wa kane',
      5 => 'Ku wa gatanu',
      6 => 'Ku wa gatandatu',
    ),
    'abbreviated' => 
    array (
      0 => 'cu.',
      1 => 'mbe.',
      2 => 'kab.',
      3 => 'gtu.',
      4 => 'kan.',
      5 => 'gnu.',
      6 => 'gnd.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Idolari ryo muri Ositaraliya',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Idolari rya Kanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Iyuwani ryo mu Bushinwa',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Iyero',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Ipawundi ryo mu Bwongereza',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Irupiya ryo mu Buhindi',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Iyeni ry\'Ubuyapani',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Idolari ry\'abanyamerika',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'BIF' => 
    array (
      'symbol' => 'FBu',
      'name' => 'Ifaranga ry\'Uburundi',
    ),
    'AED' => 
    array (
      'name' => 'Idiramu ryo muri Leta Zunze Ubumwe z\'Abarabu',
    ),
    'AOA' => 
    array (
      'name' => 'Ikwanza ryo muri Angola',
    ),
    'BHD' => 
    array (
      'name' => 'Idinari ry\'iribahireyini',
    ),
    'BWP' => 
    array (
      'name' => 'Ipula ryo muri Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'Ifaranga rya Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'Ifaranga ry\'Ubusuwisi',
    ),
    'CVE' => 
    array (
      'name' => 'Irikaboveridiyano ryo muri Esikudo',
    ),
    'DJF' => 
    array (
      'name' => 'Ifaranga ryo muri Jibuti',
    ),
    'DZD' => 
    array (
      'name' => 'Idinari ryo muri Alijeriya',
    ),
    'EGP' => 
    array (
      'name' => 'Ipawundi rya Misiri',
    ),
    'ERN' => 
    array (
      'name' => 'Irinakufa ryo muri Eritereya',
    ),
    'ETB' => 
    array (
      'name' => 'Ibiri ryo muri Etiyopiya',
    ),
    'GHC' => 
    array (
      'name' => 'Icedi ryo muri Gana',
    ),
    'GMD' => 
    array (
      'name' => 'Idalasi ryo muri Gambiya',
    ),
    'GNS' => 
    array (
      'name' => 'Ifaranga ryo muri Gineya',
    ),
    'KES' => 
    array (
      'name' => 'Ishilingi rya Kenya',
    ),
    'KMF' => 
    array (
      'name' => 'Ifaranga rya Komore',
    ),
    'LRD' => 
    array (
      'name' => 'Idolari rya Liberiya',
    ),
    'LSL' => 
    array (
      'name' => 'Iloti ryo muro Lesoto',
    ),
    'LYD' => 
    array (
      'name' => 'Idinari rya Libiya',
    ),
    'MAD' => 
    array (
      'name' => 'Idiramu ryo muri Maroke',
    ),
    'MGA' => 
    array (
      'name' => 'Iriyari ryo muri Madagasikari',
    ),
    'MRO' => 
    array (
      'name' => 'Ugwiya ryo muri Moritaniya',
    ),
    'MUR' => 
    array (
      'name' => 'Irupiya ryo mu birwa bya Morise',
    ),
    'MWK' => 
    array (
      'name' => 'Ikwaca ryo muri Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Irimetikali ryo muri Mozambike',
    ),
    'NAD' => 
    array (
      'name' => 'Idolari rya Namibiya',
    ),
    'NGN' => 
    array (
      'name' => 'Inayira ryo muri Nijeriya',
    ),
    'RWF' => 
    array (
      'name' => 'Ifaranga ry\'u Rwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Iriyari ryo muri Arabiya Sawudite',
    ),
    'SCR' => 
    array (
      'name' => 'Irupiya ryo mu birwa bya Sayisheli',
    ),
    'SDG' => 
    array (
      'name' => 'Ipawundi rya Sudani',
    ),
    'SHP' => 
    array (
      'name' => 'Ipawundi rya Sente Helena',
    ),
    'SLL' => 
    array (
      'name' => 'Ilewone',
    ),
    'SOS' => 
    array (
      'name' => 'Ishilingi ryo muri Somaliya',
    ),
    'STD' => 
    array (
      'name' => 'Idobura ryo muri Sawotome na Perensipe',
    ),
    'SZL' => 
    array (
      'name' => 'Ililangeni',
    ),
    'TND' => 
    array (
      'name' => 'Idinari ryo muri Tuniziya',
    ),
    'TZS' => 
    array (
      'name' => 'Ishilingi rya Tanzaniya',
    ),
    'UGX' => 
    array (
      'name' => 'Ishilingi ry\'Ubugande',
    ),
    'ZAR' => 
    array (
      'name' => 'Irandi ryo muri Afurika y\'Epfo',
    ),
    'ZMK' => 
    array (
      'name' => 'Ikwaca ryo muri Zambiya',
    ),
    'ZWD' => 
    array (
      'name' => 'Idolari ryo muri Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ar' => 'Icarabu',
    'es' => 'Icesipanyolo',
    'en' => 'Icongereza',
    'cs' => 'Igiceke',
    'fr' => 'Igifaransa',
    'ha' => 'Igihawusa',
    'hi' => 'Igihindi',
    'nl' => 'Igiholandi',
    'km' => 'Igikambodiya',
    'ak' => 'Igikani',
    'fa' => 'Igiperisi',
    'pt' => 'Igiporutugari',
    'pa' => 'Igipunjabi',
    'zh' => 'Igishinwa',
    'so' => 'Igisomali',
    'sv' => 'Igisuweduwa',
    'it' => 'Igitaliyani',
    'ta' => 'Igitamili',
    'tr' => 'Igiturukiya',
    'be' => 'Ikibelarusiya',
    'bn' => 'Ikibengali',
    'de' => 'Ikidage',
    'el' => 'Ikigereki',
    'ig' => 'Ikigubo',
    'am' => 'Ikimuhariki',
    'ne' => 'Ikinepali',
    'my' => 'Ikinyabirimaniya',
    'bg' => 'Ikinyabuligariya',
    'hu' => 'Ikinyahongiriya',
    'ko' => 'Ikinyakoreya',
    'ms' => 'Ikinyamaleziya',
    'pl' => 'Ikinyapolonye',
    'ro' => 'Ikinyarumaniya',
    'rw' => 'Ikinyarwanda',
    'th' => 'Ikinyatayilandi',
    'vi' => 'Ikinyaviyetinamu',
    'uk' => 'Ikinyayukereni',
    'jv' => 'Ikinyejava',
    'id' => 'Ikinyendoziya',
    'rn' => 'Ikirundi',
    'ru' => 'Ikirusiya',
    'ja' => 'Ikiyapani',
    'yo' => 'Ikiyoruba',
    'zu' => 'Ikizulu',
    'ur' => 'Inyeyurudu',
  ),
  'countries' => 
  array (
    'AF' => 'Afuganisitani',
    'ZA' => 'Afurika y\'Epfo',
    'DZ' => 'Alijeriya',
    'AL' => 'Alubaniya',
    'VI' => 'Amazinga y\'Isugi y\'Abanyamerika',
    'PH' => 'Amazinga ya Filipine',
    'MP' => 'Amazinga ya Mariyana ryo mu majaruguru',
    'RE' => 'Amazinga ya Reyiniyo',
    'SB' => 'Amazinga ya Salumoni',
    'SC' => 'Amazinga ya Seyisheli',
    'TC' => 'Amazinga ya Turkisi na Cayikosi',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Angwila',
    'AG' => 'Antigwa na Baribuda',
    'AN' => 'Antiye y\'Abaholandi',
    'SA' => 'Arabiya Sawudite',
    'AR' => 'Arijantine',
    'AW' => 'Aruba',
    'AM' => 'Arumeniya',
    'IS' => 'Ayisilandi',
    'AZ' => 'Azerubayijani',
    'BS' => 'Bahamasi',
    'BH' => 'Bahareyini',
    'BD' => 'Bangaladeshi',
    'BB' => 'Barubadosi',
    'BY' => 'Belausi',
    'BZ' => 'Belize',
    'BJ' => 'Bene',
    'BM' => 'Berimuda',
    'MM' => 'Birimaniya',
    'BO' => 'Boliviya',
    'BA' => 'Bosiniya na Herigozevine',
    'BW' => 'Botswana',
    'BG' => 'Buligariya',
    'BR' => 'Burezili',
    'BF' => 'Burukina Faso',
    'BN' => 'Buruneyi',
    'BT' => 'Butani',
    'TD' => 'Cadi',
    'DK' => 'Danimariki',
    'DM' => 'Dominika',
    'EC' => 'Ekwateri',
    'SV' => 'Eli Saluvatori',
    'ER' => 'Elitereya',
    'EE' => 'Esitoniya',
    'ET' => 'Etiyopiya',
    'FJ' => 'Fiji',
    'FI' => 'Finilandi',
    'GA' => 'Gabo',
    'GM' => 'Gambiya',
    'GH' => 'Gana',
    'GD' => 'Gerenada',
    'GW' => 'Gineya Bisawu',
    'GQ' => 'Gineya Ekwatoriyali',
    'GN' => 'Guneya',
    'GL' => 'Gurunilandi',
    'GY' => 'Guyane',
    'GP' => 'Gwadelupe',
    'GU' => 'Gwamu',
    'GT' => 'Gwatemala',
    'GF' => 'Gwayana y\'Abafaransa',
    'HT' => 'Hayiti',
    'ES' => 'Hisipaniya',
    'HN' => 'Hondurasi',
    'HU' => 'Hungariya',
    'CK' => 'I\\inga rya Kuku',
    'VG' => 'Ibirwa by\'isugi by\'Abongereza',
    'CV' => 'Ibirwa bya Kapuveri',
    'KY' => 'Ibirwa bya Keyimani',
    'UA' => 'Ikerene',
    'ID' => 'Indoneziya',
    'IO' => 'Intara y\'Ubwongereza yo mu birwa by\'Abahindi',
    'IQ' => 'Iraki',
    'IR' => 'Irani',
    'UY' => 'Irigwe',
    'IE' => 'Irilandi',
    'IL' => 'Isiraheli',
    'FK' => 'Izinga rya Filikilandi',
    'KM' => 'Izinga rya Komore',
    'MH' => 'Izinga rya Marishari',
    'MU' => 'Izinga rya Morise',
    'NF' => 'Izinga rya Norufoluke',
    'CY' => 'Izinga rya Shipure',
    'JM' => 'Jamayika',
    'GE' => 'Jeworujiya',
    'DJ' => 'Jibuti',
    'GI' => 'Juburalitari',
    'KH' => 'Kamboje',
    'CM' => 'Kameruni',
    'CA' => 'Kanada',
    'QA' => 'Katari',
    'KZ' => 'Kazakisitani',
    'KE' => 'Kenya',
    'CU' => 'Kiba',
    'KI' => 'Kiribati',
    'KG' => 'Kirigisitani',
    'CO' => 'Kolombiya',
    'CG' => 'Kongo',
    'KP' => 'Koreya y\'amajaruguru',
    'KR' => 'Koreya y\'amajepfo',
    'HR' => 'Korowasiya',
    'CR' => 'Kositarika',
    'CI' => 'Kotedivuware',
    'KW' => 'Koweti',
    'LV' => 'Lativa',
    'LA' => 'Layosi',
    'LS' => 'Lesoto',
    'AE' => 'Leta Zunze Ubumwe z\'Abarabu',
    'US' => 'Leta Zunze Ubumwe za Amerika',
    'LB' => 'Libani',
    'LR' => 'Liberiya',
    'LY' => 'Libiya',
    'LI' => 'Lishyitenshitayini',
    'LT' => 'Lituwaniya',
    'LU' => 'Lukusamburu',
    'MG' => 'Madagasikari',
    'MW' => 'Malawi',
    'MY' => 'Maleziya',
    'ML' => 'Mali',
    'MT' => 'Malita',
    'MQ' => 'Maritiniki',
    'MA' => 'Maroke',
    'MK' => 'Masedoniya',
    'YT' => 'Mayote',
    'MX' => 'Migizike',
    'FM' => 'Mikoroniziya',
    'EG' => 'Misiri',
    'MV' => 'Moludave',
    'MD' => 'Moludavi',
    'MC' => 'Monako',
    'MN' => 'Mongoliya',
    'MS' => 'Monteserati',
    'MR' => 'Moritaniya',
    'MZ' => 'Mozambiki',
    'NA' => 'Namibiya',
    'NR' => 'Nawuru',
    'NP' => 'Nepali',
    'NE' => 'Nijeri',
    'NG' => 'Nijeriya',
    'NI' => 'Nikaragwa',
    'NC' => 'Niyukaledoniya',
    'NU' => 'Niyuwe',
    'NO' => 'Noruveji',
    'NZ' => 'Nuvelizelandi',
    'OM' => 'Omani',
    'AU' => 'Ositaraliya',
    'AT' => 'Otirishe',
    'PK' => 'Pakisitani',
    'PW' => 'Palawu',
    'PS' => 'Palesitina Wesitibanka na Gaza',
    'PA' => 'Panama',
    'PG' => 'Papuwa Niyugineya',
    'PY' => 'Paragwe',
    'PE' => 'Peru',
    'PN' => 'Pitikeyirini',
    'PF' => 'Polineziya y\'Abafaransa',
    'PL' => 'Polonye',
    'PT' => 'Porutugali',
    'PR' => 'Puwetoriko',
    'CD' => 'Repubulika Iharanira Demokarasi ya Kongo',
    'CZ' => 'Repubulika ya Ceke',
    'DO' => 'Repubulika ya Dominika',
    'CF' => 'Repubulika ya Santarafurika',
    'RO' => 'Rumaniya',
    'WS' => 'Samowa',
    'AS' => 'Samowa nyamerika',
    'SM' => 'Sanimarino',
    'ST' => 'Sawotome na Perensipe',
    'SH' => 'Sehelene',
    'KN' => 'Sekitsi na Nevisi',
    'LC' => 'Selusiya',
    'PM' => 'Sempiyeri na Mikeloni',
    'SN' => 'Senegali',
    'CS' => 'Seribiya na Montenegoro',
    'VC' => 'Sevensa na Gerenadine',
    'CL' => 'Shili',
    'SK' => 'Silovakiya',
    'SI' => 'Siloveniya',
    'SG' => 'Singapuru',
    'LK' => 'Sirilanka',
    'SY' => 'Siriya',
    'SL' => 'Siyeralewone',
    'SO' => 'Somaliya',
    'SD' => 'Sudani',
    'SR' => 'Suriname',
    'SZ' => 'Suwazilandi',
    'SE' => 'Suwedi',
    'TJ' => 'Tajikisitani',
    'TZ' => 'Tanzaniya',
    'TH' => 'Tayilandi',
    'TW' => 'Tayiwani',
    'TL' => 'Timoru y\'iburasirazuba',
    'TT' => 'Tirinidadi na Tobago',
    'TG' => 'Togo',
    'TK' => 'Tokelawu',
    'TO' => 'Tonga',
    'TN' => 'Tuniziya',
    'TR' => 'Turukiya',
    'TM' => 'Turukumenisitani',
    'TV' => 'Tuvalu',
    'RW' => 'U Rwanda',
    'BE' => 'Ububiligi',
    'DE' => 'Ubudage',
    'FR' => 'Ubufaransa',
    'UG' => 'Ubugande',
    'GR' => 'Ubugereki',
    'IN' => 'Ubuhindi',
    'NL' => 'Ubuholandi',
    'BI' => 'Uburundi',
    'RU' => 'Uburusiya',
    'CN' => 'Ubushinwa',
    'CH' => 'Ubusuwisi',
    'IT' => 'Ubutaliyani',
    'JP' => 'Ubuyapani',
    'GB' => 'Ubwongereza',
    'VA' => 'Umurwa wa Vatikani',
    'UZ' => 'Uzubekisitani',
    'VU' => 'Vanuwatu',
    'VE' => 'Venezuwela',
    'VN' => 'Viyetinamu',
    'WF' => 'Walisi na Futuna',
    'YE' => 'Yemeni',
    'JO' => 'Yorudaniya',
    'ZM' => 'Zambiya',
    'ZW' => 'Zimbabwe',
  ),
);
