<?php
/**
 * Locale data for 'rw'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤ #,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Mutarama',
      2 => 'Gashyantare',
      3 => 'Werurwe',
      4 => 'Mata',
      5 => 'Gicuransi',
      6 => 'Kamena',
      7 => 'Nyakanga',
      8 => 'Kanama',
      9 => 'Nzeli',
      10 => 'Ukwakira',
      11 => 'Ugushyingo',
      12 => 'Ukuboza',
    ),
    'abbreviated' => 
    array (
      1 => 'mut.',
      2 => 'gas.',
      3 => 'wer.',
      4 => 'mat.',
      5 => 'gic.',
      6 => 'kam.',
      7 => 'nya.',
      8 => 'kan.',
      9 => 'nze.',
      10 => 'ukw.',
      11 => 'ugu.',
      12 => 'uku.',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ku cyumweru',
      1 => 'Kuwa mbere',
      2 => 'Kuwa kabiri',
      3 => 'Kuwa gatatu',
      4 => 'Kuwa kane',
      5 => 'Kuwa gatanu',
      6 => 'Kuwa gatandatu',
    ),
    'abbreviated' => 
    array (
      0 => 'cyu.',
      1 => 'mbe.',
      2 => 'kab.',
      3 => 'gtu.',
      4 => 'kan.',
      5 => 'gnu.',
      6 => 'gnd.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'RWF' => 
    array (
      'symbol' => 'RF',
    ),
  ),
  'languages' => 
  array (
    'sq' => 'Icyalubaniya',
    'ar' => 'Icyarabu',
    'as' => 'Icyasamizi',
    'es' => 'Icyesipanyolo',
    'eo' => 'Icyesiperanto',
    'et' => 'Icyesitoniya',
    'en' => 'Icyongereza',
    'cs' => 'Igiceke',
    'fr' => 'Igifaransa',
    'fi' => 'Igifinilande',
    'fy' => 'Igifiriziyani',
    'he' => 'Igiheburayo',
    'hi' => 'Igihindi',
    'hu' => 'Igihongiriya',
    'km' => 'Igikambodiya',
    'kn' => 'Igikanada',
    'ca' => 'Igikatalani',
    'ko' => 'Igikoreya',
    'hr' => 'Igikorowasiya',
    'pl' => 'Igipolone',
    'pt' => 'Igiporutugali',
    'pa' => 'Igipunjabi',
    'sa' => 'Igisansikiri',
    'sr' => 'Igiseribe',
    'is' => 'Igisilande',
    'sk' => 'Igisilovaki',
    'sd' => 'Igisindi',
    'so' => 'Igisomali',
    'sv' => 'Igisuweduwa',
    'sw' => 'Igiswahili',
    'it' => 'Igitaliyani',
    'ta' => 'Igitamili',
    'th' => 'Igitayi',
    'te' => 'Igitelugu',
    'tr' => 'Igiturukiya',
    'eu' => 'Ikibasiki',
    'be' => 'Ikibelarusiya',
    'bn' => 'Ikibengali',
    'de' => 'Ikidage',
    'da' => 'Ikidaninwa',
    'gl' => 'Ikigalisiya',
    'cy' => 'Ikigaluwa',
    'gd' => 'Ikigaluwa cy\'Igisweduwa',
    'el' => 'Ikigereki',
    'la' => 'Ikilatini',
    'lo' => 'Ikilawotiyani',
    'lt' => 'Ikilituwaniya',
    'ml' => 'Ikimalayalami',
    'ms' => 'Ikimalayi',
    'mt' => 'Ikimaliteze',
    'mr' => 'Ikimarati',
    'mk' => 'Ikimasedoniyani',
    'mn' => 'Ikimongoli',
    'ne' => 'Ikinepali',
    'nl' => 'Ikinerilande',
    'no' => 'Ikinoruveji',
    'fil' => 'Ikinyafilipine',
    'af' => 'Ikinyafurikaneri',
    'lv' => 'Ikinyaletoviyani',
    'ro' => 'Ikinyarumaniya',
    'hy' => 'Ikinyarumeniya',
    'sl' => 'Ikinyasiloveniya',
    'vi' => 'Ikinyaviyetinamu',
    'uk' => 'Ikinyayukereni',
    'id' => 'Ikinyendoziya',
    'ga' => 'Ikirilandi',
    'ru' => 'Ikirusiya',
    'ug' => 'Ikiwiguri',
    'ja' => 'Ikiyapani',
    'ln' => 'Ilingala',
    'ps' => 'Impashito',
    'ky' => 'Inkerigizi',
    'gn' => 'Inyaguwarani',
    'am' => 'Inyamuhariki',
    'ti' => 'Inyatigirinya',
    'az' => 'Inyazeribayijani',
    'bh' => 'Inyebihari',
    'br' => 'Inyebiritoni',
    'bs' => 'Inyebosiniya',
    'fo' => 'Inyefaroyizi',
    'gu' => 'Inyegujarati',
    'xh' => 'Inyehawusa',
    'jv' => 'Inyejava',
    'ka' => 'Inyejeworujiya',
    'tlh' => 'Inyekilingoni',
    'ku' => 'Inyekuridishi',
    'nn' => 'Inyenoruveji (Nyonorusiki)',
    'fa' => 'Inyeperisi',
    'pt_BR' => 'Inyeporutigali (Brezili)',
    'pt_PT' => 'Inyeporutigali (Igiporutigali)',
    'sh' => 'Inyeseribiya na Korowasiya',
    'st' => 'Inyesesoto',
    'si' => 'Inyesimpaleze',
    'su' => 'Inyesudani',
    'tk' => 'Inyeturukimeni',
    'tw' => 'Inyetuwi',
    'yi' => 'Inyeyidishi',
    'ur' => 'Inyeyurudu',
    'uz' => 'Inyeyuzubeki',
    'zu' => 'Inyezulu',
    'oc' => 'Inyogusitani',
    'or' => 'Inyoriya',
    'rw' => 'Kinyarwanda',
    'ie' => 'Uruhuzandimi',
    'bg' => 'Urunyabuligariya',
    'ia' => 'Ururimi Gahuzamiryango',
  ),
  'countries' => 
  array (
    'TO' => 'Igitonga',
    'RW' => 'Rwanda',
  ),
);
