<?php
/**
 * Locale data for 'sn_ZW'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ndira',
      2 => 'Kukadzi',
      3 => 'Kurume',
      4 => 'Kubvumbi',
      5 => 'Chivabvu',
      6 => 'Chikumi',
      7 => 'Chikunguru',
      8 => 'Nyamavhuvhu',
      9 => 'Gunyana',
      10 => 'Gumiguru',
      11 => 'Mbudzi',
      12 => 'Zvita',
    ),
    'abbreviated' => 
    array (
      1 => 'Ndi',
      2 => 'Kuk',
      3 => 'Kur',
      4 => 'Kub',
      5 => 'Chi',
      6 => 'Chi',
      7 => 'Chi',
      8 => 'Nya',
      9 => 'Gun',
      10 => 'Gum',
      11 => 'Mb',
      12 => 'Zvi',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'N',
      2 => 'K',
      3 => 'K',
      4 => 'K',
      5 => 'C',
      6 => 'C',
      7 => 'C',
      8 => 'N',
      9 => 'G',
      10 => 'G',
      11 => 'M',
      12 => 'Z',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Svondo',
      1 => 'Muvhuro',
      2 => 'Chipiri',
      3 => 'Chitatu',
      4 => 'China',
      5 => 'Chishanu',
      6 => 'Mugovera',
    ),
    'abbreviated' => 
    array (
      0 => 'Svo',
      1 => 'Muv',
      2 => 'Chip',
      3 => 'Chit',
      4 => 'Chin',
      5 => 'Chis',
      6 => 'Mug',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'C',
      3 => 'C',
      4 => 'C',
      5 => 'C',
      6 => 'M',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Dora re Australia',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Dora re Kanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Yuan Renminbi ye China',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Yuro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Paundi ye Bhiriteni',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Rupe re India',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Yeni ye Japani',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Dora re Amerika',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Furenki CFA BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Furenki CFA BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'AED' => 
    array (
      'name' => 'Diramu re United Arab Emirates',
    ),
    'AOA' => 
    array (
      'name' => 'Kwanza ye Angola',
    ),
    'BHD' => 
    array (
      'name' => 'Dhinari re Bhahareni',
    ),
    'BIF' => 
    array (
      'name' => 'Furenki re Bhurundi',
    ),
    'BWP' => 
    array (
      'name' => 'Pura re Botswana',
    ),
    'CDF' => 
    array (
      'name' => 'Furenki re Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'Furenki re Swisi',
    ),
    'CVE' => 
    array (
      'name' => 'Dhora re Escudo',
    ),
    'DJF' => 
    array (
      'name' => 'Furenki re Jibhuti',
    ),
    'DZD' => 
    array (
      'name' => 'Dhinari re Aljeria',
    ),
    'EGP' => 
    array (
      'name' => 'Paundi re Ijipita',
    ),
    'ERN' => 
    array (
      'name' => 'Nakfa re Eritrea',
    ),
    'ETB' => 
    array (
      'name' => 'Dhora re Etiopia',
    ),
    'GHC' => 
    array (
      'name' => 'Sedi ye Ghana',
    ),
    'GMD' => 
    array (
      'name' => 'Dalasi ye Gambia',
    ),
    'GNS' => 
    array (
      'name' => 'Furenki re Gine',
    ),
    'KES' => 
    array (
      'name' => 'Shiringi ye Kenya',
    ),
    'KMF' => 
    array (
      'name' => 'Furenki re Komoro',
    ),
    'LRD' => 
    array (
      'name' => 'Dora re Liberia',
    ),
    'LSL' => 
    array (
      'name' => 'Loti ye Lesoto',
    ),
    'LYD' => 
    array (
      'name' => 'Dinari re Libya',
    ),
    'MAD' => 
    array (
      'name' => 'Dirham ye Moroko',
    ),
    'MGA' => 
    array (
      'name' => 'Furenki re Malagasi',
    ),
    'MRO' => 
    array (
      'name' => 'Ugwiya ye Moritania',
    ),
    'MUR' => 
    array (
      'name' => 'Rupi ye Morishasi',
    ),
    'MWK' => 
    array (
      'name' => 'Kwacha ye Malawi',
    ),
    'MZM' => 
    array (
      'name' => 'Metika ye Mozambiki',
    ),
    'NAD' => 
    array (
      'name' => 'Dora re Namibia',
    ),
    'NGN' => 
    array (
      'name' => 'Naira ye Nijeria',
    ),
    'RWF' => 
    array (
      'name' => 'Furenki re Ruwanda',
    ),
    'SAR' => 
    array (
      'name' => 'Riyali re Saudi',
    ),
    'SCR' => 
    array (
      'name' => 'Rupi re Seyisheri',
    ),
    'SDG' => 
    array (
      'name' => 'Dinari re Sudani',
    ),
    'SDP' => 
    array (
      'name' => 'Paundi re Sudani',
    ),
    'SHP' => 
    array (
      'name' => 'Paundi re Senti Helena',
    ),
    'SLL' => 
    array (
      'name' => 'Leoni',
    ),
    'SOS' => 
    array (
      'name' => 'Shiringi re Somalia',
    ),
    'STD' => 
    array (
      'name' => 'Dobra re Sao Tome ne Principe',
    ),
    'SZL' => 
    array (
      'name' => 'Lilangeni',
    ),
    'TND' => 
    array (
      'name' => 'Dinari re Tunisia',
    ),
    'TZS' => 
    array (
      'name' => 'Shiringi re Tanzania',
    ),
    'UGX' => 
    array (
      'name' => 'Shiringi re Uganda',
    ),
    'ZAR' => 
    array (
      'name' => 'Randi',
    ),
    'ZMK' => 
    array (
      'name' => 'Kwacha ye Zambia',
    ),
    'ZWD' => 
    array (
      'name' => 'Dora re Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ak' => 'ChiAkani',
    'am' => 'ChiAmaric',
    'ar' => 'ChiArabu',
    'be' => 'ChiBelarusi',
    'bn' => 'ChiBengali',
    'bg' => 'ChiBulgarian',
    'my' => 'ChiBurma',
    'zh' => 'ChiChinese',
    'cs' => 'ChiCzech',
    'nl' => 'ChiDutch',
    'fr' => 'ChiFurenchi',
    'el' => 'ChiGreek',
    'ha' => 'ChiHausa',
    'hi' => 'ChiHindi',
    'hu' => 'ChiHungari',
    'ig' => 'ChiIgbo',
    'id' => 'ChiIndonesia',
    'ja' => 'ChiJapani',
    'jv' => 'ChiJava',
    'de' => 'ChiJerimani',
    'km' => 'ChiKhema',
    'ko' => 'ChiKoria',
    'ms' => 'ChiMalay',
    'ne' => 'ChiNepali',
    'fa' => 'ChiPeshiya',
    'pl' => 'ChiPolish',
    'pa' => 'ChiPunjabi',
    'pt' => 'ChiPutukezi',
    'ru' => 'ChiRashiya',
    'ro' => 'ChiRomanian',
    'rw' => 'ChiRwanda',
    'sn' => 'ChiShona',
    'so' => 'ChiSomali',
    'es' => 'ChiSpanish',
    'sv' => 'ChiSwedish',
    'ta' => 'ChiTamil',
    'it' => 'ChiTariana',
    'th' => 'ChiThai',
    'tr' => 'ChiTurkish',
    'uk' => 'ChiUkrenia',
    'ur' => 'ChiUrdu',
    'vi' => 'ChiVietnam',
    'yo' => 'ChiYoruba',
    'zu' => 'ChiZulu',
    'en' => 'Chirungu',
  ),
  'countries' => 
  array (
    'PS' => '',
    'AF' => 'Afuganistani',
    'AR' => 'Ajentina',
    'AL' => 'Albania',
    'DZ' => 'Aljeria',
    'US' => 'Amerika',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Anguila',
    'AG' => 'Antigua ne Barbuda',
    'AM' => 'Armenia',
    'AW' => 'Arubha',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azabajani',
    'BS' => 'Bahama',
    'BH' => 'Bahareni',
    'BD' => 'Bangladeshi',
    'BB' => 'Barbados',
    'BY' => 'Belarusi',
    'BZ' => 'Belize',
    'BE' => 'Beljium',
    'BJ' => 'Benini',
    'BM' => 'Bermuda',
    'BT' => 'Bhutani',
    'BO' => 'Bolivia',
    'BW' => 'Botswana',
    'BA' => 'Boznia ne Herzegovina',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'BF' => 'Bukinafaso',
    'BG' => 'Bulgaria',
    'BI' => 'Burundi',
    'BN' => 'Burunei',
    'CF' => 'Central African Republic',
    'TD' => 'Chadi',
    'CL' => 'Chile',
    'CN' => 'China',
    'NF' => 'Chitsuwa cheNorfolk',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'CD' => 'Democratic Republic of the Congo',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'TL' => 'East Timor',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Etiopia',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HN' => 'Honduras',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IT' => 'Italy',
    'CI' => 'Ivory Coast',
    'IL' => 'Izuraeri',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JO' => 'Jordan',
    'KH' => 'Kambodia',
    'CM' => 'Kameruni',
    'CA' => 'Kanada',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'CO' => 'Kolombia',
    'KM' => 'Komoro',
    'CG' => 'Kongo',
    'HR' => 'Korasia',
    'KP' => 'Korea, North',
    'KR' => 'Korea, South',
    'CR' => 'Kostarika',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MK' => 'Macedonia',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'RE' => 'Réunion',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'PM' => 'Saint Pierre and Miquelon',
    'VC' => 'Saint Vincent and the Grenadines',
    'WS' => 'Samoa',
    'AS' => 'Samoa ye Amerika',
    'SM' => 'San Marino',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'CS' => 'Serbia and Montenegro',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syria',
    'ST' => 'São Tomé and Príncipe',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad and Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VA' => 'Vatican State',
    'VE' => 'Venezuela',
    'VN' => 'Vietnam',
    'WF' => 'Wallis and Futuna',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
    'SB' => 'Zvitsuwa zvaSolomon',
    'VI' => 'Zvitsuwa zveAmerika',
    'CV' => 'Zvitsuwa zveCape Verde',
    'KY' => 'Zvitsuwa zveCayman',
    'CK' => 'Zvitsuwa zveCook',
    'FK' => 'Zvitsuwa zveFalklands',
    'VG' => 'Zvitsuwa zveHingirandi',
    'MH' => 'Zvitsuwa zveMarshall',
    'TC' => 'Zvitsuwa zveTurk neCaico',
    'MP' => 'Zvitsuwa zvekumaodzanyemba eMariana',
  ),
);
