<?php
/**
 * Locale data for 'sr_Latn_ME'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5695',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE, dd. MMMM y.',
    'long' => 'd.MM.yyyy.',
    'medium' => 'dd.MM.y.',
    'short' => 'd.M.yy.',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH.mm.ss zzzz',
    'long' => 'HH.mm.ss z',
    'medium' => 'HH.mm.ss',
    'short' => 'HH.mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'januar',
      2 => 'februar',
      3 => 'mart',
      4 => 'april',
      5 => 'maj',
      6 => 'jun',
      7 => 'jul',
      8 => 'avgust',
      9 => 'septembar',
      10 => 'oktobar',
      11 => 'novembar',
      12 => 'decembar',
    ),
    'abbreviated' => 
    array (
      1 => 'jan',
      2 => 'feb',
      3 => 'mar',
      4 => 'apr',
      5 => 'maj',
      6 => 'jun',
      7 => 'jul',
      8 => 'avg',
      9 => 'sep',
      10 => 'okt',
      11 => 'nov',
      12 => 'dec',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'j',
      2 => 'f',
      3 => 'm',
      4 => 'a',
      5 => 'm',
      6 => 'j',
      7 => 'j',
      8 => 'a',
      9 => 's',
      10 => 'o',
      11 => 'n',
      12 => 'd',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'nedelja',
      1 => 'ponedeljak',
      2 => 'utorak',
      3 => 'sreda',
      4 => 'četvrtak',
      5 => 'petak',
      6 => 'subota',
    ),
    'abbreviated' => 
    array (
      0 => 'ned',
      1 => 'pon',
      2 => 'uto',
      3 => 'sre',
      4 => 'čet',
      5 => 'pet',
      6 => 'sub',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'n',
      1 => 'p',
      2 => 'u',
      3 => 's',
      4 => 'č',
      5 => 'p',
      6 => 's',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Australijski dolar',
      'name-single' => 'australijski dolar',
      'name-multiple' => 'australijskih dolara',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'Brazilski real',
      'name-single' => 'brazilski real',
      'name-multiple' => 'brazilskih reala',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Kanadski dolar',
      'name-single' => 'kanadski dolar',
      'name-multiple' => 'kanadskih dolara',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Kineski Juan Renminbi',
      'name-single' => 'kineski juan',
      'name-multiple' => 'kineskih juana',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Evro',
      'name-single' => 'evro',
      'name-multiple' => 'evra',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Britanska funta sterlinga',
      'name-single' => 'britanska funta sterlinga',
      'name-multiple' => 'britanskih funti sterlinga',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
      'name' => 'Honkonški dolar',
      'name-single' => 'hongkonški dolar',
      'name-multiple' => 'hongkonških dolara',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
      'name' => 'Izraelski šekel',
      'name-single' => 'novi izraelski šekel',
      'name-multiple' => 'novih izraelskih šekela',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Indijski rupi',
      'name-single' => 'indijska rupija',
      'name-multiple' => 'indijskih rupija',
    ),
    'JPY' => 
    array (
      'symbol' => '¥',
      'name' => 'Japanski jen',
      'name-single' => 'japanski jen',
      'name-multiple' => 'japanski jen',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
      'name' => 'Južno-korejski Von',
      'name-single' => 'južno-korejski von',
      'name-multiple' => 'južno-korejski von',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'Meksički peso',
      'name-single' => 'meksički pezos',
      'name-multiple' => 'meksičkih pezosa',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
      'name' => 'Novozelandski dolar',
      'name-single' => 'novozelandski dolar',
      'name-multiple' => 'novozelandskih dolara',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
      'name' => 'Tai baht (THB)',
      'name-single' => 'tajlandska bahta',
      'name-multiple' => 'tajlandska bahta',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
      'name' => 'Novi tajvanski dolar',
      'name-single' => 'novi tajvanski dolar',
      'name-multiple' => 'novi tajvanski dolari',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Američki dolar',
      'name-single' => 'američki dolar',
      'name-multiple' => 'američkih dolara',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
      'name' => 'Vijetnamski dong',
      'name-single' => 'vijetnamski dong',
      'name-multiple' => 'vijetnamski dong',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'CFA franak BEAC (XAF)',
      'name-single' => 'CFA franak BEAC',
      'name-multiple' => 'CFA franci BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
      'name' => 'Istočnokaribijski dolar (XCD)',
      'name-single' => 'istočnokaripski dolar',
      'name-multiple' => 'istočnokaripski dolar',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'CFA franak BCEAO (XOF)',
      'name-single' => 'CFA franak BCEAO',
      'name-multiple' => 'CFA franci BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
      'name' => 'CFP franak (XPF)',
      'name-single' => 'CFP franak',
      'name-multiple' => 'CFP franci',
    ),
    'BAM' => 
    array (
      'symbol' => 'KM',
      'name' => 'Bosansko-Hercegovačka konvertibilna marka',
      'name-single' => 'bosansko-hercegovačka konvertibilna marka',
      'name-multiple' => 'bosansko-hercegovačkih konvertibilnih maraka',
    ),
    'CZK' => 
    array (
      'symbol' => 'Kč',
      'name' => 'Češka kruna',
      'name-single' => 'češka kruna',
      'name-multiple' => 'čeških kruna',
    ),
    'PLN' => 
    array (
      'symbol' => 'zl',
      'name' => 'Poljski zlot (PLN)',
      'name-single' => 'poljski zlot',
      'name-multiple' => 'poljski zlot',
    ),
    'RSD' => 
    array (
      'symbol' => 'din.',
      'name' => 'Srpski dinar',
      'name-single' => 'srpski dinar',
      'name-multiple' => 'srpski dinari',
    ),
    'TRY' => 
    array (
      'symbol' => 'TL',
      'name' => 'Turska lira',
      'name-single' => 'turska lira',
      'name-multiple' => 'novih turskih lira',
    ),
    'ADP' => 
    array (
      'name' => 'Andorska pezeta (ADP)',
      'name-single' => 'Andorijska pezeta',
      'name-multiple' => 'Andorijske pezete',
    ),
    'AED' => 
    array (
      'name' => 'Ujedinjeni arapski emirati dirham',
      'name-single' => 'UAE diram',
      'name-multiple' => 'UAE dirama',
    ),
    'AFA' => 
    array (
      'name' => 'Avganistanski avgani (1927-2002) AFA',
      'name-single' => 'Avganistanski avgan (AFA)',
      'name-multiple' => 'Avganistanski avgan (AFA)',
    ),
    'AFN' => 
    array (
      'name' => 'Avganistanski avgani (AFN)',
      'name-single' => 'Avganistanski avgan',
      'name-multiple' => 'Avganistanski avgan',
    ),
    'ALK' => 
    array (
      'name-single' => 'stari albanski lek',
      'name-multiple' => 'starih albanskih lekova',
    ),
    'ALL' => 
    array (
      'name' => 'Albanski lek',
      'name-single' => 'albanski lek',
      'name-multiple' => 'albanski lek',
    ),
    'AMD' => 
    array (
      'name' => 'Jermenski dram',
      'name-single' => 'jermenski dram',
      'name-multiple' => 'jermenski drami',
    ),
    'ANG' => 
    array (
      'name' => 'Holandski Antili gilder (ANG)',
      'name-single' => 'Holandskoantilski gilder',
      'name-multiple' => 'Holandskoantilski gildera',
    ),
    'AOA' => 
    array (
      'name' => 'Angolijska kvanza (AOA)',
      'name-single' => 'Angolijska kvanza',
      'name-multiple' => 'Angolijskih kvanzi',
    ),
    'AOK' => 
    array (
      'name' => 'Angolijska kvanza (1977-1990) (AOK)',
      'name-single' => 'Angolijska kvanza (AOK)',
      'name-multiple' => 'Angolijskih kvanzi (AOK)',
    ),
    'AON' => 
    array (
      'name' => 'Angolijska nova kvanza (1990-2000) (AON)',
      'name-single' => 'angolijska nova kvanza (AON)',
      'name-multiple' => 'angolski novi kvanze (AON)',
    ),
    'AOR' => 
    array (
      'name' => 'Angolijska kvanza reajustado (1995-1999) (AOR)',
      'name-single' => 'angolijska kvanza reađustado',
      'name-multiple' => 'angolijskih kvanzi reađustado',
    ),
    'ARA' => 
    array (
      'name' => 'Argentinski austral (ARA)',
      'name-single' => 'argentinski austral (ARA)',
      'name-multiple' => 'argentinski australs (ARA)',
    ),
    'ARL' => 
    array (
      'name-single' => 'argentinski pezos lej',
      'name-multiple' => 'argentinski pezos lej',
    ),
    'ARM' => 
    array (
      'name-single' => 'argentinski pezo monedo nacional',
      'name-multiple' => 'argentinskih pezosa moneda nacional',
    ),
    'ARP' => 
    array (
      'name' => 'Argentinski pezo (1983-1985) (ARP)',
      'name-single' => 'argentinski pezo (ARP)',
      'name-multiple' => 'argentinskih pezosa (ARP)',
    ),
    'ARS' => 
    array (
      'name' => 'Argentinski pezo',
      'name-single' => 'argentinski pezos',
      'name-multiple' => 'argentinskih pezosa',
    ),
    'ATS' => 
    array (
      'name' => 'Austrijski šiling',
      'name-single' => 'austrijski šiling',
      'name-multiple' => 'austrijskih šilinga',
    ),
    'AWG' => 
    array (
      'name' => 'Arubijski florin (AWG)',
      'name-single' => 'arubanski florin',
      'name-multiple' => 'arubanskih florina',
    ),
    'AZM' => 
    array (
      'name' => 'Azerbejdžanski manat (AZM)',
      'name-single' => 'azerbejdžanski manat (AZM)',
      'name-multiple' => 'azerbejdžanskih manata (AZM)',
    ),
    'AZN' => 
    array (
      'name' => 'Azerbejdžanski manat (AZN)',
      'name-single' => 'azerbejdžanski manat',
      'name-multiple' => 'azerbejdžanskih manata',
    ),
    'BAD' => 
    array (
      'name' => 'Bosansko-Hercegovački dinar',
      'name-single' => 'bosansko-hercegovački dinar',
      'name-multiple' => 'bosansko-hercegovačkih dinara',
    ),
    'BAN' => 
    array (
      'name-single' => 'bosansko-hercegovački novi dinar',
      'name-multiple' => 'bosansko-hercegovački novi dinar',
    ),
    'BBD' => 
    array (
      'name' => 'Barbadoski dolar (BBD)',
      'name-single' => 'barbadoški dolar',
      'name-multiple' => 'barbadoških dolara',
    ),
    'BDT' => 
    array (
      'name' => 'Bangladeška taka (BDT)',
      'name-single' => 'bangladeška taka',
      'name-multiple' => 'bangladeških taka',
    ),
    'BEC' => 
    array (
      'name' => 'Belgijski frank (konvertibilni) (BEC)',
      'name-single' => 'belgijski franak (konvertibilni)',
      'name-multiple' => 'belgijskih franaka BEC (konvertibilnih)',
    ),
    'BEF' => 
    array (
      'name' => 'Belgijski franak',
      'name-single' => 'belgijski franak',
      'name-multiple' => 'belgijskih franaka',
    ),
    'BEL' => 
    array (
      'name' => 'Belgijski frank (finansijski) (BEL)',
      'name-single' => 'belgijski franak (finansijski)',
      'name-multiple' => 'belgijskih franaka BEL (finansijskih)',
    ),
    'BGL' => 
    array (
      'name' => 'Bugarski tvrdi lev (BGL)',
      'name-single' => 'bugarski tvrdi lev',
      'name-multiple' => 'bugarskih tvrdih leva',
    ),
    'BGM' => 
    array (
      'name-single' => 'bugarski socijalistički lev',
      'name-multiple' => 'bugarskih socijalističkih leva',
    ),
    'BGN' => 
    array (
      'name' => 'Bugarski lev',
      'name-single' => 'bugarski lev',
      'name-multiple' => 'Bugarskih leva',
    ),
    'BGO' => 
    array (
      'name-single' => 'stari bugarski lev',
      'name-multiple' => 'starih bugarskih leva',
    ),
    'BHD' => 
    array (
      'name' => 'Bahreinski dinar (BHD)',
      'name-single' => 'bahreinskih dinara',
      'name-multiple' => 'bahreinskih dinara',
    ),
    'BIF' => 
    array (
      'name' => 'Burundski franak (BIF)',
      'name-single' => 'burundski franak',
      'name-multiple' => 'бурундски франци',
    ),
    'BMD' => 
    array (
      'name' => 'Bermudski dolar (BMD)',
      'name-single' => 'bermudski dolar',
      'name-multiple' => 'bermudskih dolara',
    ),
    'BND' => 
    array (
      'name' => 'Brunejski dolar',
      'name-single' => 'brunejski dolar',
      'name-multiple' => 'brunejskih dolara',
    ),
    'BOB' => 
    array (
      'name' => 'Bolivijski boliviano',
      'name-single' => 'bolivijski boliviano',
      'name-multiple' => 'bolivijskih boliviana',
    ),
    'BOL' => 
    array (
      'name-single' => 'stari bolivijski bolivijano',
      'name-multiple' => 'starih bolivijskih bolivijana',
    ),
    'BOP' => 
    array (
      'name' => 'Bolivijski pezo (BOP)',
      'name-single' => 'bolivijski pezo',
      'name-multiple' => 'bolivijskih pezosa',
    ),
    'BOV' => 
    array (
      'name' => 'Bolivijski mvdol (BOV)',
      'name-single' => 'bolivijski mvdol',
      'name-multiple' => 'bolivijskih mvdola',
    ),
    'BRB' => 
    array (
      'name' => 'Brazilski kruzeiro novo (1967-1986) (BRB)',
      'name-single' => 'brazilski novi kruzeiro (BRB)',
      'name-multiple' => 'brazilskih novih kruzeira (BRB)',
    ),
    'BRC' => 
    array (
      'name' => 'Brazilski kruzado (BRC)',
      'name-single' => 'brazilskih kruzado',
      'name-multiple' => 'brazilskih kruzadosa',
    ),
    'BRE' => 
    array (
      'name' => 'Brazilski kruzeiro (1990-1993) (BRE)',
      'name-single' => 'brazilski kruzeiro (BRE)',
      'name-multiple' => 'brazilskih kruzeira (BRE)',
    ),
    'BRN' => 
    array (
      'name' => 'Brazilski kruzado novo (BRN)',
      'name-single' => 'brazilski novi kruzado',
      'name-multiple' => 'brazilskih novih kruzada',
    ),
    'BRR' => 
    array (
      'name' => 'Brazilski kruzeiro (BRR)',
      'name-single' => 'brazilski kruzeiro',
      'name-multiple' => 'brazilskih kruzeira',
    ),
    'BRZ' => 
    array (
      'name-single' => 'stari brazilski kruzeiro',
      'name-multiple' => 'stari brazilski kruzeirosi',
    ),
    'BSD' => 
    array (
      'name' => 'Bahamski dolar (BSD)',
      'name-single' => 'bahamski dolar',
      'name-multiple' => 'bahamskih dolara',
    ),
    'BTN' => 
    array (
      'name' => 'Butanski ngultrum (BTN)',
      'name-single' => 'butanski ngultrum',
      'name-multiple' => 'butanski ngultruma',
    ),
    'BUK' => 
    array (
      'name' => 'Burmanski kjat (BUK)',
      'name-single' => 'burmanski kjat',
      'name-multiple' => 'burmanskih kjata',
    ),
    'BWP' => 
    array (
      'name' => 'Botsvanska pula (BWP)',
      'name-single' => 'bocvanska pula',
      'name-multiple' => 'bocvanskih pula',
    ),
    'BYB' => 
    array (
      'name' => 'Beloruska nova rublja (1994-1999) (BYB)',
      'name-single' => 'beloruska nova rublja (BYB)',
      'name-multiple' => 'beloruskih novih rublji (BYB)',
    ),
    'BYR' => 
    array (
      'name' => 'Beloruska rublja (BYR)',
      'name-single' => 'beloruska rublja',
      'name-multiple' => 'bjeloruske rublje',
    ),
    'BZD' => 
    array (
      'name' => 'Belize dolar (BZD)',
      'name-single' => 'belizeanski dolar',
      'name-multiple' => 'belizeanskih dolara',
    ),
    'CDF' => 
    array (
      'name' => 'Kongolski franak (CDF)',
      'name-single' => 'kongolski franak',
      'name-multiple' => 'kongolskih franaka',
    ),
    'CHE' => 
    array (
      'name' => 'WIR Evro (CHE)',
      'name-single' => 'WIR evro',
      'name-multiple' => 'WIR evra',
    ),
    'CHF' => 
    array (
      'name' => 'Švajcarski franak',
      'name-single' => 'švajcarski franak',
      'name-multiple' => 'švajcarskih franaka',
    ),
    'CHW' => 
    array (
      'name' => 'WIR franak (CHW)',
      'name-single' => 'WIR franak',
      'name-multiple' => 'WIR franak',
    ),
    'CLE' => 
    array (
      'name-single' => 'čileanski eskudo',
      'name-multiple' => 'čileanskih eskuda',
    ),
    'CLF' => 
    array (
      'name' => 'Čileanski unidades de fomento (CLF)',
      'name-single' => 'čileanski unidades de fomentos',
      'name-multiple' => 'čileanski unidades de fomentos',
    ),
    'CLP' => 
    array (
      'name' => 'Čileanski pezo',
      'name-single' => 'čileanski pezos',
      'name-multiple' => 'čileanski pezos',
    ),
    'CNX' => 
    array (
      'name-single' => 'dolar kineske narodne banke',
      'name-multiple' => 'dolar kineske narodne banke',
    ),
    'COP' => 
    array (
      'name' => 'Kolumbijski pezo',
      'name-single' => 'kolumbijski pezo',
      'name-multiple' => 'kolumbijski pezosi',
    ),
    'COU' => 
    array (
      'name' => 'Unidad de Valor real (COU)',
      'name-single' => 'unidad de valor real',
      'name-multiple' => 'unidad de valor real',
    ),
    'CRC' => 
    array (
      'name' => 'Kostarikanski kolon (CRC)',
      'name-single' => 'kostarikanski kolon',
      'name-multiple' => 'костарикански колони',
    ),
    'CSD' => 
    array (
      'name' => 'Stari srpski dinar',
      'name-single' => 'stari srpski dinar',
      'name-multiple' => 'starih srpskih dinara',
    ),
    'CSK' => 
    array (
      'name' => 'Čehoslovačka tvrda koruna (CSK)',
      'name-single' => 'čehoslovačka tvrda kruna',
      'name-multiple' => 'čehoslovačka tvrda kruna',
    ),
    'CUC' => 
    array (
      'name-single' => 'kubanski konvertibilni pezo',
      'name-multiple' => 'kubanskih konvertibilnih pezosa',
    ),
    'CUP' => 
    array (
      'name' => 'Kubanski pezo (CUP)',
      'name-single' => 'kubanski pezos',
      'name-multiple' => 'kubanskih pezosa',
    ),
    'CVE' => 
    array (
      'name' => 'Kejp verdanški eskudo (CVE)',
      'name-single' => 'zelenortski eskudo',
      'name-multiple' => 'zelenortskih eskuda',
    ),
    'CYP' => 
    array (
      'name' => 'Kipratska funta (CYP)',
      'name-single' => 'kiparska funta',
      'name-multiple' => 'kiparska funta',
    ),
    'DDM' => 
    array (
      'name' => 'Istočnoevropska marka (DDM)',
      'name-single' => 'istočnonemačka marka',
      'name-multiple' => 'istočnonemačkih maraka',
    ),
    'DEM' => 
    array (
      'name' => 'Nemačka marka',
      'name-single' => 'nemačka marka',
      'name-multiple' => 'nemačkih maraka',
    ),
    'DJF' => 
    array (
      'name' => 'Džibutanski franak (DJF)',
      'name-single' => 'džibutski franak',
      'name-multiple' => 'džibutski franak',
    ),
    'DKK' => 
    array (
      'name' => 'Danska kruna',
      'name-single' => 'danska kruna',
      'name-multiple' => 'danskih kruna',
    ),
    'DOP' => 
    array (
      'name' => 'DOminikanski pezo (DOP)',
      'name-single' => 'dominikanski pezo',
      'name-multiple' => 'dominikanskih pezosa',
    ),
    'DZD' => 
    array (
      'name' => 'Alžirski dinar (DZD)',
      'name-single' => 'alžirski dinar',
      'name-multiple' => 'alžirskih dinara',
    ),
    'ECS' => 
    array (
      'name' => 'Ekvadorijski sukr (ECS)',
      'name-single' => 'ekvadorska sakra',
      'name-multiple' => 'ekvadorskih sakra',
    ),
    'ECV' => 
    array (
      'name' => 'Ekvadorski unidad de valor konstantin (UVC)',
      'name-single' => 'ekvadorski unidad de valor constante (UVC)',
      'name-multiple' => 'ekvadorski unidad de valor constante (UVC)',
    ),
    'EEK' => 
    array (
      'name' => 'Estonska kruna',
      'name-single' => 'estonska kruna',
      'name-multiple' => 'estonskih kruna',
    ),
    'EGP' => 
    array (
      'name' => 'Egipatska funta',
      'name-single' => 'egipatska funta',
      'name-multiple' => 'egipatskih funti',
    ),
    'ERN' => 
    array (
      'name' => 'Eritreanska nakfa (ERN)',
      'name-single' => 'eritrejska nakfa',
      'name-multiple' => 'eritrejska nakfa',
    ),
    'ESA' => 
    array (
      'name' => 'Španska pezeta (račun) ESA',
      'name-single' => 'španska pezeta (A račun)',
      'name-multiple' => 'španska pezeta (A račun)',
    ),
    'ESB' => 
    array (
      'name' => 'Španska pezeta (konvertibilni račun) (ESB)',
      'name-single' => 'španska pezeta (konvertibilan račun)',
      'name-multiple' => 'španska pezeta (konvertibilan račun)',
    ),
    'ESP' => 
    array (
      'name' => 'Španska pezeta',
      'name-single' => 'španskа pezetа',
      'name-multiple' => 'španskе pezetе',
    ),
    'ETB' => 
    array (
      'name' => 'Etopijski bir (ETB)',
      'name-single' => 'etiopijski bir',
      'name-multiple' => 'etiopijskih bira',
    ),
    'FIM' => 
    array (
      'name' => 'Finska marka',
      'name-single' => 'finska marka',
      'name-multiple' => 'finskih maraka',
    ),
    'FJD' => 
    array (
      'name' => 'Fidži dolar',
      'name-single' => 'fidži dolar',
      'name-multiple' => 'fidži dolara',
    ),
    'FKP' => 
    array (
      'name' => 'Foklandska ostrva funta (FKP)',
      'name-single' => 'folklandska funta',
      'name-multiple' => 'folklandska funta',
    ),
    'FRF' => 
    array (
      'name' => 'Francuski franak',
      'name-single' => 'francuski franak',
      'name-multiple' => 'francuskih franaka',
    ),
    'GEK' => 
    array (
      'name' => 'Gruzijski kupon larit (GEK)',
      'name-single' => 'gruzijski kupon larit',
      'name-multiple' => 'gruzijskih kupon larita',
    ),
    'GEL' => 
    array (
      'name' => 'Džordžijski lari (GEL)',
      'name-single' => 'gruzijski laris',
      'name-multiple' => 'gruzijskih larisa',
    ),
    'GHC' => 
    array (
      'name' => 'Ganijski cedi (1979-2007) (GHC)',
      'name-single' => 'ganski ced (GHC)',
      'name-multiple' => 'ganskih ceda (GHC)',
    ),
    'GHS' => 
    array (
      'name' => 'Ganijski cedi (GHS)',
      'name-single' => 'ganski cedi',
      'name-multiple' => 'ganski cedi',
    ),
    'GIP' => 
    array (
      'name' => 'Gibraltarska funta (GIP)',
      'name-single' => 'gibraltarska funta',
      'name-multiple' => 'gibraltarska funta',
    ),
    'GMD' => 
    array (
      'name' => 'Gambijski dalasi (GMD)',
      'name-single' => 'gambijski dalas',
      'name-multiple' => 'gambijskih dalasa',
    ),
    'GNF' => 
    array (
      'name' => 'Gvinejski franak (GNF)',
      'name-single' => 'gvinejski franak',
      'name-multiple' => 'gvinejski franak',
    ),
    'GNS' => 
    array (
      'name' => 'Gvinejski sili (GNS)',
      'name-single' => 'gvinejski sili',
      'name-multiple' => 'gvinejski silij',
    ),
    'GQE' => 
    array (
      'name' => 'Evatorijalna gvineja ekvele (GQE)',
      'name-single' => 'evatorijаlno-gvinejski ekvele',
      'name-multiple' => 'evatorijаlno-gvinejskih ekvelа',
    ),
    'GRD' => 
    array (
      'name' => 'Drahma',
      'name-single' => 'grčka drahma',
      'name-multiple' => 'grčkih drahmi',
    ),
    'GTQ' => 
    array (
      'name' => 'Gvatemalski kvetzal (GTQ)',
      'name-single' => 'gvatemalski kvecal',
      'name-multiple' => 'gvatemalskih kvecala',
    ),
    'GWE' => 
    array (
      'name' => 'Portugalska Gvineja eskudo (GWE)',
      'name-single' => 'portugalsko-gvinejski eskudo',
      'name-multiple' => 'portugalsko-gvinejski eskudo',
    ),
    'GWP' => 
    array (
      'name' => 'Gvineja bisao pezo (GWP)',
      'name-single' => 'gvinejа-bisaoški pezo',
      'name-multiple' => 'gvinejsko-bisaoski pezos',
    ),
    'GYD' => 
    array (
      'name' => 'Guajanski dolar (GYD)',
      'name-single' => 'gvajanski dolar',
      'name-multiple' => 'gvajanski dolari',
    ),
    'HNL' => 
    array (
      'name' => 'Honduranska lempira (HNL)',
      'name-single' => 'honduraški lempir',
      'name-multiple' => 'honduraških lempirа',
    ),
    'HRD' => 
    array (
      'name' => 'Hrvatski dinar',
      'name-single' => 'hrvatski dinar',
      'name-multiple' => 'hrvatskih dinara',
    ),
    'HRK' => 
    array (
      'name' => 'Hrvatska kuna',
      'name-single' => 'hrvatska kuna',
      'name-multiple' => 'hrvatskih kuna',
    ),
    'HTG' => 
    array (
      'name' => 'Haitski gurd (HTG)',
      'name-single' => 'haićanski gourd',
      'name-multiple' => 'haićanski gourd',
    ),
    'HUF' => 
    array (
      'name' => 'Mađarska forinta',
      'name-single' => 'mađarska forinta',
      'name-multiple' => 'mađarske forinte',
    ),
    'IDR' => 
    array (
      'name' => 'Indonezijska rupiah',
      'name-single' => 'indonežanska rupija',
      'name-multiple' => 'indonežanske rupije',
    ),
    'IEP' => 
    array (
      'name' => 'Irska funta',
      'name-single' => 'irska funta',
      'name-multiple' => 'irskih funti',
    ),
    'ILP' => 
    array (
      'name' => 'Izraelska funta (ILP)',
      'name-single' => 'izraelska funta',
      'name-multiple' => 'izraelska funta',
    ),
    'ILR' => 
    array (
      'name' => 'stari izraelski šekeli',
      'name-single' => 'stari izraelski šekeli',
      'name-multiple' => 'stari izraelski šekeli',
    ),
    'IQD' => 
    array (
      'name' => 'Irački dinar (IQD)',
      'name-single' => 'irački dinar',
      'name-multiple' => 'irački dinari',
    ),
    'IRR' => 
    array (
      'name' => 'Iranijski rial (IRR)',
      'name-single' => 'iranski rijal',
      'name-multiple' => 'iranski rijali',
    ),
    'ISJ' => 
    array (
      'name' => 'stara islandska kruna',
      'name-single' => 'stara islandska kruna',
      'name-multiple' => 'stara islandska kruna',
    ),
    'ISK' => 
    array (
      'name' => 'Islandska kruna (ISK)',
      'name-single' => 'islandska kruna',
      'name-multiple' => 'islandska kruna',
    ),
    'ITL' => 
    array (
      'name' => 'Italijanska lira',
      'name-single' => 'italijanska lira',
      'name-multiple' => 'italijanske lire',
    ),
    'JMD' => 
    array (
      'name' => 'Jamajski dolar (JMD)',
      'name-single' => 'jamajski dolar',
      'name-multiple' => 'jamajskih dolara',
    ),
    'JOD' => 
    array (
      'name' => 'Jordanski dinar (JOD)',
      'name-single' => 'ordanskih dinara',
      'name-multiple' => 'ordanskih dinara',
    ),
    'KES' => 
    array (
      'name' => 'Kenijski šiling',
      'name-single' => 'kenijski šiling',
      'name-multiple' => 'kenijskih šilinga',
    ),
    'KGS' => 
    array (
      'name' => 'Kirgistanski som (KGS)',
      'name-single' => 'kirgistanski som',
      'name-multiple' => 'kirgijski som',
    ),
    'KHR' => 
    array (
      'name' => 'Kambodžijski riel (KHR)',
      'name-single' => 'kambodžanski rijal',
      'name-multiple' => 'kambodžanskih rijela',
    ),
    'KMF' => 
    array (
      'name' => 'Komoranski franak (KMF)',
      'name-single' => 'komoranski franak',
      'name-multiple' => 'komoranski franci',
    ),
    'KPW' => 
    array (
      'name' => 'Severnokorejski von (KPW)',
      'name-single' => 'severnokorejski von',
      'name-multiple' => 'severnokorejski von',
    ),
    'KRH' => 
    array (
      'name-single' => 'južnokorejski hvan',
      'name-multiple' => 'južnokorejskih hvana',
    ),
    'KRO' => 
    array (
      'name-single' => 'stari južnokorejski von',
      'name-multiple' => 'starih južnokorejskih vona',
    ),
    'KWD' => 
    array (
      'name' => 'Kuvajtski dinar',
      'name-single' => 'kuvajtskih dinara',
      'name-multiple' => 'kuvajtskih dinara',
    ),
    'KYD' => 
    array (
      'name' => 'Kajmanska ostrva dolar (KYD)',
      'name-single' => 'kajmanski dolar',
      'name-multiple' => 'kajmanski dolar',
    ),
    'KZT' => 
    array (
      'name' => 'Kazahstanski tendž (JZT)',
      'name-single' => 'kazahstanska tendža',
      'name-multiple' => 'kazahstanskih tendži',
    ),
    'LAK' => 
    array (
      'name' => 'Laoški kip (LAK)',
      'name-single' => 'laoški kip',
      'name-multiple' => 'laoški kipovi',
    ),
    'LBP' => 
    array (
      'name' => 'Lebanska funta (LBR)',
      'name-single' => 'lebanska funta',
      'name-multiple' => 'lebanske funte',
    ),
    'LKR' => 
    array (
      'name' => 'Šrilankanski rupi (LKR)',
      'name-single' => 'šrilankanska rupija',
      'name-multiple' => 'šrilankanska rupija',
    ),
    'LRD' => 
    array (
      'name' => 'Liberijski dolar (LRD)',
      'name-single' => 'liberijski dolar',
      'name-multiple' => 'liberijskih dolara',
    ),
    'LSL' => 
    array (
      'name' => 'Lesotski loti (LSL)',
      'name-single' => 'lesotski lotis',
      'name-multiple' => 'lesotskih lotisa',
    ),
    'LTL' => 
    array (
      'name' => 'Litvanski litas',
      'name-single' => 'litvanska lita',
      'name-multiple' => 'litvanskih lita',
    ),
    'LTT' => 
    array (
      'name' => 'Litvanski talonas (LTT)',
      'name-single' => 'litvanska talona',
      'name-multiple' => 'litvanskih talona',
    ),
    'LUC' => 
    array (
      'name' => 'Luksemburški konvertibilni franak (LUC)',
      'name-single' => 'luksemburški konvertibilni franak',
      'name-multiple' => 'luksemburški konvertibilni franak',
    ),
    'LUF' => 
    array (
      'name' => 'Luksemburški franak',
      'name-single' => 'luksemburški franak',
      'name-multiple' => 'luksemburški franci',
    ),
    'LUL' => 
    array (
      'name' => 'Luksemburški finansijski franak (LUL)',
      'name-single' => 'luksemburški financijski franak',
      'name-multiple' => 'luksemburški financijski franak',
    ),
    'LVL' => 
    array (
      'name' => 'Latvijski lats (LVL)',
      'name-single' => 'latvijski lat',
      'name-multiple' => 'latvijski lat',
    ),
    'LVR' => 
    array (
      'name' => 'Latvijska rublja (LVR)',
      'name-single' => 'latvijska rublja',
      'name-multiple' => 'latvijska rublja',
    ),
    'LYD' => 
    array (
      'name' => 'Libijski dinar',
      'name-single' => 'Libijskih dinara',
      'name-multiple' => 'libijskih dinara',
    ),
    'MAD' => 
    array (
      'name' => 'Marokanski dirham',
      'name-single' => 'marokanska dirama',
      'name-multiple' => 'marokanskih dirama',
    ),
    'MAF' => 
    array (
      'name' => 'Marokanski franak (MAF)',
      'name-single' => 'marokanski franak',
      'name-multiple' => 'marokanski franak',
    ),
    'MCF' => 
    array (
      'name-single' => 'monegaskaški franak',
      'name-multiple' => 'monegaskaških franaka',
    ),
    'MDC' => 
    array (
      'name-single' => 'moldovanski kupon',
      'name-multiple' => 'moldovanskih kupona',
    ),
    'MDL' => 
    array (
      'name' => 'Moldovski lju (MDL)',
      'name-single' => 'moldavski lej',
      'name-multiple' => 'moldavski lej',
    ),
    'MGA' => 
    array (
      'name' => 'Malagasijski ariari (MGA)',
      'name-single' => 'madagaskarski ariarij',
      'name-multiple' => 'madagaskarski ariariji',
    ),
    'MGF' => 
    array (
      'name' => 'Malagasijski franak (MGF)',
      'name-single' => 'madagaskarski franak',
      'name-multiple' => 'малагашајски франци',
    ),
    'MKD' => 
    array (
      'name' => 'Makedonski denar',
      'name-single' => 'Makedonski denar',
      'name-multiple' => 'makedonskih dinara',
    ),
    'MKN' => 
    array (
      'name-single' => 'stari makedonski denar',
      'name-multiple' => 'starih makedonskih denara',
    ),
    'MLF' => 
    array (
      'name' => 'Malijanski franak (MLF)',
      'name-single' => 'malijski franak',
      'name-multiple' => 'malijski franak',
    ),
    'MMK' => 
    array (
      'name' => 'Mjanmaški kjat (MMK)',
      'name-single' => 'mjanmarski kjat',
      'name-multiple' => 'mjanmarski kjati',
    ),
    'MNT' => 
    array (
      'name' => 'Mongolski tugrik (MNT)',
      'name-single' => 'mongolski tugrik',
      'name-multiple' => 'mongolski tugrici',
    ),
    'MOP' => 
    array (
      'name' => 'Makaniška pataka (MOP)',
      'name-single' => 'makaneški patak',
      'name-multiple' => 'makaneški patak',
    ),
    'MRO' => 
    array (
      'name' => 'Mauritanijska ugvija',
      'name-single' => 'mauritanijska ouguja',
      'name-multiple' => 'mauritanijske ouguje',
    ),
    'MTL' => 
    array (
      'name' => 'Malteška lira',
      'name-single' => 'malteška lira',
      'name-multiple' => 'malteških lira',
    ),
    'MTP' => 
    array (
      'name' => 'Malteška funta (MTP)',
      'name-single' => 'malteška funta',
      'name-multiple' => 'malteška funta',
    ),
    'MUR' => 
    array (
      'name' => 'Mauricijska ruplja (MUR)',
      'name-single' => 'mauricijska rupija',
      'name-multiple' => 'mauricijske rupije',
    ),
    'MVR' => 
    array (
      'name' => 'Maldivijska rufija (MVR)',
      'name-single' => 'maldivijska rufija',
      'name-multiple' => 'maldivijska rufija',
    ),
    'MWK' => 
    array (
      'name' => 'Malavijska kvača (MWK)',
      'name-single' => 'malavijska kvača',
      'name-multiple' => 'malavijska kvača',
    ),
    'MXP' => 
    array (
      'name' => 'Meksijski srebrno pezo (1861-1992) (MXP)',
      'name-single' => 'meksički srebrni pezos (MXP)',
      'name-multiple' => 'meksički srebrni pezos (MXP)',
    ),
    'MXV' => 
    array (
      'name' => 'Meksijski unidad de inverzion (MXV)',
      'name-single' => 'meksički unidads de inversion (UDI)',
      'name-multiple' => 'meksički unidads de inversion (UDI)',
    ),
    'MYR' => 
    array (
      'name' => 'Malezijski ringit',
      'name-single' => 'malezijski ringit',
      'name-multiple' => 'malezijskih ringita',
    ),
    'MZE' => 
    array (
      'name' => 'Mozambijski eskudo (MZE)',
      'name-single' => 'mozambijski eskudo',
      'name-multiple' => 'mozambijski eskudo',
    ),
    'MZM' => 
    array (
      'name' => 'Stari mozambijski metikal (MZM)',
      'name-single' => 'stari mozambijski metikal',
      'name-multiple' => 'stari mozambijski metikal',
    ),
    'MZN' => 
    array (
      'name' => 'Mozambijski metikal (MZN)',
      'name-single' => 'mozambijski metikal',
      'name-multiple' => 'mozambijski metikal',
    ),
    'NAD' => 
    array (
      'name' => 'Nambijski dolar (NAD)',
      'name-single' => 'namibijski dolar',
      'name-multiple' => 'namibijski dolar',
    ),
    'NGN' => 
    array (
      'name' => 'Nigerijska naira (NGN)',
      'name-single' => 'nigerijski nair',
      'name-multiple' => 'nigerijski nair',
    ),
    'NIC' => 
    array (
      'name' => 'Nikaragvanška kordoba (NIC)',
      'name-single' => 'nikaragvanska kordoba',
      'name-multiple' => 'nikaragvanska kordoba',
    ),
    'NIO' => 
    array (
      'name' => 'Nikaragvanška kordoba oro',
      'name-single' => 'nikaragvanska zlatna kordoba',
      'name-multiple' => 'nikaragvanska zlatna kordoba',
    ),
    'NLG' => 
    array (
      'name' => 'Holandski gulden',
      'name-single' => 'holandski gulden',
      'name-multiple' => 'holandskih guldena',
    ),
    'NOK' => 
    array (
      'name' => 'Norveška kruna',
      'name-single' => 'Norveška kuna',
      'name-multiple' => 'norveških kruna',
    ),
    'NPR' => 
    array (
      'name' => 'Nepalska ruplja (NPR)',
      'name-single' => 'nepalska rupija',
      'name-multiple' => 'nepalska rupija',
    ),
    'OMR' => 
    array (
      'name' => 'Omanski rial (OMR)',
      'name-single' => 'omanski rijal',
      'name-multiple' => 'omanski rijal',
    ),
    'PAB' => 
    array (
      'name' => 'Panamanska balboa (PAB)',
      'name-single' => 'panamska balboa',
      'name-multiple' => 'panamska balboa',
    ),
    'PEI' => 
    array (
      'name' => 'Peruvijski inti (PEI)',
      'name-single' => 'peruanska inta',
      'name-multiple' => 'peruanska inta',
    ),
    'PEN' => 
    array (
      'name' => 'Peruanski nuevo sol',
      'name-single' => 'peruanski nuevo sol',
      'name-multiple' => 'peruanskih nuevo sola',
    ),
    'PES' => 
    array (
      'name' => 'Peruvijski sol (PES)',
      'name-single' => 'peruanski sol',
      'name-multiple' => 'peruanski sol',
    ),
    'PGK' => 
    array (
      'name' => 'Papua Nova Gvineja kina (PGK)',
      'name-single' => 'kina Papue Nove Gvineje',
      'name-multiple' => 'kina Papue Nove Gvineje',
    ),
    'PHP' => 
    array (
      'name' => 'Filipinski peso',
      'name-single' => 'filipinski pezo',
      'name-multiple' => 'filipinskih pezosa',
    ),
    'PKR' => 
    array (
      'name' => 'Pakistanski rupi',
      'name-single' => 'pakistanska rupija',
      'name-multiple' => 'pakistanske rupije',
    ),
    'PLZ' => 
    array (
      'name' => 'Poljski zloti (1950-1995) (PLZ)',
      'name-single' => 'poljski zlot (PLZ)',
      'name-multiple' => 'poljski zlot (PLZ)',
    ),
    'PTE' => 
    array (
      'name' => 'Portugalski eskudo',
      'name-single' => 'portugalski eskudo',
      'name-multiple' => 'portugalskih eskuda',
    ),
    'PYG' => 
    array (
      'name' => 'Paragvajski guarni (PYG)',
      'name-single' => 'paragvajski gvarani',
      'name-multiple' => 'paragvajski gvarani',
    ),
    'QAR' => 
    array (
      'name' => 'Katarski rial (QAR)',
      'name-single' => 'katarski rijal',
      'name-multiple' => 'katarski rijal',
    ),
    'RHD' => 
    array (
      'name' => 'Rodizijski dolar (RHD)',
      'name-single' => 'rodezijski dolar',
      'name-multiple' => 'rodezijski dolar',
    ),
    'ROL' => 
    array (
      'name' => 'Stari romanski lju (ROL)',
      'name-single' => 'stari rumunjski lej',
      'name-multiple' => 'stari rumunjski lej',
    ),
    'RON' => 
    array (
      'name' => 'Rumunski leu',
      'name-single' => 'rumunski leu',
      'name-multiple' => 'rumunskih leua',
    ),
    'RUB' => 
    array (
      'name' => 'Ruska rublja',
      'name-single' => 'ruska rublja',
      'name-multiple' => 'ruskih rublji',
    ),
    'RUR' => 
    array (
      'name' => 'Ruska rublja (1991-1998)',
      'name-single' => 'ruska rublja (RUR)',
      'name-multiple' => 'ruskih rublji (RUR)',
    ),
    'RWF' => 
    array (
      'name' => 'Ruandski franak (RWF)',
      'name-single' => 'ruandski franak',
      'name-multiple' => 'ruandski franci',
    ),
    'SAR' => 
    array (
      'name' => 'Saudijski rijal (SAR)',
      'name-single' => 'saudijski rijal',
      'name-multiple' => 'saudijski rijal',
    ),
    'SBD' => 
    array (
      'name' => 'Solomonska ostrva dolar (SBD)',
      'name-single' => 'solomonskoostrvski dolar',
      'name-multiple' => 'solomonskoostrvski dolar',
    ),
    'SCR' => 
    array (
      'name' => 'Sejšelski rupi (SCR)',
      'name-single' => 'sejšelska rupija',
      'name-multiple' => 'sejšelska rupija',
    ),
    'SDD' => 
    array (
      'name' => 'STari sudanski dinar (SDD)',
      'name-single' => 'stari sudanski dinar',
      'name-multiple' => 'stari sudanski dinar',
    ),
    'SDG' => 
    array (
      'name' => 'Sudanska funta (SDG)',
      'name-single' => 'sudanska funta',
      'name-multiple' => 'sudanska funta',
    ),
    'SDP' => 
    array (
      'name' => 'Stara sudanska funta (SDP)',
      'name-single' => 'stara sudanska funta',
      'name-multiple' => 'stara sudanska funta',
    ),
    'SEK' => 
    array (
      'name' => 'Švedska kruna',
      'name-single' => 'švedska kruna',
      'name-multiple' => 'švedskih kruna',
    ),
    'SGD' => 
    array (
      'name' => 'Singapurski dolar',
      'name-single' => 'singapurški dolar',
      'name-multiple' => 'singapurških dolara',
    ),
    'SHP' => 
    array (
      'name' => 'Sv. Helenska funta (SHP)',
      'name-single' => 'sv. jelenska funta',
      'name-multiple' => 'sv. jelenska funta',
    ),
    'SIT' => 
    array (
      'name' => 'Slovenski tolar',
      'name-single' => 'slovenački tolar',
      'name-multiple' => 'slovenačkih tolara',
    ),
    'SKK' => 
    array (
      'name' => 'Slovačka kruna',
      'name-single' => 'slovačka kuna',
      'name-multiple' => 'slovačkih kuna',
    ),
    'SLL' => 
    array (
      'name' => 'Sijeraleonski leone (SLL)',
      'name-single' => 'sijeraleonska leona',
      'name-multiple' => 'sijeraleonske leone',
    ),
    'SOS' => 
    array (
      'name' => 'Somalijski šiling (SOS)',
      'name-single' => 'somalijski šiling',
      'name-multiple' => 'somalijski šilinzi',
    ),
    'SRD' => 
    array (
      'name' => 'Surinamski dolar (SRD)',
      'name-single' => 'surinamski dolar',
      'name-multiple' => 'surinamski dolar',
    ),
    'SRG' => 
    array (
      'name' => 'Surinamski gilder (SRG)',
      'name-single' => 'surinamski gulden',
      'name-multiple' => 'surinamski gulden',
    ),
    'STD' => 
    array (
      'name' => 'Sao Tome i Principe dobra (STD)',
      'name-single' => 'dobra Sao Toma i Principa',
      'name-multiple' => 'dobra Sao Toma i Principa',
    ),
    'SUR' => 
    array (
      'name' => 'Sovjetska rublja (SUR)',
      'name-single' => 'sovjetska rublja',
      'name-multiple' => 'sovjetske rublje',
    ),
    'SVC' => 
    array (
      'name' => 'Salvadorski kolon (SVC)',
      'name-single' => 'salvadorski kolon',
      'name-multiple' => 'salvadorski kolon',
    ),
    'SYP' => 
    array (
      'name' => 'Sirijska funta (SYP)',
      'name-single' => 'sirijska funta',
      'name-multiple' => 'sirijske funtie',
    ),
    'SZL' => 
    array (
      'name' => 'Švazi lilangeni (SZL)',
      'name-single' => 'svazi lilangena',
      'name-multiple' => 'svazi lilangena',
    ),
    'TJR' => 
    array (
      'name' => 'Tadžakistanska rublja (SYR)',
      'name-single' => 'tadžikistanska rublja',
      'name-multiple' => 'tadžikistanska rublja',
    ),
    'TJS' => 
    array (
      'name' => 'Tadžikistanski somoni (TJS)',
      'name-single' => 'tadžikistanski somon',
      'name-multiple' => 'tadžikistanski somon',
    ),
    'TMM' => 
    array (
      'name' => 'Turkmenistanski manat (TMM)',
      'name-single' => 'turkmenistanski manat',
      'name-multiple' => 'turkmenistanski manat',
    ),
    'TMT' => 
    array (
      'name' => 'Туркменистански манат',
      'name-single' => 'turkmenistanski novi manat',
      'name-multiple' => 'turkmenistanskih novih manata',
    ),
    'TND' => 
    array (
      'name' => 'Tunizijski dinar (TND)',
      'name-single' => 'tunizijski dinar',
      'name-multiple' => 'tunizijski dinar',
    ),
    'TOP' => 
    array (
      'name' => 'Tongška Paʻanga (TOP)',
      'name-single' => 'tongaška pa\'anga',
      'name-multiple' => 'tongaška pa\'anga',
    ),
    'TPE' => 
    array (
      'name' => 'Timorški eskudo (TPE)',
      'name-single' => 'timorski eskudo',
      'name-multiple' => 'timorski eskudo',
    ),
    'TRL' => 
    array (
      'name' => 'Stara turska lira (TRL)',
      'name-single' => 'stara turska lira',
      'name-multiple' => 'stara turska lira',
    ),
    'TTD' => 
    array (
      'name' => 'Trinidad i Tobago dolar (TTD)',
      'name-single' => 'trinidadtobaški dolar',
      'name-multiple' => 'trinidadtobaški dolar',
    ),
    'TZS' => 
    array (
      'name' => 'Tanzijski šiling (TZS)',
      'name-single' => 'tanzanijski šiling',
      'name-multiple' => 'tanzanijski šilinzi',
    ),
    'UAH' => 
    array (
      'name' => 'Ukrajinska hrivnja',
      'name-single' => 'ukrajinska hrivnja',
      'name-multiple' => 'ukrajinskih hrivnji',
    ),
    'UAK' => 
    array (
      'name' => 'Ukrajinski karbovaneti (UAK)',
      'name-single' => 'ukrajinski karbovantsiv',
      'name-multiple' => 'ukrajinski karbovantsiv',
    ),
    'UGS' => 
    array (
      'name' => 'Ugandijski šiling (1966-1987) (UGS)',
      'name-single' => 'ugandski šiling (UGS)',
      'name-multiple' => 'ugandski šiling (UGS)',
    ),
    'UGX' => 
    array (
      'name' => 'Ugandijski šiling (UGX)',
      'name-single' => 'ugandski šiling',
      'name-multiple' => 'ugandski šilinzi',
    ),
    'USN' => 
    array (
      'name' => 'SAD dolar (sledeći dan) (USN)',
      'name-single' => 'američki dolar (sledeći dan)',
      'name-multiple' => 'američki dolar (sledeći dan)',
    ),
    'USS' => 
    array (
      'name' => 'SAD dolar (isti dan) (USS)',
      'name-single' => 'američki dolar (isti dan)',
      'name-multiple' => 'američki dolar (isti dan)',
    ),
    'UYI' => 
    array (
      'name' => 'Urugvajski pezo en unidades indeksades (UYI)',
      'name-single' => 'urugvajski pesos en unidades indexadas',
      'name-multiple' => 'urugvajski pesos en unidades indexadas',
    ),
    'UYP' => 
    array (
      'name' => 'Urugvajski pezo (1975-1993) (UYP)',
      'name-single' => 'urugvajski pezos (UYP)',
      'name-multiple' => 'urugvajski pezos (UYP)',
    ),
    'UYU' => 
    array (
      'name' => 'Urugvajski pezo (UYU)',
      'name-single' => 'urugvajski pezos',
      'name-multiple' => 'urugvajski pezos',
    ),
    'UZS' => 
    array (
      'name' => 'Uzbekistanski som (UZS)',
      'name-single' => 'uzbekistanski som',
      'name-multiple' => 'uzbekistanski som',
    ),
    'VEB' => 
    array (
      'name' => 'Venecuelanski bolivar',
      'name-single' => 'venecuelski bolivar',
      'name-multiple' => 'venecuelskih bolivara',
    ),
    'VEF' => 
    array (
      'name' => 'Venecuelanska bolivija fuerte (VEF)',
      'name-single' => 'venezuelanski bolivar fuertes',
      'name-multiple' => 'venezuelanski bolivar fuertes',
    ),
    'VNN' => 
    array (
      'name-single' => 'stari vijetnamski dong',
      'name-multiple' => 'starih vijetnamskih donga',
    ),
    'VUV' => 
    array (
      'name' => 'Vanatuški vatu (VUV)',
      'name-single' => 'vanuatski vatu',
      'name-multiple' => 'vanuatski vatui',
    ),
    'WST' => 
    array (
      'name' => 'Samoanska tala (WST)',
      'name-single' => 'samoanska tala',
      'name-multiple' => 'samoanska tala',
    ),
    'XAG' => 
    array (
      'name' => 'Srebro (CAG)',
      'name-single' => 'srebro',
      'name-multiple' => 'srebro',
    ),
    'XAU' => 
    array (
      'name' => 'Zlato (XAU)',
      'name-single' => 'zlato',
      'name-multiple' => 'zlato',
    ),
    'XBA' => 
    array (
      'name' => 'Evropska kompozitna jedinica (XBA)',
      'name-single' => 'evropska složena jedinica',
      'name-multiple' => 'evropska složena jedinica',
    ),
    'XBB' => 
    array (
      'name' => 'Evropska novčana jedinica (XBB)',
      'name-single' => 'evropska monetarna jedinica',
      'name-multiple' => 'evropska monetarna jedinica',
    ),
    'XBC' => 
    array (
      'name' => 'Evropska jedinica računa (XBC)',
      'name-single' => 'evropska obračunska jedinica (XBC)',
      'name-multiple' => 'evropska obračunska jedinica (XBC)',
    ),
    'XBD' => 
    array (
      'name' => 'Evropska jedinica računa (XBD)',
      'name-single' => 'evropska obračunska jedinica (XBC',
      'name-multiple' => 'evropska obračunska jedinica (XBC',
    ),
    'XDR' => 
    array (
      'name' => 'Posebna prava (XDR)',
      'name-single' => 'posebno crtaće pravo',
      'name-multiple' => 'posebnih crtaćih prava',
    ),
    'XEU' => 
    array (
      'name' => 'Evropska valutna jedinica (XEU)',
      'name-single' => 'evropska monetarna jedinica (ECU)',
      'name-multiple' => 'evropskih monetarnih jedinica (ECU)',
    ),
    'XFO' => 
    array (
      'name' => 'Francuski zlatni frank (XFO)',
      'name-single' => 'francuski zlatni franak',
      'name-multiple' => 'francuskih zlatnih franaka',
    ),
    'XFU' => 
    array (
      'name' => 'Francuski UIC-frank (XFU)',
      'name-single' => 'francuski UIC-franak',
      'name-multiple' => 'francuskih UIC-franaka',
    ),
    'XPD' => 
    array (
      'name' => 'Paladijum (XPD)',
      'name-single' => 'paladijum',
      'name-multiple' => 'paladijuma',
    ),
    'XPT' => 
    array (
      'name' => 'Platina (XPT)',
      'name-single' => 'platina',
      'name-multiple' => 'platina',
    ),
    'XRE' => 
    array (
      'name' => 'RINET fondovi (XRE)',
      'name-single' => 'RINET fond',
      'name-multiple' => 'RINET fondova',
    ),
    'XTS' => 
    array (
      'name' => 'Kod testirane valute (XTS)',
      'name-single' => 'ispitni kod valute',
      'name-multiple' => 'ispitnih kodova valute',
    ),
    'XXX' => 
    array (
      'name' => 'Nepoznata ili nevažeća valuta',
      'name-single' => 'nepoznate ili nevažeće valute',
      'name-multiple' => 'nepoznatih ili nevažećih valuta',
    ),
    'YDD' => 
    array (
      'name' => 'Jemenski dinar (YDD)',
      'name-single' => 'jemenski dinar',
      'name-multiple' => 'jemenskih dinara',
    ),
    'YER' => 
    array (
      'name' => 'Jemenski rial (YER)',
      'name-single' => 'jemenski rijal',
      'name-multiple' => 'jemenski rijali',
    ),
    'YUD' => 
    array (
      'name' => 'Jugoslovenski tvrdi dinar (YUD)',
      'name-single' => 'jugoslovenski čvrsti dinar',
      'name-multiple' => 'jugoslovenskih čvstih dinara',
    ),
    'YUM' => 
    array (
      'name' => 'Jugoslovenski novi dinar (YUM)',
      'name-single' => 'jugoslovenski novi dinar',
      'name-multiple' => 'jugoslovenskih novih dinara',
    ),
    'YUN' => 
    array (
      'name' => 'Jugoslovenski konvertibilni dinar (YUN)',
      'name-single' => 'jugoslovenski konvertibilni dinar',
      'name-multiple' => 'jugoslovenskih konvertibilnih dinara',
    ),
    'YUR' => 
    array (
      'name-single' => 'jugoslovenski reformirani dinar',
      'name-multiple' => 'jugoslovenskih reformiranih dinara',
    ),
    'ZAL' => 
    array (
      'name' => 'Južnoafrički rand (finansijski) ZAL',
      'name-single' => 'južnoafrički rand (financijski)',
      'name-multiple' => 'južnoafičkih randa (financijskih)',
    ),
    'ZAR' => 
    array (
      'name' => 'Južna Afrika Rand',
      'name-single' => 'južnoafrički rand',
      'name-multiple' => 'južnoafričkih randa',
    ),
    'ZMK' => 
    array (
      'name' => 'Zambijska kvača (ZMK)',
      'name-single' => 'zambijska kvača',
      'name-multiple' => 'zambijske kvače',
    ),
    'ZRN' => 
    array (
      'name' => 'Zairski novi zair (ZRN)',
      'name-single' => 'zairski novi zair',
      'name-multiple' => 'zairskih novih zaira',
    ),
    'ZRZ' => 
    array (
      'name' => 'Zairski zair (ZRZ)',
      'name-single' => 'zairski zair',
      'name-multiple' => 'zairskih zaira',
    ),
    'ZWD' => 
    array (
      'name' => 'Zimbabvejski dolar (ZWD)',
      'name-single' => 'zimbabvejski dolar',
      'name-multiple' => 'zimbabvejski dolari',
    ),
    'ZWL' => 
    array (
      'name' => 'Зимбабвеански долар (2009)',
      'name-single' => 'zimbabvejski dolaz (2009)',
      'name-multiple' => 'zimbabvejskih dolara (2009)',
    ),
    'ZWR' => 
    array (
      'name' => 'Зимбабвеански долар (2008)',
      'name-single' => 'zimbabvejski dolar (2008)',
      'name-multiple' => 'zimbabvejskih dolara (2008)',
    ),
  ),
  'languages' => 
  array (
    'ab' => 'Abkazijski',
    'ada' => 'Adangmejski',
    'ady' => 'Adigejski',
    'aa' => 'Afarski',
    'afh' => 'Afrihili',
    'af' => 'Afrikanerski',
    'afa' => 'Afro-azijatski',
    'ain' => 'Ainu',
    'ay' => 'Ajmara',
    'akk' => 'Akadijski',
    'ak' => 'Akan',
    'ach' => 'Akoli',
    'sq' => 'Albanski',
    'alg' => 'Algonkvijanski jezik',
    'ale' => 'Aljut',
    'tut' => 'Altaički jezik',
    'am' => 'Amharski',
    'anp' => 'Angika',
    'apa' => 'Apački jezik',
    'an' => 'Aragonežanski',
    'arp' => 'Arapaho',
    'ar' => 'Arapski',
    'arw' => 'Aravak',
    'arc' => 'Armajski',
    'arn' => 'Arokanijski',
    'rup' => 'Aromanijski',
    'as' => 'Asemijski',
    'ast' => 'Asturijski',
    'ath' => 'Atapaskan',
    'cch' => 'Atsam',
    'en_AU' => 'Australijski engleski',
    'aus' => 'Australijski jezik',
    'de_AT' => 'Austrijski nemački',
    'map' => 'Austronežanski',
    'awa' => 'Avadhi',
    'av' => 'Avarski',
    'ae' => 'Avestanski',
    'az' => 'Azerbejdžanski',
    'ace' => 'Ačineski',
    'ban' => 'Balinezijski',
    'bat' => 'Baltički jezik',
    'bal' => 'Baluči',
    'bm' => 'Bambara',
    'bai' => 'Bamileke',
    'bad' => 'Banda',
    'bnt' => 'Bantu',
    'bas' => 'Basa',
    'eu' => 'Baskijski',
    'btk' => 'Batak',
    'ba' => 'Baškir',
    'bej' => 'Beja',
    'be' => 'Beloruski',
    'bem' => 'Bemba',
    'bn' => 'Bengalski',
    'ber' => 'Berber',
    'zxx' => 'Bez lingvističkog sadržaja',
    'bh' => 'Biharski',
    'bik' => 'Bikol',
    'bin' => 'Bini',
    'bi' => 'Bislama',
    'byn' => 'Blin',
    'zbl' => 'Blisimboli',
    'bho' => 'Bojpuri',
    'bs' => 'Bosanski',
    'bra' => 'Braj',
    'pt_BR' => 'Brazilski portugalski',
    'br' => 'Bretonski',
    'en_GB' => 'Britanski engleski',
    'bg' => 'Bugarski',
    'bug' => 'Buginežanskii',
    'bua' => 'Buriat',
    'my' => 'Burmanski',
    'ceb' => 'Cebuano',
    'day' => 'Dajaški',
    'dak' => 'Dakota',
    'da' => 'Danski',
    'dar' => 'Dargva',
    'del' => 'Delaver',
    'din' => 'Dinka',
    'dv' => 'Divehijski',
    'doi' => 'Dogri',
    'dgr' => 'Dogrib',
    'dra' => 'Dravidijski jezik',
    'dua' => 'Duala',
    'gez' => 'Džiz',
    'dz' => 'Džonga',
    'efi' => 'Efikski',
    'eka' => 'Ekajuk',
    'elx' => 'Elamitski',
    'en' => 'Engleski',
    'en_US' => 'Engleski (SAD)',
    'myv' => 'Erzija',
    'eo' => 'Esperanto',
    'et' => 'Estonski',
    'ee' => 'Eve',
    'ewo' => 'Evondo',
    'fan' => 'Fang',
    'fat' => 'Fanti',
    'fo' => 'Farski',
    'phn' => 'Feničanski',
    'fj' => 'Fidžijski',
    'fil' => 'Filipinski',
    'phi' => 'Filipinski jezik',
    'fi' => 'Finski',
    'nl_BE' => 'Flamanski',
    'fon' => 'Fon',
    'fr' => 'Francuski',
    'fur' => 'Friulijski',
    'fy' => 'Frizijski',
    'ff' => 'Fulah',
    'gaa' => 'Ga',
    'gay' => 'Gajo',
    'gl' => 'Galski',
    'lg' => 'Ganda',
    'gba' => 'Gbaja',
    'gem' => 'Germanski jezik',
    'gil' => 'Gilbertški',
    'gon' => 'Gondi',
    'hsb' => 'Gornji sorbijski',
    'gor' => 'Gorontalo',
    'got' => 'Gotski',
    'grb' => 'Grebo',
    'ka' => 'Gruzijski',
    'el' => 'Grčki',
    'gu' => 'Gudžarati',
    'gn' => 'Gvarani',
    'gwi' => 'Gvich\'in',
    'hai' => 'Haida',
    'ht' => 'Haićanski',
    'ha' => 'Hausa',
    'haw' => 'Havajski',
    'he' => 'Hebrejski',
    'hz' => 'Herero',
    'hil' => 'Hiligajnon',
    'him' => 'Himačali',
    'hi' => 'Hindi',
    'ho' => 'Hiri Motu',
    'hit' => 'Hitite',
    'hmn' => 'Hmong',
    'nl' => 'Holandski',
    'hr' => 'Hrvatski',
    'hup' => 'Hupa',
    'iba' => 'Iban',
    'pt_PT' => 'Iberijski portugalski',
    'es_ES' => 'Iberijski španski',
    'io' => 'Ido',
    'ig' => 'Igbo',
    'ijo' => 'Ijo',
    'ilo' => 'Iloko',
    'smn' => 'Inari sami',
    'inc' => 'Indik',
    'ine' => 'Indo-evropski jezik',
    'id' => 'Indonezijski',
    'inh' => 'Ingušetski',
    'ia' => 'Interlingva',
    'ie' => 'Interlingve',
    'iu' => 'Inuktitut',
    'ik' => 'Inupiak',
    'ira' => 'Iranski jezik',
    'iro' => 'Irokvojanski',
    'ga' => 'Irski',
    'is' => 'Islandski',
    'frs' => 'Istočni frizijski',
    'it' => 'Italijanski',
    'sah' => 'Jakut',
    'yao' => 'Jao',
    'ja' => 'Japanski',
    'yap' => 'Japeški',
    'jv' => 'Javanski',
    'hy' => 'Jermenski',
    'cai' => 'Jezik centralno-američkih Indijanaca',
    'sai' => 'Jezik južno-američkih Indijanaca',
    'nai' => 'Jezik severno-američkih Indijanaca',
    'sgn' => 'Jezik znakova',
    'yi' => 'Jidiš',
    'yo' => 'Jorubanski',
    'jrb' => 'Judeo-arapski',
    'jpr' => 'Judeo-persijski',
    'ypk' => 'Jupik',
    'alt' => 'Južni altai',
    'nr' => 'Južni ndebele',
    'sma' => 'Južni sami',
    'kbd' => 'Kabardijski',
    'kab' => 'Kabile',
    'cad' => 'Kado',
    'kl' => 'Kalalisutski',
    'xal' => 'Kalmik',
    'kam' => 'Kamba',
    'kn' => 'Kanada',
    'en_CA' => 'Kanadski engleski',
    'fr_CA' => 'Kanadski francuski',
    'yue' => 'Kantonski',
    'kr' => 'Kanuri',
    'kaa' => 'Kara-kalpaški',
    'krc' => 'Karačaj-balkar',
    'krl' => 'Karelijski',
    'kar' => 'Karenski',
    'car' => 'Karipski',
    'kha' => 'Kasi',
    'ca' => 'Katalonski',
    'kaw' => 'Kavi',
    'cau' => 'Kavkaski',
    'kac' => 'Kačin',
    'ks' => 'Kašmiri',
    'csb' => 'Kašubijanski',
    'cel' => 'Keltski jezik',
    'xh' => 'Khosa',
    'ki' => 'Kikuju',
    'kmb' => 'Kimbundu',
    'zh' => 'Kineski',
    'zh_Hans' => 'Kineski (pojednostavljen)',
    'zh_Hant' => 'Kineski (tradicionalni)',
    'rw' => 'Kinjarvanda',
    'ky' => 'Kirgiski',
    'nwc' => 'Klasični nevari',
    'syc' => 'Klasični sirijski',
    'tlh' => 'Klingonski',
    'km' => 'Kmerski',
    'khi' => 'Koisanski jezik',
    'kv' => 'Komi',
    'swb' => 'Komorski',
    'kg' => 'Kongo',
    'kok' => 'Konkani',
    'cop' => 'Koptski',
    'ko' => 'Korejski',
    'kw' => 'Korniški',
    'kfo' => 'Koro',
    'co' => 'Korzikanski',
    'kos' => 'Kosreanski',
    'kho' => 'Kotanizijski',
    'kk' => 'Kozački',
    'kpe' => 'Kpele',
    'crp' => 'Kreolski ili pidžin',
    'cpp' => 'Kreolski ili pidžin baziran na portugalskom',
    'cpe' => 'Kreolski ili pidžin zasnovan na engleskom',
    'cpf' => 'Kreolski ili pidžin zasnovan na francuskom',
    'cr' => 'Kri',
    'crh' => 'Krimeanski turski',
    'mus' => 'Kriški',
    'kro' => 'Kru',
    'kj' => 'Kuanjama',
    'kum' => 'Kumik',
    'ku' => 'Kurdski',
    'kru' => 'Kurukh',
    'kut' => 'Kutenai',
    'cus' => 'Kušitički jezik',
    'qu' => 'Kvenča',
    'lad' => 'Ladino',
    'lam' => 'Lamba',
    'lah' => 'Landa',
    'lo' => 'Laoški',
    'es_419' => 'Latino-američki španski',
    'la' => 'Latinski',
    'lv' => 'Letonski',
    'lez' => 'Lezgian',
    'li' => 'Limburgiš',
    'ln' => 'Lingala',
    'lt' => 'Litvanski',
    'jbo' => 'Lojban',
    'loz' => 'Lozi',
    'lu' => 'Luba-katanga',
    'lua' => 'Luba-lulua',
    'lui' => 'Luiseno',
    'lb' => 'Luksemburški',
    'smj' => 'Lule sami',
    'lun' => 'Lunda',
    'luo' => 'Luo',
    'lus' => 'Lušai',
    'mad' => 'Madureški',
    'mag' => 'Magahi',
    'moh' => 'Mahavski',
    'mai' => 'Maitili',
    'myn' => 'Majanski jezik',
    'mak' => 'Makasar',
    'mk' => 'Makedonski',
    'mg' => 'Malagazijski',
    'ml' => 'Malajalam',
    'ms' => 'Malajski',
    'mdr' => 'Mandar',
    'man' => 'Mandingo',
    'mni' => 'Manipuri',
    'gv' => 'Manks',
    'mno' => 'Manobo jezik',
    'mnc' => 'Manču',
    'mi' => 'Maorski',
    'mr' => 'Marati',
    'chm' => 'Mari',
    'mwr' => 'Marvari',
    'mh' => 'Maršalski',
    'mas' => 'Masai',
    'hu' => 'Mađarski',
    'mt' => 'Melteški',
    'men' => 'Mende',
    'mic' => 'Mikmak',
    'min' => 'Minangkabau',
    'mwl' => 'Mirandeški',
    'mdf' => 'Mokša',
    'mo' => 'Moldavski',
    'mkh' => 'Mon-kmerski jezik',
    'lol' => 'Mongo',
    'mn' => 'Mongolski',
    'mos' => 'Mosi',
    'mun' => 'Munda jezik',
    'nah' => 'Nahuatl',
    'na' => 'Nauru',
    'nv' => 'Navaho',
    'ng' => 'Ndonga',
    'nap' => 'Neapolitanski',
    'de' => 'Nemački',
    'ne' => 'Nepalski',
    'und' => 'Nepoznat ili nevažeći jezik',
    'new' => 'Nevari',
    'nia' => 'Nias',
    'nic' => 'Niger-kordofanijski jezik',
    'ssa' => 'Nilo-saharski jezik',
    'dsb' => 'Niski Sorbijanski',
    'nds' => 'Niski nemački',
    'niu' => 'Niuean',
    'nym' => 'Njamvezi',
    'ny' => 'Njanja',
    'nyn' => 'Njankole',
    'tog' => 'Njasa tonga',
    'nyo' => 'Njoro',
    'nog' => 'Nogai',
    'no' => 'Norveški',
    'nb' => 'Norveški bokmål',
    'nn' => 'Norveški njorsk',
    'nub' => 'Nubijski jezik',
    'nzi' => 'Nzima',
    'nqo' => 'N’ko',
    'oj' => 'Ojibva',
    'or' => 'Orijski',
    'om' => 'Oromo',
    'osa' => 'Osage',
    'os' => 'Osetski',
    'oto' => 'Otomanski jezik',
    'ota' => 'Otomanski turski',
    'pal' => 'Pahlavi',
    'pau' => 'Palauanski',
    'pi' => 'Pali',
    'pam' => 'Pampanga',
    'pa' => 'Pandžabski',
    'pag' => 'Pangasinski',
    'pap' => 'Papiamento',
    'paa' => 'Papuanski jezik',
    'ps' => 'Paštunski',
    'fa' => 'Persijski',
    'pl' => 'Poljski',
    'pon' => 'Ponpejski',
    'pt' => 'Portugalski',
    'pra' => 'Prakritski jezik',
    'oc' => 'Provansalski',
    'rap' => 'Rapanui',
    'rar' => 'Rarotongan',
    'mis' => 'Razni jezici',
    'raj' => 'Rađastani',
    'rm' => 'Reto-Romanski',
    'rom' => 'Romani',
    'roa' => 'Romanski jezik',
    'ro' => 'Rumunski',
    'root' => 'Run',
    'rn' => 'Rundi',
    'ru' => 'Ruski',
    'sal' => 'Sališanski jezik',
    'sam' => 'Samaritanski aramejski',
    'smi' => 'Sami jezik',
    'sm' => 'Samoanski',
    'sad' => 'Sandave',
    'sg' => 'Sango',
    'sa' => 'Sanskrit',
    'sat' => 'Santali',
    'sc' => 'Sardinijski',
    'sas' => 'Sasak',
    'sel' => 'Selkap',
    'sem' => 'Semitski jezik',
    'srr' => 'Serer',
    'st' => 'Sesoto',
    'nd' => 'Severni ndebele',
    'se' => 'Severni sami',
    'nso' => 'Severni soto',
    'frr' => 'Severno-frizijski',
    'scn' => 'Sicilijanski',
    'sid' => 'Sidamo',
    'bla' => 'Siksika',
    'sd' => 'Sindi',
    'si' => 'Singaleski',
    'sit' => 'Sino-tibetanski jezik',
    'syr' => 'Sirijski',
    'sio' => 'Siuanski jezik',
    'ii' => 'Sičuan ji',
    'sms' => 'Skoltski jezik',
    'den' => 'Slavski',
    'sk' => 'Slovački',
    'sl' => 'Slovenački',
    'sla' => 'Slovenski jezik',
    'sog' => 'Sodžijenski',
    'so' => 'Somalski',
    'son' => 'Songai',
    'snk' => 'Soninke',
    'wen' => 'Sorbijanski jezik',
    'srn' => 'Srananski tongo',
    'enm' => 'Srednji engleski',
    'frm' => 'Srednji francuski',
    'dum' => 'Srednji holandski',
    'mga' => 'Srednji irski',
    'gmh' => 'Srednji visoki nemački',
    'sr' => 'Srpski',
    'sh' => 'Srpskohrvatski',
    'non' => 'Stari norski',
    'egy' => 'Staroegipatski',
    'ang' => 'Staroengleski',
    'fro' => 'Starofrancuski',
    'grc' => 'Starogrčki',
    'sga' => 'Staroirski',
    'goh' => 'Staronemački',
    'peo' => 'Staropersijski',
    'pro' => 'Staroprovansalski',
    'cu' => 'Staroslovenski',
    'su' => 'Sudanski',
    'suk' => 'Sukuma',
    'sux' => 'Sumerski',
    'sus' => 'Susu',
    'sw' => 'Svahili',
    'ss' => 'Svati',
    'tl' => 'Tagalski',
    'ty' => 'Tahićanski',
    'tai' => 'Tai jezik',
    'th' => 'Tajlandski',
    'tmh' => 'Tamašek',
    'ta' => 'Tamilski',
    'tt' => 'Tatarski',
    'tg' => 'Tađik',
    'te' => 'Telugu',
    'ter' => 'Tereno',
    'tet' => 'Tetum',
    'bo' => 'Tibetanski',
    'tig' => 'Tigre',
    'ti' => 'Tigrinja',
    'tem' => 'Timne',
    'tiv' => 'Tiv',
    'kcg' => 'Tjap',
    'tli' => 'Tlingit',
    'tpi' => 'Tok pisin',
    'tkl' => 'Tokelau',
    'to' => 'Tonga',
    'tsi' => 'Tsimšian',
    'ts' => 'Tsonga',
    'tn' => 'Tsvana',
    'tum' => 'Tumbuka',
    'tup' => 'Tupi jezik',
    'tk' => 'Turkmenski',
    'tr' => 'Turski',
    'tvl' => 'Tuvalu',
    'tyv' => 'Tuvinijski',
    'tw' => 'Tvi',
    'udm' => 'Udmurt',
    'uga' => 'Ugaritski',
    'fiu' => 'Ugro-finski jezik',
    'ug' => 'Ujgurski',
    'uk' => 'Ukrajinski',
    'umb' => 'Umbundu',
    'ur' => 'Urdu',
    'uz' => 'Uzbečki',
    'vai' => 'Vai',
    'wak' => 'Vakašanski jezik',
    'wal' => 'Valamo',
    'wa' => 'Valun',
    'war' => 'Varej',
    'was' => 'Vašo',
    'cy' => 'Velški',
    've' => 'Venda',
    'art' => 'Veštački',
    'vi' => 'Vijetnamski',
    'mul' => 'Više jezika',
    'vo' => 'Volapük',
    'wo' => 'Volof',
    'vot' => 'Votski',
    'znd' => 'Zande',
    'zap' => 'Zapotečki',
    'zza' => 'Zaza',
    'zen' => 'Zenaga',
    'za' => 'Zuang',
    'zu' => 'Zulu',
    'zun' => 'Zuni',
    'chg' => 'Čagatai',
    'ch' => 'Čamoro',
    'cmc' => 'Čamski jezik',
    'chy' => 'Čejenski',
    'chr' => 'Čeroki',
    'ce' => 'Čečenski',
    'cs' => 'Češki',
    'chb' => 'Čibča',
    'chn' => 'Činukski',
    'chp' => 'Čipvijanski',
    'cho' => 'Čoktavski',
    'chk' => 'Čukeski',
    'cv' => 'Čuvaški',
    'dyu' => 'Đula',
    'shn' => 'Šan',
    'sco' => 'Škotski',
    'gd' => 'Škotski Galski',
    'sn' => 'Šona',
    'es' => 'Španski',
    'fr_CH' => 'Švajcarski francuski',
    'de_CH' => 'Švajcarski visoki nemački',
    'gsw' => 'Švajcarsko nemački',
    'sv' => 'Švedski',
    'kaj' => 'Žju',
  ),
  'countries' => 
  array (
    'AX' => 'Alandska ostrva',
    'AL' => 'Albanija',
    'DZ' => 'Alžir',
    'AS' => 'Američka Samoa',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Angvila',
    'AQ' => 'Antarktika',
    'AG' => 'Antigva i Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenija',
    'AW' => 'Aruba',
    'AU' => 'Australija',
    'AT' => 'Austrija',
    'AF' => 'Avganistan',
    'AZ' => 'Azerbejdžan',
    'BS' => 'Bahami',
    'BH' => 'Bahrein',
    'BD' => 'Bangladeš',
    'BB' => 'Barbados',
    'BE' => 'Belgija',
    'BZ' => 'Belise',
    'BY' => 'Belorusija',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BW' => 'Bocvana',
    'BO' => 'Bolivija',
    'BA' => 'Bosna i Hercegovina',
    'CX' => 'Božićna Ostrva',
    'BR' => 'Brazil',
    'VG' => 'Britanska Devičanska Ostrva',
    'IO' => 'Britansko Indijska Okeanska Teritorija',
    'BN' => 'Brunej',
    'BG' => 'Bugarska',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'BT' => 'Butan',
    'BV' => 'Buve Ostrva',
    'CF' => 'Centralno Afrička Republika',
    'ME' => 'Crna Gora',
    'DK' => 'Danska',
    'DG' => 'Dijego Garsija',
    'DM' => 'Dominika',
    'DO' => 'Dominikanska Republika',
    'JE' => 'Džersi',
    'DJ' => 'Džibuti',
    'EG' => 'Egipat',
    'EC' => 'Ekvador',
    'GQ' => 'Ekvatorijalna Gvineja',
    'ER' => 'Eritreja',
    'EE' => 'Estonija',
    'ET' => 'Etiopija',
    'EU' => 'Evropska unija',
    'FO' => 'Farska Ostrva',
    'FJ' => 'Fidži',
    'PH' => 'Filipini',
    'FI' => 'Finska',
    'FK' => 'Folklandska ostrva (Malvinska ostrva)',
    'FR' => 'Francuska',
    'GF' => 'Francuska Gvajana',
    'PF' => 'Francuska Polinezija',
    'TF' => 'Francuske Južne Teritorije',
    'GA' => 'Gabon',
    'GM' => 'Gambija',
    'GH' => 'Gana',
    'GI' => 'Gibraltar',
    'GD' => 'Grenada',
    'GL' => 'Grenland',
    'GE' => 'Gruzija',
    'GR' => 'Grčka',
    'GU' => 'Guam',
    'GG' => 'Gurnsi',
    'GP' => 'Gvadelupe',
    'GY' => 'Gvajana',
    'GT' => 'Gvatemala',
    'GN' => 'Gvineja',
    'GW' => 'Gvineja-Bisao',
    'HT' => 'Haiti',
    'HM' => 'Herd i Mekdonald Ostrva',
    'NL' => 'Holandija',
    'AN' => 'Holandski Antili',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HR' => 'Hrvatska',
    'IN' => 'Indija',
    'ID' => 'Indonezija',
    'IQ' => 'Irak',
    'IR' => 'Iran',
    'IE' => 'Irska',
    'IS' => 'Island',
    'TL' => 'Istočni Timor',
    'IT' => 'Italija',
    'IL' => 'Izrael',
    'JM' => 'Jamajka',
    'JP' => 'Japan',
    'YE' => 'Jemen',
    'JO' => 'Jordan',
    'GS' => 'Južna Džordžija i Južna Sendvič Ostrva',
    'KR' => 'Južna Koreja',
    'ZA' => 'Južnoafrička Republika',
    'KY' => 'Kajmanska Ostrva',
    'KH' => 'Kambodža',
    'CM' => 'Kamerun',
    'CA' => 'Kanada',
    'IC' => 'Kanarska ostrva',
    'CV' => 'Kape Verde',
    'QA' => 'Katar',
    'KZ' => 'Kazahstan',
    'KE' => 'Kenija',
    'CN' => 'Kina',
    'CY' => 'Kipar',
    'KG' => 'Kirgizstan',
    'KI' => 'Kiribati',
    'CC' => 'Kokos (Keling) Ostrva',
    'CO' => 'Kolumbija',
    'KM' => 'Komorska Ostrva',
    'CD' => 'Kongo [DRC]',
    'CR' => 'Kostarika',
    'CU' => 'Kuba',
    'CK' => 'Kukova Ostrva',
    'KW' => 'Kuvajt',
    'LA' => 'Laos',
    'LS' => 'Lesoto',
    'LV' => 'Letonija',
    'LB' => 'Liban',
    'LR' => 'Liberija',
    'LY' => 'Libija',
    'LI' => 'Lihtenštajn',
    'LT' => 'Litvanija',
    'LU' => 'Luksemburg',
    'MG' => 'Madagaskar',
    'YT' => 'Majote',
    'MO' => 'Makao',
    'MK' => 'Makedonija (BJR)',
    'MW' => 'Malavi',
    'MV' => 'Maldivi',
    'MY' => 'Malezija',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'UM' => 'Manja Udaljena Ostrva SAD',
    'MA' => 'Maroko',
    'MQ' => 'Martinik',
    'MH' => 'Maršalska Ostrva',
    'MU' => 'Mauricius',
    'MR' => 'Mauritanija',
    'HU' => 'Mađarska',
    'MX' => 'Meksiko',
    'MM' => 'Mijanmar',
    'FM' => 'Mikronezija',
    'MD' => 'Moldavija',
    'MC' => 'Monako',
    'MN' => 'Mongolija',
    'MS' => 'Monserat',
    'MZ' => 'Mozambik',
    'NA' => 'Namibija',
    'NR' => 'Nauru',
    'DE' => 'Nemačka',
    'NP' => 'Nepal',
    'ZZ' => 'Nepoznat ili nevažeći region',
    'NE' => 'Niger',
    'NG' => 'Nigerija',
    'NI' => 'Nikaragva',
    'NU' => 'Niue',
    'NF' => 'Norfolk Ostrvo',
    'NO' => 'Norveška',
    'NC' => 'Nova Kaledonija',
    'NZ' => 'Novi Zeland',
    'CI' => 'Obala Slonovače',
    'OM' => 'Oman',
    'QO' => 'Ostala okeanija',
    'AC' => 'Ostrvo Asension',
    'CP' => 'Ostrvo Kliperton',
    'IM' => 'Ostrvo Man',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinska Teritorija',
    'PA' => 'Panama',
    'PG' => 'Papua Nova Gvineja',
    'PY' => 'Paragvaj',
    'PE' => 'Peru',
    'PN' => 'Pitcairn',
    'PL' => 'Poljska',
    'PR' => 'Porto Riko',
    'PT' => 'Portugal',
    'RE' => 'Rejunion',
    'CG' => 'Republika Kongo',
    'RW' => 'Ruanda',
    'RO' => 'Rumunija',
    'RU' => 'Rusija',
    'VI' => 'S.A.D. Devičanska Ostrva',
    'SV' => 'Salvador',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome i Principe',
    'SA' => 'Saudijska Arabija',
    'SC' => 'Sejšeli',
    'PM' => 'Sen Pjer i Mikelon',
    'SN' => 'Senegal',
    'KN' => 'Sent Kits i Nevis',
    'LC' => 'Sent Lucija',
    'VC' => 'Sent Vinsent i Grenadini',
    'EA' => 'Seuta i Melilja',
    'KP' => 'Severna Koreja',
    'MP' => 'Severna Marijanska Ostrva',
    'SL' => 'Sijera Leone',
    'SG' => 'Singapur',
    'SY' => 'Sirija',
    'US' => 'Sjedinjene Američke Države',
    'SK' => 'Slovačka',
    'SI' => 'Slovenija',
    'SB' => 'Solomonska Ostrva',
    'SO' => 'Somalija',
    'RS' => 'Srbija',
    'CS' => 'Srbija i Crna Gora',
    'SD' => 'Sudan',
    'SR' => 'Surinam',
    'BL' => 'Sv. Bartolomej',
    'MF' => 'Sv. Martin',
    'SJ' => 'Svalbard i Janmajen Ostrva',
    'SZ' => 'Svazilend',
    'SH' => 'Sveta Jelena',
    'TJ' => 'Tadžikistan',
    'TH' => 'Tajland',
    'TW' => 'Tajvan',
    'TZ' => 'Tanzanija',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad i Tobago',
    'TA' => 'Tristan da Kunja',
    'TN' => 'Tunis',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks i Kajkos Ostrva',
    'TR' => 'Turska',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'AE' => 'Ujedinjeni Arapski Emirati',
    'UA' => 'Ukrajina',
    'UY' => 'Urugvaj',
    'UZ' => 'Uzbekistan',
    'WF' => 'Valis i Futuna Ostrva',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikan',
    'GB' => 'Velika Britanija',
    'VE' => 'Venecuela',
    'VN' => 'Vijetnam',
    'ZM' => 'Zambija',
    'EH' => 'Zapadna Sahara',
    'ZW' => 'Zimbabve',
    'TD' => 'Čad',
    'CZ' => 'Češka',
    'CL' => 'Čile',
    'ES' => 'Španija',
    'LK' => 'Šri Lanka',
    'CH' => 'Švajcarska',
    'SE' => 'Švedska',
  ),
);
