<?php
/**
 * Locale data for 'sw'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5953',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => 'K0.0',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januari',
      2 => 'Februari',
      3 => 'Machi',
      4 => 'Aprili',
      5 => 'Mei',
      6 => 'Juni',
      7 => 'Julai',
      8 => 'Agosti',
      9 => 'Septemba',
      10 => 'Oktoba',
      11 => 'Novemba',
      12 => 'Desemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mac',
      4 => 'Apr',
      5 => 'Mei',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Ago',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Des',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Jumapili',
      1 => 'Jumatatu',
      2 => 'Jumanne',
      3 => 'Jumatano',
      4 => 'Alhamisi',
      5 => 'Ijumaa',
      6 => 'Jumamosi',
    ),
    'abbreviated' => 
    array (
      0 => 'J2',
      1 => 'J3',
      2 => 'J4',
      3 => 'J5',
      4 => 'Alh',
      5 => 'Ij',
      6 => 'J1',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '2',
      1 => '3',
      2 => '4',
      3 => '5',
      4 => 'A',
      5 => 'I',
      6 => '1',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'dola ya Australia',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'Real ya Brazil',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'dola ya Kanada',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'yuan Renminbi ya China',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'yuro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'pauni ya Uingereza',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
      'name' => 'Dola ya Hong Kong',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
      'name' => 'Sheqel Mpya ya Israeli',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'rupia ya India',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'sarafu ya Kijapani',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
      'name' => 'Won ya Korea Kusini',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'Peso ya Meksiko',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
      'name' => 'Dola ya Nyuzilandi',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
      'name' => 'Baht ya Tailandi',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
      'name' => 'Dola ya Taiwan',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'dola ya Marekani',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
      'name' => 'Dong ya Kivietinamu',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'faranga CFA BEAC',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
      'name' => 'Dola ya Karibea ya Mashariki',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'faranga CFA BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
      'name' => 'Franc ya CFP',
    ),
    'KES' => 
    array (
      'symbol' => 'Ksh',
      'name' => 'shilingi ya Kenya',
    ),
    'TZS' => 
    array (
      'symbol' => 'TSh',
      'name' => 'shilingi ya Tanzania',
    ),
    'AED' => 
    array (
      'name' => 'dirham ya Falme za Kiarabu',
    ),
    'AFN' => 
    array (
      'name' => 'Afghani ya Afuganistani',
    ),
    'ALL' => 
    array (
      'name' => 'Lek ya Albania',
    ),
    'AMD' => 
    array (
      'name' => 'Dram ya Armenia',
    ),
    'ANG' => 
    array (
      'name' => 'Guilder ya Antili za Kiholanzi',
    ),
    'AOA' => 
    array (
      'name' => 'kwanza ya Angola',
    ),
    'ARS' => 
    array (
      'name' => 'Peso ya Ajentina',
    ),
    'AWG' => 
    array (
      'name' => 'Florin ya Aruba',
    ),
    'AZN' => 
    array (
      'name' => 'Manat ya Azebaijan',
    ),
    'BAM' => 
    array (
      'name' => 'Mark ya Bosnia na Hezegovina Inayoweza Kubadilishwa',
    ),
    'BBD' => 
    array (
      'name' => 'Dola ya Barbados',
    ),
    'BDT' => 
    array (
      'name' => 'Taka ya Bangladesh',
    ),
    'BGN' => 
    array (
      'name' => 'Lev ya Bulgaria',
    ),
    'BHD' => 
    array (
      'name' => 'dinari ya Bahareni',
    ),
    'BIF' => 
    array (
      'name' => 'faranga ya Burundi',
    ),
    'BMD' => 
    array (
      'name' => 'Dola ya Bermuda',
    ),
    'BND' => 
    array (
      'name' => 'Dola ya Brunei',
    ),
    'BOB' => 
    array (
      'name' => 'Boliviano ya Bolivia',
    ),
    'BSD' => 
    array (
      'name' => 'Dola ya Bahamas',
    ),
    'BTN' => 
    array (
      'name' => 'Ngultrum ya Bhutan',
    ),
    'BWP' => 
    array (
      'name' => 'pula ya Botswana',
    ),
    'BYR' => 
    array (
      'name' => 'Ruble ya Belarusi',
    ),
    'BZD' => 
    array (
      'name' => 'Dola ya Belize',
    ),
    'CDF' => 
    array (
      'name' => 'faranga ya Kongo',
    ),
    'CHF' => 
    array (
      'name' => 'faranga ya Uswisi',
    ),
    'CLP' => 
    array (
      'name' => 'Peso ya Chile',
    ),
    'COP' => 
    array (
      'name' => 'Peso ya Kolombia',
    ),
    'CRC' => 
    array (
      'name' => 'Colon ya Kostarika',
    ),
    'CUC' => 
    array (
      'name' => 'Peso ya Cuba Inayoweza Kubadilishwa',
    ),
    'CUP' => 
    array (
      'name' => 'Peso ya Cuba',
    ),
    'CVE' => 
    array (
      'name' => 'eskudo ya Kepuvede',
    ),
    'CZK' => 
    array (
      'name' => 'Koruna ya Jamhuri ya Cheki',
    ),
    'DJF' => 
    array (
      'name' => 'faranga ya Jibuti',
    ),
    'DKK' => 
    array (
      'name' => 'Krone ya Denmaki',
    ),
    'DOP' => 
    array (
      'name' => 'Peso ya Dominika',
    ),
    'DZD' => 
    array (
      'name' => 'dinari ya Aljeria',
    ),
    'EGP' => 
    array (
      'name' => 'pauni ya Misri',
    ),
    'ERN' => 
    array (
      'name' => 'nakfa ya Eritrea',
    ),
    'ETB' => 
    array (
      'name' => 'bir ya Uhabeshi',
    ),
    'FJD' => 
    array (
      'name' => 'Dola ya Fiji',
    ),
    'FKP' => 
    array (
      'name' => 'Pauni ya Visiwa vya Falkland',
    ),
    'GEL' => 
    array (
      'name' => 'Lari ya Georgia',
    ),
    'GHC' => 
    array (
      'name' => 'sedi ya Ghana',
    ),
    'GHS' => 
    array (
      'name' => 'Cedi ya Ghana',
    ),
    'GIP' => 
    array (
      'name' => 'Pauni ya Gibraltar',
    ),
    'GMD' => 
    array (
      'name' => 'dalasi ya Gambia',
    ),
    'GNF' => 
    array (
      'name' => 'Franc ya Guinea',
    ),
    'GNS' => 
    array (
      'name' => 'faranga ya Gine',
    ),
    'GTQ' => 
    array (
      'name' => 'Quetzal ya Guatemala',
    ),
    'GYD' => 
    array (
      'name' => 'Dola ya Guyana',
    ),
    'HNL' => 
    array (
      'name' => 'Lempira ya Hondurasi',
    ),
    'HRK' => 
    array (
      'name' => 'Kuna ya Kroeshia',
    ),
    'HTG' => 
    array (
      'name' => 'Gourde ya Haiti',
    ),
    'HUF' => 
    array (
      'name' => 'Forint ya Hangaria',
    ),
    'IDR' => 
    array (
      'name' => 'Rupiah ya Indonesia',
    ),
    'IQD' => 
    array (
      'name' => 'Dinari ya Irak',
    ),
    'IRR' => 
    array (
      'name' => 'Rial ya Iran',
    ),
    'ISK' => 
    array (
      'name' => 'Króna ya Iceland',
    ),
    'JMD' => 
    array (
      'name' => 'Dola ya Jamaica',
    ),
    'JOD' => 
    array (
      'name' => 'Dinar ya Yordani',
    ),
    'KGS' => 
    array (
      'name' => 'Som ya Kirigistani',
    ),
    'KHR' => 
    array (
      'name' => 'Riel ya Kambodia',
    ),
    'KMF' => 
    array (
      'name' => 'faranga ya Komoro',
    ),
    'KPW' => 
    array (
      'name' => 'Won ya Korea Kaskazini',
    ),
    'KWD' => 
    array (
      'name' => 'Dinar ya Kuwait',
    ),
    'KYD' => 
    array (
      'name' => 'Dola ya Visiwa vya Cayman',
    ),
    'KZT' => 
    array (
      'name' => 'Tenge ya Kazakistani',
    ),
    'LAK' => 
    array (
      'name' => 'Kip ya Laosi',
    ),
    'LBP' => 
    array (
      'name' => 'Pauni ya Lebanon',
    ),
    'LKR' => 
    array (
      'name' => 'Rupee ya Sri Lanka',
    ),
    'LRD' => 
    array (
      'name' => 'dola ya Liberia',
    ),
    'LSL' => 
    array (
      'name' => 'loti ya Lesoto',
    ),
    'LTL' => 
    array (
      'name' => 'Litas ya Lithuania',
    ),
    'LVL' => 
    array (
      'name' => 'Lats ya Lativia',
    ),
    'LYD' => 
    array (
      'name' => 'dinari ya Libya',
    ),
    'MAD' => 
    array (
      'name' => 'dirham ya Moroko',
    ),
    'MDL' => 
    array (
      'name' => 'Leu ya Moldova',
    ),
    'MGA' => 
    array (
      'name' => 'faranga ya Bukini',
    ),
    'MKD' => 
    array (
      'name' => 'Denar ya Masedonia',
    ),
    'MMK' => 
    array (
      'name' => 'Kyat ya Myama',
    ),
    'MNT' => 
    array (
      'name' => 'Tugrik ya Mongolia',
    ),
    'MOP' => 
    array (
      'name' => 'Pataca ya Macau',
    ),
    'MRO' => 
    array (
      'name' => 'ugwiya ya Moritania',
    ),
    'MUR' => 
    array (
      'name' => 'rupia ya Morisi',
    ),
    'MVR' => 
    array (
      'name' => 'Rufiyaa ya Maldivi',
    ),
    'MWK' => 
    array (
      'name' => 'kwacha ya Malawi',
    ),
    'MYR' => 
    array (
      'name' => 'Ringgit ya Malaysia',
    ),
    'MZM' => 
    array (
      'name' => 'metikali ya Msumbiji',
    ),
    'NAD' => 
    array (
      'name' => 'dola ya Namibia',
    ),
    'NGN' => 
    array (
      'name' => 'naira ya Nijeria',
    ),
    'NIO' => 
    array (
      'name' => 'Córdoba ya Nikaragua',
    ),
    'NOK' => 
    array (
      'name' => 'Krone ya Norwe',
    ),
    'NPR' => 
    array (
      'name' => 'Rupee ya Nepali',
    ),
    'OMR' => 
    array (
      'name' => 'Rial ya Oman',
    ),
    'PAB' => 
    array (
      'name' => 'Balboa ya Panama',
    ),
    'PEN' => 
    array (
      'name' => 'Nuevo Sol ya Peru',
    ),
    'PGK' => 
    array (
      'name' => 'Kina ya Papua New Guinea',
    ),
    'PHP' => 
    array (
      'name' => 'Peso ya Ufilipino',
    ),
    'PKR' => 
    array (
      'name' => 'Rupee ya Pakistan',
    ),
    'PLN' => 
    array (
      'name' => 'Zloty ya Polandi',
    ),
    'PYG' => 
    array (
      'name' => 'Guarani ya Paragwai',
    ),
    'QAR' => 
    array (
      'name' => 'Rial ya Katari',
    ),
    'RSD' => 
    array (
      'name' => 'Dinar ya Serbia',
    ),
    'RUB' => 
    array (
      'name' => 'Ruble ya Urusi',
    ),
    'RWF' => 
    array (
      'name' => 'faranga ya Rwanda',
    ),
    'SAR' => 
    array (
      'name' => 'riyal ya Saudia',
    ),
    'SBD' => 
    array (
      'name' => 'Dola ya Visiwa vya Solomon',
    ),
    'SCR' => 
    array (
      'name' => 'rupia ya Shelisheli',
    ),
    'SDG' => 
    array (
      'name' => 'dinari ya Sudani',
    ),
    'SDP' => 
    array (
      'name' => 'pauni ya Sudani',
    ),
    'SEK' => 
    array (
      'name' => 'Krona ya Uswidi',
    ),
    'SGD' => 
    array (
      'name' => 'Dola ya Singapuri',
    ),
    'SHP' => 
    array (
      'name' => 'pauni ya Santahelena',
    ),
    'SLL' => 
    array (
      'name' => 'leoni',
    ),
    'SOS' => 
    array (
      'name' => 'shilingi ya Somalia',
    ),
    'SRD' => 
    array (
      'name' => 'Dola ya Suriname',
    ),
    'STD' => 
    array (
      'name' => 'dobra ya Sao Tome na Principe',
    ),
    'SYP' => 
    array (
      'name' => 'Pauni ya Syria',
    ),
    'SZL' => 
    array (
      'name' => 'lilangeni',
    ),
    'TJS' => 
    array (
      'name' => 'Somoni ya Tajikistani',
    ),
    'TMT' => 
    array (
      'name' => 'Manat ya Turukimenistani',
    ),
    'TND' => 
    array (
      'name' => 'dinari ya Tunisia',
    ),
    'TOP' => 
    array (
      'name' => 'Paʻanga ya Tonga',
    ),
    'TRY' => 
    array (
      'name' => 'Lira ya Uturuki',
    ),
    'TTD' => 
    array (
      'name' => 'Dola ya Trinidad na Tobago',
    ),
    'UAH' => 
    array (
      'name' => 'Hryvnia ya Ukrania',
    ),
    'UGX' => 
    array (
      'name' => 'shilingi ya Uganda',
    ),
    'UYU' => 
    array (
      'name' => 'Peso ya Urugwai',
    ),
    'UZS' => 
    array (
      'name' => 'Som ya Uzibekistani',
    ),
    'VEF' => 
    array (
      'name' => 'Bolivar ya Venezuela',
    ),
    'VUV' => 
    array (
      'name' => 'Vatu ya Vanuatu',
    ),
    'WST' => 
    array (
      'name' => 'Tala ya Samoa',
    ),
    'XXX' => 
    array (
      'name' => 'Fedha Isiyojulikana',
    ),
    'YER' => 
    array (
      'name' => 'Rial ya Yemen',
    ),
    'ZAR' => 
    array (
      'name' => 'randi ya Afrika Kusini',
    ),
    'ZMK' => 
    array (
      'name' => 'kwacha ya Zambia',
    ),
    'ZWD' => 
    array (
      'name' => 'dola ya Zimbabwe',
    ),
  ),
  'languages' => 
  array (
    'ay' => 'Aimara',
    'zxx' => 'Hakuna maudhui ya lugha',
    'ks' => 'Kashmiri',
    'ab' => 'Kiabkhazi',
    'af' => 'Kiafrikana',
    'is' => 'Kiaisilandi',
    'fa' => 'Kiajemi',
    'ak' => 'Kiakan',
    'sq' => 'Kialbania',
    'am' => 'Kiamhari',
    'ar' => 'Kiarabu',
    'hy' => 'Kiarmenia',
    'as' => 'Kiassam',
    'ga' => 'Kiayalandi',
    'az' => 'Kiazeri',
    'bn' => 'Kibangla',
    'eu' => 'Kibasque',
    'be' => 'Kibelarusi',
    'bez' => 'Kibena',
    'bh' => 'Kibihari',
    'nb' => 'Kibokmal cha Norwe',
    'bs' => 'Kibosnia',
    'br' => 'Kibreton',
    'bg' => 'Kibulgaria',
    'my' => 'Kiburma',
    'cs' => 'Kicheki',
    'zh' => 'Kichina',
    'zh_Hans' => 'Kichina Rahisi',
    'zh_Hant' => 'Kichina cha Jadi',
    'da' => 'Kidenmaki',
    'dv' => 'Kidivehi',
    'he' => 'Kiebrania',
    'efi' => 'Kiefiki',
    'eo' => 'Kiesperanto',
    'et' => 'Kiestonia',
    'fr' => 'Kifaransa',
    'fr_CA' => 'Kifaransa cha Kanada',
    'fr_CH' => 'Kifaransa cha Uswisi',
    'fo' => 'Kifaroe',
    'fj' => 'Kifiji',
    'fil' => 'Kifilipino',
    'fi' => 'Kifinlandi',
    'nl_BE' => 'Kiflemi',
    'fy' => 'Kifrisia cha Magharibi',
    'gd' => 'Kigaeli cha Uskoti',
    'gl' => 'Kigalisia',
    'el' => 'Kigiriki',
    'gn' => 'Kiguarani',
    'gu' => 'Kigujarati',
    'ht' => 'Kihaiti',
    'ha' => 'Kihausa',
    'haw' => 'Kihawai',
    'hi' => 'Kihindi',
    'es' => 'Kihispania',
    'es_419' => 'Kihispania cha Amerika ya Kilatinini',
    'es_ES' => 'Kihispania cha Iberia',
    'nl' => 'Kiholanzi',
    'hu' => 'Kihungari',
    'ig' => 'Kiigbo',
    'id' => 'Kiindonesia',
    'en' => 'Kiingereza',
    'en_AU' => 'Kiingereza cha Australia',
    'en_CA' => 'Kiingereza cha Kanada',
    'en_US' => 'Kiingereza cha Marekani',
    'en_GB' => 'Kiingereza cha Uingereza',
    'ia' => 'Kiinterlingua',
    'it' => 'Kiitaliano',
    'ja' => 'Kijapani',
    'jv' => 'Kijava',
    'de' => 'Kijerumani',
    'de_AT' => 'Kijerumani cha Austria',
    'de_CH' => 'Kijerumani cha Juu cha Uswisi',
    'gsw' => 'Kijerumani cha Uswisi',
    'ka' => 'Kijojia',
    'km' => 'Kikambodia',
    'kn' => 'Kikannada',
    'ca' => 'Kikatalani',
    'kk' => 'Kikazaki',
    'tlh' => 'Kiklingon',
    'ko' => 'Kikorea',
    'ku' => 'Kikurdi',
    'lo' => 'Kilaosi',
    'lb' => 'Kilasembagi',
    'la' => 'Kilatini',
    'lv' => 'Kilatvia',
    'ln' => 'Kilingala',
    'lt' => 'Kilithuania',
    'ml' => 'Kimalayalam',
    'ms' => 'Kimalesia',
    'mt' => 'Kimalta',
    'mr' => 'Kimarathi',
    'mk' => 'Kimasedonia',
    'nd' => 'Kindebele cha Kaskazini',
    'ne' => 'Kinepali',
    'nn' => 'Kinorwe Kipya',
    'no' => 'Kinorwei',
    'ny' => 'Kinyanja',
    'rw' => 'Kinyarwanda',
    'or' => 'Kioriya',
    'os' => 'Kiosetia',
    'oc' => 'Kiositani',
    'asa' => 'Kipare',
    'pl' => 'Kipolandi',
    'pa' => 'Kipunjabi',
    'ps' => 'Kipushto',
    'pt' => 'Kireno',
    'pt_BR' => 'Kireno cha Brazil',
    'pt_PT' => 'Kireno cha Iberia',
    'ky' => 'Kirigizi',
    'ro' => 'Kiromania',
    'rm' => 'Kiromanshi',
    'rn' => 'Kirundi',
    'ru' => 'Kirusi',
    'rwk' => 'Kirwo',
    'se' => 'Kisami cha Kaskazini',
    'sm' => 'Kisamoa',
    'sg' => 'Kisango',
    'sa' => 'Kisanskriti',
    'sr' => 'Kiserbia',
    'sh' => 'Kiserbia-kroeshia',
    'sn' => 'Kishona',
    'sd' => 'Kisindhi',
    'si' => 'Kisinhala',
    'sk' => 'Kislovakia',
    'sl' => 'Kislovenia',
    'so' => 'Kisomali',
    'nso' => 'Kisotho cha Kaskazini',
    'st' => 'Kisotho cha Kusini',
    'su' => 'Kisunda',
    'sw' => 'Kiswahili',
    'ss' => 'Kiswati',
    'sv' => 'Kiswidi',
    'ty' => 'Kitahiti',
    'th' => 'Kitailandi',
    'ta' => 'Kitamil',
    'tt' => 'Kitatari',
    'te' => 'Kitelugu',
    'tet' => 'Kitetum',
    'bo' => 'Kitibeti',
    'ti' => 'Kitigrinya',
    'tpi' => 'Kitokpisin',
    'ts' => 'Kitsonga',
    'tn' => 'Kitswana',
    'tr' => 'Kituruki',
    'tk' => 'Kiturukimeni',
    'tw' => 'Kitwii',
    'ug' => 'Kiuiguri',
    'uk' => 'Kiukrania',
    'ur' => 'Kiurdu',
    'uz' => 'Kiuzbeki',
    've' => 'Kivenda',
    'vi' => 'Kivietinamu',
    'cy' => 'Kiwelisi',
    'xh' => 'Kixhosa',
    'yi' => 'Kiyidish',
    'yo' => 'Kiyoruba',
    'dz' => 'Kizongkha',
    'zu' => 'Kizulu',
    'hr' => 'Kroeshia',
    'und' => 'Lugha Isiyojulikana',
    'mul' => 'Lugha nyingi',
    'ie' => 'Lugha ya kisayansi',
    'mg' => 'Malagasi',
    'mi' => 'Maori',
    'mn' => 'Mongolia',
    'qu' => 'Quechua',
    'tg' => 'Tajiki',
    'to' => 'Tonga',
    'wo' => 'Wolof',
  ),
  'countries' => 
  array (
    'ZA' => 'Afrika Kusini',
    'AF' => 'Afuganistani',
    'IS' => 'Aislandi',
    'AR' => 'Ajentina',
    'AL' => 'Albania',
    'DZ' => 'Aljeria',
    'AD' => 'Andora',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antaktika',
    'AG' => 'Antigua na Barbuda',
    'AN' => 'Antili za Uholanzi',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'IE' => 'Ayalandi',
    'AZ' => 'Azabajani',
    'BB' => 'Babadosi',
    'BS' => 'Bahama',
    'BH' => 'Bahareni',
    'BD' => 'Bangladeshi',
    'BY' => 'Belarusi',
    'BZ' => 'Belize',
    'BJ' => 'Benini',
    'BM' => 'Bermuda',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia na Hezegovina',
    'BW' => 'Botswana',
    'BR' => 'Brazili',
    'BN' => 'Brunei',
    'BF' => 'Bukinafaso',
    'MG' => 'Bukini',
    'BG' => 'Bulgaria',
    'BI' => 'Burundi',
    'BT' => 'Butani',
    'EA' => 'Ceuta na Melilla',
    'TD' => 'Chadi',
    'CL' => 'Chile',
    'CN' => 'China',
    'CI' => 'Cote d\'Ivoire',
    'DK' => 'Denmaki',
    'DG' => 'Diego Garcia',
    'DM' => 'Dominika',
    'EC' => 'Ekwado',
    'SV' => 'Elsavado',
    'IO' => 'Eneo la Uingereza katika Bahari Hindi',
    'ZZ' => 'Eneo lisilojulikana',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'AE' => 'Falme za Kiarabu',
    'FJ' => 'Fiji',
    'PH' => 'Filipino',
    'GA' => 'Gaboni',
    'GM' => 'Gambia',
    'GH' => 'Ghana',
    'GN' => 'Gine',
    'GW' => 'Ginebisau',
    'GQ' => 'Ginekweta',
    'GD' => 'Grenada',
    'GL' => 'Grinlandi',
    'GG' => 'Guernsey',
    'GY' => 'Guyana',
    'GP' => 'Gwadelupe',
    'GU' => 'Gwam',
    'GT' => 'Gwatemala',
    'GF' => 'Gwiyana ya Ufaransa',
    'HT' => 'Haiti',
    'ES' => 'Hispania',
    'HN' => 'Hondurasi',
    'HK' => 'Hong Kong',
    'HU' => 'Hungaria',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IQ' => 'Iraki',
    'IM' => 'Isle of Man',
    'IL' => 'Israeli',
    'IT' => 'Italia',
    'JM' => 'Jamaika',
    'CF' => 'Jamhuri ya Afrika ya Kati',
    'CZ' => 'Jamhuri ya Cheki',
    'DO' => 'Jamhuri ya Dominika',
    'JP' => 'Japani',
    'JE' => 'Jersey',
    'GI' => 'Jibralta',
    'DJ' => 'Jibuti',
    'GE' => 'Jojia',
    'GS' => 'Jojia Kusini na Visiwa vya Sandwich Kusini',
    'KH' => 'Kambodia',
    'CM' => 'Kameruni',
    'CA' => 'Kanada',
    'QA' => 'Katari',
    'KZ' => 'Kazakistani',
    'KE' => 'Kenya',
    'CV' => 'Kepuvede',
    'KI' => 'Kiribati',
    'KG' => 'Kirigizistani',
    'AC' => 'Kisiwa cha Ascension',
    'BV' => 'Kisiwa cha Bouvet',
    'CP' => 'Kisiwa cha Clipperton',
    'HM' => 'Kisiwa cha Heard na Visiwa vya McDonald',
    'CX' => 'Kisiwa cha Krismasi',
    'NF' => 'Kisiwa cha Norfok',
    'CO' => 'Kolombia',
    'KM' => 'Komoro',
    'CD' => 'Kongo [Jamhuri ya Kidemokrasia]',
    'CG' => 'Kongo [Jamhuri ya]',
    'HR' => 'Korasia',
    'KP' => 'Korea Kaskazini',
    'KR' => 'Korea Kusini',
    'CR' => 'Kostarika',
    'CU' => 'Kuba',
    'CY' => 'Kuprosi',
    'KW' => 'Kuwaiti',
    'LA' => 'Laosi',
    'LU' => 'Lasembagi',
    'LV' => 'Lativia',
    'LB' => 'Lebanoni',
    'LS' => 'Lesoto',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Lishenteni',
    'LT' => 'Litwania',
    'MO' => 'Macau',
    'TF' => 'Maeneo ya Kusini ya Ufaransa',
    'MW' => 'Malawi',
    'MY' => 'Malesia',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'US' => 'Marekani',
    'MQ' => 'Martiniki',
    'MK' => 'Masedonia [FYROM]',
    'YT' => 'Mayotte',
    'MX' => 'Meksiko',
    'FM' => 'Mikronesia',
    'EG' => 'Misri',
    'MV' => 'Modivu',
    'MD' => 'Moldova',
    'MC' => 'Monako',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrati',
    'MU' => 'Morisi',
    'MR' => 'Moritania',
    'MA' => 'Moroko',
    'MZ' => 'Msumbiji',
    'MM' => 'Myama',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepali',
    'NE' => 'Nijeri',
    'NG' => 'Nijeria',
    'NI' => 'Nikaragwa',
    'NU' => 'Niue',
    'NO' => 'Norwe',
    'NC' => 'Nyukaledonia',
    'NZ' => 'Nyuzilandi',
    'QO' => 'Oceania ya Nje',
    'OM' => 'Omani',
    'PK' => 'Pakistani',
    'PW' => 'Palau',
    'PA' => 'Panama',
    'PG' => 'Papua',
    'PY' => 'Paragwai',
    'PE' => 'Peru',
    'PN' => 'Pitkairni',
    'PL' => 'Polandi',
    'PF' => 'Polinesia ya Ufaransa',
    'PR' => 'Pwetoriko',
    'RE' => 'Riyunioni',
    'RO' => 'Romania',
    'RW' => 'Rwanda',
    'EH' => 'Sahara Magharibi',
    'BL' => 'Saint Barthélemy',
    'MF' => 'Saint Martin',
    'SM' => 'Samarino',
    'WS' => 'Samoa',
    'AS' => 'Samoa ya Marekani',
    'SH' => 'Santahelena',
    'KN' => 'Santakitzi na Nevis',
    'LC' => 'Santalusia',
    'PM' => 'Santapieri na Mikeloni',
    'VC' => 'Santavisenti na Grenadini',
    'ST' => 'Sao Tome na Principe',
    'SA' => 'Saudi',
    'SN' => 'Senegali',
    'RS' => 'Serbia',
    'CS' => 'Serbia na Montenegro',
    'SC' => 'Shelisheli',
    'SL' => 'Siera Leoni',
    'SG' => 'Singapoo',
    'SY' => 'Siria',
    'LK' => 'Sirilanka',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SO' => 'Somalia',
    'SD' => 'Sudani',
    'SR' => 'Surinamu',
    'SJ' => 'Svalbard na Jan Mayen',
    'TH' => 'Tailandi',
    'TW' => 'Taiwani',
    'TJ' => 'Tajikistani',
    'TZ' => 'Tanzania',
    'TL' => 'Timori Mashariki',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad na Tobago',
    'TA' => 'Tristan da Cunha',
    'TN' => 'Tunisia',
    'TM' => 'Turukimenistani',
    'TV' => 'Tuvalu',
    'IR' => 'Uajemi',
    'BE' => 'Ubelgiji',
    'FR' => 'Ufaransa',
    'FI' => 'Ufini',
    'UG' => 'Uganda',
    'GR' => 'Ugiriki',
    'ET' => 'Uhabeshi',
    'NL' => 'Uholanzi',
    'GB' => 'Uingereza',
    'DE' => 'Ujerumani',
    'PS' => 'Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina',
    'UA' => 'Ukraini',
    'EU' => 'Umoja wa Ulaya',
    'PT' => 'Ureno',
    'UY' => 'Urugwai',
    'RU' => 'Urusi',
    'SZ' => 'Uswazi',
    'SE' => 'Uswidi',
    'CH' => 'Uswisi',
    'TR' => 'Uturuki',
    'UZ' => 'Uzibekistani',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikani',
    'VE' => 'Venezuela',
    'VN' => 'Vietinamu',
    'UM' => 'Visiwa Vidogo vya Nje vya Marekani',
    'AX' => 'Visiwa vya Alandi',
    'CC' => 'Visiwa vya Cocos [Keeling]',
    'CK' => 'Visiwa vya Cook',
    'FK' => 'Visiwa vya Falklandi [Islas Malvinas]',
    'FO' => 'Visiwa vya Faroe',
    'IC' => 'Visiwa vya Kanari',
    'KY' => 'Visiwa vya Kayman',
    'MP' => 'Visiwa vya Mariana vya Kaskazini',
    'MH' => 'Visiwa vya Marshal',
    'SB' => 'Visiwa vya Solomon',
    'TC' => 'Visiwa vya Turki na Kaiko',
    'VI' => 'Visiwa vya Virgin vya Marekani',
    'VG' => 'Visiwa vya Virgin vya Uingereza',
    'WF' => 'Walis na Futuna',
    'YE' => 'Yemeni',
    'JO' => 'Yordani',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
  ),
);
