<?php
/**
 * Locale data for 'tzm_Latn'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5798',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM/yyyy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Yennayer',
      2 => 'Yebrayer',
      3 => 'Mars',
      4 => 'Ibrir',
      5 => 'Mayyu',
      6 => 'Yunyu',
      7 => 'Yulyuz',
      8 => 'Ɣuct',
      9 => 'Cutanbir',
      10 => 'Kṭuber',
      11 => 'Nwanbir',
      12 => 'Dujanbir',
    ),
    'abbreviated' => 
    array (
      1 => 'Yen',
      2 => 'Yeb',
      3 => 'Mar',
      4 => 'Ibr',
      5 => 'May',
      6 => 'Yun',
      7 => 'Yul',
      8 => 'Ɣuc',
      9 => 'Cut',
      10 => 'Kṭu',
      11 => 'Nwa',
      12 => 'Duj',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Y',
      2 => 'Y',
      3 => 'M',
      4 => 'I',
      5 => 'M',
      6 => 'Y',
      7 => 'Y',
      8 => 'Ɣ',
      9 => 'C',
      10 => 'K',
      11 => 'N',
      12 => 'D',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Asamas',
      1 => 'Aynas',
      2 => 'Asinas',
      3 => 'Akras',
      4 => 'Akwas',
      5 => 'Asimwas',
      6 => 'Asiḍyas',
    ),
    'abbreviated' => 
    array (
      0 => 'Asa',
      1 => 'Ayn',
      2 => 'Asn',
      3 => 'Akr',
      4 => 'Akw',
      5 => 'Asm',
      6 => 'Asḍ',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'A',
      1 => 'A',
      2 => 'A',
      3 => 'A',
      4 => 'A',
      5 => 'A',
      6 => 'A',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'Ḍular Usṭrali',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'Ḍular Ukanadi',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'Ywan Renminbi Ucinwi',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'Uṛu',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'Junih Usterlini Ubriṭani',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'Rupi Uḥindi',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'Yann Ujappuni',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'Ḍular Umirikani',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'Frank CFA (BEAC)',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'Frank CFA (BCEAO)',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'AED' => 
    array (
      'name' => 'Derhem Uymarati',
    ),
    'AOA' => 
    array (
      'name' => 'Kwanza Unguli',
    ),
    'BHD' => 
    array (
      'name' => 'Ḍinar Ubaḥrayni',
    ),
    'BIF' => 
    array (
      'name' => 'Frank Uburundi',
    ),
    'BWP' => 
    array (
      'name' => 'Pula Ubutswani',
    ),
    'CDF' => 
    array (
      'name' => 'Frank Ukunguli',
    ),
    'CHF' => 
    array (
      'name' => 'Frank Uswisri',
    ),
    'CVE' => 
    array (
      'name' => 'Iskudu Ukabuvirdyani',
    ),
    'DJF' => 
    array (
      'name' => 'Frank Uğibuti',
    ),
    'DZD' => 
    array (
      'name' => 'Ḍinar Udzayri',
    ),
    'EGP' => 
    array (
      'name' => 'Junih Umiṣṛi',
    ),
    'ERN' => 
    array (
      'name' => 'Nakfa Uyritri',
    ),
    'ETB' => 
    array (
      'name' => 'Birr Uyityuppi',
    ),
    'GHC' => 
    array (
      'name' => 'Sidi Uɣani',
    ),
    'GMD' => 
    array (
      'name' => 'Dalasi Agambi',
    ),
    'GNS' => 
    array (
      'name' => 'Frank Uɣini',
    ),
    'KES' => 
    array (
      'name' => 'Cillin Ukini',
    ),
    'KMF' => 
    array (
      'name' => 'Frank Uqumuri',
    ),
    'LRD' => 
    array (
      'name' => 'Ḍular Ulibiri',
    ),
    'LSL' => 
    array (
      'name' => 'Luti Ulusuṭi',
    ),
    'LYD' => 
    array (
      'name' => 'Ḍinar Ulibi',
    ),
    'MAD' => 
    array (
      'name' => 'Derhem Umeṛṛuki',
    ),
    'MGA' => 
    array (
      'name' => 'Aryari Umalɣaci',
    ),
    'MRO' => 
    array (
      'name' => 'Uqiyya Umuritani',
    ),
    'MUR' => 
    array (
      'name' => 'Rupi Umurisi',
    ),
    'MWK' => 
    array (
      'name' => 'Kwača Umalawi',
    ),
    'MZM' => 
    array (
      'name' => 'Mitikal Umuzambiqi',
    ),
    'NAD' => 
    array (
      'name' => 'Ḍular Unamibi',
    ),
    'NGN' => 
    array (
      'name' => 'Nayra Unijiri',
    ),
    'RWF' => 
    array (
      'name' => 'Frank Urwandi',
    ),
    'SAR' => 
    array (
      'name' => 'Ryal Usaεudi',
    ),
    'SCR' => 
    array (
      'name' => 'Rupi Usicili',
    ),
    'SDG' => 
    array (
      'name' => 'Junih Usudani',
    ),
    'SDP' => 
    array (
      'name' => 'Junih Usudani (1956–2007)',
    ),
    'SHP' => 
    array (
      'name' => 'Junih Usantehilini',
    ),
    'SLL' => 
    array (
      'name' => 'Lyun Usirralyuni',
    ),
    'SOS' => 
    array (
      'name' => 'Cilin Uṣumali',
    ),
    'STD' => 
    array (
      'name' => 'Dubra Usawṭumi',
    ),
    'SZL' => 
    array (
      'name' => 'Lilanjini Uswazi',
    ),
    'TND' => 
    array (
      'name' => 'Ḍinar Utunsi',
    ),
    'TZS' => 
    array (
      'name' => 'Cilin Uṭanzani',
    ),
    'UGX' => 
    array (
      'name' => 'Cilin Uɣandi (1966-1987)',
    ),
    'ZAR' => 
    array (
      'name' => 'Rand Ufriki Unzul',
    ),
    'ZMK' => 
    array (
      'name' => 'Kwača Uzambi',
    ),
    'ZWD' => 
    array (
      'name' => 'Ḍular Uzimbabwi',
    ),
  ),
  'languages' => 
  array (
    'bg' => 'Tabelɣarit',
    'pa' => 'Tabenjabit',
    'be' => 'Tabilarusit',
    'bn' => 'Tabinɣalit',
    'my' => 'Taburmanit',
    'pt' => 'Taburtuɣalit',
    'zh' => 'Tacinwit,Mandarin',
    'fa' => 'Tafarisit',
    'fr' => 'Tafṛansist',
    'ha' => 'Tahawsat',
    'hu' => 'Tahenɣarit',
    'hi' => 'Tahindit',
    'nl' => 'Tahulanḍit',
    'ja' => 'Tajappunit',
    'jv' => 'Tajavanit',
    'ak' => 'Takanit',
    'ko' => 'Takurit',
    'de' => 'Talmanit',
    'ms' => 'Tamalizit',
    'tzm' => 'Tamaziɣt',
    'am' => 'Tamharit',
    'en' => 'Tanglizt',
    'ne' => 'Tanippalit',
    'pl' => 'Tappulunit',
    'ru' => 'Tarusit',
    'rw' => 'Tarwandit',
    'es' => 'Tasbelyunit',
    'sv' => 'Taswidit',
    'ta' => 'Tatamilt',
    'tr' => 'Taturkit',
    'vi' => 'Taviṭnamit',
    'km' => 'Taxmert ,Talammast',
    'el' => 'Tayunanit',
    'yo' => 'Tayurubat',
    'zu' => 'Tazulut',
    'cs' => 'Tačikt',
    'ar' => 'Taεrabt',
    'ro' => 'Taṛumanit',
    'so' => 'Taṣumalit',
    'it' => 'Taṭalyant',
    'th' => 'Taṭayt',
    'ig' => 'Tigbut',
    'id' => 'Tindunisit',
    'uk' => 'Tukranit',
    'ur' => 'Turdut',
  ),
  'countries' => 
  array (
    'AF' => 'Afɣanistan',
    'PS' => 'Agemmaḍ Ugut d Ɣazza Ifilisṭiniyen',
    'AL' => 'Albanya',
    'DE' => 'Almanya',
    'IO' => 'Amur n Agaraw Uhindi Ubṛiṭani',
    'AO' => 'Angula',
    'AI' => 'Angwilla',
    'AG' => 'Antigwa d Barbuda',
    'AN' => 'Antil Tihulanḍiyyin',
    'AD' => 'Anḍurra',
    'AR' => 'Arjuntin',
    'AM' => 'Arminya',
    'AW' => 'Aruba',
    'VA' => 'Awank iɣrem n Vatikan',
    'AZ' => 'Azerbiǧan',
    'BS' => 'Bahamas',
    'BD' => 'Bangladic',
    'BB' => 'Barbadus',
    'BH' => 'Baḥrayn',
    'BE' => 'Beljika',
    'BG' => 'Belɣarya',
    'BY' => 'Bilarusya',
    'BZ' => 'Biliz',
    'BJ' => 'Binin',
    'BM' => 'Birmuda',
    'BN' => 'Brunay',
    'BO' => 'Bulivya',
    'BF' => 'Burkina Fasu',
    'BI' => 'Burundi',
    'BA' => 'Busna-d-Hirsik',
    'BW' => 'Butswana',
    'BT' => 'Buṭan',
    'BR' => 'Bṛazil',
    'CL' => 'Ccili',
    'DK' => 'Danmark',
    'DZ' => 'Dzayer',
    'FJ' => 'Fiji',
    'PH' => 'Filippin',
    'FI' => 'Finlanḍa',
    'FR' => 'Fṛansa',
    'GA' => 'Gabun',
    'GM' => 'Gambya',
    'GD' => 'Grinada',
    'GL' => 'Grinlanḍa',
    'GY' => 'Guyana',
    'GF' => 'Guyana Tafransist',
    'GP' => 'Gwadalup',
    'GU' => 'Gwam',
    'GT' => 'Gwatimala',
    'HT' => 'Hayti',
    'HU' => 'Henɣarya',
    'IN' => 'Hind',
    'HN' => 'Hinduras',
    'NL' => 'Hulanḍa',
    'EC' => 'Ikwaḍur',
    'AE' => 'Imarat Tiεrabin Tidduklin',
    'ID' => 'Indunizya',
    'IR' => 'Iran',
    'ER' => 'Iritrya',
    'IE' => 'Irlanḍa',
    'IS' => 'Islanḍa',
    'IL' => 'Israeil',
    'EE' => 'Isṭunya',
    'ET' => 'Ityupya',
    'US' => 'Iwunak Idduklen n Amirika',
    'IT' => 'Iṭalya',
    'JM' => 'Jamayka',
    'GI' => 'Jibralṭar',
    'JP' => 'Jjappun',
    'GE' => 'Jyurjya',
    'NC' => 'Kalidunya Tamaynut',
    'KH' => 'Kambudj',
    'CM' => 'Kamerun',
    'CA' => 'Kanada',
    'KZ' => 'Kazaxistan',
    'KE' => 'Kinya',
    'KI' => 'Kiribati',
    'KG' => 'Kirɣistan',
    'HR' => 'Krwatya',
    'CU' => 'Kuba',
    'CO' => 'Kulumbya',
    'CG' => 'Kungu',
    'KP' => 'Kurya Tugafat',
    'KR' => 'Kurya Tunẓult',
    'CR' => 'Kusṭa Rika',
    'KW' => 'Kuwwayt',
    'LA' => 'Laws',
    'LR' => 'Libirya',
    'LY' => 'Libya',
    'LI' => 'Lictencṭayn',
    'LU' => 'Liksumburg',
    'LS' => 'Lisuṭu',
    'LT' => 'Litwanya',
    'LV' => 'Liṭṭunya',
    'LB' => 'Lubnan',
    'MG' => 'Madaɣacqar',
    'MW' => 'Malawi',
    'MV' => 'Maldiv',
    'ML' => 'Mali',
    'MY' => 'Malizya',
    'MT' => 'Malṭa',
    'MN' => 'Manɣulya',
    'MK' => 'Maqdunya',
    'MQ' => 'Martinik',
    'YT' => 'Mayuṭ',
    'MA' => 'Meṛṛuk',
    'FM' => 'Mikrunizya',
    'MX' => 'Miksik',
    'EG' => 'Miṣr',
    'MD' => 'Mulḍavya',
    'MC' => 'Munaku',
    'MS' => 'Muntsirra',
    'MU' => 'Muris',
    'MR' => 'Muritanya',
    'MZ' => 'Muzambiq',
    'MM' => 'Myanmar',
    'NA' => 'Namibya',
    'NR' => 'Nawru',
    'NG' => 'Nijiria',
    'NI' => 'Nikaragwa',
    'NP' => 'Nippal',
    'NU' => 'Niwi',
    'NE' => 'Nnijer',
    'NO' => 'Nnurwij',
    'PK' => 'Pakistan',
    'PW' => 'Palu',
    'PA' => 'Panama',
    'PG' => 'Papwa Ɣinya Tamaynut',
    'PY' => 'Paragway',
    'PE' => 'Piru',
    'PN' => 'Pitkirn',
    'PF' => 'Pulinizya Tafransist',
    'PL' => 'Pulunya',
    'PR' => 'Purturiku',
    'PT' => 'Purtuɣal',
    'QA' => 'Qaṭar',
    'CY' => 'Qubrus',
    'KM' => 'Qumur',
    'RE' => 'Riyyunyun',
    'RU' => 'Rusya',
    'RW' => 'Ruwwanḍa',
    'SV' => 'Salvaḍur',
    'WS' => 'Samwa',
    'AS' => 'Samwa Imirikaniyyin',
    'SM' => 'Sanmarinu',
    'SH' => 'Santehilin',
    'KN' => 'Santekits d Nivis',
    'LC' => 'Santelusya',
    'PM' => 'Santepyir d Mikelun',
    'VC' => 'Santevinsent d Grinadin',
    'SG' => 'Sanɣafura',
    'ST' => 'Sawṭumi d Prinsip',
    'ES' => 'Sbanya',
    'SL' => 'Siralyun',
    'SK' => 'Sluvakya',
    'SI' => 'Sluvinya',
    'LK' => 'Srilanka',
    'SA' => 'Ssaεudiyya Taεrabt',
    'SE' => 'Ssewwid',
    'SC' => 'Ssicil',
    'SN' => 'Ssiniɣal',
    'SD' => 'Ssudan',
    'SR' => 'Surinam',
    'SY' => 'Surya',
    'SZ' => 'Swazilanḍa',
    'CH' => 'Swisra',
    'ZA' => 'Tafrikt Tunẓul',
    'CD' => 'Tagduda Tadimuqraṭit n Kungu',
    'CF' => 'Tagduda n Afrika Wammas',
    'CZ' => 'Tagduda n Čik',
    'DO' => 'Tagduda n Ḍuminikan',
    'GB' => 'Tagelda Taddukelt',
    'CI' => 'Taɣazut n Uszer',
    'TD' => 'Tcad',
    'VG' => 'Tigzirin (Virgin) Tibṛiṭaniyin',
    'TC' => 'Tigzirin Turkiyyin d Tikaykusin',
    'FK' => 'Tigzirin n Falkland',
    'CV' => 'Tigzirin n Iɣf Uzegzaw',
    'KY' => 'Tigzirin n Kayman',
    'CK' => 'Tigzirin n Kuk',
    'MH' => 'Tigzirin n Marcal',
    'MP' => 'Tigzirin n Maryana Tugafat',
    'SB' => 'Tigzirin n Salumun',
    'VI' => 'Tigzirin n Virjin n Iwunak Yedduklen',
    'NF' => 'Tigzirt Nurfulk',
    'TL' => 'Timur Tagmuṭ',
    'TT' => 'Trinidad d Ṭubagu',
    'TK' => 'Tuklu',
    'TN' => 'Tunes',
    'TM' => 'Turkmanistan',
    'TR' => 'Turkya',
    'UA' => 'Ukranya',
    'UY' => 'Urugway',
    'JO' => 'Urḍun',
    'AT' => 'Ustriyya',
    'AU' => 'Usṭralya',
    'UZ' => 'Uzbakistan',
    'UG' => 'Uɣanda',
    'VU' => 'Vanwatu',
    'VE' => 'Vinzwilla',
    'VN' => 'Viṭnam',
    'WF' => 'Walis d Futuna',
    'YE' => 'Yaman',
    'GR' => 'Yunan',
    'ZM' => 'Zambya',
    'NZ' => 'Zilanḍa Tamaynut',
    'ZW' => 'Zimbabwi',
    'IQ' => 'Ɛiraq',
    'OM' => 'Ɛumman',
    'GH' => 'Ɣana',
    'GN' => 'Ɣinya',
    'GQ' => 'Ɣinya Tikwaṭur it',
    'GW' => 'Ɣinya-Bissaw',
    'DJ' => 'Ǧibuti',
    'DM' => 'Ḍuminika',
    'RO' => 'Ṛumanya',
    'CS' => 'Ṣiṛbya d Muntinigru',
    'CN' => 'Ṣṣin',
    'SO' => 'Ṣṣumal',
    'TZ' => 'Ṭanzanya',
    'TH' => 'Ṭaylanḍa',
    'TW' => 'Ṭaywan',
    'TJ' => 'Ṭaǧikistan',
    'TO' => 'Ṭunga',
    'TV' => 'Ṭuvalu',
    'TG' => 'Ṭṭugu',
  ),
);
