<?php
/**
 * Locale data for 'wal_ET'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '4123',
  'symbols' => 
  array (
    'decimal' => '.',
    'group' => 'ወ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE፥ dd MMMM ጋላሳ y G',
    'long' => 'dd MMMM y',
    'medium' => 'dd-MMM-y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'ጃንዩወሪ',
      2 => 'ፌብሩወሪ',
      3 => 'ማርች',
      4 => 'ኤፕረል',
      5 => 'ሜይ',
      6 => 'ጁን',
      7 => 'ጁላይ',
      8 => 'ኦገስት',
      9 => 'ሴፕቴምበር',
      10 => 'ኦክተውበር',
      11 => 'ኖቬምበር',
      12 => 'ዲሴምበር',
    ),
    'abbreviated' => 
    array (
      1 => 'ጃንዩ',
      2 => 'ፌብሩ',
      3 => 'ማርች',
      4 => 'ኤፕረ',
      5 => 'ሜይ',
      6 => 'ጁን',
      7 => 'ጁላይ',
      8 => 'ኦገስ',
      9 => 'ሴፕቴ',
      10 => 'ኦክተ',
      11 => 'ኖቬም',
      12 => 'ዲሴም',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'ጃ',
      2 => 'ፌ',
      3 => 'ማ',
      4 => 'ኤ',
      5 => 'ሜ',
      6 => 'ጁ',
      7 => 'ጁ',
      8 => 'ኦ',
      9 => 'ሴ',
      10 => 'ኦ',
      11 => 'ኖ',
      12 => 'ዲ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ወጋ',
      1 => 'ሳይኖ',
      2 => 'ማቆሳኛ',
      3 => 'አሩዋ',
      4 => 'ሃሙሳ',
      5 => 'አርባ',
      6 => 'ቄራ',
    ),
    'abbreviated' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'ወ',
      1 => 'ሳ',
      2 => 'ማ',
      3 => 'አ',
      4 => 'ሃ',
      5 => 'አ',
      6 => 'ቄ',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
    ),
    'ETB' => 
    array (
      'symbol' => 'Br',
    ),
  ),
  'languages' => 
  array (
    'hi' => 'ሐንድኛ',
    'ru' => 'ራሽኛ',
    'es' => 'ስፓኒሽ',
    'zh' => 'ቻይንኛ',
    'en' => 'እንግሊዝኛ',
    'wal' => 'ወላይታቱ',
    'ar' => 'ዐርቢኛ',
    'de' => 'ጀርመን',
    'ja' => 'ጃፓንኛ',
    'it' => 'ጣሊያንኛ',
    'fr' => 'ፈረንሳይኛ',
    'pt' => 'ፖርቱጋሊኛ',
  ),
  'countries' => 
  array (
    'HU' => 'ሀንጋሪ',
    'HT' => 'ሀይቲ',
    'IN' => 'ህንድ',
    'HK' => 'ሆንግ ኮንግ',
    'LY' => 'ሊቢያ',
    'LB' => 'ሊባኖስ',
    'LT' => 'ሊቱዌኒያ',
    'LV' => 'ላትቪያ',
    'FM' => 'ሚክሮኔዢያ',
    'MY' => 'ማሌዢያ',
    'MT' => 'ማልታ',
    'MU' => 'ማሩሸስ',
    'MK' => 'ማከዶኒያ',
    'MO' => 'ማካዎ',
    'MX' => 'ሜክሲኮ',
    'TL' => 'ምስራቅ ቲሞር',
    'EH' => 'ምዕራባዊ ሳህራ',
    'MD' => 'ሞልዶቫ',
    'MR' => 'ሞሪቴኒያ',
    'MA' => 'ሞሮኮ',
    'MN' => 'ሞንጎሊያ',
    'RU' => 'ራሺያ',
    'RO' => 'ሮሜኒያ',
    'KR' => 'ሰሜን ኮሪያ',
    'CS' => 'ሰርቢያ',
    'SO' => 'ሱማሌ',
    'SD' => 'ሱዳን',
    'SY' => 'ሲሪያ',
    'SG' => 'ሲንጋፖር',
    'SA' => 'ሳውድአረቢያ',
    'CY' => 'ሳይፕረስ',
    'SN' => 'ሴኔጋል',
    'SK' => 'ስሎቫኪያ',
    'SI' => 'ስሎቬኒያ',
    'CH' => 'ስዊዘርላንድ',
    'SE' => 'ስዊድን',
    'ES' => 'ስፔን',
    'BT' => 'ቡህታን',
    'BG' => 'ቡልጌሪያ',
    'GW' => 'ቢሳዎ',
    'BH' => 'ባህሬን',
    'BB' => 'ባርቤዶስ',
    'BZ' => 'ቤሊዘ',
    'BY' => 'ቤላሩስ',
    'BE' => 'ቤልጄም',
    'BM' => 'ቤርሙዳ',
    'BR' => 'ብራዚል',
    'BO' => 'ቦሊቪያ',
    'BA' => 'ቦስኒያ እና ሄርዞጎቪኒያ',
    'VE' => 'ቬንዙዌላ',
    'TR' => 'ቱርክ',
    'TN' => 'ቱኒዚያ',
    'TZ' => 'ታንዛኒያ',
    'TH' => 'ታይላንድ',
    'TJ' => 'ታጃኪስታን',
    'TT' => 'ትሪኒዳድ እና ቶባጎ',
    'CL' => 'ቺሊ',
    'CN' => 'ቻይና',
    'TD' => 'ቻድ',
    'CZ' => 'ቼክ ሪፑብሊክ',
    'NC' => 'ኒው ካሌዶኒያ',
    'NZ' => 'ኒው ዚላንድ',
    'NA' => 'ናሚቢያ',
    'NG' => 'ናይጄሪያ',
    'NL' => 'ኔዘርላንድ',
    'AN' => 'ኔዘርላንድስ አንቲልስ',
    'NP' => 'ኔፓል',
    'NO' => 'ኖርዌ',
    'AL' => 'አልባኒያ',
    'DZ' => 'አልጄሪያ',
    'US' => 'አሜሪካ',
    'AM' => 'አርሜኒያ',
    'AR' => 'አርጀንቲና',
    'AD' => 'አንዶራ',
    'AU' => 'አውስትሬሊያ',
    'AZ' => 'አዘርባጃን',
    'IE' => 'አየርላንድ',
    'IS' => 'አይስላንድ',
    'IQ' => 'ኢራቅ',
    'ET' => 'ኢትዮጵያ',
    'ID' => 'ኢንዶኔዢያ',
    'GQ' => 'ኢኳቶሪያል ጊኒ',
    'EC' => 'ኢኳዶር',
    'ER' => 'ኤርትራ',
    'EE' => 'ኤስቶኒያ',
    'IL' => 'እስራኤል',
    'GB' => 'እንግሊዝ',
    'AT' => 'ኦስትሪያ',
    'CM' => 'ካሜሩን',
    'KH' => 'ካምቦዲያ',
    'CV' => 'ኬፕ ቬርዴ',
    'HR' => 'ክሮኤሽያ',
    'KW' => 'ክዌት',
    'CO' => 'ኮሎምቢያ',
    'KM' => 'ኮሞሮስ',
    'CD' => 'ኮንጎ',
    'ZM' => 'ዛምቢያ',
    'YE' => 'የመን',
    'CF' => 'የመካከለኛው አፍሪካ ሪፐብሊክ',
    'AE' => 'የተባበሩት አረብ ኤምሬትስ',
    'VI' => 'የአሜሪካ ቨርጂን ደሴቶች',
    'VG' => 'የእንግሊዝ ድንግል ደሴቶች',
    'TF' => 'የፈረንሳይ ደቡባዊ ግዛቶች',
    'GF' => 'የፈረንሳይ ጉዊአና',
    'PF' => 'የፈረንሳይ ፖሊኔዢያ',
    'UZ' => 'ዩዝበኪስታን',
    'UG' => 'ዩጋንዳ',
    'ZA' => 'ደቡብ አፍሪካ',
    'KP' => 'ደቡብ ኮሪያ',
    'DK' => 'ዴንማርክ',
    'DM' => 'ዶሚኒካ',
    'DO' => 'ዶሚኒክ ሪፑብሊክ',
    'DE' => 'ጀርመን',
    'JM' => 'ጃማይካ',
    'JP' => 'ጃፓን',
    'JO' => 'ጆርዳን',
    'GE' => 'ጆርጂያ',
    'GY' => 'ጉያና',
    'GN' => 'ጊኒ',
    'GM' => 'ጋምቢያ',
    'GR' => 'ግሪክ',
    'EG' => 'ግብጽ',
    'IT' => 'ጣሊያን',
    'FR' => 'ፈረንሳይ',
    'FI' => 'ፊንላንድ',
    'FJ' => 'ፊጂ',
    'PG' => 'ፓፑዋ ኒው ጊኒ',
    'PE' => 'ፔሩ',
    'PL' => 'ፖላንድ',
    'PR' => 'ፖርታ ሪኮ',
  ),
);
