<?php
/**
 * Locale data for 'zu'.
 *
 * This file is automatically generated by CLDR\I18n\Parser\Resource\createCoreResources function.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright (C) 2009 Google Inc.
 * Distributed under the Terms of Use in http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Copyright © 2011 CLDR
 */
return array (
  'version' => '5953',
  'symbols' => 
  array (
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
    'alias' => '',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'yyyy-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Januwari',
      2 => 'Februwari',
      3 => 'Mashi',
      4 => 'Apreli',
      5 => 'Meyi',
      6 => 'Juni',
      7 => 'Julayi',
      8 => 'Agasti',
      9 => 'Septhemba',
      10 => 'Okthoba',
      11 => 'Novemba',
      12 => 'Disemba',
    ),
    'abbreviated' => 
    array (
      1 => 'Jan',
      2 => 'Feb',
      3 => 'Mas',
      4 => 'Apr',
      5 => 'Mey',
      6 => 'Jun',
      7 => 'Jul',
      8 => 'Aga',
      9 => 'Sep',
      10 => 'Okt',
      11 => 'Nov',
      12 => 'Dis',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'J',
      2 => 'F',
      3 => 'M',
      4 => 'A',
      5 => 'M',
      6 => 'J',
      7 => 'J',
      8 => 'A',
      9 => 'S',
      10 => 'O',
      11 => 'N',
      12 => 'D',
    ),
    'wide' => 
    array (
      1 => 'uJanuwari',
      2 => 'uFebruwari',
      3 => 'uMashi',
      4 => 'u-Apreli',
      5 => 'uMeyi',
      6 => 'uJuni',
      7 => 'uJulayi',
      8 => 'uAgasti',
      9 => 'uSepthemba',
      10 => 'u-Okthoba',
      11 => 'uNovemba',
      12 => 'uDisemba',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sonto',
      1 => 'Msombuluko',
      2 => 'Lwesibili',
      3 => 'Lwesithathu',
      4 => 'uLwesine',
      5 => 'Lwesihlanu',
      6 => 'Mgqibelo',
    ),
    'abbreviated' => 
    array (
      0 => 'Son',
      1 => 'Mso',
      2 => 'Bil',
      3 => 'Tha',
      4 => 'Sin',
      5 => 'Hla',
      6 => 'Mgq',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'B',
      3 => 'T',
      4 => 'S',
      5 => 'H',
      6 => 'M',
    ),
  ),
  'currency' => 
  array (
    'AUD' => 
    array (
      'symbol' => 'AU$',
      'name' => 'i-Austrilian Dollar',
    ),
    'BRL' => 
    array (
      'symbol' => 'BR$',
      'name' => 'i-Brazilian Real',
    ),
    'CAD' => 
    array (
      'symbol' => 'CA$',
      'name' => 'i-Candian Dollar',
    ),
    'CNY' => 
    array (
      'symbol' => 'CN¥',
      'name' => 'i-Chinese Yuan',
    ),
    'EUR' => 
    array (
      'symbol' => '€',
      'name' => 'i-Euro',
    ),
    'GBP' => 
    array (
      'symbol' => '£',
      'name' => 'i-British Pound Sterling',
    ),
    'HKD' => 
    array (
      'symbol' => 'HK$',
      'name' => 'i-Hong Kong Dollar',
    ),
    'ILS' => 
    array (
      'symbol' => '₪',
      'name' => 'i-Israeli New Sheqel',
    ),
    'INR' => 
    array (
      'symbol' => '₹',
      'name' => 'i-Indian Rupee',
    ),
    'JPY' => 
    array (
      'symbol' => 'JP¥',
      'name' => 'i-Japanese Yen',
    ),
    'KRW' => 
    array (
      'symbol' => '₩',
      'name' => 'i-South Korean Won',
    ),
    'MXN' => 
    array (
      'symbol' => 'MX$',
      'name' => 'i-Mexican Peso',
    ),
    'NZD' => 
    array (
      'symbol' => 'NZ$',
      'name' => 'i-New Zealand Dollar',
    ),
    'THB' => 
    array (
      'symbol' => '฿',
      'name' => 'i-Thai Baht',
    ),
    'TWD' => 
    array (
      'symbol' => 'NT$',
      'name' => 'i-New Taiwan Dollar',
    ),
    'USD' => 
    array (
      'symbol' => 'US$',
      'name' => 'i-US Dollar',
    ),
    'VND' => 
    array (
      'symbol' => '₫',
      'name' => 'i-Vietnamese Dong',
    ),
    'XAF' => 
    array (
      'symbol' => 'FCFA',
      'name' => 'i-CFA Franc BCEA',
    ),
    'XCD' => 
    array (
      'symbol' => 'EC$',
      'name' => 'i-East Caribbean Dollar',
    ),
    'XOF' => 
    array (
      'symbol' => 'CFA',
      'name' => 'i-CFA Franc BCEAO',
    ),
    'XPF' => 
    array (
      'symbol' => 'CFPF',
      'name' => 'i-CFP Franc',
    ),
    'ZAR' => 
    array (
      'symbol' => 'R',
      'name' => 'i-South African Rand',
    ),
    'AED' => 
    array (
      'name' => 'i-Dirham yase-United Arab Emirates',
    ),
    'AFN' => 
    array (
      'name' => 'i-Afghan Afghani',
    ),
    'ALL' => 
    array (
      'name' => 'i-Albanian Lek',
    ),
    'AMD' => 
    array (
      'name' => 'i-Armenian Dram',
    ),
    'ANG' => 
    array (
      'name' => 'i-Netherlands Antillean Guilder',
    ),
    'AOA' => 
    array (
      'name' => 'i-Angolan Kwanza',
    ),
    'ARS' => 
    array (
      'name' => 'i-Argentina Peso',
    ),
    'AWG' => 
    array (
      'name' => 'i-Aruban Florin',
    ),
    'AZN' => 
    array (
      'name' => 'i-Azerbaijani Manat',
    ),
    'BAM' => 
    array (
      'name' => 'i-Bosnia-Herzegovina Convertible Mark',
    ),
    'BBD' => 
    array (
      'name' => 'i-Barbadian Dollar',
    ),
    'BDT' => 
    array (
      'name' => 'i-Bangladeshi Taka',
    ),
    'BGN' => 
    array (
      'name' => 'i-Bulgarian Lev',
    ),
    'BHD' => 
    array (
      'name' => 'i-Bahraini Dinar',
    ),
    'BIF' => 
    array (
      'name' => 'i-Burundian Franc',
    ),
    'BMD' => 
    array (
      'name' => 'i-Bermudan Dollar',
    ),
    'BND' => 
    array (
      'name' => 'i-Brunei Dollar',
    ),
    'BOB' => 
    array (
      'name' => 'i-Bolivian Boliviano',
    ),
    'BSD' => 
    array (
      'name' => 'i-Bahamian Dollar',
    ),
    'BTN' => 
    array (
      'name' => 'i-Bhutanese Ngultrum',
    ),
    'BWP' => 
    array (
      'name' => 'i-Botswana Pula',
    ),
    'BYR' => 
    array (
      'name' => 'i-Belarusian Ruble',
    ),
    'BZD' => 
    array (
      'name' => 'i-Belize Dollar',
    ),
    'CDF' => 
    array (
      'name' => 'i-Congolese Franc',
    ),
    'CHF' => 
    array (
      'name' => 'i-Swiss Franc',
    ),
    'CLP' => 
    array (
      'name' => 'i-Chilean Peso',
    ),
    'COP' => 
    array (
      'name' => 'i-Colombian Peso',
    ),
    'CRC' => 
    array (
      'name' => 'i-Costa Rican Colón',
    ),
    'CUC' => 
    array (
      'name' => 'i-Cuban Convertable Peso',
    ),
    'CUP' => 
    array (
      'name' => 'I-Cuban Peso',
    ),
    'CVE' => 
    array (
      'name' => 'i-Cape Verdean Escudo',
    ),
    'CZK' => 
    array (
      'name' => 'i-Czech Republic Koruna',
    ),
    'DJF' => 
    array (
      'name' => 'i-Djiboutian Franc',
    ),
    'DKK' => 
    array (
      'name' => 'i-Danish Krone',
    ),
    'DOP' => 
    array (
      'name' => 'i-Dominican Peso',
    ),
    'DZD' => 
    array (
      'name' => 'i-Algerian Dinar',
    ),
    'EGP' => 
    array (
      'name' => 'i-Egyptian Pound',
    ),
    'ERN' => 
    array (
      'name' => 'i-Eritrean Nakfa',
    ),
    'ETB' => 
    array (
      'name' => 'i-Ethopian Birr',
    ),
    'FJD' => 
    array (
      'name' => 'i-Fijian Dollar',
    ),
    'FKP' => 
    array (
      'name' => 'i-Falkland Islands Pound',
    ),
    'GEL' => 
    array (
      'name' => 'i-Georgian Lari',
    ),
    'GHS' => 
    array (
      'name' => 'i-Ghanaian Cedi',
    ),
    'GIP' => 
    array (
      'name' => 'i-Gibraltar Pound',
    ),
    'GMD' => 
    array (
      'name' => 'i-Gambian Dalasi',
    ),
    'GNF' => 
    array (
      'name' => 'i-Gunean Franc',
    ),
    'GTQ' => 
    array (
      'name' => 'i-Guatemalan Quetzal',
    ),
    'GYD' => 
    array (
      'name' => 'i-Guyanaese Dollar',
    ),
    'HNL' => 
    array (
      'name' => 'i-Honduran Lempira',
    ),
    'HRK' => 
    array (
      'name' => 'i-Croatian Kuna',
    ),
    'HTG' => 
    array (
      'name' => 'i-Haitian Gourde',
    ),
    'HUF' => 
    array (
      'name' => 'i-Hungarian Forint',
    ),
    'IDR' => 
    array (
      'name' => 'i-Indonesian Rupiah',
    ),
    'IQD' => 
    array (
      'name' => 'i-Iraqi Dinar',
    ),
    'IRR' => 
    array (
      'name' => 'i-Iranian Rial',
    ),
    'ISK' => 
    array (
      'name' => 'i-Icelandic Króna',
    ),
    'JMD' => 
    array (
      'name' => 'i-Jamaican Dollar',
    ),
    'JOD' => 
    array (
      'name' => 'i-Jordanian Dinar',
    ),
    'KES' => 
    array (
      'name' => 'i-Kenyan Shilling',
    ),
    'KGS' => 
    array (
      'name' => 'i-Kyrgystani Som',
    ),
    'KHR' => 
    array (
      'name' => 'i-Cambodian Riel',
    ),
    'KMF' => 
    array (
      'name' => 'i-Comorian Franc',
    ),
    'KPW' => 
    array (
      'name' => 'i-North Korean Won',
    ),
    'KWD' => 
    array (
      'name' => 'i-Kuwaiti Dinar',
    ),
    'KYD' => 
    array (
      'name' => 'i-Cayman Islands Dollar',
    ),
    'KZT' => 
    array (
      'name' => 'i-Kazakhstani Tenge',
    ),
    'LAK' => 
    array (
      'name' => 'i-Laotian Kip',
    ),
    'LBP' => 
    array (
      'name' => 'i-Lebanese Pound',
    ),
    'LKR' => 
    array (
      'name' => 'i-Sri Lankan Rupee',
    ),
    'LRD' => 
    array (
      'name' => 'i-Liberian Dollar',
    ),
    'LSL' => 
    array (
      'name' => 'i-Lesotho Loti',
    ),
    'LTL' => 
    array (
      'name' => 'i-Lithuanian Litas',
    ),
    'LVL' => 
    array (
      'name' => 'i-Latvian Lats',
    ),
    'LYD' => 
    array (
      'name' => 'i-Libyan Dinar',
    ),
    'MAD' => 
    array (
      'name' => 'i-Moroccan Dirham',
    ),
    'MDL' => 
    array (
      'name' => 'i-Moldovan Leu',
    ),
    'MGA' => 
    array (
      'name' => 'i-Malagasy Ariary',
    ),
    'MKD' => 
    array (
      'name' => 'i-Macedonian Denar',
    ),
    'MMK' => 
    array (
      'name' => 'i-Myanma Kyat',
    ),
    'MNT' => 
    array (
      'name' => 'i-Mongolian Tugrik',
    ),
    'MOP' => 
    array (
      'name' => 'i-Macanese Pataca',
    ),
    'MRO' => 
    array (
      'name' => 'i-Mauritanian Ouguiya',
    ),
    'MUR' => 
    array (
      'name' => 'i-Mauritian Rupee',
    ),
    'MVR' => 
    array (
      'name' => 'i-Maldivian Rufiyana',
    ),
    'MWK' => 
    array (
      'name' => 'i-Malawian Kwacha',
    ),
    'MYR' => 
    array (
      'name' => 'i-Malaysian Ringgit',
    ),
    'NAD' => 
    array (
      'name' => 'i-Namibian Dollar',
    ),
    'NGN' => 
    array (
      'name' => 'i-Nigerian Naira',
    ),
    'NIO' => 
    array (
      'name' => 'i-Nicaraguan Córdoba',
    ),
    'NOK' => 
    array (
      'name' => 'i-Norwegian Krone',
    ),
    'NPR' => 
    array (
      'name' => 'i-Nepalese Rupee',
    ),
    'OMR' => 
    array (
      'name' => 'i-Omani Rial',
    ),
    'PAB' => 
    array (
      'name' => 'i-Panamanian Balboa',
    ),
    'PEN' => 
    array (
      'name' => 'i-Peruvian Nuevo Sol',
    ),
    'PGK' => 
    array (
      'name' => 'i-Papua New Guinean Kina',
    ),
    'PHP' => 
    array (
      'name' => 'i-Philippine Peso',
    ),
    'PKR' => 
    array (
      'name' => 'i-Pakistani Rupee',
    ),
    'PLN' => 
    array (
      'name' => 'i-Polish Zloty',
    ),
    'PYG' => 
    array (
      'name' => 'i-Paraguayan Guarani',
    ),
    'QAR' => 
    array (
      'name' => 'i-Qatari Rial',
    ),
    'RSD' => 
    array (
      'name' => 'i-Serbian Dinar',
    ),
    'RUB' => 
    array (
      'name' => 'i-Russian Ruble',
    ),
    'RWF' => 
    array (
      'name' => 'i-Rwandan Franc',
    ),
    'SAR' => 
    array (
      'name' => 'i-Saudi Riyal',
    ),
    'SBD' => 
    array (
      'name' => 'i-Solomon Islands Dollar',
    ),
    'SCR' => 
    array (
      'name' => 'i-Seychellois Rupee',
    ),
    'SDG' => 
    array (
      'name' => 'i-Sudanese Pound',
    ),
    'SEK' => 
    array (
      'name' => 'i-Swedish Krona',
    ),
    'SGD' => 
    array (
      'name' => 'i-Singapore Dollar',
    ),
    'SHP' => 
    array (
      'name' => 'i-Saint Helena Pound',
    ),
    'SLL' => 
    array (
      'name' => 'i-Sierra Leonean Leone',
    ),
    'SOS' => 
    array (
      'name' => 'i-Somali Shilling',
    ),
    'SRD' => 
    array (
      'name' => 'i-Surinamese Dollar',
    ),
    'STD' => 
    array (
      'name' => 'i-São Tomé kanye ne-Príncipe Dobra',
    ),
    'SYP' => 
    array (
      'name' => 'i-Syrian Pound',
    ),
    'SZL' => 
    array (
      'name' => 'i-Swazi Lilangeni',
    ),
    'TJS' => 
    array (
      'name' => 'i-Tajikistani Somoni',
    ),
    'TMT' => 
    array (
      'name' => 'i-Turkmenistani Manat',
    ),
    'TND' => 
    array (
      'name' => 'i-Tunisian Dinar',
    ),
    'TOP' => 
    array (
      'name' => 'i-Tongan Paʻanga',
    ),
    'TRY' => 
    array (
      'name' => 'i-Turkish Lira',
    ),
    'TTD' => 
    array (
      'name' => 'Idola lase-Trinidad nase-Tobago',
    ),
    'TZS' => 
    array (
      'name' => 'i-Tanzanian Shilling',
    ),
    'UAH' => 
    array (
      'name' => 'i-Ukrainian Hryvnia',
    ),
    'UGX' => 
    array (
      'name' => 'i-Ugandan Shilling',
    ),
    'UYU' => 
    array (
      'name' => 'i-Uruguayan Peso',
    ),
    'UZS' => 
    array (
      'name' => 'i-Uzbekistan Som',
    ),
    'VEF' => 
    array (
      'name' => 'i-Venezuelan Bolívar',
    ),
    'VUV' => 
    array (
      'name' => 'i-Vanuatu Vatu',
    ),
    'WST' => 
    array (
      'name' => 'i-Samoan Tala',
    ),
    'XXX' => 
    array (
      'name' => 'Ikharensi engaziwa',
    ),
    'YER' => 
    array (
      'name' => 'i-Yemeni Rial',
    ),
    'ZMK' => 
    array (
      'name' => 'i-Zambian Kwacha',
    ),
  ),
  'languages' => 
  array (
    'zxx' => 'Akukho okuqukethwe kolimi',
    'se' => 'E-Northern Sami',
    'en_GB' => 'I-British English',
    'en_CA' => 'I-Canadian English',
    'fr_CA' => 'I-Canadian French',
    'nl' => 'I-Dutch',
    'lo' => 'I-Lao',
    'nb' => 'I-Norwegian Bokmål',
    'nn' => 'I-Norwegian Nynorsk',
    'gd' => 'I-Scottish Gaelic',
    'si' => 'I-Sinhala',
    'en_US' => 'I-U.S. English',
    'ab' => 'Isi-Abkhazian',
    'ar' => 'Isi-Alabhu',
    'sq' => 'Isi-Albania',
    'am' => 'Isi-Amharic',
    'hy' => 'Isi-Armenia',
    'as' => 'Isi-Assamese',
    'de_AT' => 'Isi-Austrian German',
    'en_AU' => 'Isi-Austrillian English',
    'ay' => 'Isi-Aymara',
    'az' => 'Isi-Azeria',
    'eu' => 'Isi-Basque',
    'be' => 'Isi-Belarusian',
    'bn' => 'Isi-Bengali',
    'bs' => 'Isi-Bosnian',
    'pt_BR' => 'Isi-Brazillian Portuguese',
    'bg' => 'Isi-Bulgari',
    'my' => 'Isi-Burmese',
    'ca' => 'Isi-Catalan',
    'zh' => 'Isi-Chinese',
    'hr' => 'Isi-Croatian',
    'cs' => 'Isi-Czech',
    'da' => 'Isi-Danish',
    'dv' => 'Isi-Divehi',
    'dz' => 'Isi-Dzongkha',
    'efi' => 'Isi-Efik',
    'eo' => 'Isi-Esperanto',
    'et' => 'Isi-Estonia',
    'fo' => 'Isi-Faroese',
    'fj' => 'Isi-Fijian',
    'fil' => 'Isi-Filipino',
    'fi' => 'Isi-Finnish',
    'nl_BE' => 'Isi-Flemish',
    'gl' => 'Isi-Galicia',
    'ka' => 'Isi-Georgian',
    'el' => 'Isi-Greek',
    'gn' => 'Isi-Guarani',
    'gu' => 'Isi-Gujarati',
    'ht' => 'Isi-Haitian',
    'ha' => 'Isi-Hausa',
    'haw' => 'Isi-Hawaiian',
    'he' => 'Isi-Hebrew',
    'hu' => 'Isi-Hungarian',
    'pt_PT' => 'Isi-Iberian Portuguese',
    'es_ES' => 'Isi-Iberian Spanish',
    'is' => 'Isi-Icelandic',
    'ig' => 'Isi-Igbo',
    'id' => 'Isi-Indonesian',
    'ga' => 'Isi-Irish',
    'it' => 'Isi-Italian',
    'ja' => 'Isi-Japanese',
    'jv' => 'Isi-Javanese',
    'kn' => 'Isi-Kannada',
    'ks' => 'Isi-Kashmiri',
    'kk' => 'Isi-Kazakh',
    'km' => 'Isi-Khmer',
    'rw' => 'Isi-Kinyarwanda',
    'ky' => 'Isi-Kirghiz',
    'ko' => 'Isi-Korean',
    'ku' => 'Isi-Kurdish',
    'la' => 'Isi-Latin',
    'es_419' => 'Isi-Latin American Spanish',
    'lv' => 'Isi-Latvia',
    'ln' => 'Isi-Lingala',
    'lt' => 'Isi-Lithuanian',
    'lb' => 'Isi-Luxembourgish',
    'mk' => 'Isi-Macedonia',
    'mg' => 'Isi-Malagasy',
    'ms' => 'Isi-Malay',
    'ml' => 'Isi-Malayalam',
    'mt' => 'Isi-Malta',
    'mi' => 'Isi-Maori',
    'mr' => 'Isi-Marathi',
    'mn' => 'Isi-Mongolian',
    'ne' => 'Isi-Nepali',
    'nd' => 'Isi-North Ndebele',
    'nso' => 'Isi-Northern Sotho',
    'ny' => 'Isi-Nyanja',
    'or' => 'Isi-Oriya',
    'oc' => 'Isi-Osithani',
    'os' => 'Isi-Ossetic',
    'fa' => 'Isi-Persian',
    'pl' => 'Isi-Polish',
    'pt' => 'Isi-Portuguese',
    'pa' => 'Isi-Punjabi',
    'ps' => 'Isi-Pushto',
    'qu' => 'Isi-Quechua',
    'ro' => 'Isi-Romanian',
    'rm' => 'Isi-Romansh',
    'rn' => 'Isi-Rundi',
    'ru' => 'Isi-Russian',
    'sm' => 'Isi-Samoan',
    'sg' => 'Isi-Sango',
    'sa' => 'Isi-Sanskrit',
    'sr' => 'Isi-Serbian',
    'sd' => 'Isi-Sindhi',
    'zh_Hans' => 'Isi-Sipmlified Chinese',
    'sk' => 'Isi-Slovak',
    'sl' => 'Isi-Slovenian',
    'so' => 'Isi-Somali',
    'su' => 'Isi-Sundanese',
    'sv' => 'Isi-Swedish',
    'fr_CH' => 'Isi-Swiss French',
    'gsw' => 'Isi-Swiss German',
    'de_CH' => 'Isi-Swiss High German',
    'ty' => 'Isi-Tahitian',
    'tg' => 'Isi-Tajik',
    'ta' => 'Isi-Tamil',
    'tt' => 'Isi-Tatar',
    'te' => 'Isi-Telugu',
    'tet' => 'Isi-Tetum',
    'th' => 'Isi-Thai',
    'bo' => 'Isi-Tibetan',
    'ti' => 'Isi-Tigrinya',
    'tpi' => 'Isi-Tok Pisin',
    'to' => 'Isi-Tonga',
    'zh_Hant' => 'Isi-Traditional Chinese',
    'ts' => 'Isi-Tsonga',
    'tn' => 'Isi-Tswana',
    'tr' => 'Isi-Turkish',
    'tk' => 'Isi-Turkmen',
    'uk' => 'Isi-Ukrainian',
    'ur' => 'Isi-Urdu',
    'ug' => 'Isi-Uyghur',
    'uz' => 'Isi-Uzbek',
    've' => 'Isi-Venda',
    'vi' => 'Isi-Vietnamese',
    'cy' => 'Isi-Welsh',
    'fy' => 'Isi-Western Frisian',
    'wo' => 'Isi-Wolof',
    'yo' => 'Isi-Yoruba',
    'bh' => 'IsiBhihari',
    'af' => 'IsiBhunu',
    'fr' => 'IsiFulentshi',
    'hi' => 'IsiHindi',
    'de' => 'IsiJalimani',
    'tlh' => 'IsiKlingoni',
    'en' => 'IsiNgisi',
    'no' => 'IsiNoweyi',
    'sn' => 'IsiShona',
    'es' => 'IsiSpeyini',
    'st' => 'IsiSuthu',
    'sw' => 'IsiSwahili',
    'ss' => 'IsiSwati',
    'xh' => 'IsiXhosa',
    'zu' => 'IsiZulu',
    'br' => 'Isihlobo sase Britain',
    'ia' => 'Izilimi ezihlangene',
    'ie' => 'Izilimu',
    'sh' => 'Serbo-Croatian',
    'tw' => 'Twi',
    'und' => 'Ulimi olungaziwa',
    'yi' => 'Ulimu olwi Yidish',
  ),
  'countries' => 
  array (
    'CD' => 'E-Congo [DRC]',
    'CG' => 'E-Congo [Republic]',
    'DG' => 'E-Diego Garcia',
    'TF' => 'E-French Southern Territories',
    'MM' => 'E-Myanmar [Burma]',
    'UM' => 'E-U.S. Minor Outlying Islands',
    'AF' => 'I-Afghanistan',
    'AL' => 'I-Albania',
    'DZ' => 'I-Algeria',
    'AS' => 'I-American Samoa',
    'AD' => 'I-Andorra',
    'AO' => 'I-Angola',
    'AI' => 'I-Anguilla',
    'AQ' => 'I-Antarctica',
    'AG' => 'I-Antigua and Barbuda',
    'AR' => 'I-Argentina',
    'AM' => 'I-Armenia',
    'AW' => 'I-Aruba',
    'AC' => 'I-Ascension Island',
    'AU' => 'I-Australia',
    'AT' => 'I-Austria',
    'AZ' => 'I-Azerbaijan',
    'BS' => 'I-Bahamas',
    'BH' => 'I-Bahrain',
    'BD' => 'I-Bangladesh',
    'BB' => 'I-Barbados',
    'BY' => 'I-Belarus',
    'BE' => 'I-Belgium',
    'BZ' => 'I-Belize',
    'BJ' => 'I-Benin',
    'BM' => 'I-Bermuda',
    'BT' => 'I-Bhutan',
    'BO' => 'I-Bolivia',
    'BA' => 'I-Bosnia ne-Herzegovina',
    'BW' => 'I-Botswana',
    'BV' => 'I-Bouvet Island',
    'BR' => 'I-Brazil',
    'IO' => 'I-British Indian Ocean Territory',
    'VG' => 'I-British Virgin Islands',
    'BN' => 'I-Brunei',
    'BG' => 'I-Bulgaria',
    'BF' => 'I-Burkina Faso',
    'BI' => 'I-Burundi',
    'KH' => 'I-Cambodia',
    'CM' => 'I-Cameroon',
    'CA' => 'I-Canada',
    'IC' => 'I-Canary Islands',
    'CV' => 'I-Cape Verde',
    'KY' => 'I-Cayman Islands',
    'CF' => 'I-Central African Republic',
    'TD' => 'I-Chad',
    'CL' => 'I-Chile',
    'CN' => 'I-China',
    'CX' => 'I-Christmas Island',
    'CP' => 'I-Clipperton Island',
    'CC' => 'I-Cocos (Keeling) Islands',
    'CO' => 'I-Colombia',
    'KM' => 'I-Comoros',
    'CK' => 'I-Cook Islands',
    'CR' => 'I-Costa Rica',
    'HR' => 'I-Croatia',
    'CU' => 'I-Cuba',
    'EA' => 'I-Cueta ne-Melilla',
    'CY' => 'I-Cyprus',
    'CZ' => 'I-Czech Republic',
    'DK' => 'I-Denmark',
    'DJ' => 'I-Djibouti',
    'DM' => 'I-Dominica',
    'DO' => 'I-Dominican Republic',
    'TL' => 'I-East Timor',
    'EC' => 'I-Ecuador',
    'EG' => 'I-Egypt',
    'SV' => 'I-El Salvador',
    'GQ' => 'I-Equatorial Guinea',
    'ER' => 'I-Eritrea',
    'EE' => 'I-Estonia',
    'ET' => 'I-Ethiopia',
    'EU' => 'I-European Union',
    'FK' => 'I-Falkland Islands (i-Islas Malvinas]',
    'FO' => 'I-Faroe Islands',
    'FJ' => 'I-Fiji',
    'FI' => 'I-Finland',
    'FR' => 'I-France',
    'PF' => 'I-French Polynesia',
    'GA' => 'I-Gabon',
    'GM' => 'I-Gambia',
    'GE' => 'I-Georgia',
    'DE' => 'I-Germany',
    'GH' => 'I-Ghana',
    'GI' => 'I-Gibraltar',
    'GR' => 'I-Greece',
    'GL' => 'I-Greenland',
    'GD' => 'I-Grenada',
    'GP' => 'I-Guadeloupe',
    'GU' => 'I-Guam',
    'GT' => 'I-Guatemala',
    'GG' => 'I-Guernsey',
    'GN' => 'I-Guinea',
    'GW' => 'I-Guinea-Bissau',
    'GY' => 'I-Guyana',
    'HT' => 'I-Haiti',
    'HM' => 'I-Heard Island ne-McDonald Islands',
    'HN' => 'I-Honduras',
    'HK' => 'I-Hong Kong',
    'HU' => 'I-Hungary',
    'IS' => 'I-Iceland',
    'IN' => 'I-India',
    'ID' => 'I-Indonesia',
    'IR' => 'I-Iran',
    'IQ' => 'I-Iraq',
    'IE' => 'I-Ireland',
    'IM' => 'I-Isle of Man',
    'IL' => 'I-Israel',
    'IT' => 'I-Italy',
    'CI' => 'I-Ivory Coast',
    'JM' => 'I-Jamaica',
    'JP' => 'I-Japan',
    'JO' => 'I-Jordan',
    'KZ' => 'I-Kazakhstan',
    'KE' => 'I-Kenya',
    'KI' => 'I-Kiribati',
    'KW' => 'I-Kuwait',
    'KG' => 'I-Kyrgyzstan',
    'LA' => 'I-Laos',
    'LV' => 'I-Latvia',
    'LB' => 'I-Lebanon',
    'LS' => 'I-Lesotho',
    'LR' => 'I-Liberia',
    'LY' => 'I-Libya',
    'LI' => 'I-Liechtenstein',
    'LT' => 'I-Lithuania',
    'LU' => 'I-Luxembourg',
    'MO' => 'I-Macau',
    'MG' => 'I-Madagascar',
    'MW' => 'I-Malawi',
    'MY' => 'I-Malaysia',
    'MV' => 'I-Maldives',
    'ML' => 'I-Mali',
    'MT' => 'I-Malta',
    'MH' => 'I-Marshall Islands',
    'MQ' => 'I-Martinique',
    'MR' => 'I-Mauritania',
    'MU' => 'I-Mauritius',
    'YT' => 'I-Mayotte',
    'MX' => 'I-Mexico',
    'FM' => 'I-Micronesia',
    'MD' => 'I-Moldova',
    'MC' => 'I-Monaco',
    'MN' => 'I-Mongolia',
    'ME' => 'I-Montenegro',
    'MS' => 'I-Montserrat',
    'MA' => 'I-Morocco',
    'MZ' => 'I-Mozambique',
    'NA' => 'I-Namibia',
    'NR' => 'I-Nauru',
    'NP' => 'I-Nepal',
    'NL' => 'I-Netherlands',
    'AN' => 'I-Netherlands Antilles',
    'NC' => 'I-New Caledonia',
    'NZ' => 'I-New Zealand',
    'NI' => 'I-Nicaragua',
    'NE' => 'I-Niger',
    'NG' => 'I-Nigeria',
    'NU' => 'I-Niue',
    'NF' => 'I-Norfolk Island',
    'KP' => 'I-North Korea',
    'MP' => 'I-Northern Mariana Islands',
    'NO' => 'I-Norway',
    'OM' => 'I-Oman',
    'QO' => 'I-Outlying Oceania',
    'PK' => 'I-Pakistan',
    'PW' => 'I-Palau',
    'PS' => 'I-Palestinian Territories',
    'PA' => 'I-Panama',
    'PG' => 'I-Papua New Guinea',
    'PY' => 'I-Paraguay',
    'PE' => 'I-Peru',
    'PH' => 'I-Philippines',
    'PN' => 'I-Pitcairn Islands',
    'PL' => 'I-Poland',
    'PT' => 'I-Portugal',
    'PR' => 'I-Puerto Rico',
    'QA' => 'I-Qatar',
    'RO' => 'I-Romania',
    'RU' => 'I-Russia',
    'RW' => 'I-Rwanda',
    'RE' => 'I-Réunion',
    'BL' => 'I-Saint Barthélemy',
    'SH' => 'I-Saint Helena',
    'KN' => 'I-Saint Kitts ne-Nevis',
    'LC' => 'I-Saint Lucia',
    'MF' => 'I-Saint Martin',
    'PM' => 'I-Saint Pierre kanye ne-Miquelon',
    'VC' => 'I-Saint Vincent ne-Grenadines',
    'WS' => 'I-Samoa',
    'SM' => 'I-San Marino',
    'SA' => 'I-Saudi Arabia',
    'SN' => 'I-Senegal',
    'RS' => 'I-Serbia',
    'SC' => 'I-Seychelles',
    'SL' => 'I-Sierra Leone',
    'SG' => 'I-Singapore',
    'SK' => 'I-Slovakia',
    'SI' => 'I-Slovenia',
    'SB' => 'I-Solomon Islands',
    'SO' => 'I-Somalia',
    'GS' => 'I-South Georgia ne-South Sandwich Islands',
    'KR' => 'I-South Korea',
    'ES' => 'I-Spain',
    'LK' => 'I-Sri Lanka',
    'SD' => 'I-Sudan',
    'SR' => 'I-Suriname',
    'SJ' => 'I-Svalbard ne-Jan Mayen',
    'SZ' => 'I-Swaziland',
    'SE' => 'I-Sweden',
    'CH' => 'I-Switzerland',
    'SY' => 'I-Syria',
    'ST' => 'I-São Tomé kanye ne-Príncipe',
    'TW' => 'I-Taiwan',
    'TJ' => 'I-Tajikistan',
    'TZ' => 'I-Tanzania',
    'TH' => 'I-Thailand',
    'TG' => 'I-Togo',
    'TK' => 'I-Tokelau',
    'TO' => 'I-Tonga',
    'TT' => 'I-Trinidad ne-Tobago',
    'TA' => 'I-Tristan da Cunha',
    'TN' => 'I-Tunisia',
    'TR' => 'I-Turkey',
    'TM' => 'I-Turkmenistan',
    'TC' => 'I-Turks and Caicos Islands',
    'TV' => 'I-Tuvalu',
    'VI' => 'I-U.S. Virgin Islands',
    'UG' => 'I-Uganda',
    'UA' => 'I-Ukraine',
    'AE' => 'I-United Arab Emirates',
    'GB' => 'I-United Kingdom',
    'US' => 'I-United States',
    'UY' => 'I-Uruguay',
    'UZ' => 'I-Uzbekistan',
    'VU' => 'I-Vanuatu',
    'VA' => 'I-Vatican City',
    'VE' => 'I-Venezuela',
    'VN' => 'I-Vietnam',
    'WF' => 'I-Wallis ne-Futuna',
    'EH' => 'I-Western Sahara',
    'YE' => 'I-Yemen',
    'ZM' => 'I-Zambia',
    'ZW' => 'I-Zimbabwe',
    'AX' => 'I-Åland Islands',
    'ZA' => 'INingizimu Afrika',
    'GF' => 'Isi-French Guiana',
    'JE' => 'Isi-Jersey',
    'MK' => 'Isi-Macedonia [FYROM]',
    'ZZ' => 'Isifunda esingaziwa',
  ),
);
